### ISSUE TITLE
Test fails after enabling feature for mocking final classes and methods

### ISSUE THREAD

**Issue by geralt-encore** [mockito/mockito#1005]
I am mocking [GoogleSignInAccount](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInAccount) with the latest Mockito version:
```
GoogleSignInAccount mockGoogleAccount = mock(GoogleSignInAccount.class);
    when(mockGoogleAccount.getId()).thenReturn("id");
    when(mockGoogleAccount.getEmail()).thenReturn("email@email.com");
    when(mockGoogleAccount.getFamilyName()).thenReturn("family name");
    when(mockGoogleAccount.getGivenName()).thenReturn("given name");
```

After enabling mocking of final classes/methods test fails with this error (which is not really helpful):
```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because:
1. you stub either of: final/private/equals()/hashCode() methods.
   Those methods *cannot* be stubbed/verified.
   Mocking methods declared on non-public parent classes is not supported.
2. inside when() you don't call method on mock but on some other object.

	at com.app.profile.data.ProfileRepositoryTest.shouldFailRegisterIfEmailNotRegisteredAndUnknownGenderGoogleAccount(ProfileRepositoryTest.java:870)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
Let me know if you need more details from me.

**Comment by TimvdLippe** [comment]
@geralt-encore Could you build a gist so that we can easily test it? I am not familiar with the Android ecosystem, would like to have a quick install to debug directly.

**Comment by geralt-encore** [comment]
Here is a sample project for reproduction: https://github.com/geralt-encore/MockitoBug

**Comment by TimvdLippe** [comment]
I have assigned @raphw, as he is probably the most knowledgeable about this bug. However, he is quite busy IRL so it might take some time before he is able to respond. Thanks for your understanding!

**Comment by geralt-encore** [comment]
Sure! Let me know if you need more info from me.

**Comment by raphw** [comment]
I do not currently have an Android SDK installed but I assume it has something to do with your use of Android? The inline mock maker requires running on a "regular" JVM and cannot be used on Android or on an emulator.

**Comment by tmurakami** [comment]
@raphw, I am interested in this issue and I investigated this with the above reproducible project.
This problem occurs on the "regular" JVM such as OpenJDK, not Android VM.

I suppose this is a bug of byte-buddy.

Running the code above causes ArrayIndexOutOfBoundsException.
(However, since Throwable objects are ignored [here](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L172), this exception will not appear.)

Here is the stack trace elements.
```
0 = {StackTraceElement@1934} "net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1194)"
1 = {StackTraceElement@1935} "net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:1141)"
2 = {StackTraceElement@1936} "net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:6590)"
3 = {StackTraceElement@1937} "net.bytebuddy.jar.asm.ClassReader.a(Unknown Source)"
4 = {StackTraceElement@1938} "net.bytebuddy.jar.asm.ClassReader.b(Unknown Source)"
5 = {StackTraceElement@1939} "net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)"
6 = {StackTraceElement@1940} "net.bytebuddy.jar.asm.ClassReader.accept(Unknown Source)"
7 = {StackTraceElement@1941} "net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2910)"
8 = {StackTraceElement@1942} "net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1628)"
9 = {StackTraceElement@1943} "net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)"
10 = {StackTraceElement@1944} "net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)"
11 = {StackTraceElement@1945} "net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2560)"
12 = {StackTraceElement@1946} "org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:156)"
[snip]
```

The exception has occurred [here](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/asm/Advice.java#L1194).

I set a breakpoint at the place where the exception occurred.
Here is a list of variables.
```
this = {Advice$StackMapFrameHandler$Default@1896} 
methodVisitor = {LineNumberPrependingMethodVisitor@1900} 
translationMode = {Advice$StackMapFrameHandler$Default$TranslationMode$1@1901} "COPY"
methodDescription = {MethodDescription$Latent@1902} "public android.accounts.Account com.google.android.gms.auth.api.signin.GoogleSignInAccount.getAccount()"
additionalTypes = {TypeList$Explicit@1903}  size = 1
type = 0
localVariableLength = 0
localVariable = {Object[1]@1904} 
stackSize = 1
stack = {Object[4]@1905} 
translated = {Object[1]@1954} 
index = 1
typeDescription = {TypeDescription$ForLoadedType@1917} "interface java.util.concurrent.Callable"
translated.length = 1
instrumentedType = {InstrumentedType$Default@1906} "class com.google.android.gms.auth.api.signin.GoogleSignInAccount"
instrumentedMethod = {MethodDescription$Latent@1902} "public android.accounts.Account com.google.android.gms.auth.api.signin.GoogleSignInAccount.getAccount()"
```

Since the length of the array `translated` is `1` and `index` is `1`, the exception is occurred.

`methodDescription` is for`GoogleSignInAccount#getAccount`, so I got javap of this method.
```
  public android.accounts.Account getAccount();
    descriptor: ()Landroid/accounts/Account;
    flags: ACC_PUBLIC
    Code:
      stack=4, locals=1, args_size=1
         0: aload_0
         1: getfield      #53                 // Field zzaka:Ljava/lang/String;
         4: ifnonnull     11
         7: aconst_null
         8: goto          24
        11: new           #13                 // class android/accounts/Account
        14: dup
        15: aload_0
        16: getfield      #53                 // Field zzaka:Ljava/lang/String;
        19: ldc           #1                  // String com.google
        21: invokespecial #60                 // Method android/accounts/Account."<init>":(Ljava/lang/String;Ljava/lang/String;)V
        24: areturn
      StackMapTable: number_of_entries = 2
        frame_type = 11 /* same */
        frame_type = 255 /* full_frame */
          offset_delta = 12
          locals = []
          stack = [ class android/accounts/Account ]
    RuntimeInvisibleAnnotations:
      0: #231()
```

The stack map table has two entries.
First is `same`, second is `full_frame`.
(The exception occurs while processing the entry of type `full_frame`.)

Moreover I ran the following code.
```java
package com.geraltencore.mockitobug;

import com.google.android.gms.auth.api.signin.GoogleSignInAccount;

import net.bytebuddy.jar.asm.ClassReader;
import net.bytebuddy.jar.asm.ClassVisitor;
import net.bytebuddy.jar.asm.MethodVisitor;
import net.bytebuddy.jar.asm.Opcodes;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.util.Arrays;

public class MyTest {

    private static final String[] TYPE_NAMES = {
            "F_NEW",
            "F_FULL",
            "F_APPEND",
            "F_CHOP",
            "F_SAME",
            "F_SAME1",
    };

    @Test
    public void test() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        InputStream in = getClass().getResourceAsStream('/' + GoogleSignInAccount.class.getName().replace('.', '/') + ".class");
        try {
            byte[] buffer = new byte[8192];
            for (int l; (l = in.read(buffer)) != -1; ) {
                out.write(buffer, 0, l);
            }
        } finally {
            in.close();
        }
        new ClassReader(out.toByteArray()).accept(new ClassVisitor(Opcodes.ASM5) {
            @Override
            public MethodVisitor visitMethod(int access, String name, String desc, String signature, String[] exceptions) {
                MethodVisitor mv = super.visitMethod(access, name, desc, signature, exceptions);
                return name.equals("getAccount") ? new MethodVisitor(api, mv) {

                    private int n = 0;

                    @Override
                    public void visitFrame(int type, int nLocal, Object[] local, int nStack, Object[] stack) {
                        super.visitFrame(type, nLocal, local, nStack, stack);
                        System.out.println("#" + n++);
                        System.out.println("  type=" + TYPE_NAMES[type + 1]);
                        System.out.println("  nLocal=" + nLocal);
                        System.out.println("  local=" + Arrays.toString(local));
                        System.out.println("  nStack=" + nStack);
                        System.out.println("  stack=" + Arrays.toString(stack));
                    }

                } : mv;
            }
        }, 0);
    }

}
```

Here is the result.
```
#0
  type=F_SAME
  nLocal=0
  local=[null]
  nStack=0
  stack=[null, null, null, null]
#1
  type=F_FULL
  nLocal=0
  local=[null]
  nStack=1
  stack=[android/accounts/Account, null, null, null]
```

`nLocal` is `0`, but the length of the array `local` is `1`.

Let me know if you need more information.

**Comment by geralt-encore** [comment]
As @tmurakami pointed I am not running this test on Android - it occurs on regular JVM.
I am also experiencing the same issue when trying to mock [FirebaseRemoteConfig](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/package-summary) if it helps somehow.

**Comment by ChristianSchwarz** [comment]
I observed the same in #939 and possibly it relates to #978 also.

**Comment by tmurakami** [comment]
@ChristianSchwarz, I think this is not Android specific problem.
It seems to occur while processing the `StackMapTable` attribute with a frame of type `full_frame`.
(The `StackMapTable` attribute is described [in the Java Virtual Machine Specification](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.4).)

The issue #939 and #978 are that `InlineByteBuddyMockMaker` cannot be initialized.
This issue is that Mockito cannot mock a specific class correctly with inline mock making.
I think that this is different from those issues.

**Comment by raphw** [comment]
This is an interesting error. The problem is the full frame that does not specify any local variables. This is incorrect for the method in question which is non-static and should therefore always specify a 'this' value. The compiler that created this method apparently voided this variable.

As a consequence, Byte Buddy cannot longer instrument the method as it requires access to the "this" reference even after the method return which has now become impossible. 

That the error is suppressed is unfortunate and we need to improve this. The error itself can however not be fixed as the stack map frames are already corrupted.

It would be interesting to know how these frames got in there. Creating the same class and compiling it with javac yields correct frames.

**Comment by tmurakami** [comment]
@raphw, thank you for your reply.

`GoogleSignInAccount` provided by Google seems to be obfuscated by [ProGuard](https://www.guardsquare.com/en/proguard).
StackMapTable might have been broken due to obfuscation.

@geralt-encore, I tried using `-noverify` option on your reproducible project and it works fine.
Try the following snippet.

```groovy
android {
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}
```

**Comment by geralt-encore** [comment]
@tmurakami I just tried it and it didn't work. Did I miss something? Looks pretty straightforward.

**Comment by tmurakami** [comment]
Add the `-noverify` option into your `app/build.gradle`.

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.geraltencore.mockitobug"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        unitTests.all {
            jvmArgs '-noverify'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.google.android.gms:play-services-auth:10.2.1'
    testCompile 'org.mockito:mockito-core:2.7.19'
    testCompile 'junit:junit:4.12'
}
```

Then, run `./gradlew clean test`.

Here is my Java environment:
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.10.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

If you run test on Android Studio, set `-noverify` as `VM options` in the `Run/Debug Configurations` dialog.

**Comment by tmurakami** [comment]
> Are there any downsides of using it?

`-noverify` disables bytecode verification, so should not be used if possible.
However I cannot think of any other way.

**Comment by ChristianSchwarz** [comment]
The Android Framework Team is going to provide better mock support with `dexmaker-mockito-inline` see PR: https://github.com/linkedin/dexmaker/pull/68

**Comment by tmurakami** [comment]
@ChristianSchwarz, thank you for your information.
However, that PR will not solve this issue.

Generally, an Android project has two kinds of tests.

1. [Local Unit Tests](https://developer.android.com/training/testing/unit-testing/local-unit-tests.html?hl=en) (on JVM)
2. [Instrumented Unit Tests](https://developer.android.com/training/testing/unit-testing/instrumented-unit-tests.html?hl=en) (on Android VM)

That PR seems to provide inline mocking feature on Android VM using [slicer](https://android.googlesource.com/platform/tools/dexter/) library.

On the other hand, this problem occurs while running local unit tests, so unfortunately that PR will not help this issue.
