### ISSUE TITLE
Clean Mockito build produces npm related stack trace in the build log

### ISSUE THREAD

**Issue by mockitoguy** [mockito/mockito#1019]
I noticed that clean and working Mockito builds produce npm related warnings ([full log](https://travis-ci.org/mockito/mockito/jobs/217498617#L332)):

```
:testng:test
7 warnings
Installing sw-precache globally
:testng:check
:testng:build
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
/home/travis/.nvm/v0.10.36/bin/sw-precache -> /home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache/cli.js
sw-precache@5.1.0 /home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache
├── pretty-bytes@4.0.2
├── lodash.defaults@4.2.0
├── lodash.template@4.4.0 (lodash._reinterpolate@3.0.0, lodash.templatesettings@4.1.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── dom-urls@1.1.0 (urijs@1.18.10)
├── glob@7.1.1 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
├── es6-promise@4.1.0
├── sw-toolbox@3.6.0 (serviceworker-cache-polyfill@4.0.0, path-to-regexp@1.7.0)
├── meow@3.7.0 (map-obj@1.0.1, trim-newlines@1.0.0, decamelize@1.2.0, object-assign@4.1.1, minimist@1.2.0, camelcase-keys@2.1.0, loud-rejection@1.6.0, redent@1.0.0, normalize-package-data@2.3.6, read-pkg-up@1.0.1)
└── update-notifier@1.0.3 (is-npm@1.0.0, lazy-req@1.1.0, xdg-basedir@2.0.0, semver-diff@2.1.0, configstore@2.1.0, chalk@1.1.3, boxen@0.6.0, latest-version@2.0.0)
/home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache/node_modules/pretty-bytes/index.js:2
const UNITS = ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache/lib/sw-precache.js:27:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
NPM is not installed. Aborting generating service-worker
:javadocJar
```

**Comment by TimvdLippe** [comment]
Hm I will need to investigate. Seems like a package has broken bacjwards compatibility

**Comment by TimvdLippe** [comment]
Related issue in #1233 and was recently removed from our build system.
