### ISSUE TITLE
"SyntaxError: Use of const in strict mode" on Travis

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#1024]
During a build on Travis the following JS error is [emitted](https://travis-ci.org/mockito/mockito/jobs/219709696#L325):

```
:testng:build
/home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache/node_modules/pretty-bytes/index.js:2
const UNITS = ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/sw-precache/lib/sw-precache.js:27:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
NPM is not installed. Aborting generating service-worker
```

**Comment by TimvdLippe** [comment]
Yes there seems to be a breaking change in the nodemodules. Something something semver... I will take a look soon :)

**Comment by szczepiq** [comment]
Already reported at #1019, closing as duplicate and waiting for fix :)
