### ISSUE TITLE
Real method on mocked object is always called

### ISSUE THREAD

**Issue by Hendrik-AS** [mockito/mockito#1053]
I am trying to mock a class from a kotlin library: 
```kotlin
class TheTest {
    val kit: AndroidKit = mock()
    val resources: Resources = mock()

    @Test
    fun stepsIntoFunctionOfMockedClass() {
        given(kit.getResource(resources, 123, String::class)).willReturn("resource")
    }
}
``` 
In the given statement the real function ```kit.getResource()``` is called which leads to an NPE since function calls on ```resources``` are not mocked. Any ideas?

[Sample project to reproduce](https://github.com/Hendrik-AS/MockitoSample)
[androidKit library](https://github.com/hkokocin/androidKit)

**Comment by tmurakami** [comment]
I have tried your reproducible project with Mockito 2.8.9 that is the latest version.

Here is the stack trace.
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.github.hkokocin.androidkit.AndroidKit.
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface com.github.hkokocin.androidkit.app.BaseKit, class com.github.hkokocin.androidkit.AndroidKit, interface com.github.hkokocin.androidkit.content.ContextKit, interface com.github.hkokocin.androidkit.widget.WidgetKit, interface com.github.hkokocin.androidkit.view.ViewKit, class java.lang.Object, interface com.github.hkokocin.androidkit.app.ActivityKit]
	at de.welt.mockitosample.TheTest.<init>(TheTest.kt:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface com.github.hkokocin.androidkit.app.BaseKit, class com.github.hkokocin.androidkit.AndroidKit, interface com.github.hkokocin.androidkit.content.ContextKit, interface com.github.hkokocin.androidkit.widget.WidgetKit, interface com.github.hkokocin.androidkit.view.ViewKit, class java.lang.Object, interface com.github.hkokocin.androidkit.app.ActivityKit]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	... 45 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:120)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:97)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:201)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:182)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
	at org.mockito.Mockito.mock(Mockito.java:1729)
	... 45 more
Caused by: java.lang.TypeNotPresentException: Type android.support.design.widget.Snackbar not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.reflectiveObjects.WildcardTypeImpl.getLowerBounds(WildcardTypeImpl.java:172)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType$ForLoadedType.getLowerBounds(TypeDescription.java:4126)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onWildcard(TypeDescription.java:1573)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForDetachment.onWildcard(TypeDescription.java:1708)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType.accept(TypeDescription.java:4039)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor.onParameterizedType(TypeDescription.java:1556)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForDetachment.onParameterizedType(TypeDescription.java:1708)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:4396)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:5297)
	at net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:145)
	at net.bytebuddy.description.method.ParameterDescription$AbstractBase.asToken(ParameterDescription.java:107)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTokenList(ParameterList.java:80)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:693)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asToken(MethodDescription.java:334)
	at net.bytebuddy.description.method.MethodList$AbstractBase.asTokenList(MethodList.java:53)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:223)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:698)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:676)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:167)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:117)
	... 58 more
Caused by: java.lang.ClassNotFoundException: android.support.design.widget.Snackbar
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 84 more
```

You must add 'com.android.support:design:25.3.1' as compile scope.
```groovy
dependencies {
    compile 'com.android.support:design:25.3.1'
}
```

**Comment by feresr** [comment]
I'm having this exact same issue and I'm not using ```org.mockito:mockito-inline:2.7.19```  just ```testCompile 'org.mockito:mockito-core:1.10.19'```

**Comment by about-midnight** [comment]
Any progress? 

Experiencing the same issue:
1) Create a kotlin class with a public method
2) Mock this class
3) Real public method gets called instead of the mocked one.
 
testImplementation 'org.mockito:mockito-core:2.11.0'

**Comment by Budincsevity** [comment]
Hi All

We are experiencing the same issue with Spring Boot and Kotlin.
Kotlin version: 1.2.0
Mockito version: org.mockito:mockito-all:1.10.19 and 2.0.2-beta

And the ` when(mockedService.sum()).thenReturn(actualSum)` line calls the real sum() method.

**Comment by TimvdLippe** [comment]
@Budincsevity Mockito 2.0.2-beta is rather old. Please update to 2.13.0 and see if that works.

**Comment by khamulbr** [comment]
Any news on this issue? I am experiencing the same issue, and I'm using mockito 2.18.3

**Comment by jaychang0917** [comment]
Latest version 2.23.11 still has this problem! Any progress?

**Comment by florian-d** [comment]
Any news on this issue? 
I'm using Mockito 3.0.

**Comment by TimvdLippe** [comment]
Would be great if someone with Kotlin expertise can determine whether this is problem in `mockito-kotlin` (which we don't maintain) or Mockito itself. PR would be greatly appreciated as well.

**Comment by tmurakami** [comment]
@jaychang0917, you need to add the `open` keyword to `Foo.foo`.

In Kotlin, all classes and members are **final**.
If you don't use the inline mock feature, you need to use the `open` keyword for members as well as the class you want to mock.

**Comment by GarthsKidStuff** [comment]
Still happening with version org.mockito:mockito-inline:3.2.0

**Comment by Nathandriel** [comment]
Seeing the same issue with mockito:2.28

**Comment by youranshul** [comment]
Facing the same issue with 
mockito_core_version        = "2.0.0-RC3"
    mockito_inline_version      = "2.8.9"

**Comment by TimvdLippe** [comment]
Your Mockito version is really old. Please update to Mockito 3+

**Comment by youranshul** [comment]
updated to 3.3.3 still the same issue

**Comment by youranshul** [comment]
> Your Mockito version is really old. Please update to Mockito 3+

updated to 3.3.3 still the same issue

**Comment by craigmiller160** [comment]
Really wish there was an answer here. Seeing the same problem myself. I made my class into an "open" class and I'm still having the problem where the real method is being called.

**Comment by rcgonzalezf** [comment]
@craigmiller160 I had the same issue, the problem is the method is final, if you can set the method to `open` the issue will go away. Isn't ideal but is a `workaround` that I used for a class. I think the solution will be that Mockito should complain about the final *method/function* instead of calling the real method.

**Comment by odravison** [comment]
I'm facing the same issue here.

**Comment by johnknelson** [comment]
Any updates or resolution on this issue that's been pending for three years?

**Comment by alpaca0984** [comment]
I'm having the same issue with mockito v3.7.0... Did someone find any workaround?

**Comment by anthonyalayo** [comment]
I know there's a big list of +1s here 🙃  but I am also hitting this which is unfortunate. I wanted to mock final objects/methods but have all the standard stubbing that `mockito-core` provides. Looks like this issue has existing for a long time, unfortunate.

**Comment by SarShalomSimchi** [comment]
I'm having the same issue with java

**Comment by mobigliani** [comment]
Could get around that in Java using different syntax:
`doReturn(value).when(mock).method(any(), any());`

**Comment by Kumaraditya-cardbyte** [comment]
Hey gys, 
I am facing the same issue, the mocked method is being called.

**Comment by jruiz94** [comment]
I'm facing the same issue but I fixed it with what @craigmiller160 said, you have to set the method to not `final`

However I agree with what they said here
 @craigmiller160 [...] I think the solution will be that Mockito should complain about the final _method/function_ instead of calling the real method.

Mockito should complain otherwise you spend all day figuring out what the heck is happening
