### ISSUE TITLE
Modifying invocation arguments results in incorrect verification

### ISSUE THREAD

**Issue by m35** [mockito/mockito#1153]
### Environment
mockito-core-2.8.9.jar
Windows 10
Java 1.8

### Issue

It's hard to summarize this issue. Modifying the invocation arguments also modifies what the verification uses. That may not be clear, so here is an example.

```
import org.junit.Assert;
import org.junit.Test;
import org.mockito.AdditionalMatchers;
import org.mockito.Mockito;
import org.mockito.invocation.InvocationOnMock;
import org.mockito.stubbing.Answer;

public class ModifyArgTest {

    public interface ModifyMyArgs {
        void modifyMe(byte[] buffer);
    }

    @Test
    public void testBug() {

        ModifyMyArgs mock = Mockito.mock(ModifyMyArgs.class);

        Mockito.doAnswer(new Answer<Void>() {
            @Override
            public Void answer(InvocationOnMock invocation) throws Throwable {
                byte[] buffer = invocation.getArgument(0);
                buffer[0] = 1;
                buffer[1] = 2;
                buffer[2] = 3;
                return null;
            }
        }).when(mock).modifyMe(AdditionalMatchers.aryEq(new byte[3]));

        byte[] actual = new byte[3];
        mock.modifyMe(actual);

        Assert.assertArrayEquals(new byte[] {1, 2, 3}, actual);

        // this next line should pass, but fails
        Mockito.verify(mock).modifyMe(AdditionalMatchers.aryEq(new byte[3]));
    }
}
```

The output is
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.306 sec <<< FAILURE! - in ModifyArgTest
testBug on testBug(ModifyArgTest)(ModifyArgTest)  Time elapsed: 0.766 sec  <<< FAILURE!
org.mockito.exceptions.verification.junit.ArgumentsAreDifferent: 
Argument(s) are different! Wanted:
modifyMyArgs.modifyMe(
    [(byte) 0x00, (byte) 0x00, (byte) 0x00]
);
-> at ModifyArgTest.testBug(ModifyArgTest.java:38)
Actual invocation has different arguments:
modifyMyArgs.modifyMe(
    [(byte) 0x01, (byte) 0x02, (byte) 0x03]
);
-> at ModifyArgTest.testBug(ModifyArgTest.java:34)

	at ModifyArgTest.testBug(ModifyArgTest.java:38)


Results :

Failed tests: 
  ModifyArgTest.testBug:38 
Argument(s) are different! Wanted:
modifyMyArgs.modifyMe(
    [(byte) 0x00, (byte) 0x00, (byte) 0x00]
);
-> at ModifyArgTest.testBug(ModifyArgTest.java:38)
Actual invocation has different arguments:
modifyMyArgs.modifyMe(
    [(byte) 0x01, (byte) 0x02, (byte) 0x03]
);
-> at ModifyArgTest.testBug(ModifyArgTest.java:34)


Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

I expected the test to pass.

**Comment by szczepiq** [comment]
Thank you for reporting! I absolutely agree that the current behavior of Mockito for this use case is not intuitive.

Here're the considerations:

- To fix the problem we would have to keep pristine copies of arguments with each invocation. This way, the verification would work on the pristine copies while mutating arguments with custom Answer would still be possible. Unfortunately, there is no safe way in Java to create a copy of any object. We would have to resort to ungodly hacks to make it happen and it would not work for every possible object anyway.
- This use case is very rare because mutating arguments using custom Answer is rare in the first place. Combined with verification on those arguments makes it extremely rare. Normally, we don't verify stubbed calls anyway.

How to solve the problem:
- [Best] Try to simplify the test / code under test. Do you really need to mutate arguments and also verify stubbing? Both of those actions might indicate a code smell.
- Relax the argument verification and use some kind of ```any()``` matcher
- Perform validation of arguments in the custom answer that mutates the arguments

If you have better ideas or suggestions please let us know!

Can you contribute an FAQ entry for this problem to Mockito wiki? This would be really helpful in case somebody else stumbles on this problem.

**Comment by szczepiq** [comment]
Added "please-contribute" label because we are missing FAQ entry on this use case.

**Comment by mureinik** [comment]
`org.mockito.internal.stubbing.answers.ClonesArguments` seems to do exactly @m35 needs, but we probably shouldn't advertise using something from an internal package in the FAQ.

Moreover - it doesn't seem accessible from any public part of Mockito. Perhaps we should add `AdditionalAnswers.clonesArguments`?

**Comment by dalewking** [comment]
Unfortunately, this is necessary when trying to mock JPA Repository save methods. Fortunately, if you can make a copy of the argument there is a workaround:

        invocation.getArguments()[0] = makeCopyOfArgument(argument);
