### ISSUE TITLE
java.lang.ClassCastException with generic types

### ISSUE THREAD

**Issue by shark300** [mockito/mockito#1174]
Hi,

I've tried this:

```
@Test
public void test() {
    given(testCollectionSourceProvider.getCollection(new ArrayList<Integer>())).willReturn(new ArrayList<>());
}

static class TestCollectionSourceProvider {
    <T extends Collection<E>, E> T getCollection(T collection) {
        return collection;
    }
}
```

But I've got an Exception with a very confusing message in Idea 2017.1.5 and Eclipse Neon.3:

```
java.lang.ClassCastException: java.util.LinkedList cannot be cast to java.util.ArrayList
	at com.example.demo.FailingTestWithCollectionsTest.test(FailingTestWithCollectionsTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
But it works from Maven.

If I cast it manually, it works from IDEs:

```
given((List<Integer>) testCollectionSourceProvider.getCollection(new ArrayList<Integer>())).willReturn(new ArrayList<>());
```

Java versions:

1. machine
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

> IntelliJ IDEA 2017.1.5
> Build #IC-171.4694.70, built on July 4, 2017
> JRE: 1.8.0_112-release-736-b21 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

> Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
> Maven home: C:\Maven
> Java version: 1.8.0_131, vendor: Oracle Corporation
> Java home: C:\Program Files\Java\jdk1.8\jre
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

2. machine
> java version "1.8.0_141"
> Java(TM) SE Runtime Environment (build 1.8.0_141-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.141-b01, mixed mode)

> Platform: Eclipse Neon.3 (4.6.3)
> Version: 3.9.0.RELEASE
> Build Id: 201707061903
> Windows 7

Please check it: https://github.com/shark300/ClassNotFoundException-in-Mockito

**Comment by shark300** [comment]
If I try a cast manually, it works:

```
given((List<Integer>) testCollectionSourceProvider.getCollection(new ArrayList<Integer>())).willReturn(new ArrayList<>());
```

**Comment by shark300** [comment]
An other workaround:

```
List<Integer> input = new ArrayList<>();
List<Integer> output = new ArrayList<>();
List<Integer> collection = testCollectionSourceProvider.getCollection(input);
given(collection).willReturn(output);
```

_org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues_ resolves Collection type to a _LinkedList_

**Comment by TimvdLippe** [comment]
> IntelliJ IDEA 2017.1.5
Build #IC-171.4694.70, built on July 4, 2017
JRE: 1.8.0_112-release-736-b21 amd64

This JRE build is quite old and older versions of Java 8 are known for compiler bugs. Please update your jdk in your IDE to resolve this issue. (Maven is correctly using one of the latest versions which are working).

Since this is very likely related to your Java version, I am closing this issue. Feel free to reopen if you can reproduce this issue in your IDE with one of the latest JDK versions.

**Comment by shark300** [comment]
I've got same Exception on this machine:

> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
> Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
> Maven home: C:\Maven
> Java version: 1.8.0_144, vendor: Oracle Corporation
> Java home: C:\Program Files\Java\jdk1.8\jre
> Default locale: en_US, platform encoding: Cp1252
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

> IntelliJ IDEA 2017.2.5
> Build #IU-172.4343.14, built on September 26, 2017
> Licensed to ...
> Subscription is active until ...
> JRE: 1.8.0_152-release-915-b12 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0

So to recap I can't reopen issue and you can reproduce this issue by using this code:

```
@Mock
private TestCollectionSourceProvider testCollectionSourceProvider;

@Test
public void test() {
   given(testCollectionSourceProvider.getCollection(new ArrayList<Integer>())).willReturn(new ArrayList<>());
}

static class TestCollectionSourceProvider {
   <T extends Collection<E>, E> T getCollection(T collection) {
        return collection;
   }
}

@Before
public void setUp() throws Exception {
    initMocks(this);
}
```

**Comment by TimvdLippe** [comment]
I have opened #1219. I am unable to reproduce this issue in both Intellij and with Gradle.

```
IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-97-generic
```
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by raphw** [comment]
Did you install some plugin in your IDE?

**Comment by shark300** [comment]
Have you tried Eclipse and Eclipse compiler in Idea?

2017. okt. 23. de. 6:34 ezt írta ("Rafael Winterhalter" <
notifications@github.com>):

Did you install some plugin in your IDE?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mockito/mockito/issues/1174#issuecomment-338545479>,
or mute
the thread

**Comment by TimvdLippe** [comment]
Yes I can reproduce this issue with the Eclipse compiler in IntelliJ. To enable the Eclipse compiler `File -> Settings -> Build, Execution, Deployment -> Compiler -> Java Compiler -> Use compiler`. Select `Eclipse`. Then recompile the test added in #1219 (`ctrl + shift + F9`) and then run the test.

**Comment by TimvdLippe** [comment]
@mockitoguy although we have the regression test to debug, the issue still exists :(

**Comment by shark300** [comment]
There is one different on bytecode level between javac and Eclipse compiler.

Javac:
```
public test()V
  @Lorg/junit/Test;()
   L0
    LINENUMBER 25 L0
    ALOAD 0
    GETFIELD com/example/demo/FailingTestWithCollectionsTest.testCollectionSourceProvider : Lcom/example/demo/FailingTestWithCollectionsTest$TestCollectionSourceProvider;
    NEW java/util/ArrayList
    DUP
    INVOKESPECIAL java/util/ArrayList.<init> ()V
    INVOKEVIRTUAL com/example/demo/FailingTestWithCollectionsTest$TestCollectionSourceProvider.getCollection (Ljava/util/Collection;)Ljava/util/Collection;
    INVOKESTATIC org/mockito/BDDMockito.given (Ljava/lang/Object;)Lorg/mockito/BDDMockito$BDDMyOngoingStubbing;
    NEW java/util/ArrayList
    DUP
    INVOKESPECIAL java/util/ArrayList.<init> ()V
    INVOKEINTERFACE org/mockito/BDDMockito$BDDMyOngoingStubbing.willReturn (Ljava/lang/Object;)Lorg/mockito/BDDMockito$BDDMyOngoingStubbing;
    POP
   L1
    LINENUMBER 26 L1
    RETURN
   L2
    LOCALVARIABLE this Lcom/example/demo/FailingTestWithCollectionsTest; L0 L2 0
    MAXSTACK = 3
    MAXLOCALS = 1
```

Eclipse:
```
public test()V
  @Lorg/junit/Test;()
   L0
    LINENUMBER 25 L0
    ALOAD 0
    GETFIELD com/example/demo/FailingTestWithCollectionsTest.testCollectionSourceProvider : Lcom/example/demo/FailingTestWithCollectionsTest$TestCollectionSourceProvider;
    NEW java/util/ArrayList
    DUP
    INVOKESPECIAL java/util/ArrayList.<init> ()V
    INVOKEVIRTUAL com/example/demo/FailingTestWithCollectionsTest$TestCollectionSourceProvider.getCollection (Ljava/util/Collection;)Ljava/util/Collection;
    CHECKCAST java/util/ArrayList
    INVOKESTATIC org/mockito/BDDMockito.given (Ljava/lang/Object;)Lorg/mockito/BDDMockito$BDDMyOngoingStubbing;
    NEW java/util/ArrayList
    DUP
    INVOKESPECIAL java/util/ArrayList.<init> ()V
    INVOKEINTERFACE org/mockito/BDDMockito$BDDMyOngoingStubbing.willReturn (Ljava/lang/Object;)Lorg/mockito/BDDMockito$BDDMyOngoingStubbing;
    POP
   L1
    LINENUMBER 26 L1
    RETURN
   L2
    LOCALVARIABLE this Lcom/example/demo/FailingTestWithCollectionsTest; L0 L2 0
    MAXSTACK = 3
    MAXLOCALS = 1
```

As you can see Eclipse comply an extra "CHECKCAST java/util/ArrayList" before BDDMockito.given invocation.

As I see, it is not illegal because getCollection method's return type is a subtype of ArrayList.

**Comment by TimvdLippe** [comment]
@raphw This regression test started failing on JDK9 when backporting our fixes from `release/2.x` to `master` in #1238: https://travis-ci.org/mockito/mockito/jobs/296206474#L773-L775

As such, this is not only an issue with the Eclipse compiler in IntelliJ, but with oraclejdk9 as well :cry: (Sadly I haven't been able to reproduce this issue locally yet)

**Comment by shark300** [comment]
@TimvdLippe I agree with you. I've tested localy with JDK9 and test was failed.

**Comment by TimvdLippe** [comment]
So I debugged this issue and it happens because generics are removed on run-time. As such, Mockito can only see that the return type is `Collection`. The whole reference to `T == ArrayList` has been reassured. Therefore, we have no way in knowing what the type should be and we do a best guess. This throws an exception, as it doesn't conform to the actual generics which is thrown in the `CHECKCAST`. I doubt we have any options here, as this is a core issue in Java instead.

**Comment by shark300** [comment]
If I understood java virtual machine documentation correctly in this case there is an INVOKESPECIAL and erased type before INVOKEVIRTUAL.

**Comment by ttanxu** [comment]
It seems `org.mockito.internal.stubbing.defaultanswers.ReturnsMocksTest#should_return_mock_value_for_generic_class()` is also susceptible to a similar issue with OpenJDK 9, where when the default return value of `classMock.execute()` is returned to `when()`.

That test can be worked around by using `doReturn("return")` series of methods though.

**Comment by shark300** [comment]
It's still failing with openjdk 11.0.2, junit-jupiter 5.4, mockito 3.0. BTW, it cannot be fixed.
