### ISSUE TITLE
Feature request: simultaneous stubbing

### ISSUE THREAD

**Issue by eugene-ivakhno** [mockito/mockito#1187]
Here is an example:

```
public class NestedStubbingTest {

    @Mock Supplier<String> supplier;

    @Mock Function<String, String> converter;

    @Test public void test() {
        initMocks(this);
        when(supplier.get()).thenReturn(prepareOutput("abcde", true));
        //...
    }

    private String prepareOutput(String output, boolean convertToUpperCase) {
        when(converter.apply(output)).thenReturn(convertToUpperCase ? output.toUpperCase() : output);
        return output;
    }
}
```

Currently the "outer" stubbing cannot be completed correctly because the "inner" one starts using `MockingProgress` before `thenReturn` of the first stubbing is called.
Result:
```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at my.package.NestedStubbingTest.test(NestedStubbingTest.java:20)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, you naughty developer!
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed


	at at my.package.NestedStubbingTest.prepareOutput(NestedStubbingTest.java:25)
	at at my.package.NestedStubbingTest.test(NestedStubbingTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
```

An obvious workaround is to make those stubbing sequentially. But it makes such convenient methods as `prepareOutput()` impossible.

Mockito version: `1.10.19`.

**Comment by ChristianSchwarz** [comment]
You should use a custom Answer in this case.

**Comment by eugene-ivakhno** [comment]
Thanks for this suggestion!
The following replacement helped:
`thenReturn(prepareOutput(...)` -> `thenAnswer(invocation -> prepareOutput(...))`.

Should I close this issue? Would still prefer to have the straightforward way work, of course. But the value of such improvement now looks minor.

**Comment by TimvdLippe** [comment]
An `Answer` is the intended feature for this usecase. A `thenReturn` states that only 1 possible answer is generated. As such, I am closing this issue. Thanks for reporting the issue!
