### ISSUE TITLE
ClassFormatError when trying to mock certain interfaces

### ISSUE THREAD

**Issue by chris-git** [mockito/mockito#1215]
Hi, 

I stumbled over some strange behaviour when trying to update from a 1.x version of Mockito to 2.x. One of my interfaces would no longer want to be mocked, throwing a MockitoException, with an error message of *Mockito cannot mock this class: interface &lt;MyInterfaceName&gt;*, ultimately triggered by a *java.lang.ClassFormatError: Duplicate field name&signature in class file &lt;MyInterfaceName&gt;$MockitoMock$1318839329*

This is the shortest code snippet I could come up with to reproduce the issue:

```java
import org.mockito.Mockito;

public class ClassFormatErrorTest {

    public static void main(String[] args) {
        // the next line will throw a MockitoException, caused by an
        // IllegalStateException, ultimately caused by ClassFormatError
        Mockito.mock(SimpleInterface.class);
    }

    private interface SimpleInterface {
        String getNameOfYs(X x, String str1, String str2, String str3);
        String getNameOfXs(Y y, String str1, String str2, String str3);
    }

    private class X {}
    private class Y {}
}
```

Software versions used:
* JVM version 1.8.0_151-b12 from Oracle (the issue also occurred with the version before)
* mockito-core 2.11.0 (also tried a few older versions, with the same result)
* on a Debian Linux system

Running above code creates the following output:

```
Exception in thread "main" org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface ClassFormatErrorTest$SimpleInterface.
Most likely it is due to mocking a private class that is not visible to Mockito

	at ClassFormatErrorTest.main(ClassFormatErrorTest.java:8)
Caused by: java.lang.IllegalStateException: Error invoking java.lang.ClassLoader#defineClass
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:412)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:185)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:187)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4456)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:115)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
	at org.mockito.Mockito.mock(Mockito.java:1821)
	at org.mockito.Mockito.mock(Mockito.java:1734)
	... 1 more
Caused by: java.lang.ClassFormatError: Duplicate field name&signature in class file ClassFormatErrorTest$SimpleInterface$MockitoMock$1318839329
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Direct.defineClass(ClassInjector.java:408)
	... 20 more
```

Before I created this short, self contained, single class example, I tried with the interface and two classes as separate files, with the same result, so it is not a problem of inner classes.

:exclamation: note that the interface's method names are important, they have to end in the class names + "s", otherwise the problem does not show.
:exclamation: also note that the methods have to take 4 parameters (works perfectly with only 3)

**Comment by raphw** [comment]
You found a bug in Byte Buddy. It computes a hash value for a unique identifier of a value and does not take the method types into accound what yields the same name for a field. This is illegal. Thanks for the report, this will be fixed in the next release.

**Comment by raphw** [comment]
So, this is the best bug I might ever have encountered. Byte Buddy requires stable names for fields that cache a value. I considered that using the hash of a `Method` would be good enough as those hashes should not collide.

Turns out that for your exact signature, due to the complementary use of X and Y in both methods, the hash calculation of `java.lang.reflect.Method` yields the exact same hash code. I need to add a check to Byte Buddy which assures that a new name is found if such a collision occurs.

This is primary because of the poor choice of hashing in the JVM but it is a really rare case despite the hash function. Thank you for reporting!

**Comment by raphw** [comment]
I have improved the collission strategy in Byte Buddy and I hope that this will be no more issue with the next release. If you change anything about your methods, the problem should no longer occur but I understand that this is not a good long term solution, I hope for your patience for the next releases of Byte Buddy and Mockito.

**Comment by chris-git** [comment]
Thanks for picking this up so quickly. In the meantime, I have slightly changed my method names. Not nice, but seems to be the least effort workaround. Fortunately, I don't need to worry about backwards compatibility in this case. I'll go back to the original names with the next update of Mockito.

**Comment by raphw** [comment]
Great, thanks for your patience and again, this is really unlucky. Changing a single letter anywhere in your signature or types fixes your problem in the meantime.
