### ISSUE TITLE
Re-stubbing from exceptional to non exceptional doesn't work

### ISSUE THREAD

**Issue by baztian** [mockito/mockito#1237]
Hi,

I want to re-stub a method that already has a default behaviour in the @Before method. The default behaviour is to throw an exception (CustomerNotFound) to simulate the behaviour on a newly setup instance of my system for any customer number. Of course I need tests describing the behaviour for existing customers. Unfortunately if I override the stubbing for some (or any) customer numbers the exception gets throws during stubbing phase.

I've written a minimal test case to show the problem. The second test `testOverrideWithNonExceptionalCase` fails.

    package mockito;
    
    import static org.hamcrest.core.Is.is;
    import static org.junit.Assert.assertThat;
    import static org.mockito.Mockito.when;
    
    import java.io.IOException;
    import java.io.InputStream;
    import org.junit.Rule;
    import org.junit.Test;
    import org.junit.rules.ExpectedException;
    import org.junit.runner.RunWith;
    import org.mockito.Mock;
    import org.mockito.junit.MockitoJUnitRunner;
    
    @RunWith(MockitoJUnitRunner.class)
    public class StubbingOverrideTest {
    
      @Mock
      private InputStream is;
    
      @Rule
      public final ExpectedException exception = ExpectedException.none();
    
      @Test
      public void testOverrideWithExceptionalCase() throws Exception {
        when(is.read()).thenReturn(42);
        when(is.read()).thenThrow(new IOException());
    
        exception.expect(IOException.class);
        is.read();
      }
    
      @Test
      public void testOverrideWithNonExceptionalCase() throws Exception {
        when(is.read()).thenThrow(new IOException());
        when(is.read()).thenReturn(42);
    
        assertThat(is.read(), is(42));
      }
    }

When running the test I get the following exception:
    
    java.io.IOException
    	at mockito.StubbingOverrideTest.testOverrideWithNonExceptionalCase(StubbingOverrideTest.java:37)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:78)
    	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:84)
    	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
    	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
    	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    
The problem exists in Mockito 2 (2.11.0) and Mockito 1 (1.10.19).

Of course to solve the problem in the show example I could just skip the first stubbing. But for my real problem it is a bit cumbersome. I would like to be able to specify a default behaviour that throws an exception.

**Comment by TimvdLippe** [comment]
Using lambdas, we could solve this usecase. I fear that in Mockito 1 and 2
this is a fundamental and unsolvable issue :(

I will try to tackle this issue in my prototype!

**Comment by G8XSU** [comment]
Should we edit this issue to include Re-stubbing with "exceptional to exceptional" along with "exceptional to non-exceptional" ?

Also, as i read if it is fundamental and unsolvable issue in Mockito 1 & 2.
Can we give warning to user that multiple thenThrows in single Unit Test are not supported.

**Comment by Marcono1234** [comment]
A workaround is to use `doReturn(...).when(...)`:
```java
when(is.read()).thenThrow(new IOException());
doReturn(42).when(is).read();
```
