### ISSUE TITLE
Provide Java 10 compatibility

### ISSUE THREAD

**Issue by sormuras** [mockito/mockito#1243]
I ran the JUnit 5 build on jdk-10-ea and encountered a Mockito-related issue.

```
  JUnit Jupiter:TestFactoryTestDescriptorTests:streamsFromTestFactoriesShouldBeClosed()
    MethodSource [className = 'org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptorTests', methodName = 'streamsFromTestFactoriesShouldBeClosed', methodParameterTypes = '']
    => org.mockito.exceptions.base.MockitoException: 

Mockito cannot mock this class: interface org.junit.jupiter.api.extension.ExtensionContext.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 10
JVM vendor name    : Oracle Corporation
JVM vendor version : 10-ea+29
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 10-ea+29
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.11.6-041106-generic

Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
```

See full log at: https://travis-ci.org/junit-team/junit5/builds/296747184
See JUnit 5 issue that tracks JDK-9+ related issues at: https://github.com/junit-team/junit5/issues/1063

I guess, there's command line switch that transforms the exception into a warning.

**Comment by TimvdLippe** [comment]
:cold_sweat: And we were just able to fix compatibility issues with JDK9 :joy: Is there a small reproduction example that we can add to our test suite and debug with?

**Comment by sormuras** [comment]
No, no small sample, yet. But I guess you'll similar issues when adding a "jdk-10" axis to your Travis CI build matrix. You're welcome to copy the installation script from https://github.com/junit-team/junit5/blob/jdk-10/src/scripts/install-jdk.sh ... usage in `.travis.yml` could look like:
```
install:
# "dot source" the jdk installation script
  - . ./src/scripts/install-jdk.sh

script:
  - ./gradlew build --scan --stacktrace
```

**Comment by sormuras** [comment]
It's ByteBuddy, @raphw `java.lang.IllegalArgumentException: Unknown Java version: 10
	at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)`

```
Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection

	at org.junit.jupiter.engine.execution.ExecutableInvokerTests.<init>(ExecutableInvokerTests.java:46)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.junit.platform.commons.util.ReflectionUtils.newInstance(ReflectionUtils.java:347)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:60)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:197)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateAndPostProcessTestInstance(ClassTestDescriptor.java:188)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstanceProvider$1(ClassTestDescriptor.java:181)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:80)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:60)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$2(HierarchicalTestExecutor.java:92)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$2(HierarchicalTestExecutor.java:92)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:430)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavailable.defineClass(ClassInjector.java:821)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:185)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:187)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4456)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:115)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
	at org.mockito.Mockito.mock(Mockito.java:1798)
	at org.mockito.Mockito.mock(Mockito.java:1711)
	... 50 more
Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
	at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
	at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:357)
	at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)
	... 67 more

```

**Comment by TimvdLippe** [comment]
Okay, that should be an easy fix: https://github.com/raphw/byte-buddy/blob/032d63eefca08d33b45e85e184dad28f752c6d76/byte-buddy-dep/src/main/java/net/bytebuddy/ClassFileVersion.java#L133 that depends on lines like https://github.com/raphw/byte-buddy/blob/032d63eefca08d33b45e85e184dad28f752c6d76/byte-buddy-dep/src/main/java/net/bytebuddy/ClassFileVersion.java#L72

E.g. if ASM defines an Opcode for Java 10, Byte Buddy can work on Java 10, such that Mockito works on Java 10, such that JUnit5 works on Java 10 :joy:

**Comment by sormuras** [comment]
...every 6 month. 🎉 

There must be better solution. Mock w/o generating byte code? Proxies? ;)

**Comment by TimvdLippe** [comment]
@raphw (I assume you have an OW2 ASM account, if you don't I can do it as well)

Could you open an issue over at their gitlab (https://gitlab.ow2.org/asm/asm/issues) to add support for Java 10 (and to make sure they update on time for future Java releases)?

**Comment by TimvdLippe** [comment]
All right, issue has been filed upstream at https://github.com/raphw/byte-buddy/issues/370 We can close this issue once BB is fixed and bumped in Mockito

**Comment by mockitoguy** [comment]
Nice! Thank you for following up on this!

**Comment by raphw** [comment]
This is fixed on master and will be part of the next Byte Buddy update.

**Comment by TimvdLippe** [comment]
@raphw Awesome work with the speedy fix. Soon we will need to enable Java 10 testing on Travis too, but let's create a separate issue for that 😄

**Comment by raphw** [comment]
I wonder if they already make the images accessible. But I agree: there will probably be regular breakages, what makes monitoring it worthwhile.

**Comment by sormuras** [comment]
You can install JDK10 via https://github.com/junit-team/junit5/blob/jdk-10/src/scripts/install-jdk.sh

**Comment by sormuras** [comment]
Thanks for the fix @raphw 

Fixed issue from the initial description via https://github.com/junit-team/junit5/commit/68d801aeb34e9964a77d622b0ab3c267151954e1

**Comment by TimvdLippe** [comment]
We are publishing a new version as we speak. Should land in maven central by tomorrow or so 🎉

**Comment by TimvdLippe** [comment]
https://bintray.com/mockito/maven/mockito/2.12.0 has been published. Doesn't show up in https://mvnrepository.com/artifact/org.mockito/mockito-core but I think it should "just work".
