### ISSUE TITLE
Unbounded recursion when spying with `mockito-inline`

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#1256]
Consider the following code:
```java
@Test
public void test() {
    ConcurrentMap<String, String> map = spy(new ConcurrentHashMap<>());
    map.putIfAbsent("a", "b");
}
```

Running it causes a `StackOverflowError`:
```
Configuring TestNG with: TestNG60Configurator
Exception in thread "TestNG-test=Surefire test-1" java.lang.StackOverflowError
        at org.mockito.internal.creation.bytebuddy.MockMethodDispatcher.get(MockMethodDispatcher.java:20)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:74)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:261)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:116)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:121)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:74)
        at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:261)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:116)
        at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:121)
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964)
        ...
```

Tested with Mockito 2.11.0 and 2.12.0. Do not happen if I disable `mockito-inline`. CC @raphw.

**Comment by raphw** [comment]
I will have a look, thanks!

**Comment by raphw** [comment]
The problem is that we use a hash map internally to store mock dispatchers. We need to exclude this map from checking for being a mock explicitly as the check involves reading from the map what triggers the recursion.
