### ISSUE TITLE
When mock-maker-inline is on, some tests with spies fail

### ISSUE THREAD

**Issue by teanlime** [mockito/mockito#1276]
HI!
When I enable mock-maker-inline in my Android project, some tests begin to fail when executed from Android Studio (all failing tests have spies). Tests pass when executed form gradle command.

Android Studio version: 3.1 Canary 5
Gradle version: 4.3.1
Android Gradle plugin: 2.3.3
Firebase (google play services): 11.6.2 

THE TESTED CLASS (stripped to minimum):
```
public class ChildFirebaseMessagingService extends FirebaseMessagingService {

    @Override
    public void onMessageReceived(@Nullable RemoteMessage message) {
        superOnMessageReceived(message);
    }

    protected void superOnMessageReceived(RemoteMessage message) {
        super.onMessageReceived(message);
    }
}
```

THE FAILING TEST:
```
@Test
    public void this_is_the_test_that_fails() {
        ChildFirebaseMessagingService listener = spy(new ChildFirebaseMessagingService());
        doNothing().when(listener).superOnMessageReceived(nullable(RemoteMessage.class));

        listener.onMessageReceived(null);

        verify(listener).superOnMessageReceived(nullable(RemoteMessage.class));
    }
```

ANDROID STUDIO ERROR:
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.package.ChildFirebaseMessagingService.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : JetBrains s.r.o
JVM vendor version : 25.152-b01
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_152-release-1024-b01
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.12.6


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class com.google.firebase.iid.zzb, class android.content.ContextWrapper, class android.content.Context, class java.lang.Object, interface android.content.ComponentCallbacks2, class com.google.firebase.messaging.FirebaseMessagingService, interface android.content.ComponentCallbacks, class com.package.ChildFirebaseMessagingService, class android.app.Service]

	at com.package.ChildFirebaseMessagingServiceTest.this_is_the_test_that_fails(ChildFirebaseMessagingServiceTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:78)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:84)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class com.google.firebase.iid.zzb, class android.content.ContextWrapper, class android.content.Context, class java.lang.Object, interface android.content.ComponentCallbacks2, class com.google.firebase.messaging.FirebaseMessagingService, interface android.content.ComponentCallbacks, class com.package.ChildFirebaseMessagingService, class android.app.Service]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	... 32 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:120)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:97)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:200)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:181)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
	at org.mockito.Mockito.spy(Mockito.java:1904)
	... 32 more
Caused by: java.lang.IllegalStateException: public final void com.google.firebase.messaging.FirebaseMessagingService.handleIntent(android.content.Intent) is inconsistent for 'this' reference: 0
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:4069)
	at net.bytebuddy.asm.Advice$StackMapFrameHandler$Default.translateFrame(Advice.java:4016)
	at net.bytebuddy.asm.Advice$AdviceVisitor.visitFrame(Advice.java:7309)
	at net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:1440)
	at net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1126)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:698)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:500)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:2941)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1633)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:171)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:92)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2639)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:181)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:117)
	... 45 more

```

**Comment by moltmann** [comment]
Hi,

byte buddy cannot mock classes on Android devices as the Android uses a
different byte code format. I am working on making the dexmaker mockmaker
<https://github.com/linkedin/dexmaker> capable of doing that but this
currently relies on yet not released Android P builds.

For now you can
- only mock final classes in host based tests, and
- mock non-final classes in on-device tests using the currently shipping
dexmaker-mockmaker.

Thanks
Philip

**Comment by teanlime** [comment]
Yes, I can see that the actual source of the issue is in this line:

`com.google.firebase.messaging.FirebaseMessagingService.handleIntent(android.content.Intent)`

And I am presuming it's the `Intent` class that causes the issue.

Thanks @moltmann. Looking forward to P coming out :)
