### ISSUE TITLE
Verify is not working with argThat

### ISSUE THREAD

**Issue by jrumbinas** [mockito/mockito#1278]
I'm getting `java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
` attempting to use `Mockito.argThat()` with `Mockito.verify`. `Mockito.any()` works as expected. Please run the test bellow: 
```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.runners.MockitoJUnitRunner;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.argThat;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class ArgThatBug {
    @Test
    public void testAnyMatcher() {
        Logger logger = spy(new Logger());
        logger.logEvent("anyMatcher");
        verify(logger).log(any(), any());
    }

    @Test
    public void testArgThat() {
        Logger logger = spy(new Logger());
        logger.logEvent("anyMatcher");
        verify(logger).log(any(), argThat(argument -> true));
    }

    static class Logger {

        public void logEvent(String name) {
            log("event: {0}", name);
        }

        void log(String format, Object... args) {
            System.out.printf(format, args);
        }
    }
}
```

Here's a full stacktrace:
```
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;

	at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:24)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:78)
	at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:151)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:76)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:148)
	at org.mockito.internal.invocation.InvocationsFinder$RemoveNotMatching.isOut(InvocationsFinder.java:140)
	at org.mockito.internal.util.collections.ListUtil.filter(ListUtil.java:16)
	at org.mockito.internal.invocation.InvocationsFinder.findInvocations(InvocationsFinder.java:23)
	at org.mockito.internal.verification.checkers.MissingInvocationChecker.checkMissingInvocation(MissingInvocationChecker.java:29)
	at org.mockito.internal.verification.Times.verify(Times.java:37)
	at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:21)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:73)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:32)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:36)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:37)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:98)
	at com.r9.MockitoBug$Logger$ArgThatBug$1292172572.log(Unknown Source)
	at com.r9.MockitoBug.testArgThat(ArgThatBug.java:31)
	
```

Version:

- junit 4.12
- mockito-core 2.2.8
- Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
- macOS 10.13.2 (17C88)

**Comment by TimvdLippe** [comment]
This probably happens because to match `VarArgs`, we need to annotate the matcher with `VarArgMatcher` (https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/internal/matchers/VarargMatcher.java) to understand you intended to match on actual var args. `Any` implements this interface, but a custom matcher passed to `argThat` does not, as `VarArgMatcher` is an internal interface. We probably need to expose this interface to make it usable by users.

**Comment by SimarFromCowbell** [comment]
Is there a plan for there to be a resolution to this issue?

**Comment by SimarFromCowbell** [comment]
For others who are facing this issue, this was pretty much my very inelegant workaround,
```
(Object obj) -> {
                           try {
                             String castedStr = (String) obj;
                             return castedStr.equals("test")
                        } catch(ClassCassException e) {
                        return false;
                        }
```

**Comment by rkrisztian** [comment]
I have a similar issue with `assertArg`:

```java
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.assertArg;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import java.text.MessageFormat;
import java.util.List;

import org.junit.jupiter.api.Test;

public class VarargAssertTest {

	static class ClassUnderTest {
		void methodUnderTest(String arg, Object... params) {
			System.out.println(MessageFormat.format(arg, params));
		}
	}

	@Test
	void testMethodUnderTest_withVarArg() {
		var mockedClass = mock(ClassUnderTest.class);

		mockedClass.methodUnderTest("arg", "param", new IllegalStateException("test exception"));

		verify(mockedClass).methodUnderTest(anyString(), assertArg((Object[] args) -> {
			assertThat(List.of(args)).last().isInstanceOf(IllegalStateException.class);
		}));
	}

	@Test
	void testMethodUnderTest_withVarArg_workaround() {
		var mockedClass = mock(ClassUnderTest.class);

		mockedClass.methodUnderTest("arg", "param", new IllegalStateException("test exception"));

		verify(mockedClass).methodUnderTest(anyString(), any(), assertArg((Object arg) -> {
			assertThat(arg).isInstanceOf(IllegalStateException.class);
		}));
	}

	@Test
	void testMethodUnderTest_noVararg() {
		var mockedClass = mock(ClassUnderTest.class);

		mockedClass.methodUnderTest("arg", "param");

		verify(mockedClass).methodUnderTest(anyString(), assertArg((String arg) -> {
			assertThat(arg).isEqualTo("param");
		}));
	}

}
```

=> `testMethodUnderTest_withVarArg` fails, the others pass.

**Comment by austek** [comment]
Same problem with 
```
org.jobrunr.scheduling.JobRequestScheduler#create(org.jobrunr.scheduling.JobBuilder)
org.jobrunr.scheduling.JobRequestScheduler#create(java.util.stream.Stream<org.jobrunr.scheduling.JobBuilder>)
```
