### ISSUE TITLE
Exception occurs when using Java 10 and Windows

### ISSUE THREAD

**Issue by Tibor17** [mockito/mockito#1300]
This is a hint for Mockito team to improve class loading via Bytebuddy.
I am a developer of Maven Surefire and have to support Java 10 in build process:
https://builds.apache.org/view/M-R/view/Maven/job/maven-surefire-pipeline/job/SUREFIRE-1463/83/console

I found this issue. I have to skip the unit class from test set.
This is the error:

[windows-jdk10-maven3.5.x] Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:357)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
[windows-jdk10-maven3.5.x] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)
[windows-jdk10-maven3.5.x] 	... 83 more
[windows-jdk10-maven3.5.x] Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Unavailable.defineClass(ClassInjector.java:821)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:185)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:187)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4456)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:115)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:138)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:161)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:355)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:41)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
[windows-jdk10-maven3.5.x] 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
[windows-jdk10-maven3.5.x] 	at org.mockito.Mockito.mock(Mockito.java:1798)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:108)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.doCreateMock(DefaultMockCreator.java:61)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:53)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
[windows-jdk10-maven3.5.x] 	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:62)
[windows-jdk10-maven3.5.x] 	... 61 more
[windows-jdk10-maven3.5.x] Caused by: java.lang.IllegalArgumentException: Unknown Java version: 10
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion.ofJavaVersion(ClassFileVersion.java:135)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion$VersionLocator$ForJava9CapableVm.locate(ClassFileVersion.java:357)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.ClassFileVersion.ofThisVm(ClassFileVersion.java:147)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:301)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:290)
[windows-jdk10-maven3.5.x] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:70)
[windows-jdk10-maven3.5.x] 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:184)
[windows-jdk10-maven3.5.x] 	... 83 more

**Comment by Tibor17** [comment]
After updating to version 2.12.3 the issue was gone!
