### ISSUE TITLE
verboseLogging breaks some stubbing

### ISSUE THREAD

**Issue by escitalopram** [mockito/mockito#1336]
When stubbing a method call with the original mock as an argument, this fails, because the logging code seems to calls the toString() method on the mock at the wrong time.

This test gets me an exception and works fine when I either remove the logging or change the argument for the stubbing.

    import static org.mockito.Mockito.mock;
    import static org.mockito.Mockito.when;
    import static org.mockito.Mockito.withSettings;
    
    import org.junit.Test;
    
    public class MockitoLogFail {
    
    	public interface Item {
    		boolean isSame(Item item);
    	}
    
    	@Test
    	public void testMockitoLogFail() {
    		Item item = mock(Item.class, withSettings().verboseLogging());
    		when(item.isSame(item)).thenReturn(true);
    	}
    }
--

    org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
    Boolean cannot be returned by toString()
    toString() should return String
    ***
    If you're unsure why you're getting above error read on.
    Due to the nature of the syntax above problem might occur because:
    1. This exception *might* occur in wrongly written multi-threaded tests.
       Please refer to Mockito FAQ on limitations of concurrency testing.
    2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
       - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.
    
    	MockitoLogFail.testMockitoLogFail(MockitoWtf.java:18)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by escitalopram** [comment]
I did some more research:

* I noticed that the problem not only appears when the mock is supposed to return itself, but with any mock as return value.

* The problem goes away when using the `Mockito.do*` methods, as recommended for spies.
