### ISSUE TITLE
Verifying class-level @Transactional-annotated Spring bean

### ISSUE THREAD

**Issue by djechelon** [mockito/mockito#1365]
Hi,

this is related to #529. I have an abstract BaseDao class that is annotated @Transactional to demand that every method invoked on the tool is wrapped in a transaction.

I am making caching tests to ensure that the DAO is (not) invoked on a cache miss (hit). I am invoking methods on a Manager class that @Autowires the DAO I want to spy.

I have tried to create a spy on my DAO in the following 3 ways:

- Mockito.spy(dao)
- Mockito.mock(dao.getClass(),AdditionalAnswers.delegatesTo(dao))
- @SpyBean on @Autowired in my test

1 and 2 were done in a BeanPostProcessor so the injected instance of the DAO was instrumented by Mockito (on the contrary calls from the manager would not be intercepted by Mockito).

Example code: (redacted for simplification and clarity)

```
public class MyManagerImpl extends BaseManager<MyEntity> implements MyManager {

    @Autowired
    private MyDao dao; //I want to spy this

}

@Transactional(propagation=MANDATORY)
public abstract class AbstractDaoImpl<T> implements AbstractDao {

    public List<T> list(){
        //Hibernate implementation
    }

}

```
Test class:

```
public class MyManagerTests {

    @Autowired
    private MyDao dao; //I want to verify this

    @Autowired
    private MyManager unitUnderTest;

    @Test
    public void cacheTest() {

        unitUnderTest.list(); //Cache miss first time
        verify(dao,times(1)).list();

        unitUnderTest.list(); //Cache hit
        verify(dao,times(0)).list();

        unitUnderTest.create(...); //Cache invalidate
        unitUnderTest.list(); //Cache miss first time
        verify(dao,times(1)).list();

    }

}
```

The problem is that the above code produces IllegalTransactionState by Spring:

The below happens on approaches 1 and 2 **without Spring boot** in the classpath:

```
org.springframework.transaction.IllegalTransactionStateException: No existing transaction found for transaction marked with propagation 'mandatory'
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:359)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:461)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy90.getMockitoInterceptor(Unknown Source)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.getHandler(SubclassByteBuddyMockMaker.java:133)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.getHandler(ByteBuddyMockMaker.java:35)
	at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:81)
	at org.mockito.internal.util.DefaultMockingDetails.isMock(DefaultMockingDetails.java:35)
	at org.mockito.internal.MockitoCore.verify(MockitoCore.java:87)
	at org.mockito.Mockito.verify(Mockito.java:2038)
	at it.phoenix.web.data.managers.spring.FolderManagerTests.testCreateCustomFolderCached(FolderManagerTests.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

The below happens on approach 3:
```
org.springframework.transaction.IllegalTransactionStateException: No existing transaction found for transaction marked with propagation 'mandatory'
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:359)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:461)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.boot.test.mock.mockito.MockitoAopProxyTargetInterceptor.invoke(MockitoAopProxyTargetInterceptor.java:66)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy92.getMockitoInterceptor(Unknown Source)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.getHandler(SubclassByteBuddyMockMaker.java:133)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.getHandler(ByteBuddyMockMaker.java:35)
	at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:81)
	at org.mockito.internal.util.DefaultMockingDetails.isMock(DefaultMockingDetails.java:35)
	at org.springframework.boot.test.mock.mockito.MockReset.get(MockReset.java:107)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.resetMocks(ResetMocksTestExecutionListener.java:69)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.resetMocks(ResetMocksTestExecutionListener.java:55)
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.afterTestMethod(ResetMocksTestExecutionListener.java:50)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

The first stack trace suggests me that when Mockito / ByteBuddy is retrieving the mock handler of the bean, without yet invoking any methods of it, it actually invokes the class-level advisors. Personally I find it unusual.

Class-level transactional annotation suggests that every method (including new methods in inherited classes) uses the transactional annotation. Retrieving an instance of a transactional-annotated object should not trigger the advisors.

I have discovered this behaviour only because I set propagation to MANDATORY and I want to make out-of-transaction verifications with Mockito.

Removing the class-level annotation solves this specific problem. I will try to solve further problems on my own or discuss them on SO.

Any ideas about this issue? I wouldn't like either to wrap verifications in a fictional transactions or worse redesign my API classes to not enforce transactional checking on actual method invocations.

Thank you.

**Comment by djechelon** [comment]
Okay I have thought more on the issue and want to share my findings.
It looks like this is caused by both Spring proxying and Bytebuddy subclass mocking.

Look at the stack trace

```
at com.sun.proxy.$Proxy92.getMockitoInterceptor(Unknown Source)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.getHandler(SubclassByteBuddyMockMaker.java:133)
```

And the [source code](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassByteBuddyMockMaker.java#L129)

```
    @Override
    public MockHandler getHandler(Object mock) {
        if (!(mock instanceof MockAccess)) {
            return null;
        }
        return ((MockAccess) mock).getMockitoInterceptor().getMockHandler();
    }
```

Basically the argument `mock` is an instance of the mockm which is a subclass of the Spring bean. According to Spring class-level annotations, they are effective by design on the target class and its subclasses. After all, I wouldn't annotate @Transactional an abstract class if I don't want to demand all subclasses to follow the transactional advisor.

And here is where ByteBuddy comes. My findings suggest that BB creates a mock under the form of a subclass of your target object which also implements `MockAccess`.

So now you have a subclass of `AbstractDaoImpl`, which mandates all methods to be run in a transaction, which legally defines a new method `getMockitoInterceptor`. According to Spring rules, it must be run in a transaction because of the aforementioned statement.

Of course this is in contrast with intuitiveness, but it's really just like that.

I don't think there is anything Mockito can do. Any comments to share?
