### ISSUE TITLE
Mockito android IllegalStateException

### ISSUE THREAD

**Issue by johnygeorge** [mockito/mockito#1370]
I am trying to mock a class using `Mockito-Android`. But I am getting `IllegalStateException` when I do so. 

I just mock a class like this `Wrapper wrapper = mock(ClassName.class);`

Tried different versions of the library, still I have the same issue. At present I am using version `2.18.0` the latest release. I have the following dependency in my gradle file.

   `androidTestImplementation "org.mockito:mockito-android:2.18.0"`

    java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
    at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
    at java.lang.reflect.Proxy.invoke(Proxy.java:913)
    at $Proxy4.isTypeMockable(Unknown Source)
    at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
    at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
    at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
    at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
    at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
    at org.mockito.Mockito.mock(Mockito.java:1875)
    at org.mockito.Mockito.mock(Mockito.java:1784)
    at com.example.ui.MockClassName.<init>(MockClassName.java:36)
    at com.example.ui.mockMasterTests.LoginActivityTests.SettingsFragmentTest.init(SettingsFragmentTest.java:52)
    at java.lang.reflect.Method.invoke(Native Method)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
    at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
    at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
    at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:109)
    at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:109)
    at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:109)
    at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:109)
    at android.support.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:109)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
    at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)
    Caused by: java.lang.ExceptionInInitializerError
    at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
    at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:43)
    at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:32)
    at org.mockito.internal.configuration.plugins.PluginFinder.findPluginClass(PluginFinder.java:38)
    at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:43)
    at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
    at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
    at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
    at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
    at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:34)
    at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
    ... 44 more
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.mockito.plugins.StackTraceCleanerProvider org.mockito.internal.configuration.plugins.PluginRegistry.getStackTraceCleanerProvider()' on a null object reference
    at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:24)
    at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:20)
    ... 55 more

**Comment by TimvdLippe** [comment]
The exception points to https://github.com/mockito/mockito/blob/3f842f139731e9bb64ef476d9500beadb1ddf298/src/main/java/org/mockito/internal/configuration/plugins/Plugins.java#L24 where `registry` would be `null`, but that makes no sense at all :thinking:

**Comment by raphw** [comment]
What Android version are you using?

**Comment by johnygeorge** [comment]
Latest. Android 8.1

**Comment by bogdanzurac** [comment]
This happens with 2.19 as well, Android P Developer Preview. I've seen several issues open on this issue tracker regarding this problem, dating from several months back. Does that mean that instrumentation tests have never worked on Android with a Kotlin code base? Because we are required to use the inline mock maker for closed classes on Kotlin.

```
androidTestImplementation("com.nhaarman.mockitokotlin2:mockito-kotlin:2.0.0-RC1", {
        exclude group: 'org.mockito', module: 'mockito-core'
    })
    androidTestImplementation 'org.mockito:mockito-android:2.19.0'
```

Error Log:

```
Caused by: org.mockito.exceptions.base.MockitoInitializationException:
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)


IMPORTANT INFORMATION FOR ANDROID USERS:

The regular Byte Buddy mock makers cannot generate code on an Android VM!
To resolve this, please use the 'mockito-android' dependency for your application:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22mockito-android%22%20g%3A%22org.mockito%22

Java               : 0.9
JVM vendor name    : The Android Project
JVM vendor version : 2.1.0
JVM name           : Dalvik
JVM version        : 0.9
JVM info           : null
OS name            : Linux
OS version         : 4.4.116-g6999c7c9f794
```
