### ISSUE TITLE
Mockito 1.10.19 mock returns null instead of result

### ISSUE THREAD

**Issue by plamenkolev2** [mockito/mockito#1374]
Mocking rest template to return a response entity fails, instead of receiving a response entity, the value returned by the mock is null.

The following snippet should make it possible to reproduce the issue

```
public class Powerangers {

    public static void main(String[] args) {
        ResponseEntity response = new ResponseEntity<>(new ArrayList<>(), HttpStatus.ACCEPTED);
        RestTemplate newRestTemplate = mock(RestTemplate.class);
        when(newRestTemplate.postForEntity(any(), any(), any())).thenReturn(response);
        Object shouldNotBeNull = newRestTemplate.postForEntity("asd", new Object(), Object.class);

        if(shouldNotBeNull == null) {
            throw new IllegalArgumentException("hello from null");
        }
    }
}
```
This issue has been observed in mockito `1.10.19`

**Comment by raphw** [comment]
We do no longer support older versions of Mockito. Please update to 2.x.

**Comment by JavaHello** [comment]
> 类似这样的问题
```java
    UserInfoService userService = mock(UserInfoService.class);
    UserInfo user1 = new UserInfo();
    Long id = 1L;
    when(userService.save(user1)).thenReturn(id);
    // 如果 user 没有覆盖 equals 和 hashCode 则不会返回 1L
    UserInfo user2 = new UserInfo();
    Long userId = userService.save(user2);
    System.out.println(userId);
    Assert.assertEquals("保存失败", userId, id);
```
> 运行结果

```txt
0
Exception in thread "main" java.lang.AssertionError: 保存失败 expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
```

**Comment by bric3** [comment]
Sorry mockito 1.x is not anymore supported.

**Comment by nnlover** [comment]
maybe you have a final field, and has a constructor with this field, if that, please remove final and this constructor;

**Comment by SiyanGuo** [comment]
This happened to me.  It turns out that I FORGOT to override equals(), hashCode(), toString() in my Class.
