### ISSUE TITLE
[W7/Java8] Could not initialize plugin: interface org.mockito.plugins.MockMaker

### ISSUE THREAD

**Issue by rcornell** [mockito/mockito#1383]
I've seen this issue occur in other Issues posted here as well as on StackOverflow, but mine seems particularly weird and none of the other posts' resolutions have worked for me.

My current project at work has ~80 tests that use Mockito 2.18.3 + Scalatest 3.0.5 together, including the `mock-maker-inline` config to be able to use the new engine and mock/spy on final classes.

All of the tests run just fine using IntelliJ Idea's test runner/debugger. When I (locally) run the `mvn test` lifecycle, since this is what happens in our deployment, all of the tests that use the final class mock fail with the stack below.

I'm importing Mockito in my pom.xml as follows

```
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-core</artifactId>
    <version>2.18.3</version>
</dependency>
```

Getting the trace below. Any tips would be appreciated.

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
  at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
  at com.sun.proxy.$Proxy26.isTypeMockable(Unknown Source)
  at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
  at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
  at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
  at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
  at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
  at org.mockito.Mockito.mock(Mockito.java:1875)
  at org.mockito.Mockito.mock(Mockito.java:1784)
  at org.scalatest.mockito.MockitoSugar$class.mock(MockitoSugar.scala:73)
  ...
  Cause: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@2bebb74f
  at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
  at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
  at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
  at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
  at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
  at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:232)
  at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
  at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
  ...
  Cause: org.mockito.exceptions.base.MockitoInitializationException: Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.161-b12
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_161-b12
JVM info           : mixed mode
OS name            : Windows 7
OS version         : 6.1
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:171)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Unknown Source)
  at java.lang.Class.newInstance(Unknown Source)
  at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
  at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
  ...
  Cause: java.lang.IllegalStateException: No compatible attachment provider is available
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:366)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:351)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:319)
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:305)
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:101)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
  at java.lang.reflect.Constructor.newInstance(Unknown Source)
  at java.lang.Class.newInstance(Unknown Source)
  ...
```

**Comment by hmedat** [comment]
Any updates?

**Comment by TimvdLippe** [comment]
Could you create an example project that we can debug?

**Comment by vpchelko** [comment]
Its working if run/debug separate test. But attempt to run multiple tests using "mvn test" or  "mvn scalatest:test" failed with MockMaker error:

Java               : 1.8                                                                                         
JVM vendor name    : Oracle Corporation                                                                          
JVM vendor version : 25.211-b12                                                                                  
JVM name           : Java HotSpot(TM) Client VM                                                                  
JVM version        : 1.8.0_211-b12                                                                               
JVM info           : mixed mode, sharing                                                                         
OS name            : Windows 10                                                                                  
OS version         : 10.0                                                                                        
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:172)  
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                       
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)                                       
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)                                   
  at java.lang.reflect.Constructor.newInstance(Unknown Source)                                                   
  at java.lang.Class.newInstance(Unknown Source)                                                                 
  at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:96)                      
  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:45)                    
  at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)                    
  at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)                                
  ...                                                                                                            
  Cause: java.lang.IllegalStateException: No compatible attachment provider is not available                     
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:347)                                         
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:332)                                         
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:300)                                         
  at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:286)                                         
  at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:102)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                       
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)                                       
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)                                   
  at java.lang.reflect.Constructor.newInstance(Unknown Source)                                                   
  at java.lang.Class.newInstance(Unknown Source)

**Comment by vpchelko** [comment]
The problem caused by simple code:

package service

import grizzled.slf4j.Logging
import org.scalatest.FlatSpec
import org.scalatest.mockito.MockitoSugar
import org.Service
//
class ServiceSpec extends FlatSpec with Logging {
  val serviceMock = MockitoSugar.mock[Service]
...
}

**Comment by Velmurugan-Asokan** [comment]
I also have same issue

**Comment by cuneytykaya** [comment]
Hi @rcornell
Any update on this issue? Did you find a solution?
I get the same error when I use **jmockit** and **mockito-inline** together in a project. 

Thanks in advance.
