### ISSUE TITLE
Unable to mock (non-final) classes in Android Instrumentation tests, as they're seen as final.

### ISSUE THREAD

**Issue by SammyOdenhoven** [mockito/mockito#1388]
I'm unable to mock classes in Android Instrumentation tests, because they're recognised as final, even though they are not. 

`androidTestImplementation "org.mockito:mockito-android:2.18.3"`

```
@RunWith(AndroidJUnit4::class)
class LoginStoreTest : BaseInstrumentationTest() {

    var mockTokenStore = mock(TokenStore::class.java)

    private lateinit var loginStore: LoginStore

    @Before
    override fun setUp() {
        super.setUp()

        MockitoAnnotations.initMocks(this)

        loginStore = LoginStore(
                mockTokenStore
        )
    }

    @Test
    fun testTest() {
        loginStore.runSomeCode()
    }
}
```
and
```
@Singleton
class LoginStore @Inject constructor(
        private val tokenStore: TokenStore
) {
    fun runSomeCode() {

    }
}
```
Error: 
```
org.mockito.exceptions.base.MockitoException:
Cannot mock/spy class com.app.TokenStore
Mockito cannot mock/spy because :
- final class
at com.app.LoginStoreTest.<init>(LoginStoreTest.kt:15)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```
I've tried using alternatives to just marking the class as `open`, as described here: https://github.com/mockito/mockito/issues/1082, but none of them work. I assume because there is an underlying issue, that is also causing the mock to fail if the class is simply marked as `open`.

**Comment by SammyOdenhoven** [comment]
The Kotlin all-open plugin (as described in [#1082](https://app.intercom.io/a/apps/nsutd8yx/messages/messages/auto/all)) did the trick for me in the end.

**Comment by liujoshua** [comment]
I'm unable to mock Java interfaces. Could this be because I'm using the Kotlin plugin? Not sure why this would affect a Java interface

**Comment by dengkmfromCG** [comment]
when I mock a package class,it will throw the same exception. My gradle is
    testImplementation 'org.robolectric:robolectric:4.2'
    testImplementation 'org.mockito:mockito-core:2.8.9'
    testImplementation 'org.powermock:powermock-module-junit4:1.7.4'
    testImplementation 'org.powermock:powermock-module-junit4-rule:1.7.4'
    testImplementation 'org.powermock:powermock-api-mockito2:1.7.4'
