### ISSUE TITLE
Mockito 2.18.3 incorrect invocation records

### ISSUE THREAD

**Issue by oiale** [mockito/mockito#1393]
I am sorry if the code snippet I provided is too complex for the purpose of showing the bug (?).
The short description would be: If I try to record invocation of a dependency method which is called with a keyset of a map and that map changes afterwards, then the invocation records are incorrect.

Versions:
 - java 1.8.0_162 (for a certain reason I cannot go to 172 yet)
 - mockito 2.18.3
 - hamcrest 1.3
 - junit 4.12

In the following code snippet I get this exception:
```
 Exception:
 Argument(s) are different! Wanted:
 mockDependency.method([world, hello]);
 -> at MockitoBug.bugTest(MockitoBug.java:28)
 Actual invocation has different arguments:
 mockDependency.method([world]);
 -> at Tested.testedMethod(MockitoBug.java:47)
```

Code output:
```
Tested.testedMethod() before dependency call: [world, hello]
Tested.testedMethod() after dependency call: [world, hello]
Tested.testedMethod() after remove call: [world]
```

Code snippet:
```
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class MockitoBug {

  @Mock
  private Dependency mockDependency;
  
  @Test
  public void bugTest() {
    Set<String> input = new HashSet<>();
    input.add("hello");
    input.add("world");
    
    new Tested(mockDependency).testedMethod(input);
    
    verify(mockDependency, times(1)).method(input);
    /*
     * Exception:
     * Argument(s) are different! Wanted:
     *  mockDependency.method([world, hello]);
     * -> at MockitoBug.bugTest(MockitoBug.java:28)
     * Actual invocation has different arguments:
     * mockDependency.method([world]);
     * -> at Tested.testedMethod(MockitoBug.java:47)
     */
  }
  
}

class Tested {
  
  private static final String ILLEGAL = "hello";
  
  private final Dependency dependency;
  
  public Tested(Dependency dependency) {
    this.dependency = dependency;
  }
  
  public void testedMethod(Set<String> input) {
    Map<String, Integer> data = mapInput(input);
    
    System.out.println("Tested.testedMethod() before dependency call: " + data.keySet());
    dependency.method(data.keySet()); 
    System.out.println("Tested.testedMethod() after dependency call: " + data.keySet());
    
    // does mockito rely on the actual object to report  ???
    data.remove(ILLEGAL); 
    // or data.keySet().remove(ILLEGAL);
    // or data.put("something", 2);
    
    System.out.println("Tested.testedMethod() after remove call: " + data.keySet());
    
    // do something else
  }

  private Map<String, Integer> mapInput(Set<String> input)
  {
    Map<String, Integer> data = new HashMap<>();
    
    for (String s : input) {
      data.put(s, 1); 
    }
    
    return data;
  }
}

class Dependency {
  public void method(Set<String> input) {
    // do some stuff
  }
}
```

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)

**Comment by oiale** [comment]
The same problem occurs when you use a different collection (set) and modify it after the call.

If it is not a bug, but a suggestion to not pass objects that can be modified inside of the called method (???) then the exception should contain additional information.
