### ISSUE TITLE
"java.lang.NoSuchMethodError: org.mockito.Mockito.mockitoSession()" error in 'beforeEach' method inside MockitoExtension

### ISSUE THREAD

**Issue by svichkar** [mockito/mockito#1394]
Dependecies:

junit-jupiter-api:  5.2.0
junit-jupiter-engine: 5.2.0
mockito-core: 2.18.3
mockito-junit-jupiter: 2.18.3

Test:

```
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.WARN)
public class AccountTest
{
 @InjectMocks
  private Account account;
 @Mock
  private AccountConfiguration accountConfiguration;

 @Test
  public void shouldSetAccountInfoToRequest()
  {
     // test logic
  }
}
```
![selection_267](https://user-images.githubusercontent.com/13480692/40347169-ef77e050-5da7-11e8-9cea-7bdcc247ca0e.png)

**Actual result:**
```
java.lang.NoSuchMethodError: org.mockito.Mockito.mockitoSession()Lorg/mockito/session/MockitoSessionBuilder;
	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:112)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$0(TestMethodTestDescriptor.java:129)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:155)
```

**Comment by cburns93** [comment]
I also get this when doing something has basic as above.

**Comment by jankoprowski** [comment]
Which version of the InteliJ IDEA you are using?

**Comment by cburns93** [comment]
2018.1 however I don't have this issue anymore.

**Comment by kamilgregorczyk** [comment]
I'm having the same issue

**Comment by nliu365** [comment]
@kamilgregorczyk your solution is working. Thank you.

**Comment by csapty12** [comment]
@kamilgregorczyk Similarly, if you are using mockito-core as your artifact id, remove that dependency your pom.xml, this worked for me

**Comment by polq** [comment]
In case the solution specified here didn't solve the problem, try deleting excessive lines that overlap libraries from .iml file (If you use IDEA). 

I had following lines: 
```
<orderEntry type="library" name="org.junit.jupiter:junit-jupiter:5.5.0" level="project" />
<orderEntry type="library" name="org.mockito:mockito-core:2.10.0" level="project" />
......
<orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-engine:5.4.2" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.apiguardian:apiguardian-api:1.0.0" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-engine:1.4.2" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.junit.jupiter:junit-jupiter-api:5.4.2" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.junit.platform:junit-platform-commons:1.4.2" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-junit-jupiter:3.2.4" level="project" />
<orderEntry type="library" scope="TEST" name="Maven: org.mockito:mockito-core:3.2.4" level="project" />
```
    
Deleting two first lines worked for me.

**Comment by umashankara** [comment]
Thanks for kamilgregorczyk  & csapty12.

Exclusion of mockito-all and mockito-core worked for me

**Comment by toficzak** [comment]
Worked for me as well, thanks guys!
