### ISSUE TITLE
InOrder is not consistent with times

### ISSUE THREAD

**Issue by raymon-02** [mockito/mockito#1397]
Mockito version: 1.10.19
JUnit version: 4.12

Test class with one single test that fails:
```java
@RunWith(MockitoJUnitRunner.class)
public class MyTest {

    @Mock
    private MyClass myClass;

    @Before
    public void setUp() {
        when(myClass.getInt()).thenReturn(1).thenReturn(2).thenReturn(3);
    }

    @Test
    public void test() {
        myClass.doNothingPre();
        int i = myClass.getInt();
        myClass.doNothingPost();
        int j = myClass.getInt();

        myClass.doNothingPre();
        double id = myClass.getDouble();
        myClass.doNothingPost();
        double jd = myClass.getDouble();

        int c = 0;
        for (int k = 0; k < 10; k++) {
            c += myClass.getInt();
        }
        System.out.println(i + j + id + jd + c);


        InOrder inorder = inOrder(myClass);
        inorder.verify(myClass, times(2)).getInt();
//        inorder.verify(myClass).getInt();
//        inorder.verify(myClass).getInt();
        inorder.verify(myClass, times(2)).getDouble();
        inorder.verify(myClass, times(10)).getInt();

        verify(myClass, times(2)).doNothingPre();
        verify(myClass, times(2)).doNothingPost();

        verifyNoMoreInteractions(myClass);
    }

}
```

It fails with `VerificationInOrderFailure`:
```
Verification in order failure:
myClass.getInt();
Wanted 2 times:
-> at test.example.MyTest.test(MyTest.java:43)
But was 12 times. Undesired invocation:
-> at test.example.MyTest.test(MyTest.java:37)
```

But if I uncomment two lines and comment line above it will pass:
```java
//        inorder.verify(myClass, times(2)).getInt();
        inorder.verify(myClass).getInt();
        inorder.verify(myClass).getInt();
```

If I understand right Mockito uses greedy algo for `InOrder` verification though both cases should fail but the second one doesn't. Intuitively they looks identically and I expect that both cases work one way.
If it's not a bug could you please explain the difference between these two variants of code?

**Comment by Sarev0k** [comment]
I want to add that the section in the wiki under [more complex examples](https://github.com/mockito/mockito/wiki/Greedy-algorithm-of-verification-InOrder#more-complex-examples) is also unhelpful.

If I have the following code:
```java
mock.add("A");
mock.add("A");
mock.add("B");
mock.add("A");
```

How am I supposed to verify that the last add("A") occurs after the add("B")?

If I write the following:
```java
inOrder.verify(mock, times(2)).add("A");
inOrder.verify(mock, times(1)).add("B");
inOrder.verify(mock, times(1)).add("A");
inOrder.verifyNoMoreInteractions(mock);
```

It fails at the first verification, because add("A") was called a total of 3 times.

When I'm using inOrder, I expect to be able to verify all calls in order.  Your current implementation, prevents me from doing this, defeating the entire purpose of this API for my use case.

**Comment by raymon-02** [comment]
One more example:
```java
@RunWith(MockitoJUnitRunner.class)
public class MyTest {

    @Mock
    private MyClass myClass;

    @Before
    public void setUp() {
        when(myClass.getInt()).thenReturn(1);
        when(myClass.getDouble()).thenReturn(1.0);
    }

    @Test
    public void test() {

        myClass.getInt();
        myClass.getInt();
        myClass.getDouble();
        myClass.getInt();

        InOrder inorder = inOrder(myClass);
        inorder.verify(myClass, times(2)).getInt();
//        inorder.verify(myClass, times(1)).getInt();
//        inorder.verify(myClass, times(1)).getInt();
        inorder.verify(myClass, times(1)).getDouble();
        inorder.verify(myClass, times(1)).getInt();

        verifyNoMoreInteractions(myClass);
    }

}
```
It suddenly passes.
But with
```java
@Test
    public void test() {

        myClass.getInt();
        myClass.getInt();
        myClass.getDouble();
        myClass.getInt();

        InOrder inorder = inOrder(myClass);
//        inorder.verify(myClass, times(2)).getInt();
        inorder.verify(myClass, times(1)).getInt();
        inorder.verify(myClass, times(1)).getInt();
        inorder.verify(myClass, times(1)).getDouble();
        inorder.verify(myClass, times(1)).getInt();

        verifyNoMoreInteractions(myClass);
    }
```
it fails.
And it's the opposite situation that you've described above.
How is that happening? And what did I wrong? It's really confusing.

**Comment by Sarev0k** [comment]
Huh, you're right.  I was completely wrong about the way that this worked.  The use case I described as not working completely works, I must have run into a test error to make me think otherwise.

The reason your second use case fails is due to the greedy matcher.  If two calls happen in succession, verification will fail unless you explicitly match both calls.  [This wiki](https://github.com/mockito/mockito/wiki/Greedy-algorithm-of-verification-InOrder) describes how this works, and the reasoning for why they choose to use a greedy vs non-greedy matcher.
