### ISSUE TITLE
Cannot mock org.json.simple.JSONObject in full suite

### ISSUE THREAD

**Issue by black-snow** [mockito/mockito#1428]
check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

Mockito Version: 2.19.0  
OS: Win 10 Pro  
Java: jdk 1.8 171

I opted for the `org.mockito.plugins.MockMaker`.

I have a test that runs fine when I execute it standalone in eclipse but fails when I run all tests.

Here's the test:

```java
package a.b.c;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;
import org.json.simple.JSONObject;
import org.junit.Test;

public class MyTest {

    @Test
    public void testIt() {
        JSONObject fix = mock(JSONObject.class);
        when(fix.get("T_ID")).thenReturn(13l);

        Item cut = new Item(fix);
        assertEquals(13l, cut.id);
    }

}
```
Here's the Item, nothing special:

```java
package a.b.c;
public class Item {

    public long id;

    /**
     * Create a mapping from a json object.
     *
     * @param json
     */
    public TenderItem(JSONObject json) {
        this.id = (long) json.get("T_ID");
    }
}
```

Now when I have the test open and hit alt+shift+x (run single test) the test runs fine. When I test the whole project I end up with this:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.json.simple.JSONObject.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.171-b11
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_171-b11
JVM info           : mixed mode
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.util.Map, interface java.io.Serializable, class java.util.AbstractMap, interface org.json.simple.JSONAware, interface org.json.simple.JSONStreamAware, interface java.lang.Cloneable, class org.json.simple.JSONObject, class java.util.HashMap]
	at a.b.c.ItemTest.testIt(ItemTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.util.Map, interface java.io.Serializable, class java.util.AbstractMap, interface org.json.simple.JSONAware, interface org.json.simple.JSONStreamAware, interface java.lang.Cloneable, class org.json.simple.JSONObject, class java.util.HashMap]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
	... 24 more
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change method modifiers
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:160)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:140)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:137)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:344)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:159)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:353)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:200)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:181)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
	at org.mockito.Mockito.mock(Mockito.java:1871)
	at org.mockito.Mockito.mock(Mockito.java:1780)
	... 24 more

```

I really wonder why. The run configurations are exactly the same (apart from run single file - run all tests).

```
<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
		    <groupId>org.mockito</groupId>
		    <artifactId>mockito-core</artifactId>
		    <version>2.19.0</version>
		    <scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
</dependencies>
```

Maybe this is rather an eclipse (Photon Release (4.8.0)) bug after all ...

**Comment by fabasoad** [comment]
Just tried it on my machine via Intellij IDEA Community 2018.1 - both cases (run single test and run all tests in project) works fine.
I propose you to check it via another IDE or via command line to exclude Eclipse option. If error still happens - maybe you have some tests which somehow can break usual behavior, try to skip (or comment) all the tests and then uncomment one by one to understand which specific test has an issue.

**Comment by TimvdLippe** [comment]
Closing per the above comment.
