### ISSUE TITLE
Java 9 and java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory

### ISSUE THREAD

**Issue by JureVI** [mockito/mockito#1451]
Hi,
I've already posted the problem I'm having with Mockito on stackoverflow (https://stackoverflow.com/q/51541554/1768483), but I figured out I might get better support here.

My project is a Wildfly 13 application which uses Mockito testing library. The app is not using Java 9 module structure. As long as the server ran on Java 8 the tests worked fine, but once we upgraded to Java 9 they failed with the following exception:

    org.objenesis.ObjenesisException: java.lang.ClassNotFoundException: sun.reflect.ReflectionFactory from [Module "test.war" from Service Module Loader]
    at test.war//org.objenesis.instantiator.sun.SunReflectionFactoryHelper.getReflectionFactoryClass(SunReflectionFactoryHelper.java:63)
    at test.war//org.objenesis.instantiator.sun.SunReflectionFactoryHelper.newConstructorForSerialization(SunReflectionFactoryHelper.java:37)
    at test.war//org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.<init>(SunReflectionFactoryInstantiator.java:41)
    at test.war//org.objenesis.strategy.StdInstantiatorStrategy.newInstantiatorOf(StdInstantiatorStrategy.java:68)
    at test.war//org.objenesis.ObjenesisBase.getInstantiatorOf(ObjenesisBase.java:94)
    at test.war//org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
    at test.war//org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:19)
    at test.war//org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:47)
    at test.war//org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
    at test.war//org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
    at test.war//org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
    at test.war//org.mockito.Mockito.mock(Mockito.java:1895)
    at test.war//org.mockito.Mockito.mock(Mockito.java:1804)
    at test.war//application code...

The test crashed when I tried to create a mock with `mock(SomeClass.class)`.
I tried all kinds of options and combinations:

- using Mockito 2.20.0 and 1.10.19
- compiling with Java 8, 9, 10
- running with the latest versions of OpenJDK 9 and 10
- setting compiler and vm options --add-modules jdk.unsupported and --add-exports jdk.unsupported/sun.reflect=ALL-UNNAMED"

Always the same error. I'm out of ideas.
Help really appreciated.

**Comment by JureVI** [comment]
I've found the solution. I've posted it on Stackoverflow https://stackoverflow.com/a/51592708/1768483

---

With more digging I found the solution at https://developer.jboss.org/thread/278334 which pointed me to https://docs.jboss.org/author/display/WFLY10/Class+Loading+in+WildFly. The article has a section titled "Accessing JDK classes" which states that not all classes are available to deployment by default, and you need to add them to `jboss-deployment-structure.xml` to make them available.

In my case:

    <jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.1">
        <deployment>
            <dependencies>
                <system export="true">
                    <paths>
                        <path name="sun/reflect"/>
                    </paths>
                </system>
            </dependencies>
        </deployment>
    </jboss-deployment-structure>

This solution works for

- Wildfly 13, running on Java 10.0.2 (9.0.4 worked too)
- app compiled with Java 8
- Mockito 1.10.19 (I tried 2.20.0 but there were new errors)
