### ISSUE TITLE
Mockito loses correct "this" reference on spy

### ISSUE THREAD

**Issue by mvdobrinin** [mockito/mockito#1478]
I am seeing an issue where my `verify` method is failing when the spy makes a call through one of its inner classes.

    public class MockitoTest {
        private final List<MListener> listeners = new ArrayList<>();
        private Inner _inner = new Inner();

        interface MListener {
            void onAdd(MockitoTest clazz, Object o);
        }

        public void addListener(MListener l) {
            listeners.add(l);
        }

        public void notifyListeners(Object o) {
            for (MListener listener : listeners) {
                listener.onAdd(this, o);
            }
        }

        class Inner {
            public void add(Object o) {
                notifyListeners(o);
            }
        }

        public void add(Object o) {
            _inner.add(o);
        }

        @Test
        public void testScenario() {
            final MockitoTest spy = Mockito.spy(new MockitoTest());
            final MListener listener = Mockito.mock(MListener.class);
            final Object o = Mockito.mock(Object.class);
            spy.addListener(listener);

            // hopping through an inner class changes "this" to the MockitoTest class rather than the spy
            spy.add(o);

            // whereas doing the same thing without hopping through the inner class first is fine
            //spy.notifyListeners(o);

            Mockito.verify(listener).onAdd(spy, o);
        }
    }

Here is the error I see when running this test case 

    Argument(s) are different! Wanted:
    mListener.onAdd(
        com.dobrinin.MockitoTest$$EnhancerByMockitoWithCGLIB$$428a6cdd@27a8c74e,
        Mock for Object, hashCode: 1995616381
    );
    -> at com.dobrinin.MockitoTest.testScenario(MockitoTest.java:57)
    Actual invocation has different arguments:
    mListener.onAdd(
        com.dobrinin.MockitoTest@2d8f65a4,
        Mock for Object, hashCode: 1995616381
    );
    -> at com.dobrinin.MockitoTest.testScenario(MockitoTest.java:52)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.dobrinin.MockitoTest.testScenario(MockitoTest.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

So the issue seems to be that the spy sees `this` as the real object rather than the spy. Also notably the issue goes away if the hop through the inner class is eliminated.

Versions
* Mockito-all - 1.10.19
* JDK 1.8.0_171

**Comment by cdalexndr** [comment]
If you implement `equals` on `MockitoTest`, then you can use `org.mockito.ArgumentMatchers.eq()` argument matcher method:

`Mockito.verify(listener).onAdd(eq(spy), eq(o));`
