### ISSUE TITLE
Exception not thrown when mocking final method

### ISSUE THREAD

**Issue by idovak** [mockito/mockito#1479]
Take the code snippet below MissingMethodInvocationException expected in both test case. But only the second fails.

Tested with Mockito 2.20 (found with mockito 2.8.47) using JDK 1.8.171, Win10x64.

```java
public class TestingMockito {

    @Test
    public void testShouldFailButPasses() {
        // GIVEN
        Foo mockFoo = mock(Foo.class);
        Aaaa a = new Aaaa();
        // WHEN
        a.setSomething(mockFoo);
        // THEN - next lines do not throw exception
        Foo mockFoo2 = mock(Foo.class);
        when(mockFoo2.getFoo()).thenReturn(null);
    }

    @Test
    public void testFailAsExpected() {
        Foo mockFoo2 = mock(Foo.class);
        when(mockFoo2.getFoo()).thenReturn(null);
    }

    public static class Aaaa {
        public void setSomething(Object something) {
            System.out.println("This is " + something);
        }
    }

    public static class Foo {
        public final String getFoo() {
            return "foo";
        }
    }

}
```

**Comment by ChristianSchwarz** [comment]
@idovak 
I tested your sample with v2.21.0, both tests turn green with plain mockito and mockito-inline. Why do you expect the when call to fail?

**Comment by idovak** [comment]
I expect both tests to fail with "MissingMethodInvocationException". Because the getFoo() method is **final** thus cannot be mocked by Mockito. I wonder what was the result in your environment? Did getFoo() returns <null> or "foo"?

```
org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.
For example:
    when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because:
1. you stub either of: final/private/equals()/hashCode() methods.
   Those methods *cannot* be stubbed/verified.
   Mocking methods declared on non-public parent classes is not supported.
2. inside when() you don't call method on mock but on some other object.
	at TestingMockito.testFailAsExpected(TestingMockito.java:29)
	....  
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
```

**Comment by ChristianSchwarz** [comment]
When mockito-inline-mocker is not used, mockito can't intercept the final method. Therefore it can't detect when it is called. 
One the other hand mockito could detect that no mock-method was called, when the `when` is called.

**Comment by freakomonk** [comment]
I have tested this on both Mockito 2.20 and the latest 2.23. I have observed that the object `a` is being intercepted by MockitoInline. Is that expected ? The test is passing only when some method is being called on object `a`. This looks like a bug.
