### ISSUE TITLE
Strange behaviour of spy with org.apache.commons.configuration2.BaseHierarchicalConfiguration clearTree

### ISSUE THREAD

**Issue by TheRoSS** [mockito/mockito#1524]
Initials:
os: Ubuntu 18.04
java: 1.8.0_191
gradle: 4.10.2
```
dependencies {
    api 'org.apache.commons:commons-configuration2:2.3'
    ...
    testImplementation 'org.mockito:mockito-core:2.23.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.2.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.2.0'
}
```

Code:
```
import org.apache.commons.configuration2.BaseHierarchicalConfiguration;
import org.apache.commons.configuration2.HierarchicalConfiguration;
import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ZooConfigurationBuilderTest {
    @Nested
    @DisplayName("child changed callback")
    class ProcessResultChild {
        @Test
        void test1() {
            HierarchicalConfiguration config = new BaseHierarchicalConfiguration();
            HierarchicalConfiguration spy = spy(config);

            spy.clearTree("key1");
            spy.clearTree("key2");
            spy.clearTree("key3");

            verify(spy).clearTree("key1");
        }

       @Test
        void test2() {
            HierarchicalConfiguration config = new BaseHierarchicalConfiguration();
            HierarchicalConfiguration spy = spy(config);

            spy.clearTree("key1");
            spy.clearTree("key2");
            spy.clearTree("key3");

            verify(spy).clearTree(anyString());
        }
    }
}
```

I run it as:
```
gradle test
```

test1 output:
```
      org.mockito.exceptions.verification.TooManyActualInvocations: 
      baseHierarchicalConfiguration.beginWrite(
          false
      );
      Wanted 1 time:
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
      But was 3 times:
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
          at ru.studionx.gamebeat.kit.ZooConfigurationBuilderTest$ProcessResultChild.testRemoveRootChild(ZooConfigurationBuilderTest.java:207)
```

You can see here that spy counts beginWrite() calls instead of expected clearTree()

test2 output:
```
      Argument(s) are different! Wanted:
      baseHierarchicalConfiguration.beginWrite(
          <any string>
      );
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
      Actual invocation has different arguments:
      baseHierarchicalConfiguration.beginWrite(
          false
      );
      -> at org.apache.commons.configuration2.AbstractHierarchicalConfiguration.clearTree(AbstractHierarchicalConfiguration.java:583)
          at ru.studionx.gamebeat.kit.ZooConfigurationBuilderTest$ProcessResultChild.testRemoveRootChild(ZooConfigurationBuilderTest.java:207)
```

The spy again tries to use beginWrite instead of clearTree and gets argument type incompatability

clearTree code from apache sources (AbstractHierarchicalConfiguration.java):
```
    public final void clearTree(String key)
    {
        beginWrite(false);
        try
        {
            fireEvent(ConfigurationEvent.CLEAR_TREE, key, null, true);
            Object nodes = clearTreeInternal(key);
            fireEvent(ConfigurationEvent.CLEAR_TREE, key, nodes, false);
        }
        finally
        {
            endWrite();
        }
    }
```

**Comment by TimvdLippe** [comment]
Closing for inactivity.
