### ISSUE TITLE
Cross-references and a single spy cause memory leak

### ISSUE THREAD

**Issue by ming13** [mockito/mockito#1533]
Not entirely sure, but I think that Mockito does not handle cross-references well. I have a semi-complex sample that proves this, but at the same time I’m not sure it is a Mockito failure and especially a fixable one. Suggestions how to avoid this behavior in general will be very helpful!

BTW I can provide a `.hprof` file if you are interested.

#### Versions

```
org.mockito:mockito-core:2.22.0
org.mockito:mockito-inline:2.22.0
```
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

#### Gradle

Heap is set to 64 MB.

```groovy
tasks.withType<Test> {
    maxHeapSize = "64m"
    jvmArgs("-XX:+HeapDumpOnOutOfMemoryError")

    failFast = true
}
```
```
$ ./gradlew :module:cleanTestDebugUnitTest :module:testDebugUnitTest --tests "com.github.sample.SubscriptionMemoryLeakSpec"
```

#### Code

```kotlin
package com.github.sample

import com.jakewharton.rxrelay2.BehaviorRelay
import com.jakewharton.rxrelay2.PublishRelay
import io.reactivex.disposables.CompositeDisposable
import org.jetbrains.spek.api.Spek
import org.jetbrains.spek.api.dsl.it
import org.junit.platform.runner.JUnitPlatform
import org.junit.runner.RunWith
import org.mockito.Mockito

@RunWith(JUnitPlatform::class)
class SubscriptionMemoryLeakSpec : Spek({

    repeat(1_000) { iteration ->

        it("iteration $iteration") {
            // Remove Mockito.spy and OOM disappears (even without component.unbind).
            val service = Mockito.spy(Service())
            val memoryConsumingService = MemoryConsumingService()

            val component = Component(service, memoryConsumingService)

            component.bind()

            // Uncomment the following line and OOM disappears.
            // component.unbind()
        }

    }

}) {

    class Service {
        val stream = PublishRelay.create<Unit>().toSerialized()
    }

    class MemoryConsumingService {
        // See at as a mass to fill the RAM.
        val streams = (0..1_000).map { BehaviorRelay.create<Int>() }
    }

    class Component(
            private val service: Service,
            private val memoryConsumingService: MemoryConsumingService
    ) {

        private val disposable = CompositeDisposable()

        fun bind() {
            disposable += service.stream.subscribe {
                // This closure keeps a reference to Component.
                memoryConsumingService.streams.size
            }
        }

        fun unbind() = disposable.clear()
    }

}
```
```
> Task :module:testDebugUnitTest
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid31753.hprof ...
Heap dump file created [96660586 bytes in 0.332 secs]

com.github.sample.SubscriptionMemoryLeakSpec > it iteration 260 STANDARD_ERROR
    java.lang.OutOfMemoryError: GC overhead limit exceeded
    	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.<init>(ReentrantReadWriteLock.java:338)
    	at java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync.<init>(ReentrantReadWriteLock.java:669)
    	at java.util.concurrent.locks.ReentrantReadWriteLock.<init>(ReentrantReadWriteLock.java:240)
    	at java.util.concurrent.locks.ReentrantReadWriteLock.<init>(ReentrantReadWriteLock.java:230)
    	at com.jakewharton.rxrelay2.BehaviorRelay.<init>(BehaviorRelay.java:99)
    	at com.jakewharton.rxrelay2.BehaviorRelay.create(BehaviorRelay.java:77)
    	at com.github.sample.SubscriptionMemoryLeakSpec$MemoryConsumingService.<init>(SubscriptionMemoryLeakSpec.kt:41)
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create byte arrau at JPLISAgent.c line: 813
    	at com.github.sample.SubscriptionMemoryLeakSpec$1$1$1.invoke(SubscriptionMemoryLeakSpec.kt:21)
    	at com.github.sample.SubscriptionMemoryLeakSpec$1$1$1.invoke(SubscriptionMemoryLeakSpec.kt:14)
    	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:102)
    	at org.jetbrains.spek.engine.Scope$Test.execute(Scope.kt:80)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$82/1204954813.execute(Unknown Source)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$89/1263089654.accept(Unknown Source)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$82/1204954813.execute(Unknown Source)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$89/1263089654.accept(Unknown Source)
    	at java.util.ArrayList.forEach(ArrayList.java:1257)
    	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$82/1204954813.execute(Unknown Source)
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)

com.github.sample.SubscriptionMemoryLeakSpec > it iteration 260 FAILED
    java.lang.OutOfMemoryError


261 tests completed, 1 failed
> Task :module:testDebugUnitTest FAILED
82 actionable tasks: 5 executed, 77 up-to-date
```

#### Eclipse Memory Analyzer

<img width="1513" alt="screen shot 2018-11-15 at 11 57 52" src="https://user-images.githubusercontent.com/200401/48541708-4991d080-e8ce-11e8-9120-7e1b2bfee689.png">
<img width="1513" alt="screen shot 2018-11-15 at 11 58 42" src="https://user-images.githubusercontent.com/200401/48541709-4991d080-e8ce-11e8-8c3c-f427f92b4ca4.png">
<img width="1513" alt="screen shot 2018-11-15 at 11 59 17" src="https://user-images.githubusercontent.com/200401/48541710-4991d080-e8ce-11e8-8927-ee310073996c.png">
<img width="1513" alt="screen shot 2018-11-15 at 11 59 58" src="https://user-images.githubusercontent.com/200401/48541711-4a2a6700-e8ce-11e8-9f1f-40d61ff6e6b8.png">
<img width="1513" alt="screen shot 2018-11-15 at 12 01 25" src="https://user-images.githubusercontent.com/200401/48541712-4a2a6700-e8ce-11e8-864c-287570e8de99.png">

---

Seems like this happens:

* `Service` is a spy and is being passed to `Component` along with `MemoryConsumingService`.
* Since `Service` is a spy it is being held by Mockito.
* `Component` subscribes to `Service.stream`. The `subscribe` closure captures `Component`, `Service` and `MemoryConsumingService`. Due to RxJava specifics `Service.stream` holds all of these thanks to the closure.
* Since `Service` is being held by Mockito (since it is a spy) and by itself (due to the `subscribe` closure) Mockito does not release it.

However:

* Releasing the subscription via `component.unbind()` removes a reference, so Mockito releases it and there is no OOM.
* Avoiding making `Service` a spy eliminates OOM as well, i. e. cross-references are not an issue for the JVM itself.

**Comment by ming13** [comment]
@TimvdLippe, @bric3, 🏓

**Comment by mockitoguy** [comment]
@ming13, @beworker, does anyone of you wants to take a stab at it? Can you write up a short design note how you would like to solve it and pros/cons of adding another weak reference field? Thanks so much!

**Comment by ming13** [comment]
@mockitoguy, hey, thanks for the reply! I think I don’t have enough expertise to do this without breaking something along the way. But just to confirm — is the issue really with Mockito or it is just a bad practices leading to this behavior?

**Comment by jemshit** [comment]
Wow, Eclipse

**Comment by ming13** [comment]
Just checked Mockito 2.27.0. Using the new `Mockito.framework().clearInlineMocks()` call does the trick and helps to avoid OOM. Thanks!
