### ISSUE TITLE
Mockito.spy fails on spring @Configurable

### ISSUE THREAD

**Issue by cdalexndr** [mockito/mockito#1580]
I'm using Spring Boot, with AspectJ load time weaving (-javaagent: aspectjweaver.jar) that will transform the `@Configurable` annotated class to inject fields.
In an unit test when I try to mock an instance of this class, the following error is thrown:
```
java.lang.VerifyError: (class: shop/product/ProductPersister$$EnhancerByMockitoWithCGLIB$$205257c, method: <init> signature: (Lshop/product/Product;)V) Illegal type in constant pool

	at sun.reflect.GeneratedSerializationConstructorAccessor9.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxy(ClassImposterizer.java:143)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:58)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.spy(Mockito.java:1368)
        ...
```

**Comment by jjDevPL** [comment]
Can you provide any code example?

**Comment by TimvdLippe** [comment]
Closing for inactivity.
