### ISSUE TITLE
ZipCompareTest failed in master branch

### ISSUE THREAD

**Issue by cmoaciopm** [mockito/mockito#159]
In file buildSrc/src/test/groovy/org/mockito/release/comparison/ZipCompareTest.groovy,

When executing "File emptyZip         = zip.newZip()", it always prompt

java.util.zip.ZipException: ZIP file must have at least one entry
	at java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:304)
	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:140)
	at java.util.zip.ZipOutputStream.close(ZipOutputStream.java:321)
	at testutil.ZipMaker.newZip(ZipMaker.groovy:39)
	at org.mockito.release.comparison.ZipCompareTest.compares zips(ZipCompareTest.groovy:20)

**Comment by szczepiq** [comment]
Can you help out fixing? The test does work on my machine and the CI ;)
17 sty 2015 07:33 "cmoaciopm" <notifications@github.com> napisaù(a):

**Comment by bric3** [comment]
@cmoaciopm any news ?

**Comment by TimvdLippe** [comment]
Builds have been succeeded for a while now, therefore closing this issue.
