### ISSUE TITLE
bug when test class has Class field

### ISSUE THREAD

**Issue by yaitskov** [mockito/mockito#1591]
library 2.23.4
java 8

reproduction:

```
@RunWith(MockitoJUnitRunner.class)
public class RedissonDistributedInstanceTest {
    private Class<String> CLAZZ = String.class;
}
```

It looks like Mockito wants to mock String class, but I guess expected behavior is just ignore that field, cause there is nothing to do for Mockito.
static or final modifiers on the field don't change anything.

Error

```

org.mockito.exceptions.base.MockitoException: 

Cannot mock/spy class java.lang.String
Mockito cannot mock/spy because :
 - final class
	at org.mockito.internal.runners.DefaultInternalRunner$1.withBefores(DefaultInternalRunner.java:39)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:276)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)

```

**Comment by alvaro-martinez-hernandez** [comment]
Hi, this problem seems solved now. This test is not failing:


```
@RunWith(MockitoJUnitRunner.class)
public class FakeTest extends TestBase {

    private Class<String> CLAZZ = String.class;

    @Test
    public void fakeTest() {
        verifyNoInteractions(CLAZZ);
    }
}
```

**Comment by TimvdLippe** [comment]
Closing per above comment.
