### ISSUE TITLE
I cannot mock a public class on JDK11.

### ISSUE THREAD

**Issue by sunbufu** [mockito/mockito#1594]
Hi, I got an error when run my unit test with mockito & PowerMock on JDK11. 
```
[ERROR] testGetRegistry(org.apache.dubbo.admin.config.ConfigCenterTest)  Time elapsed: 0.254 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.apache.dubbo.common.extension.ExtensionLoader.
Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.2+7-LTS
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.2+7-LTS
JVM info           : mixed mode
OS name            : Linux
OS version         : 4.4.0-101-generic
Underlying exception : java.lang.UnsupportedOperationException: Cannot define class using reflection
	at org.apache.dubbo.admin.config.ConfigCenterTest.testGetRegistry(ConfigCenterTest.java:96)
Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection
	at org.apache.dubbo.admin.config.ConfigCenterTest.testGetRegistry(ConfigCenterTest.java:96)
Caused by: java.lang.IllegalStateException: Could not find sun.misc.Unsafe
	at org.apache.dubbo.admin.config.ConfigCenterTest.testGetMetadataCollector(ConfigCenterTest.java:120)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String, [B, int, int, java.lang.ClassLoader, java.security.ProtectionDomain)
	at org.apache.dubbo.admin.config.ConfigCenterTest.testGetMetadataCollector(ConfigCenterTest.java:120)
```
and my `pom.xml` like this.
```
<dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>2.15.0</version>
</dependency>
<dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.0</version>
</dependency>
<dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>2.0.0</version>
</dependency>
```
In fact, `org.apache.dubbo.common.extension` is a public & non-final class. Please Check it, thank you.

**Comment by sunbufu** [comment]
Thank you.
