### ISSUE TITLE
UnfinishedStubbingException raised with deep stubs when using the do* style stubbing

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#1636]
The following example will raise `UnfinishedStubbingException`.

```java
abstract class A {
  abstract Closeable closeable();
}
A mock1 = mock(A.class, RETURNS_DEEP_STUBS);
doNothing().when(mock1.closeable()).close();
```

This seem quite an old issue actually, the state validation do not understand the nature of deep stubs and then raises the issue to the user.

```
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at x.x.x.x.test(X.java:42)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed


	at x.x.x.x.test(X.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

There is a workaround though, just first extract the _stub path_ in a variable before `doReturn` : 

```java
abstract class A {
  abstract Closeable closeable();
}
A mock1 = mock(A.class, RETURNS_DEEP_STUBS);
Closeable c = mock1.closeable();
doNothing().when(closeable).close();
```

**Comment by bric3** [comment]
By the way it seems there's a question on SO (almost 4years old at this time) regarding this issue : https://stackoverflow.com/questions/30885194/deep-stubbing-together-with-the-doreturn-method

**Comment by ChristianLutz** [comment]
@bric3 Is this related to #330

**Comment by Abdelsattar** [comment]
I have the same problem when using doReturn with when

**Comment by alvaro-martinez-hernandez** [comment]
This piece of code also shows how `doReturn()` is failing. This makes no sense at all:

```
public class FakeTest {

    public abstract class A {

        public abstract Closeable closeable();
    }

    @Test
    public void ok() throws IOException, InterruptedException {
        A mock1 = mock(A.class, RETURNS_DEEP_STUBS);
        Closeable c = mock1.closeable();
        doReturn("xxx").when(c).toString();
    }

    @Test
    public void ko() throws IOException, InterruptedException {
        A mock1 = mock(A.class, RETURNS_DEEP_STUBS);
        doReturn("xxx").when(mock1.closeable()).toString();
    }
}
```
