### ISSUE TITLE
Have a way to detect unmatched calls

### ISSUE THREAD

**Issue by henri-tremblay** [mockito/mockito#1677]
Following your advice on [twitter](https://twitter.com/MockitoJava/status/1111650664613101569), here is my recommendation to make Mockito as a better place.

As you probably know, I'm [EasyMock](http://easymock.org/) lead dev. But working on many projects where I haven't picked the mocking framework, I happen to work a lot with Mockito as well.

I'm annoyed by a bunch of little things but one problem makes me want to throw my computer by the window. They might already be a solution for it but I am not aware of it. I know you worked on the verification mode lately to do more or less that but it doesn't work when not using `@Mock` and not really satisfactory.

So, let's say I'm working on legacy code with tests using Mockito. My current example is code the worked perfectly and then I did a Mockito migration. So `any()` isn't matching `null` anymore. So my `when` are not matching anymore. Mockito is returning `null` by default and the test is failing because of that.

The problem is that I have no clue where the `when` was called. This is complicated legacy code and tests are not as simple as one would like. So, here is what I can do:

1- Find usage, put a breakpoint everywhere the method is called, find which call is returning null, fix the `when()`

But I have 20 recordings... Takes ages to find what I'm looking for

2- Convert to Easymock. The unexpected calls will fail right away. I will fix them and be done

I will restate again: The wrongly non-matching `when` have been a source of annoyance with Mockito for many many years now.

**Comment by TimvdLippe** [comment]
Thanks for the issue! Would [strict mocks](https://static.javadoc.io/org.mockito/mockito-core/2.25.1/org/mockito/Mockito.html#40) solve this problem for you? They should throw an exception as soon as you call a method and it was not stubbed before.

**Comment by henri-tremblay** [comment]
I just tried. Assuming I'm using it correctly. Unsatisfactory so far.

Here is an example:

```java
        MockitoSession session = Mockito.mockitoSession()
                .strictness(Strictness.STRICT_STUBS)
                .startMocking();
        List<String> list = mock(List.class);
        when(list.get(0)).thenReturn("allo"); // I think this will be called
        session.finishMocking();
        assertThat(list.get(1)).isEqualTo("allo"); // but in fact, somewhere deep in the test, this is called
```

The error given is:

```
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 
Unnecessary stubbings detected.
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at pro.tremblay.easymock.questions.misc.StrictMock.test(StrictMock.java:23)
Please remove unnecessary stubbings or use 'silent' option. More info: javadoc for UnnecessaryStubbingException class.

	at pro.tremblay.easymock.questions.misc.StrictMock.test(StrictMock.java:24)
```

This is mostly useless. I now know that the thing that isn't mocked correctly is probably on line 23. But I have no idea which unexpected calls exist.

If I convert to EasyMock

```java
        List<String> list = EasyMock.mock(List.class);
        expect(list.get(0)).andReturn("allo");
        replay(list);
        assertThat(list.get(1)).isEqualTo("allo");
```

I get

```
java.lang.AssertionError: 
  Unexpected method call List.get(1 (int)):
    List.get(0 (int)): expected: 1, actual: 0

	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
	at com.sun.proxy.$Proxy4.get(Unknown Source)
	at pro.tremblay.easymock.questions.misc.StrictMock.testEasyMock(StrictMock.java:34)
```

I have exactly what I'm looking for! Right away.

**Comment by henri-tremblay** [comment]
I've continued digging. Two things are helpful:
- `Mockito.mockingDetails(mock).printInvocations()` will print the invocation so if you think some mock is not called as expected, you can dig into that
- `Mockito.verifyZeroInteractions(mock)` to make it fail and see the unexpected invocation

They are helpful but when you have a lot of mocks it requires a code change and a bit of guessing and investigating to find out what's failing. Not a nice a the direct failure a strict mock will allow.

Due to the Mockito architecture (no replay phase), my assumption is that isn't possible without adding something like `Mockito.goStrict(mock)` before the test phase.

**Comment by mockitoguy** [comment]
Thank you for feedback! I think you're right. New feature for legacy tests would be useful.

Let's say we have "strict" mocks. Do you think that "strict mock" should fail early every time, or only when 'non-void' methods are called?

**Comment by mockitoguy** [comment]
I see that we have a spec for strict mocks at: https://github.com/mockito/mockito/issues/1097

**Comment by henri-tremblay** [comment]
Reading #1097, my opinion:

> unstubbed, non-void method fails immediately with "I am unstubbed!" exception
Seems ok. Not sure you need to bother yourself about void/non-void. Having void to fail can make the test more resilient to unexpected calls (assuming, the tester forgot to verify for no more interactions)
> such method is implicitly marked as verified for the verifyNoMoreInteractions() calls
Probably a good idea
> unused stubs are detected at the end of test and trigger failure
Yes. You might need to some `verifyAllStubsWereUsed` when not using rules or runner
> requires to use doReturn API for stubbing mocks (limitation of the syntax, already known gotcha when using test "spy" or strict stubs)
This is a problem because it is needed after the fact. So you are already in front of tons of mocks and recording and don't want to change them. You are just looking for the stupid `any()` that was matching `null` in previous versions of Mockito. That's why I was proposing a `goStrict()` that will put the mock in a strict mode. Any `when()` or `doReturn` would fail after `goStrict()` and so will an unexpected call.

**Comment by mockitoguy** [comment]
@henri-tremblay, thank you for taking the time and giving feedback on all ideas!

**Comment by stellingsimon** [comment]
I'm facing the same issues and sentiments as @henri-tremblay did 3 years ago. I can see that #1097 got some commits ~2.5 years ago but then went cold. => Just humbly showing that I'd still be very interested to see this issue resolved.

**Comment by zdanek** [comment]
Guys, just add the missing feature that users (devs) require. Listen to demands of users, not only your Ego and ideas that you're driven by. Being deaf to needs of the users is silly.

**Comment by TimvdLippe** [comment]
@zdanek Mockito is a volunteer-based open source project. If you want this issue to be solved, please submit a pull request.

**Comment by zdanek** [comment]
@TimvdLippe I'd be happy to contribute if you promise me to accept this functionality :)

I'm not talking about blindly accepting messy code, but we're talking about certain feature.
I'd like to be sure that nobody will then say, "this is against our _feng shui_". Like it was for years with mocking statics. Official response was - use PowerMock instead :) 

So the question is - if sbd will provide good quality code, would you accept proposed feature?
Problably it would be also good to discuss it a bit before implementing :)

**Comment by TimvdLippe** [comment]
@zdanek As any open source project, we evaluate a contribution based on our contribution guidelines (https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md) and how it integrates with the general codebase. There appears to be sufficient requests for strict mocks, but implementation tends to be a lot harder to get right. You can take on this project if you want to, for which a design + discussion would make sense. While the requests have come in, nobody has taken up this task just yet, predominantly because it is large and tricky to get right.
