### ISSUE TITLE
"description" not printing when verify args don't match

### ISSUE THREAD

**Issue by tir38** [mockito/mockito#1712]
Mockito version 2.27.0

I have a test that uses `description` inside a `verify` method. The `description` is correctly printing when the test fails because we don't interact with the mock

```
import static org.mockito.Mockito.description;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;

import org.junit.Test;

public class ExampleTest {
    @Test
    public void shouldFailWithDescription() {
        Dependency dependency = spy(Dependency.class);
        SystemUnderTest systemUnderTest = new SystemUnderTest();
        systemUnderTest.doSomething(dependency);
        verify(dependency, description("Failed to call doSomethingElse")).doSomethingElse(false);
    }

    static class SystemUnderTest {
        void doSomething(Dependency dependency) {
            // dependency.doSomethingElse(true); // <---- TEST FAILS BECAUSE WE DON'T INTERACT WITH MOCK
        }
    }

    static class Dependency {
        void doSomethingElse(boolean value) {
            // ...
        }
    }
}
```

Results in this failure message:

```
org.mockito.exceptions.base.MockitoAssertionError: Failed to call doSomethingElse <---- SEE OUR DESCRIPTION

Wanted but not invoked:
dependency.doSomethingElse(false);
-> at com.example.ExampleTest$Dependency.doSomethingElse(ExampleTest.java:28)
Actually, there were zero interactions with this mock.
```

In this case the test failed because there were no interactions with this mock. However if we update the SUT so that it calls the method with the wrong argument:

```
public class ExampleTest {
    @Test
    public void shouldFailWithDescription() {
        Dependency dependency = spy(Dependency.class);
        SystemUnderTest systemUnderTest = new SystemUnderTest();
        systemUnderTest.doSomething(dependency);
        verify(dependency, description("Failed to call doSomethingElse")).doSomethingElse(false);
    }

    static class SystemUnderTest {
        void doSomething(Dependency dependency) {
             dependency.doSomethingElse(true);  // <---- TEST FAILS BECAUSE WE PASS WRONG ARGS
        }
    }

    static class Dependency {
        void doSomethingElse(boolean value) {
            // ...
        }
    }
}
```

The test still fails. But this time it **does not include the description**:

```
Argument(s) are different! Wanted: <----- WE SHOULD SEE DESCRIPTION
dependency.doSomethingElse(false);
-> at com.example.ExampleTest$Dependency.doSomethingElse(ExampleTest.java:28)
Actual invocation has different arguments:
dependency.doSomethingElse(true);
-> at com.example.ExampleTest$SystemUnderTest.doSomething(ExampleTest.java:21)

Comparison Failure: 
Expected :dependency.doSomethingElse(false);
Actual   :dependency.doSomethingElse(true);
```

**Comment by tir38** [comment]
Nevermind, Updating to latest 2.27.0 solved the problem

**Comment by tir38** [comment]
Not pretty but this seems to work if I use a `VerificationListener` and manually log the error:


```
import static org.mockito.Mockito.description;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;

import org.junit.Test;
import org.mockito.Mockito;
import org.mockito.MockitoFramework;
import org.mockito.listeners.VerificationListener;

public class ExampleTest {
    @Test
    public void shouldFailWithDescription() {
        MockitoFramework framework = Mockito.framework();
        String failureMessage = "Failed to call doSomethingElse";

        // not all test failures will print the description so we have to manually log it =(
        VerificationListener listener = verificationEvent -> {
            if (verificationEvent.getVerificationError() != null) {
                System.out.println("FAILURE: " + failureMessage);
            }
        };
        framework.addListener(listener);

        Dependency dependency = spy(Dependency.class);
        SystemUnderTest systemUnderTest = new SystemUnderTest();
        systemUnderTest.doSomething(dependency);
        verify(dependency, description(failureMessage)).doSomethingElse(false);

        // not sure if we need to remove for next test, or if mockito will auto-clear
        framework.removeListener(listener);
    }

    static class SystemUnderTest {
        void doSomething(Dependency dependency) {
            dependency.doSomethingElse(true);  // <---- TEST FAILS BECAUSE WE PASS WRONG ARGS
        }
    }

    static class Dependency {
        void doSomethingElse(boolean value) {
            // ...
        }
    }
}
```

now prints out 

```
FAILURE: Failed to call doSomethingElse

Argument(s) are different! Wanted:
dependency.doSomethingElse(false);
-> at com.example.ExampleTest$Dependency.doSomethingElse(ExampleTest.java:47)
Actual invocation has different arguments:
dependency.doSomethingElse(true);
-> at com.example.ExampleTest$SystemUnderTest.doSomething(ExampleTest.java:40)
```

**Comment by jjDevPL** [comment]
I would like to analyze this issue and eventually provide fixes.

**Comment by tasomaniac** [comment]
I can also verify the same issue.

**Comment by mockitoguy** [comment]
Seems like a bug. Please submit a PR. Thanks!

**Comment by adrianriley** [comment]
The cause of this is that Reporter.argumentsAreDifferent() returns an ArgumentsAreDifferent, a subclass of org.opentest4j.AssertionFailedError and not, crucially, MockitoAssertionError. Hence the exception is not caught in Description.verify and wrapped in a MockitoAssertionError with the description. I think the catch block there should also catch AssertionFailedError and handle that in the same way.

**Comment by adrianriley** [comment]
... or maybe ArgumentsAreDifferent should extend MockitoAssertionError? I'm not sure which.

**Comment by tasomaniac** [comment]
It's extending those because of tooling and IDE support, I believe. In IntelliJ IDEA for example, this error is displayed really nice. You can see and compare the differences on the arguments.

**Comment by adrianriley** [comment]
The various ArgumentsAreDifferent exceptions come from org.mockito.internal.junit.ExceptionFactory, which deals solely with that condition. The header comment of MockitoAssertionError suggests it should be the base of all verification errors triggered by verify() methods. So maybe some refactoring is required. 

I don't know enough to say whether the solution is to handle the exceptions which are actually being thrown or change to throw subclasses of MockitoAssertionError which would then fix the issue.

**Comment by adrianriley** [comment]
Here's a test for the issue: https://github.com/adrianriley/mockito/blob/feature/%231712/src/test/java/org/mockito/DescriptionTest.java

**Comment by adrianriley** [comment]
Created a PR with a possible solution: https://github.com/mockito/mockito/pull/1949
