### ISSUE TITLE
Mocked Kotlin function can not return Array when it also takes a list as parameter

### ISSUE THREAD

**Issue by daweiser** [mockito/mockito#1722]
* Android API 21
* Mockito > 26.0.0

When a Kotlin function returns an Array and also takes a list as parameter, the following exception is thrown for Mockito > 26.0.0 (with the all-open-plugin it works for <= 26.0.0):

`java.lang.IllegalStateException: This was not supposed to happend
at org.mockito.internal.util.reflection.GenericMetadataSupport$GenericArrayReturnType.rawType(GenericMetadataSupport.java:527)
at org.mockito.internal.stubbing.answers.InvocationInfo.isVoid(InvocationInfo.java:55)
at org.mockito.internal.stubbing.answers.Returns.validateFor(Returns.java:32)
at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:70)
at org.mockito.internal.stubbing.InvocationContainerImpl.addAnswer(InvocationContainerImpl.java:56)
at org.mockito.internal.stubbing.OngoingStubbingImpl.thenAnswer(OngoingStubbingImpl.java:32)
at org.mockito.internal.stubbing.BaseStubbing.thenReturn(BaseStubbing.java:35)
at com.dawe.myapplication.ExampleInstrumentedTest.testFail(ExampleInstrumentedTest.kt:21)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
Caused by: java.lang.ClassNotFoundException: [Lchar;
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:453)
at org.mockito.internal.util.reflection.GenericMetadataSupport$GenericArrayReturnType.rawType(GenericMetadataSupport.java:525)
... 35 more
Caused by: java.lang.ClassNotFoundException: char
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 38 more`

Working example: https://github.com/daweiser/MockitoTest

**Comment by ChristianSchwarz** [comment]
I've made very good experiences with [MockK](https://mockk.io/) a Kotlin Mocking framework, with pretty similar API to mockito but build in support for the Kotlin language features (mocking of object classes, reified generics, ...)

**Comment by TimvdLippe** [comment]
For Kotlin projects, please use `mockito-kotlin` instead, which should not exhibit this problem: https://github.com/mockito/mockito-kotlin
