### ISSUE TITLE
NPE thrown when primitive type is matched with Mockito.any

### ISSUE THREAD

**Issue by jamesaspence** [mockito/mockito#1735]
Hi all, was testing some code tonight and ran into a weird issue. Please look at this example:

```java
public class MockitoTest {
    @Test
    public void testDoAThing() {
        final TestThing thing = Mockito.mock(TestThing.class);

        Mockito.when(thing.doAThing(Mockito.any(), Mockito.any()))
            .thenReturn("asd");
    }

    public static class TestThing {
        public String doAThing(String foo, boolean second) {
            return second ? foo + "asd" : foo;
        }
    }
}
```

When the `Mockito.when` is hit, we end up receiving the following NPE:
```
java.lang.NullPointerException
	at com.example.MockitoTest.testDoAThing(MockitoTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

This appears to be due to the second parameter being a primitive type `boolean` - when either modifying to type `Boolean`, or converting second `Mockito.any` to `Mockito.anyBoolean`, NPE disappears and test runs as expected.

This is similar to https://github.com/mockito/mockito/issues/822 but appears to be slightly different in that there is no other output in stack trace or exception.

Appears on version 2.28.2, first observed on older version of 1.10.19.

**Comment by TimvdLippe** [comment]
This is the same stacktrace in #822, but that stacktrace has additional information in a subsequent test that failed because of left-over static state. Closing as duplicate.

(Note that this is a fundamental issue that we can not solve in the current architecture. See #1264 for more info)
