### ISSUE TITLE
org.mockito.exceptions.misusing.UnfinishedStubbingException thrown on void method

### ISSUE THREAD

**Issue by johanaaharon** [mockito/mockito#1741]
Hey, 

We have an issue that UnfinishedStubbingException is thrown randomly while running in a foreach loop. 

  @MockBean(answer = Answers.RETURNS_SMART_NULLS)
  private SomeMock someMock;
  
@Test
    void testUnfinishedStubbingExceptionRandomlyThrown() {
            final AtomicInteger atomicInteger = new AtomicInteger(ids.size());
            ids.forEach(id -> {
                final int index = atomicInteger.decrementAndGet();
                if (index % 2 == 0) {
                  Mockito.doThrow(RuntimeException.class)
                        .when(someMock)
                        .voidMethod(Mockito.eq(id), Mockito.eq(val2), Mockito.eq(val3);
                }
            });
}

This is the exception thrown randomly:

org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.baeldung.mockito.misusing.MockitoMisusingUnitTest.givenNotASpy_whenDoReturn_thenThrowNotAMock(MockitoMisusingUnitTest.java:28)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod();
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3: you are stubbing the behaviour of another mock inside before 'thenReturn' instruction if completed

-> at org.baeldung.mockito.MockitoVoidMethodsUnitTest.whenAddCalledValueCaptured(MockitoVoidMethodsUnitTest.java:30)

**Comment by venkaDaria** [comment]
@johanaaharon 
Are you sure that someMock isn't null when you try to mock voidMethod?

**Comment by johanaaharon** [comment]
@venkaDaria yes the mock is not null for sure...

Sometime the exception is not throw but we have a second unexpected behavior that the mock doesn't really throw the exception instead of that it do nothing, so the test is failing cause the behavior is randomly not as expected.

Seems that there is a race condition (there is something weird that if before doThrow we will add a sleep of 1 ms we will dont experience this issue anymore...)

**Comment by venkaDaria** [comment]
Example like that is working for me:

```
@RunWith(MockitoJUnitRunner.class)
public class SimpleTest {

    @Mock(answer = Answers.RETURNS_SMART_NULLS)
    private SomeMock someMock;

    @Test(expected = RuntimeException.class)
    public void testUnfinishedStubbingExceptionRandomlyThrown() {
        List<Integer> ids = Arrays.asList(0, 1, 2);
        int val2 = 1;
        int val3 = 2;

        final AtomicInteger atomicInteger = new AtomicInteger(ids.size());
        ids.forEach(id -> {
            final int index = atomicInteger.decrementAndGet();
            if (index % 2 == 0) {
                Mockito.doThrow(RuntimeException.class)
                    .when(someMock)
                    .voidMethod(Mockito.eq(id), Mockito.eq(val2), Mockito.eq(val3));
            }
        });

        try {
            someMock.voidMethod(1, val2, val3);
        } catch (RuntimeException e) {
            Assert.fail();
        }

        someMock.voidMethod(2, val2, val3);
    }

    private static class SomeMock {

        <T> void voidMethod(T eq, int eq1, int eq2) {
            System.out.println(eq);
            System.out.println(eq1);
            System.out.println(eq2);
        }
    }
}

```

**Comment by TimvdLippe** [comment]
You are probably running into thread-safety issues, documented at https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe
