### ISSUE TITLE
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker

### ISSUE THREAD

**Issue by blackberrybhtg** [mockito/mockito#1759]
Hi Mockito project members,

I ran into the exception when using mockito. Here's the stack trace. For some reason, when I run the build target again, this exception doesn't show up.

```
  2> java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
        at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
        at com.sun.proxy.$Proxy53.getHandler(Unknown Source)
        at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:81)
        at org.mockito.internal.configuration.injection.scanner.MockScanner.isMockOrSpy(MockScanner.java:83)
        at org.mockito.internal.configuration.injection.scanner.MockScanner.preparedMock(MockScanner.java:71)
        at org.mockito.internal.configuration.injection.scanner.MockScanner.scan(MockScanner.java:59)
        at org.mockito.internal.configuration.injection.scanner.MockScanner.addPreparedMocks(MockScanner.java:45)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:74)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:42)
        at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:69)
        at Tests.setup(Tests.java:20)

        Caused by:
        java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@41cbef77
            at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
            at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
            at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
            at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:22)
            at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:19)
            at org.mockito.internal.configuration.GlobalConfiguration.tryGetPluginAnnotationEngine(GlobalConfiguration.java:55)
            at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:68)
            ... 1 more

            Caused by:
            org.mockito.exceptions.base.MockitoInitializationException: 
            Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

            Java               : 12
            JVM vendor name    : Oracle Corporation
            JVM vendor version : 12.0.2+10
            JVM name           : OpenJDK 64-Bit Server VM
            JVM version        : 12.0.2+10
            JVM info           : mixed mode, sharing
            OS name            : Linux
            OS version         : 4.4.0-157-generic
                at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:168)
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
                at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
                at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
                at java.base/java.lang.Class.newInstance(Class.java:590)
                at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
                ... 7 more

                Caused by:
                java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7ac5739b
                    at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
                    at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581)
                    at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533)
                    at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510)
                    at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<clinit>(InlineByteBuddyMockMaker.java:104)
                    ... 15 more

                    Caused by:
                    java.io.IOException: Cannot run program "/home/local/ANT/noname/tool/jdk-12.0.2/bin/java": error=13, Permission denied
                        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
                        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
                        at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:669)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:601)
                        ... 19 more

                        Caused by:
                        java.io.IOException: error=13, Permission denied
                            at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
                            at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
                            at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
                            at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
                            ... 22 more
```

The version of mockito I use is 3.0.0. I tested on other 2 versions and had the same exception.

**Comment by TimvdLippe** [comment]
The exception lists the error:

```
Caused by:
                    java.io.IOException: Cannot run program "/home/local/ANT/noname/tool/jdk-12.0.2/bin/java": error=13, Permission denied
                        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
                        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
                        at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:669)
                        at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:601)
                        ... 19 more

                        Caused by:
                        java.io.IOException: error=13, Permission denied
                            at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
                            at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
                            at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
                            at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
                            ... 22 more
```

Make sure you can run `java` with the correct permissions for your current user. This is not an issue related to Mockito.
