### ISSUE TITLE
Problem mocking a final method with hooks

### ISSUE THREAD

**Issue by dgruntz** [mockito/mockito#1826]
I tried to test a template method which invokes two hook methods. The template method is declared `final`. The whole test class is defined in package `mockito`, i.e. stored in the folder `src/main/java/mockito`:

	package mockito;

	public abstract class AbstractBaseClass {

		protected abstract void hook1();
		protected abstract void hook2();

		public final void templateMethod() {
			hook1();
			hook2();
		}
	}

The test class is stored in folder `src/test/java/mockito`

	package mockito;

	import static org.mockito.Mockito.mock;
	import static org.mockito.Mockito.verify;
	import static org.mockito.Mockito.verifyNoMoreInteractions;

	import org.junit.jupiter.api.Test;

	public class TemplateTest {

		@Test
		public void testTemplate() {
			final var method = mock(AbstractBaseClass.class);
			method.templateMethod();
			verify(method).templateMethod();
			verifyNoMoreInteractions(method);
		}

	}

If the test is executed, then the check `verifyNoMoreInteractions(method);` will report unverified invocations.

The test runs without problem, 
- if method `templateMethod` were not declared `final`
- if method `templateMethod` only invokes `hook1` or `hook2`

This is my Gradle file (I use version 3.1.0 of mockito-core):

	plugins {
		id 'java'
	}

	repositories {
		jcenter()
	}

	sourceCompatibility = 11
	targetCompatibility = 11
	compileJava.options.encoding = 'UTF-8'
	compileTestJava.options.encoding = 'UTF-8'

	dependencies {
		testImplementation 'org.junit.jupiter:junit-jupiter:5.5.2'
		testImplementation 'org.mockito:mockito-core:3.1.0'
	}

	test {
		useJUnitPlatform()
	}

If I run the test (from within Eclipse) I see the following error:

	org.mockito.exceptions.verification.NoInteractionsWanted: 
	No interactions wanted here:
	-> at mockito.TemplateTest.testTemplate(TemplateTest.java:16)
	But found this interaction on mock 'abstractBaseClass':
	-> at mockito.AbstractBaseClass.templateMethod(AbstractBaseClass.java:10)
	***
	For your reference, here is the list of all invocations ([?] - means unverified).
	1. -> at mockito.AbstractBaseClass.templateMethod(AbstractBaseClass.java:9)
	2. [?]-> at mockito.AbstractBaseClass.templateMethod(AbstractBaseClass.java:10)
	3. [?]-> at mockito.AbstractBaseClass.templateMethod(AbstractBaseClass.java:10)

		at mockito.TemplateTest.testTemplate(TemplateTest.java:16)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
		at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
		at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
		at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
		at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
		at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
		at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
		at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
		at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
		at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
		at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
		at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)

The same error is shown if the test is executed with gradle

	% gradle test

	> Task :test FAILED

	mockito.TemplateTest > testTemplate() FAILED
		org.mockito.exceptions.verification.NoInteractionsWanted at TemplateTest.java:16

	1 test completed, 1 failed

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':test'.
	> There were failing tests. See the report at: file:///mockito/build/reports/tests/test/index.html

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug
	option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 2s
	3 actionable tasks: 1 executed, 2 up-to-date

**Comment by dean-burdaky** [comment]
I did a bit more exploratory testing in a similar vein to the tests described by the author and found the problem seemed to be with **final methods with no return type**. I think the mocking system isn't handling this case properly.

I ran the three tests described the author for three different return types.
**Tests:**
- Final method with two hooks.
- Final method with one hook.
- Non-final method with two hooks.

**Return types:**
- void
- int
- Object

In addition, I check to see if the real method was called for each (test, return type) pair. Here is what I've found:
- The final void methods did call the real methods. So `verifyNoMoreInteractions` was expected to fail due to the invocation of the hooks.
- Only the final void method with two hooks failed `verifyNoMoreInteractions`, but that gave an exception similar to the one described by the author.
- The int/Object final methods didn't call the real methods and didn't fail.
- The non-final method tests also didn't call the real methods and didn't fail.

A couple of things to notice about the exceptions (particularly the one described by the author):
- The verification system recognises three invocations and, more importantly, the first invocation was verified but the second and third invocations were not.
- However, the verification system doesn't seem to assign the correct call instructions for each invocation.
  - For the verified invocation, it assigns it to the call of the first hook, not the call of the final void method.
  - For the unverified invocations, it assigns them both to the call of the second hook and not one for each hook call.

Since I'm not particularly well versed with the internals of the mocks and the internals of the verification system, I do not know how to fix this, but hope this helps anyone trying to fix this.

**Comment by ohbus** [comment]
Hi Mockito Team!

Is there any roadmap for fixing this issue.

Or would you want to point us in some direction to get this issue fixed?

Thanks.

**Comment by dgruntz** [comment]
If `mockito-inline` inline is used instead of `mockito-core` then the test passes. This is described in the [Mockito Documentation](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#39). This extension provides an alternative Mock-Maker with support for mocking final classes and methods.

I used the following dependencies:

	dependencies {
		testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
		testImplementation 'org.mockito:mockito-inline:4.8.0'
	}
