### ISSUE TITLE
StrictStubs incorrectly detects PotentialStubbingProblem for Spy's

### ISSUE THREAD

**Issue by norrisjeremy** [mockito/mockito#1873]
Mockito version: 3.2.4

I believe the following code block incorrectly throws `PotentialStubbingProblem` when a stubbed method call on a `Spy` is not issued before a non-stubbed method call.

If on the other hand the stubbed method call on the `Spy` is issued before the non-stubbed method call or if one explicitly adds a matching `doCallRealMethod()` for the `Spy`, then a `PotentialStubbingProblem` is not thrown.

I do not believe the order in which stubbed versus non-stubbed calls for a Spy should matter, unless I am misunderstanding something?

```
org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'a' method:
    a.a(
    "aaa",
    java.util.stream.ReferencePipeline$Head@7ee8290b
);
    -> at mockitotest.B.b(B.java:10)
 - has following stubbing(s) with different arguments:
    1. a.a(null, null);
      -> at mockitotest.BTest.testB(BTest.java:25)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.
	at mockitotest.B.b(B.java:10)
	at mockitotest.BTest.testB(BTest.java:27)
...
```

```
package mockitotest;

import java.util.stream.Stream;

import static java.util.stream.Collectors.*;

public class A {

    public String a(String one, Stream<String> two) {
        return one + two.collect(joining(""));
    }
}
```

```
package mockitotest;

import java.util.stream.Stream;

public class B {

    private A a;

    public String b(String one, String two) {
        return a.a(one, Stream.of(two));
    }
}
```

```
package mockitotest;

import java.util.stream.Stream;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Spy;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

@RunWith(MockitoJUnitRunner.StrictStubs.class)
public class BTest {

    @Spy
    A a = new A();

    @InjectMocks
    B b = new B();

    @Test
    @SuppressWarnings("unchecked")
    public void testB() {
        doThrow(new RuntimeException()).when(a).a(eq("bbb"), any(Stream.class));

        assertEquals("aaa", b.b("aaa", ""));
        assertThrows(RuntimeException.class, () -> b.b("bbb", ""));
    }
}
```

**Comment by lllewellyn** [comment]
I encountered a similar issue in Mockito 3.6.0 and JUnit 5 (using MockitoExtension). 

My test violated this condition from the error message:

>  stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).

Even adding `lenient()` before the call didn't help in my case. And I could not use `doCallRealMethod()` because one of the overloaded methods was marked 'final'.

I inherited this code, I am going to try reworking it to avoid the spy if I can. It worked with older, not-strict versions of Mockito and failed when I updated versions.
