### ISSUE TITLE
Issue with initializing inline Byte Buddy mock maker on IBM java

### ISSUE THREAD

**Issue by RadoslavGavrailov** [mockito/mockito#1899]
Hey,

we've recently encountered an issue in one of our tests using mocks when executed with IBM java.

Java               : 1.8
JVM vendor name    : IBM Corporation
JVM vendor version : 2.9
JVM name           : IBM J9 VM
JVM version        : 8.0.6.6 - pxz6480sr6fp6-20200303_01(SR6 FP6)
JVM info           : JRE 1.8.0 Linux s390x-64-Bit Compressed References 20200124_438197 (JIT enabled, AOT enabled)
OpenJ9   - 6754bf2
OMR      - dca2cde
IBM      - 5cc5f54
OS name            : Linux
OS version         : 3.10.0-1062.18.1.el7.s390x

The issue we faced is : 

> java.lang.RuntimeException: Invoking the beforeTestMethod method on PowerMock test listener org.powermock.api.extension.listener.AnnotationEnabler@2f6ccf22 failed.
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:84)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:308)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:820)
Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy20.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
	at org.mockito.Mockito.mock(Mockito.java:1895)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:108)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.doCreateMock(DefaultMockCreator.java:61)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:53)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:40)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:181)
	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:98)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:55)
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:82)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.ClassLoader$CompoundEnumeration@81276057
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:21)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:18)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker. (This mock maker is not supported on Android.)

Version of the jars used : 

byte-buddy-1.10.8.jar
byte-buddy-agent-1.10.8.jar
cglib-nodep-3.2.9.jar
mockito-core-2.23.0.jar
objenesis-3.0.1.jar
powermock-mockito2-2.0.2-full.jar

Strange is that the exception message says : This mock maker is not supported on Android.

Any hints are welcomed.

**Comment by raphw** [comment]
We should probably change the message to something like: *Are you running this code on Android? It cannot work there.* since it is just a suggestion what might be wrong.

J9 does not necessarily support dynamic attachment. If you run a minimal *public static void main* with `ByteBuddyAgent.install()`, does it crash, too?

**Comment by rgg1992** [comment]
Hello,

I tried executing the attached java class on the problematic machine and it was successful. 

MockitoTest.java : 
`import net.bytebuddy.agent.ByteBuddyAgent;

public class MockitoTest {

  public static void main(String[] args) {
	System.out.println("Before install");
    ByteBuddyAgent.install();
	System.out.println("After install");
  }

}

`

Output from the execution after compilation : 
bash-4.4$ java -classpath .:/FS/fs0129/testenv/rgav_test/byte-buddy-agent-1.10.8.jar MockitoTest
Before install
After install

**Comment by raphw** [comment]
In your code, is there another agent active? Those might compete. Otherwise, I have no known issues with OpenJ9 and Byte Buddy.

**Comment by rgg1992** [comment]
I don't think we have another agent running.

Unfortunately we have not been able to resolve this issue so far and we had to disable the tests that use powermock on some of our machines.

**Comment by raphw** [comment]
Not sure about PowerMockito but does it now also attach an agent? Maybe it's also some class path scanning that triggers a form of premature loading.

**Comment by bmarwell** [comment]
Maybe duplicate of https://github.com/mockito/mockito/issues/2278 (please close this in favour of #2278 if so).
Upstream issue: https://github.com/eclipse-openj9/openj9/issues/17454

HTH
