### ISSUE TITLE
Build Fails with NoClassDefFoundError on CglibMockMaker

### ISSUE THREAD

**Issue by arunnaparna** [mockito/mockito#190]
Hi,
   my maven build fails when I try to mock a class with the error below. I am beginner with mockito. Can someone please help with this? I am trying to build from command line. I am trying to build a scala project. 

Java version: 1.7
Project type: scala project
mockito version: 
```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-all</artifactId>
    <version>1.10.19</version>
</dependency>
```

Error that I get during maven build:

```
←[31m*** RUN ABORTED ***←[0m
←[31m  java.lang.NoClassDefFoundError: org/mockito/internal/creation/CglibMockMaker←[0m
←[31m  at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:40)←[0m
←[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)←[0m
←[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)←[0m
←[31m  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)←[0m
←[31m  at java.lang.reflect.Constructor.newInstance(Constructor.java:526)←[0m
←[31m  at java.lang.Class.newInstance(Class.java:374)←[0m
←[31m  at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:61)←[0m
←[31m  at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)←[0m
←[31m  at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)←[0m
←[31m  at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)←[0m
←[31m  ...←[0m
←[31m  Cause: java.lang.ClassNotFoundException: org.mockito.internal.creation.CglibMockMaker←[0m
←[31m  at java.net.URLClassLoader$1.run(URLClassLoader.java:366)←[0m
←[31m  at java.net.URLClassLoader$1.run(URLClassLoader.java:355)←[0m
←[31m  at java.security.AccessController.doPrivileged(Native Method)←[0m
←[31m  at java.net.URLClassLoader.findClass(URLClassLoader.java:354)←[0m
←[31m  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)←[0m
←[31m  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)←[0m
←[31m  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)←[0m
←[31m  at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:40)←[0m
←[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)←[0m
←[31m  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)←[0m
←[31m  ...←[0m
```

**Comment by bric3** [comment]
Hi,

We are happy that you are using mockito, but for support please use the mailing list or stackoverflow :)

With the given info there's not enough info to diagnose the issue, it seems to be related to classpath though.

**Comment by bric3** [comment]
Oh I just identified the issue, this project is using powermock, which is depending / hacking in mockito internals, those have change in version 1.10.8. However there's a new version of powermock 1.6.2 that work with mockito 1.10.19

**Comment by sanket0354** [comment]
Thanks...It did the trick  and saved my time!! :)

**Comment by europaJDM** [comment]
This trick saved my life

**Comment by kiranbiliyawala** [comment]
You saved the day bro!
Thanks. :)

**Comment by sanyamd** [comment]
Thanks a lot bric3 :)
