### ISSUE TITLE
Kotlin + MockIto + Android Instrumentation Test

### ISSUE THREAD

**Issue by theapache64** [mockito/mockito#1919]
I am trying to run an `Instrumentation` test `(androidTest)` using `Mockito` in Android with `Kotlin`.

- I've the core library in my dependencies. `'org.mockito:mockito-core:3.3.3'` 
- My project is written in `Kotlin` so I've `org.mockito:mockito-inline:3.3.3` to fix the final class issue.
- As I want to run the mocks in `Android`, I've `org.mockito:mockito-android:3.3.3` also in my dependencies.

but am getting below error while compiling the code

> More than one file was found with OS independent path
> 'mockito-extensions/org.mockito.plugins.MockMaker'

Here's a sample test code to reproduce the issue. Run this test as an Instrumentation test. `(androidTest)`. 

**MainActivityTest**

```kotlin
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Assert.assertEquals
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.mockito.Mock
import org.mockito.Mockito.`when`
import org.mockito.MockitoAnnotations

class Calculator {
    fun add(x: Int, y: Int): Int {
        return x + y
    }
}

@RunWith(AndroidJUnit4::class)
class MainActivityTest {

    @Mock
    lateinit var calculator: Calculator

    @Before
    fun before() {
        MockitoAnnotations.initMocks(this)
    }

    @Test
    fun test() {
        `when`(calculator.add(10, 10)).thenReturn(20)
        assertEquals(calculator.add(10, 10), 20)
    }
}
```

**app/build.gradle**

```groovy
plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-android-extensions'
}

android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "com.theapache64.mockitosample"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation 'org.mockito:mockito-core:3.3.3'
    androidTestImplementation 'org.mockito:mockito-android:3.3.3'
    androidTestImplementation 'org.mockito:mockito-inline:3.3.3'
}
```

Isn't it possible to run `Android instrumentation test` using `Kotlin` with `Mockito` ?

*NOTE: If you think this is a duplicate question, I've searched all over the internet. There are other issues with similar stack-trace, but my case is different.*

Any help would be highly appreciated

**Comment by TimvdLippe** [comment]
You can't use `mockito-inline` on Android. You probably want to use `dexmaker-mockito-inline` instead: https://github.com/linkedin/dexmaker#mocking-final-classes--methods

Note that the exception happens because you include both `mockito-inline` and `mockito-android`. Since these artifact both define their own Mockmaker, Mockito detects a duplication of the two. Therefore, it throws an error saying you should only include one.

**Comment by theapache64** [comment]
Okay. I've removed `mockito-inline` and replaced it with `dexmaker-mockito-inline`
```groovy
androidTestImplementation 'org.mockito:mockito-core:3.3.3'
androidTestImplementation 'org.mockito:mockito-android:3.3.3'
androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.25.1'
```
Then am getting the same error
```
More than one file was found with OS independent path 'mockito-extensions/org.mockito.plugins.MockMaker'
```

**Comment by TimvdLippe** [comment]
You need to solely use `dexmaker-mockito-inline`, so remove `mockito-android`.

**Comment by theapache64** [comment]
Okay.
```groovy
androidTestImplementation 'org.mockito:mockito-core:3.3.3'
androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.25.1'
```

Now am getting another error

```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.mockito.plugins.MockMaker$TypeMockability.mockable()' on a null object reference
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:23)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:241)
at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:229)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
at org.mockito.Mockito.mock(Mockito.java:1908)
at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:44)
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:19)
at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:39)
at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:63)
at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:58)
at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:42)
at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:68)
at com.theapache64.mockitosample.TheTest.before(MainActivityTest.kt:26)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:76)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2022)
```

**Comment by marlonlom** [comment]
why this is closed? exists a solution for this? or, mockito is just for unit testing without the android said of things? i think you should update the documentation specifying that.

**Comment by theapache64** [comment]
@marlonlom This is still an open issue.

**Comment by plastiv** [comment]
> why this is closed? exists a solution for this? or, mockito is just for unit testing without the android said of things? i think you should update the documentation specifying that.

Android ships with forked java virtual machine tailored for resource limited mobile environments. Historically, Google Android team didn't invest much into keeping android vm on par with desktop jvm. Up until android P (api 28, 2018) android virtual machine doesn't support inlining api. Mockito (or any other mock library) can't rewrite finals at runtime on such androids due to lack of supported apis. 

Which leads us to next cases:
* use mockito-inline with jvm tests no problem since they run on desktop vm
* use dexmaker if you run `androidTest` on api 28+ android devices only
* open kotlin classes at compilation time with `open` keyword or `all-open` annotation (extra plugin) for running `androidTest` tests on android devices with api 27 and below

Detailed comparison table for the reference: https://mockk.io/ANDROID.html

**Comment by tasomaniac** [comment]
Here is a reference to all-open plugin mentioned in the last comment: https://kotlinlang.org/docs/reference/compiler-plugins.html#all-open-compiler-plugin

**Comment by autorunman22** [comment]
This works for me
`androidTestImplementation 'org.mockito:mockito-core:3.3.3'`
`androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.28.0'`

**Comment by Shawn-Nichol** [comment]
Is there something else you need to add to get dexmaker-mockito-inline to work. 

I'm using 
`androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.28.0'`

And I get the following error. 
```
Execution failed for task ':app:processDebugAndroidTestManifest'.
> Could not resolve all files for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not find com.linkedin.dexmaker:dexmaker-mockito-inline:2.28.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/linkedin/dexmaker/dexmaker-mockito-inline/2.28.0/dexmaker-mockito-inline-2.28.0.pom
       - https://repo.maven.apache.org/maven2/com/linkedin/dexmaker/dexmaker-mockito-inline/2.28.0/dexmaker-mockito-inline-2.28.0.pom
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by tasomaniac** [comment]
That error means that Gradle could not find the dexmaker to download. I see that you have google maven and mavenCentral. Perhaps adding jCenter() to your repositories will help.

**Comment by crysxd** [comment]
```
androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.28.0'
```
is not on Maven Central, you need to use 
```
androidTestImplementation 'com.linkedin.dexmaker:dexmaker-mockito-inline:2.28.1'
```

**Comment by sparsh-kamat** [comment]
Hey, is this never going to be implemented? I cannot mock static methods with mockito, since I use dexmaker-mockito for mocking final classes. Is there any way to get the mockStatic method with dexmaker-mockito-inline?

**Comment by marlonlom** [comment]
> Hey, is this never going to be implemented? I cannot mock static methods with mockito, since I use dexmaker-mockito for mocking final classes. Is there any way to get the mockStatic method with dexmaker-mockito-inline?

@sparsh-kamat i think you can try adding powermockito, for mocking static methods and classes.
btw, you can think about changing the static methods for non-static and by using `dependency injection` or `factory design pattern` for refactoring these static utilities you have.
