### ISSUE TITLE
Java 14 support

### ISSUE THREAD

**Issue by davido** [mockito/mockito#1941]
I'm trying to build Gerrit Code Review, that is currently using this combination:

```
"org.mockito:mockito-core:2.24.0"
"net.bytebuddy:byte-buddy:1.9.7"
"org.ow2.asm:asm:7.2" 
```

with JDK 14 using Bazel and seeing these test breakages:

```
FAIL: //javatests/com/google/gerrit/httpd:httpd_tests (see /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/httpd/httpd_tests/test_attempts/attempt_2.log)
INFO: From Building javatests/com/google/gerrit/metrics/proc/proc_tests.jar (2 source files):
OpenJDK 64-Bit Server VM warning: Option UseParallelOldGC was deprecated in version 14.0 and will likely be removed in a future release.
INFO: From Building javatests/com/google/gerrit/acceptance/server/project/server_project.jar (4 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor):
OpenJDK 64-Bit Server VM warning: Option UseParallelOldGC was deprecated in version 14.0 and will likely be removed in a future release.
INFO: From Building javatests/com/google/gerrit/acceptance/rest/project/SetLabelIT.jar (2 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor):
OpenJDK 64-Bit Server VM warning: Option UseParallelOldGC was deprecated in version 14.0 and will likely be removed in a future release.
FAIL: //javatests/com/google/gerrit/httpd:httpd_tests (see /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/httpd/httpd_tests/test.log)

FAILED: //javatests/com/google/gerrit/httpd:httpd_tests (Summary)
      /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/httpd/httpd_tests/test.log
      /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/httpd/httpd_tests/test_attempts/attempt_1.log
      /home/jenkins/.cache/bazel/_bazel_jenkins/3239551e333dc09ba2b5ef07ff4549b6/execroot/gerrit/bazel-out/k8-fastbuild/testlogs/javatests/com/google/gerrit/httpd/httpd_tests/test_attempts/attempt_2.log
INFO: From Testing //javatests/com/google/gerrit/httpd:httpd_tests:
==================== Test output for //javatests/com/google/gerrit/httpd:httpd_tests:
JUnit4 Test Runner
.E.E.E.E.E.E.E.............................
Time: 5.91
There were 7 failures:
1) postponedLoading(com.google.gerrit.httpd.AllRequestFilterFilterProxyTest)
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface javax.servlet.FilterConfig.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Java               : 14
JVM vendor name    : Azul Systems, Inc.
JVM vendor version : 14.0.1+8
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 14.0.1+8
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 3.10.0-1127.el7.x86_64


Underlying exception : java.lang.IllegalArgumentException: org.mockito.codegenFilterConfig$MockitoMock$957995668 must be defined in the same package as org.mockito.codegen.InjectionBase/package
	at com.google.gerrit.httpd.AllRequestFilterFilterProxyTest.postponedLoading(AllRequestFilterFilterProxyTest.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)
Caused by: java.lang.IllegalArgumentException: org.mockito.codegenFilterConfig$MockitoMock$957995668 must be defined in the same package as org.mockito.codegen.InjectionBase/package
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1415)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:112)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:466)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5628)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:173)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:71)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:42)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:25)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1896)
	at org.mockito.Mockito.mock(Mockito.java:1805)
	... 33 more
```

Reproducer is here: [1].

Am I right to assume, that upgrading of Mockito/Byte Buddy/ASM might help?

Since 8.0.0 ASM supports JDK 14 (https://asm.ow2.io/versions.html) and since Byte Buddy 1.10.10 (https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.10.10), ASM 8.0.1 is used?

However, the latest available Mockito release (3.3.3) is still using Byte Buddy 1.10.05.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/269382

**Comment by davido** [comment]
I bumped the versions used to in this [CL](https://gerrit-review.googlesource.com/c/gerrit/+/269572) and kicked CI verification.

```
ADM_VERS = "8.0.1"
MOCKITO_VERS = "3.3.3"
BYTE_BUDDY_VERS = "1.10.10"
```

**Comment by TimvdLippe** [comment]
Do I understand correctly that the latest version of Mockito works with Java 14 as expected?

**Comment by davido** [comment]
Yes. it works as expected.
