### ISSUE TITLE
mockito-android fails with AndroidStudio 4

### ISSUE THREAD

**Issue by danielgomezrico** [mockito/mockito#1944]
# Env
Using:
- mockito 3.3.3:
    * `androidTestImplementation "org.mockito:mockito-android:$mockito"`
    * `testImplementation "org.mockito:mockito-core:$mockito"`

- Android Studio 4.0
- kotlin 1.3.72.

# Description
Having `androidTestImplementation "org.mockito:mockito-android:$mockito"` in gradle causes the unit test (which is not what androidTestImplementation is intended for) to fail when I call mock function I get an error on MockMaker:

```kotlin
Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
	at com.sun.proxy.$Proxy2.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:241)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:229)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1908)
...
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@66c94af4
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:54)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:44)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:22)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:19)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	... 30 more
Caused by: java.lang.NullPointerException
	at org.mockito.internal.configuration.plugins.Plugins.getMockitoLogger(Plugins.java:66)
	at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.<init>(AndroidByteBuddyMockMaker.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:49)
	... 35 more
```

I need to mock objects in my Instrumentation Tests also, so I need this dependency.

What can I do?

**Comment by danielgomezrico** [comment]
Setting 

```
    def byte_buddy = "1.10.10"

    testImplementation "net.bytebuddy:byte-buddy:$byte_buddy"
    testImplementation "net.bytebuddy:byte-buddy-android:$byte_buddy"
    testImplementation "net.bytebuddy:byte-buddy-agent:$byte_buddy"
```

Make it work, for both unit tests and instrumentation tests.

**Comment by danielgomezrico** [comment]
After updating the Android Build Tools to version `30` mockito does not crash anymore.

To be honest I don't understand why that fixed it.

**Comment by danielgomezrico** [comment]
Unit test runs but Instrumentation test still fails.

**Comment by TimvdLippe** [comment]
I think the correct scope is `androidTestCompile` instead of `androidTestInstrumentation`: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.1

**Comment by danielgomezrico** [comment]
@TimvdLippe the scope is not defined as `androidTestInstrumentation` but `androidTestImplementation`. `*Compile` is an old way of defining dependencies

**Comment by danielgomezrico** [comment]
It turns out that I was not including the dependency after all, so I confirm that after updating the `Android Build Tools 30` it works fine.

**Comment by danielgomezrico** [comment]
Nope, it is failing somewhere, Im still facing this issue.
Related to https://github.com/mockito/mockito/issues/1694

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by TimvdLippe** [comment]
Closing per the above comment.
