### ISSUE TITLE
Static Mocking Facing StackOverflowError Exception

### ISSUE THREAD

**Issue by QumberAbbas** [mockito/mockito#1990]
I am facing the following exception when trying to mock the static method

java.lang.StackOverflowError
	at org.mockito.internal.invocation.MatchersBinder.validateMatchers(MatchersBinder.java:34)
	at org.mockito.internal.invocation.MatchersBinder.bindMatchers(MatchersBinder.java:24)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:59)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:33)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:57)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handleStatic(MockMethodAdvice.java:139)
	at Application.getInstance(Application.java:)

`mockStatic(Application::class.java) {
            when (Application.getInstance()).thenReturn(ArgumentMatchers.any(Application::class.java))
        }`

Mokcito Version: 3.4.0

**Comment by QumberAbbas** [comment]
I have updated the version to 3.4.6 and I am getting the following exception, with some code snippet

java.lang.StackOverflowError
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$LatentKey.<init>(WeakConcurrentMap.java:229)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.get(WeakConcurrentMap.java:57)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.get(WeakConcurrentMap.java:259)
	at org.mockito.internal.util.concurrent.DetachedThreadLocal.get(DetachedThreadLocal.java:45)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMockedStatic(MockMethodAdvice.java:164)

**Comment by TimvdLippe** [comment]
This should now be fixed. If you are still encountering this exception, please provide a small reproduction case.
