### ISSUE TITLE
StackOverflowError when mocking java.lang.ref.ReferenceQueue

### ISSUE THREAD

**Issue by buletti** [mockito/mockito#1999]
Hi,

when I mock `java.lang.ref.ReferenceQueue` Mockito dies with a StackOverflowError.

Here is a simple test case to verify.

```java
import java.lang.ref.ReferenceQueue;
import org.junit.Assert;
import org.junit.Test;
import org.mockito.Mockito;

public class ReferenceQueueTest {

    @Test
    public void testReferenceQueueMock() {
        ReferenceQueue<String> referenceQueueMock = Mockito.mock(ReferenceQueue.class);
        Assert.assertNotNull(referenceQueueMock);
    }

}
```

I ran this test with JUnit 4.12 and Mockito 3.4.6.
I use a `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker` file with `mock-maker-inline`.

Result is
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" java.lang.StackOverflowError
	at org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher.get(MockMethodDispatcher.java:22)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:151)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:156)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:151)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:156)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:151)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:156)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:151)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:156)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.expungeStaleEntries(WeakConcurrentMap.java:130)
	at org.mockito.internal.util.concurrent.WeakConcurrentMap$WithInlinedExpunction.containsKey(WeakConcurrentMap.java:264)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:151)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMocked(MockMethodAdvice.java:156)
	at java.base/java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:117)
        [...]
```

**Comment by TimvdLippe** [comment]
You should not mock a type you dont own, especially those in the Java lang package. We dont guarantee well-behaved mocking if you mock these types, as Mockito itself is built on top of them.
