### ISSUE TITLE
Issues mocking Java framework classes in Robolectric with mockito-inline

### ISSUE THREAD

**Issue by hoisie** [mockito/mockito#2015]
Hi Mockito folks,

Currently it is not possible to mock a Java framework class (e.g. java.io.File) in Robolectric when mockito-inline is used. This issue has come up a bunch of times in Robolectric, mostly when Kotlin is used to write Robolectric tests.

https://github.com/robolectric/robolectric/issues/5522
https://github.com/robolectric/robolectric/issues/5638
https://github.com/robolectric/robolectric/issues/5865

For instance, if a trivial tests is run with the Robolectric test runner with mockito-inline:

```java
  @Test
  public void file_getAbsolutePath_isMockable() throws Exception {
    File file = mock(File.class);
    doReturn("absolute/path").when(file).getAbsolutePath();
    assertThat(file.getAbsolutePath()).isEqualTo("absolute/path");
  }
```

An NPE will result:
```
java.lang.NullPointerException
	at org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher.isConstructorMock(MockMethodDispatcher.java:41)
	at java.base/java.io.File.<init>(File.java)
	at java.base/sun.net.www.protocol.file.Handler.openConnection(Handler.java:80)
	at java.base/sun.net.www.protocol.file.Handler.openConnection(Handler.java:72)
	at java.base/java.net.URL.openConnection(URL.java:1063)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:84)
	at java.base/sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
	at java.base/java.net.URL.openConnection(URL.java:1063)
	at java.base/java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:327)
	at org.robolectric.internal.bytecode.SandboxClassLoader.getClassBytesAsStreamPreferringLocalUrls(SandboxClassLoader.java:101)
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:172)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:129)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.robolectric.Shadows.reset(Shadows.java:2298)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:349)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:347)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Robolectric uses an instrumenting ClassLoader that transforms Android classes to use real implementations:
https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/internal/bytecode/SandboxClassLoader.java#L105

Here is a fork of Robolectric that has a test that captures the issue:
https://github.com/hoisie/robolectric/tree/mockito-inline-test

You can see the failure using the following command:
`./gradlew  :integration_tests:mockito-experimental:test`

Any tips/help debugging would be greatly appreciated. It would be nice to figure out what Robolectric is doing to prevent this from working.

**Comment by raphw** [comment]
Are you moving `org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher` to another class loader? Normally, Mockito injects this class into the bootstrap class loader and then initializes this dispatcher with a random identifier. All inline mocks call this class with the very same identifier to communicate with Mockito. The bootstrap loader is used to avoid any issues with class loader hierarchies.

The null pointer exception suggests that the class `org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher` exists on multiple class loaders and that the initialization hit another class loader then the dispatcher. The easiest would be to build something into Robolectric that makes sure that the class loader tricks you apply never targets the `MockMethodDispatcher`. It must only exist in the boot loader at all times.

**Comment by raphw** [comment]
This is indeed the problem, the loader of `MockMethodDispatcher` if resolved from the mock type is `org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader`. The dispatcher must always be loaded by the bootstrap class loader. You need to exclude it from your class loader shadowing for it to work with boot classes.

**Comment by raphw** [comment]
Can you try again with the release from just now? I defined the window of intercpting construction as narrowly as possible.
