### ISSUE TITLE
Error mocking when using Java 15

### ISSUE THREAD

**Issue by mitchdennett** [mockito/mockito#2057]
When calling `mock(HttpServletRequest.class)` I get the following error when using Java 15.

Mockito Version: 3.5.13
Java: OpenJDK 15

```
2020-09-30T00:46:39.4931240Z java.lang.instrument.IllegalClassFormatException: Error while instrumenting org/mockito/codegen/HttpServletRequest$MockitoMock$1385459789.
2020-09-30T00:46:39.4932810Z 	at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
2020-09-30T00:46:39.4934630Z 	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
2020-09-30T00:46:39.4936730Z 	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
2020-09-30T00:46:39.4938460Z 	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
2020-09-30T00:46:39.4940270Z 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
2020-09-30T00:46:39.4941200Z 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
2020-09-30T00:46:39.4942150Z 	at java.base/java.lang.ClassLoader$ByteBuddyAccessor$M0qCSb1L.defineClass(Unknown Source)
2020-09-30T00:46:39.4955440Z 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
2020-09-30T00:46:39.4957840Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-30T00:46:39.4959370Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-09-30T00:46:39.4960750Z 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:918)
2020-09-30T00:46:39.4962520Z 	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:234)
2020-09-30T00:46:39.4966450Z 	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:110)
2020-09-30T00:46:39.4968220Z 	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:233)
2020-09-30T00:46:39.4970040Z 	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
2020-09-30T00:46:39.4974760Z 	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6292)
2020-09-30T00:46:39.4983040Z 	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:200)
2020-09-30T00:46:39.4985890Z 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
2020-09-30T00:46:39.4988600Z 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
2020-09-30T00:46:39.4990410Z 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
2020-09-30T00:46:39.4991460Z 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
2020-09-30T00:46:39.4992510Z 	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
2020-09-30T00:46:39.4993550Z 	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
2020-09-30T00:46:39.4995770Z 	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
2020-09-30T00:46:39.4999180Z 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:77)
2020-09-30T00:46:39.5007830Z 	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:43)
2020-09-30T00:46:39.5010800Z 	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:29)
2020-09-30T00:46:39.5012620Z 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:52)
2020-09-30T00:46:39.5013690Z 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
2020-09-30T00:46:39.5014460Z 	at org.mockito.Mockito.mock(Mockito.java:1949)
2020-09-30T00:46:39.5015030Z 	at org.mockito.Mockito.mock(Mockito.java:1860)
2020-09-30T00:46:39.5016000Z 	at com.severell.core.jetty.BasicServletTest.setup(BasicServletTest.java:37)
2020-09-30T00:46:39.5017470Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-09-30T00:46:39.5019210Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
2020-09-30T00:46:39.5021280Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-09-30T00:46:39.5022780Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-09-30T00:46:39.5024610Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
2020-09-30T00:46:39.5026510Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2020-09-30T00:46:39.5028780Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2020-09-30T00:46:39.5031090Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-09-30T00:46:39.5033810Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:126)
2020-09-30T00:46:39.5036650Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeEachMethod(TimeoutExtension.java:76)
2020-09-30T00:46:39.5039490Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-09-30T00:46:39.5041610Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-09-30T00:46:39.5043940Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-09-30T00:46:39.5046610Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-09-30T00:46:39.5049530Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-09-30T00:46:39.5052400Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-09-30T00:46:39.5054680Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-09-30T00:46:39.5056800Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-09-30T00:46:39.5059850Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:490)
2020-09-30T00:46:39.5063620Z 	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$19(ClassBasedTestDescriptor.java:475)
2020-09-30T00:46:39.5070720Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$2(TestMethodTestDescriptor.java:167)
2020-09-30T00:46:39.5074320Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:195)
2020-09-30T00:46:39.5077540Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5081790Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:195)
2020-09-30T00:46:39.5086480Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:164)
2020-09-30T00:46:39.5089620Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
2020-09-30T00:46:39.5092210Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
2020-09-30T00:46:39.5094640Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-09-30T00:46:39.5097460Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5100000Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-09-30T00:46:39.5102140Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-09-30T00:46:39.5104220Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-09-30T00:46:39.5106750Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5109940Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-09-30T00:46:39.5112460Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-09-30T00:46:39.5115310Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-09-30T00:46:39.5130070Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-09-30T00:46:39.5134100Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-09-30T00:46:39.5136980Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5139500Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-09-30T00:46:39.5141490Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-09-30T00:46:39.5143460Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-09-30T00:46:39.5145950Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5148670Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-09-30T00:46:39.5151160Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-09-30T00:46:39.5152630Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-09-30T00:46:39.5155550Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-09-30T00:46:39.5159280Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-09-30T00:46:39.5161960Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5164510Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-09-30T00:46:39.5166530Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-09-30T00:46:39.5171660Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-09-30T00:46:39.5176460Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-09-30T00:46:39.5179330Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-09-30T00:46:39.5202580Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-09-30T00:46:39.5207080Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-09-30T00:46:39.5211340Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-09-30T00:46:39.5216060Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-09-30T00:46:39.5218420Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
2020-09-30T00:46:39.5220140Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
2020-09-30T00:46:39.5221860Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
2020-09-30T00:46:39.5224200Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
2020-09-30T00:46:39.5226900Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
2020-09-30T00:46:39.5229940Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
2020-09-30T00:46:39.5232450Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
2020-09-30T00:46:39.5234260Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
2020-09-30T00:46:39.5235740Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
2020-09-30T00:46:39.5236970Z Caused by: java.io.IOException: Error while instrumenting org/mockito/codegen/HttpServletRequest$MockitoMock$1385459789.
2020-09-30T00:46:39.5238210Z 	at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrumentError(Instrumenter.java:159)
2020-09-30T00:46:39.5239810Z 	at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:109)
2020-09-30T00:46:39.5241180Z 	at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:92)
2020-09-30T00:46:39.5241960Z 	... 98 more
2020-09-30T00:46:39.5242560Z Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
2020-09-30T00:46:39.5243520Z 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:195)
2020-09-30T00:46:39.5244430Z 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:176)
2020-09-30T00:46:39.5245340Z 	at org.jacoco.agent.rt.internal_43f5073.asm.ClassReader.<init>(ClassReader.java:162)
2020-09-30T00:46:39.5246670Z 	at org.jacoco.agent.rt.internal_43f5073.core.internal.instr.InstrSupport.classReaderFor(InstrSupport.java:280)
2020-09-30T00:46:39.5248200Z 	at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:75)
2020-09-30T00:46:39.5249500Z 	at org.jacoco.agent.rt.internal_43f5073.core.instr.Instrumenter.instrument(Instrumenter.java:107)
2020-09-30T00:46:39.5250250Z 	... 99 more
```
If you need more info from me please ask. First time posting an issue here.

**Comment by mitchdennett** [comment]
issue with Jacoco not mockito. Sorry for the issue. Update Jacoco to 0.8.6 and it fixed this issue
