### ISSUE TITLE
Misleading error message for failed InOrder argument matcher

### ISSUE THREAD

**Issue by Marcono1234** [mockito/mockito#2060]
### Version
Mockito version: 3.5.13

### Description
When using `org.mockito.InOrder` and the argument matcher fails for the second or any subsequent verification call (but not the first one), the error is reported as:
> Verification in order failure
Wanted but not invoked:

This is misleading because the method is actually invoked, but the arguments did not match. Normally, when not using `InOrder` or when verifying the first `InOrder` call, the error is, as expected, reported as:
> Argument(s) are different! Wanted:

### Test case
```java
interface MyInterface {
    void doSomething(String s);
}

public static void main(String[] args) {
    MyInterface mock = mock(MyInterface.class);
    mock.doSomething("something");
    mock.doSomething("this");
    InOrder inOrder = inOrder(mock);
    inOrder.verify(mock).doSomething("something");
    // Using custom ArgumentMatcher here to demonstrate that error is even
    // more confusing then
    inOrder.verify(mock).doSomething(argThat(arg -> arg.equals("that")));
}
```

Exception:
```
Exception in thread "main" org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure
Wanted but not invoked:
myInterface.doSomething(
    <Mockito test$$ lambda$ 4 6/ 0x 0 0 0 0 0 0 0 8 0 0c 8fc 4 0>
);
-> at MockitoTest.main(MockitoTest.java:18)
Wanted anywhere AFTER following interaction:
myInterface.doSomething("something");
-> at MockitoTest.main(MockitoTest.java:12)

	at MockitoTest.main(MockitoTest.java:18)
```

**Comment by madisoncfallin** [comment]
I'll look into this

**Comment by madisoncfallin** [comment]
Please assign this to me! 😄

**Comment by Marcono1234** [comment]
@madisoncfallin, I would not mind if you gave it a try. Though I do not know whether the maintainers actually consider this a bug. [`CONTRIBUTING.md`](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md) might be useful for you in case you have not seen it yet.

**Comment by alvaro-martinez-hernandez** [comment]
@Marcono1234 @madisoncfallin I think we have found a fix for this. In `MissingInvocationChecker:68`, you can re-write this:

```
        if (previousInOrder != null)) {
            throw wantedButNotInvokedInOrder(wanted, previousInOrder);
        }
```

As this:
```
        if (previousInOrder != null && !wanted.getInvocation().getMethod().equals(previousInOrder.getMethod())) {
            throw wantedButNotInvokedInOrder(wanted, previousInOrder);
        }
```

So the `VerificationInOrderFailure` error is only thrown if methods are actually different. Otherwise, `checkMissingInvocation` is called. What do you think?

**Comment by Marcono1234** [comment]
Thanks a lot for taking a look at this! That change looks reasonable to me, though I am not very familiar with the code base. Might be worth creating a pull request for it. Feel free to use the test case I showed above, in case you want to add a new test for this.
