### ISSUE TITLE
Mockito throws NPE with some combination of mocks

### ISSUE THREAD

**Issue by abysas** [mockito/mockito#2081]
This is a really weird issue. With Mockito 3.5.15/3.6.0, the following test fails:

```java
@ExtendWith(MockitoExtension.class)
public class MethodMockTest {

    @Mock
    private java.lang.reflect.Method method;

    @Mock
    private RequiredPermission permission;

    @Test
    void testMock() {
        when(permission.function()).thenReturn("VIEW");
        Assertions.assertEquals("VIEW", permission.function());
    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    public @interface RequiredPermission {
        String function();
    }
}
```

The test fails with NPE:
```
java.lang.NullPointerException
	at java.base/java.lang.reflect.Method.getParameterTypes(Method.java:311)
	at org.mockito.internal.creation.DelegatingMethod.<init>(DelegatingMethod.java:20)
	at org.mockito.internal.invocation.DefaultInvocationFactory.createMockitoMethod(DefaultInvocationFactory.java:80)
	at org.mockito.internal.invocation.DefaultInvocationFactory.createInvocation(DefaultInvocationFactory.java:59)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:83)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:157)
	at org.example.MethodMockTest$RequiredPermission$MockitoMock$13836760.function(Unknown Source)
	at org.example.MethodMockTest.testMock(MethodMockTest.java:26)
...
```

If there is no ` java.lang.reflect.Method` mock created (note that it is not used in the test), the test works perfectly. 

This test was working with Mockito 3.3.3.

Java JDK: 11.0.3+12-LTS

**Comment by abysas** [comment]
Maven project: [annotation-mock.zip](https://github.com/mockito/mockito/files/5447445/annotation-mock.zip)

**Comment by TimvdLippe** [comment]
The mocking of `java.lang.*` classes (and particularly its reflection API including `java.lang.reflect.Method`) is not supported. These are the building blocks that Mockito relies on and produce undefined behavior.
