### ISSUE TITLE
[mock-maker-inline] java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost, NestMembers, Record, or PermittedSubclasses attribute

### ISSUE THREAD

**Issue by sratz** [mockito/mockito#2169]
- [X] The mockito message in the stacktrace have useful information, but it didn't help
 - [X] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [X] Provide versions (mockito / jdk / os / any other relevant information)
 - [X] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [X] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

Environment:
- Mockito 3.7.0
- OpenJDK 11 / 15
- Windows 10 / Linux SLES 15 SP1

Using mock-maker-inline, some classes cannot be spied.

I narrowed it down to the following minimal example:

```java
import org.junit.Test;
import org.mockito.Mockito;

public class TestWithProblematicClass {

	@Test
	public void test() throws Exception {
		Mockito.spy(new ProblematicClass());
	}
}

class ProblematicClass {

	public void foo() {
		new Thread(() -> {
			new Object() {
			};
		});
	}

}

```

It fails with

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class ProblematicClass.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 15
JVM vendor name    : SAP SE
JVM vendor version : 15.0.1+9
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 15.0.1+9
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class ProblematicClass]
	at TestWithProblematicClass.test(TestWithProblematicClass.java:8)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class ProblematicClass]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	... 27 more
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost, NestMembers, Record, or PermittedSubclasses attribute
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:278)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:212)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:46)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:43)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:36)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:379)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.doCreateMock(InlineByteBuddyMockMaker.java:339)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createSpy(InlineByteBuddyMockMaker.java:329)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:45)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
	at org.mockito.Mockito.spy(Mockito.java:2033)
	... 27 more


```
Seems to be a caused by mixture of lambda expressions inside constructor calls and nested anonymous classes. 

All of these alternative variants work fine:

```java
class ProblematicClass {

	public void foo() {
		new Thread(() -> {
			new Object();
		});
	}

}
```

```java
class ProblematicClass {

	public void foo() {
		Runnable r = () -> {
			new Object() {
			};
		};
		new Thread(r);
	}

}
```

```java
class ProblematicClass {

	public void foo() {
		new Thread(new Runnable() {
			@Override
			public void run() {
				new Object() {
				};
			}
		});
	}

}
```

**Comment by raphw** [comment]
Seems like the JVM now forbids unsealing by instrumentation. In this case, we cannot longer support mocking sealed classes and interfaces.

**Comment by raphw** [comment]
I cannot reproduce this, tried with SAP Machine 15, just freshly downloaded and Mockito 3.7.7.

**Comment by sratz** [comment]
This is interesting.
Indeed, the following works fine:

```
$ javac -classpath .;org.objenesis_3.1.0.jar;org.mockito.mockito-core_3.7.7.jar;net.bytebuddy.byte-buddy-agent_1.10.19.jar;net.bytebuddy.byte-buddy_1.10.19.jar;junit-4.13.1.jar;org.hamcrest_2.2.0.jar TestWithProblematicClass.java
$ java -classpath .;org.objenesis_3.1.0.jar;org.mockito.mockito-core_3.7.7.jar;net.bytebuddy.byte-buddy-agent_1.10.19.jar;net.bytebuddy.byte-buddy_1.10.19.jar;junit-4.13.1.jar;org.hamcrest_2.2.0.jar org.junit.runner.JUnitCore TestWithProblematicClass
JUnit version 4.13.1
.OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

Time: 0,84

OK (1 test)
```

However, when I compile using Eclipse (2020-12), it fails.

I have attached the 3 .class file created by Eclipse:
[compiledByEcj.zip](https://github.com/mockito/mockito/files/5829444/compiledByEcj.zip)

Is there a way to find out what's different here?

**Comment by raphw** [comment]
Could you run with -Dnet.bytebuddy.dump=/some/folder? This captures in and output of Byte Buddy.

**Comment by sratz** [comment]
[byteBuddyDump.zip](https://github.com/mockito/mockito/files/5829554/byteBuddyDump.zip)

**Comment by sratz** [comment]
I tracked this down a bit further: This only happens if I target JavaSE-11 or higher. Targeting JavaSE-1.8 this works even in Eclipse.

**Comment by raphw** [comment]
Sorry for the overly late reply. I just had a look at the class files and it seems to me like the nestmates attribute has changed. This should not happen, but is consistent with your observation that this only happens in Java 11 or later where this attribute was introduced.

Could you double check if this is still the case with a recent version of Byte Buddy? You can add version 1.10.22 explicitly to enforce this.

**Comment by sratz** [comment]
I tested with 1.10.22, but the issue persists.

**Comment by raphw** [comment]
Are you using the eclipse compiler by any chance? If it's a general issue, could you create a reproducer?

**Comment by sratz** [comment]
Yes, I am using Eclipse targeting Java 11.

I created a simple, self-contained, reproducer:
[MockitoByteBuddyInlineJava11EcjProblem.zip](https://github.com/mockito/mockito/files/6162859/MockitoByteBuddyInlineJava11EcjProblem.zip)

- Import project
- Open foo.bar.TestWithProblematicClass
- Run -> Run As -> JUnit Test

**Comment by raphw** [comment]
I'm using IntelliJ and only get:

> java.lang.reflect.InaccessibleObjectException: Unable to make public void foo.bar.TestWithProblematicClass.test() throws java.lang.Exception accessible: module MockitoByteBuddyInlineJava11EcjProblem does not "exports foo.bar" to module junit

**Comment by sratz** [comment]
Hmm,
maybe IntelliJ did not pick up the modular project setup from .classpath? (Why IntelliJ in the first place?)

Can you try again with this non-modular setup?
[MockitoByteBuddyInlineJava11EcjProblemV2.zip](https://github.com/mockito/mockito/files/6170879/MockitoByteBuddyInlineJava11EcjProblemV2.zip)

**Comment by raphw** [comment]
That's what I already tried. I believe this is an issue with the Eclipse Java compiler. Could you try with a regular *javac*?

**Comment by sratz** [comment]
Yes, it works fine using regular javac. That's what I did in comment https://github.com/mockito/mockito/issues/2169#issuecomment-762142492

So there must be something different in the .class files generated by javac and ecj.

I created two fresh .class files, once with ecj and once with javac:
[ecj.jar.zip](https://github.com/mockito/mockito/files/6172153/ecj.jar.zip)
[javac.jar.zip](https://github.com/mockito/mockito/files/6172154/javac.jar.zip)

```
$ java -classpath javac.jar;mockito-core-3.8.0.jar;byte-buddy-1.10.22.jar;byte-buddy-agent-1.10.22.jar;junit-4.13.2.jar;org.hamcrest_2.2.0.jar org.junit.runner.JUnitCore foo.bar.TestWithProblematicClass
JUnit version 4.13.2
.
Time: 1,954

OK (1 test)
```
```
$ java -classpath ecj.jar;mockito-core-3.8.0.jar;byte-buddy-1.10.22.jar;byte-buddy-agent-1.10.22.jar;junit-4.13.2.jar;org.hamcrest_2.2.0.jar org.junit.runner.JUnitCore foo.bar.TestWithProblematicClass
JUnit version 4.13.2
.E
Time: 1,852
There was 1 failure:
1) test(foo.bar.TestWithProblematicClass)
org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: class foo.bar.ProblematicClass.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : SAP SE
JVM vendor version : 11.0.10+9-LTS-sapmachine
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.10+9-LTS-sapmachine
JVM info           : mixed mode
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class foo.bar.ProblematicClass]
        at foo.bar.TestWithProblematicClass.test(TestWithProblematicClass.java:9)
        ... 32 trimmed
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class foo.bar.ProblematicClass]
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
        ... 34 more
Caused by: java.lang.IllegalStateException:
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:280)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:213)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:51)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:48)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
        at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:41)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:379)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.doCreateMock(InlineByteBuddyMockMaker.java:339)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createSpy(InlineByteBuddyMockMaker.java:329)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:45)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
        at org.mockito.Mockito.spy(Mockito.java:2035)
        ... 34 more
Caused by: java.lang.IllegalStateException: Could not invoke Class::getNestMembers
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher$ForJava11CapableVm.getNestMembers(TypeDescription.java:9052)
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getNestMembers(TypeDescription.java:8830)
        at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:432)
        at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:782)
        at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:757)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:379)
        at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
        at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:276)
        ... 48 more
Caused by: java.lang.NoClassDefFoundError: foo/bar/ProblematicClass$2
        at java.base/java.lang.Class.getNestMembers0(Native Method)
        at java.base/java.lang.Class.getNestMembers(Class.java:4016)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType$Dispatcher$ForJava11CapableVm.getNestMembers(TypeDescription.java:9048)
        ... 59 more
Caused by: java.lang.ClassNotFoundException: foo.bar.ProblematicClass$2
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 66 more

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by raphw** [comment]
The difference lies in the nest mates attribute which gets normalized by ASM and becomes incompatible as a consequence. The attribute should be the same as when using javac. The problem here is the Eclipse compiler, in my opinion.

**Comment by sratz** [comment]
Interesting. I have opened Eclipse bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=572190

**Comment by sratz** [comment]
The bug in ECJ has been found and fixed.

Closing this bug here (invalid/not-mockito).

Thank you for the help and analysis, @raphw!
