### ISSUE TITLE
Regression when mocking a type in a signed package

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#218]
I just tried to upgrade from 2.0.8-beta to 2.0.9-beta (and then 2.0.10-beta). One of our tests started failing:

	org.mockito.exceptions.base.MockitoException: 
	Mockito cannot mock this class: interface com.microsoft.windowsazure.services.servicebus.ServiceBusContract

	Mockito can only mock visible & non-final classes.
	If you're not sure why you're getting this error, please report to the mailing list.
		at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
		at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$ClassLoadingAction.run(ClassInjector.java:336)
		at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$ClassLoadingAction.run(ClassInjector.java:306)
		at java.security.AccessController.doPrivileged(Native Method)
		at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.inject(ClassInjector.java:122)
		at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$5.load(ClassLoadingStrategy.java:144)
		at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:3380)
		at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:55)
		at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
		at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
		at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
		at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:49)
		at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:22)
		at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
		at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
		at org.mockito.Mockito.mock(Mockito.java:1378)
		at org.mockito.Mockito.mock(Mockito.java:1256)

I thought this was odd, since the mentioned type (`ServiceBusContract`) is a public interface. So I put a breakpoint at `org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator:85`. The underlying error turns out to be:

    java.lang.SecurityException: class "com.microsoft.windowsazure.services.servicebus.models.BrokeredMessage$MockitoMock$931493758$auxiliary$gVJxoE2i"'s signer information does not match signer information of other classes in the same package

If I understand correctly, Mockito just switched from GCLIB to Byte Buddy. Perhaps this is an edge case that the new library doesn't cover yet?

**Comment by bric3** [comment]
That is possible or more probable we missed something. Thank you for testing this builds so early ;)

I'd like some integration tests for "uncommon" stuff like signed package, OSGI stuff etc.

**Comment by bric3** [comment]
This was indeed something I missed, I pushed a fix. CI should generate a new beta. That should be propagated first on bintray then maven (sync takes 1 days or so).

**Comment by Stephan202** [comment]
Awesome, thanks!

**Comment by bric3** [comment]
Should be in 2.0.11-beta

**Comment by Stephan202** [comment]
Just upgraded to 2.0.11-beta. Verified fixed. Thanks again :)

**Comment by bric3** [comment]
Cool thanks again for the feedback

**Comment by bric3** [comment]
By the way, since you're an early beta user, I'd like to warn you that at some point along the 2.0.x beta development there will be breaking changes in the matcher API in 2.0. We'll see how to mitigate impact along the way too.
