### ISSUE TITLE
2.0.8-beta -> 2.0.9-beta 'Unable to initialize @Spy annotated field

### ISSUE THREAD

**Issue by brcolow** [mockito/mockito#220]
No test failures when using 2.0.8-beta, but when incrementing to 2.0.9-beta, the following error occurs:

````
org.mockito.exceptions.base.MockitoException: Unable to initialize @Spy annotated field 'monitorTaskScheduler'.
Unable to create mock instance of type 'MonitorTaskScheduler'
	at net.project.dash.monitor.MonitorTaskScheduler$MockitoMock$1184625981.getExecutorService(Unknown Source)
	at net.project.dash.monitor.MonitorTaskScheduler.<init>(MonitorTaskScheduler.java:39)
	at net.project.dash.monitor.MonitorTaskScheduler$MockitoMock$1184625981.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.invokeConstructor(ConstructorInstantiator.java:42)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.noArgConstructor(ConstructorInstantiator.java:66)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.newInstance(ConstructorInstantiator.java:17)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1284)
	at org.mockito.internal.configuration.SpyAnnotationEngine.newSpyInstance(SpyAnnotationEngine.java:117)
	at org.mockito.internal.configuration.SpyAnnotationEngine.process(SpyAnnotationEngine.java:67)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:73)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:55)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
	at net.project.dash.monitor.MonitorTaskSchedulerTest.setUp(MonitorTaskSchedulerTest.java:38)
````

Relevant code (MonitorTaskSchedulerTest.java)

````java
@Spy
MonitorTaskScheduler monitorTaskScheduler;

@Before
public void setUp()
{
    MockitoAnnotations.initMocks(this);
}
````

Relevant code (MonitorTaskScheduler.java)

````java
public class MonitorTaskScheduler
{
    public MonitorTaskScheduler()
    {
        this.futureToTaskMap = new ConcurrentHashMap<>();
    }
}
````

**Comment by bric3** [comment]
Can you try with 2.0.11-beta ?

**Comment by brcolow** [comment]
Same problem with 2.0.11-beta (in fact, I started with that version, and then decremented one by one till the problem was gone).

**Comment by brcolow** [comment]
If I had to make a (somewhat) educated guess I would say it is most likely related to 3b445aa057ada4e64b096634b011eab399f03f56

**Comment by bric3** [comment]
It's not really that commit, it probably have to do with the change from CGLIB to ByteBuddy. I cannot reproduce locally, can you craft a reproducible test ?

**Comment by brcolow** [comment]
MonitorTaskScheduler.java: 
````java
public class MonitorTaskScheduler
{
    private final Map<ScheduledFuture<?>, MonitorTask> futureToTaskMap;
    private final ScheduledExecutorService executor;

    public MonitorTaskScheduler()
    {
        futureToTaskMap = new ConcurrentHashMap<>();
        executor = (ScheduledExecutorService) getExecutorService();
    }

    @VisibleForTesting
    ExecutorService getExecutorService()
    {
        return new MonitorTaskExecutor(this);
    }
}
````

MonitorTaskSchedulerTest.java:
````java
@Spy
MonitorTaskScheduler monitorTaskScheduler;

@Before
public void setUp()
{
    MockitoAnnotations.initMocks(this);
    doReturn(new SynchronousExecutor()).when(monitorTaskScheduler).getExecutorService();
}

@Test
public void test()
{
    monitorTaskScheduler.schedule(() -> { System.out.println("Task") });
}

public class SynchronousExecutor extends AbstractExecutorService
{
    private volatile boolean shutdown;

    public void shutdown()
    {
        shutdown = true;
    }

    public List<Runnable> shutdownNow()
    {
        return null;
    }

    public boolean isShutdown()
    {
        return shutdown;
    }

    public boolean isTerminated()
    {
        return shutdown;
    }

    public boolean awaitTermination(long time, TimeUnit unit) throws InterruptedException
    {
        return true;
    }

    public void execute(Runnable runnable)
   {
        runnable.run();
    }

}
````

**Comment by bric3** [comment]
I've identified an issue but the given code is incomplete and I don't get the same stacktrace, so it may be another issue.

Here's mine : 

```java
public class ConstrucotrInvokingMethodShouldWorkTest {
    @Test
    public void should_be_able_to_create_spy() throws Exception {
        Mockito.spy(new HasConstructorInvokingMethod());
    }

    private static class HasConstructorInvokingMethod {
        public HasConstructorInvokingMethod() {
            someMethod();
        }
        void someMethod() { }
    }
}
```

In the meantime two workaround, sticks to an older version, or modify the code so it doesn't call methods in the constructor, which may indicate the design is wrong in OOP (builders or factory to the rescue).

**Comment by bric3** [comment]
Actually there maybe a better workaround, use the `Mockito.spy()` factory method.

**Comment by brcolow** [comment]
Sorry for not providing a complete example..was trying to copy and paste stuff from difference sources for simplification purposes. Glad you were at least able to identify an issue out of it. I will take your suggestions and do what I can. Thanks.

**Comment by bric3** [comment]
You're welcome, thanks for testing betas ;)

**Comment by brcolow** [comment]
2d036ec fixed my original issue indeed! Thanks so much, great work.
