### ISSUE TITLE
3.7.7 inline can not find MockMethodDispatcher - has worked in 3.2.4

### ISSUE THREAD

**Issue by smiklosovic** [mockito/mockito#2203]
Hi,

I am from Apache Cassandra project where we want to use Mockito to mock static methods, I know this feature was introduced in Mockito 3.4.0, we had version 3.2.4 so I had to update it.

My test where I was mocking statics works fine but update to that version broke other tests and I am not sure why. The exception I am getting all over again is this:

Dependency versions are:

mockito-inline:3.7.7
bytebuddy and bytebuddy-agent: 1.10.20
junit 4.12

I do not have any extension files etc, I just merely bumped versions, we had `mockito-core` but as I understand it mockito-inline already includes it so we do not depend on it explicitly.

Any suggestions how to resolve this would be appreciated.

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
	at com.sun.proxy.$Proxy26.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:250)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:232)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:60)
	at org.mockito.Mockito.spy(Mockito.java:2035)
	at org.apache.cassandra.distributed.mock.nodetool.InternalNodeProbe.connect(InternalNodeProbe.java:76)
	at org.apache.cassandra.distributed.mock.nodetool.InternalNodeProbe.<init>(InternalNodeProbe.java:60)
	at org.apache.cassandra.distributed.impl.Instance$DTestNodeTool.<init>(Instance.java:818)
	at org.apache.cassandra.distributed.impl.Instance.lambda$nodetoolResult$39(Instance.java:726)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@1a352001
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:65)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:19)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:16)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:28)
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:52)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: org/mockito/internal/creation/bytebuddy/inject/MockMethodDispatcher
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:305)
	... 24 more
Caused by: java.lang.ClassNotFoundException: org.mockito.internal.creation.bytebuddy.inject.MockMethodDispatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at org.apache.cassandra.distributed.shared.InstanceClassLoader.loadClassInternal(InstanceClassLoader.java:101)
	at org.apache.cassandra.distributed.shared.InstanceClassLoader.loadClass(InstanceClassLoader.java:87)
	... 25 more
```

It particularly fails on doing this spy

`StorageServiceMBean mock = Mockito.spy(StorageService.instance);`

What is interesting is that some code in MockMethodDispatcher is red like this, invalidating caches and restart of IDEA does not seem to help either.

What has happened between Mockito core 3.2.4 and inline 3.7.7 that it stopped to work? 3.4.0 does not work either ...

https://ibb.co/rQ4Pkrg

**Comment by TimvdLippe** [comment]
Exceptions like these most commonly occur with corrupted `.m2` repositories. Could you clear your `.m2` repository for Mockito and ByteBuddy and reinstall the dependencies?

**Comment by TuomasKiviaho** [comment]
> Exceptions like these most commonly occur with corrupted `.m2` repositories. Could you clear your `.m2` repository for Mockito and ByteBuddy and reinstall the dependencies?

This has to do with `MockMethodDispatcher.raw` work-a-round (#845) albeit it indeed feels like the class file would be actually be missing from jar itself. The dynamically crafted `mockitoboot.jar` containing the actual class derived from the raw is indeed installed successfully to bootstrap classloader but in environments with sophisticated classloading mechanism like OSGi it may not be reachable by the `InlineByteBuddyMockMaker` or more specific the `InlineBytecodeGenerator` since the test is not done the classloader that is being actually used.

```
Caused by: java.lang.NoClassDefFoundError: org/mockito/internal/creation/bytebuddy/inject/MockMethodDispatcher
        at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:317)
        at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:25)
```

**Comment by TuomasKiviaho** [comment]
I think that instead of using the generic `Respoter.missingByteBuddyDependency` there could be at least a bit more specific error message in this case that gives hints on the steps needed to fix the issue. 

The first thing that came to my mind would have been to try to fix this by providing the `MockMethodDispatcher` to the classloader of `InlineBytecodeGenerator` in the way explained at https://github.com/mockito/mockito/issues/845#issuecomment-496939995 but wouldn't this lead to class incompatibilities where call to `MockMethodDispatcher.set` would wind up into wrong class being loaded.

**Comment by pkolaczk** [comment]
I'm also running into this with Cassandra 4.0 distributed tests while trying to add a test that mocks a final method.
Is there any workaround? Looks like our `InstanceClassloader` cannot load the `MockMethodDispatcher.raw` file.
How should a custom classloader behave in order to be able to work with mock-maker-inline?

**Comment by raphw** [comment]
I think that it does not correctly resolve the resource. The class loader is queried for getResourceAsStream(name). If this call returns null, the error in question is raised.

**Comment by rovarga** [comment]
With mockito-5 defaulting to the inline mockmaker, the problem with OSGi highlighted above has become a bit annoying, the default configuration triggers it.

In OpenDaylight we have a few tests which hack around quite a bit to get Mockito working in OSGi (through pax-exam). Much of this is historic, but as we are in control of the environment being booted up (to the point of JVM options), I wonder whether we could deploy an artifact to the JVM substrate and indicate to mockito it should expect the JVM-level setup being done and not try to do funky things.

**Comment by raphw** [comment]
Everything we can automate, I would prefer it automated. Could you create a reproductive test case and add it as a PR draft to the Mockito repository? I am happy to see if I can work around it.

**Comment by timothyjward** [comment]
Is there a solution to this for OSGi environments now?
