### ISSUE TITLE
PotentialStubbingProblem wrongly reported with spy and overload

### ISSUE THREAD

**Issue by henri-tremblay** [mockito/mockito#2215]
This is related to #769 and #1496. I give a full test case below. There are numerous problems with it. If you run it, you get this error:

```
org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'isTrustedPrincipal' method:
    accessControl.isTrustedPrincipal(
    pro.tremblay.Principal@2b4bac49
);
    -> at pro.tremblay.AccessControl.allowAccess(AccessControl.java:12)
 - has following stubbing(s) with different arguments:
    1. accessControl.isTrustedPrincipal("");
      -> at pro.tremblay.StrictnessTest.test(StrictnessTest.java:22)
Typically, stubbing argument mismatch indicates user mistake when writing tests.
Mockito fails early so that you can debug potential problem easily.
However, there are legit scenarios when this exception generates false negative signal:
  - stubbing the same method multiple times using 'given().will()' or 'when().then()' API
    Please use 'will().given()' or 'doReturn().when()' API for stubbing.
  - stubbed method is intentionally invoked with different arguments by code under test
    Please use default or 'silent' JUnit Rule (equivalent of Strictness.LENIENT).
For more information see javadoc for PotentialStubbingProblem class.

	at pro.tremblay.AccessControl.allowAccess(AccessControl.java:12)
	at pro.tremblay.StrictnessTest.test(StrictnessTest.java:23)
```

1. It reports a wrong bad stubbing. I think it's caused by the overloaded method on the spy
2. The message is wrong because is talks about stubbing of isTrustedPrincipal("") because anyString returns ""
3. PotentialStubbingProblem is an exception. I don't think it should be. It should probably extend AssertionError.

About this last point, the problem is that my original code was doing something like this:

```
    public boolean allowAccess() {
        try {
            return isTrustedPrincipal(principal);
        } catch(Exception e) {
            return true;
        }
    }
```

So the `PotentialStubbingProblem` is just eaten. Throwing the AssertionError will make this much less likely to happen.

Here is the full test case:

```
public class Principal {

    private final String principal;

    public Principal(String principal) {
        this.principal = principal;
    }

    public String principal() {
        return principal;
    }
}

public class AccessControl {

    private final Principal principal;

    public AccessControl(Principal principal) {
        this.principal = principal;
    }

    public boolean allowAccess() {
        return isTrustedPrincipal(principal);
    }

    boolean isTrustedPrincipal(Principal principal) {
        return isTrustedPrincipal(principal.principal());
    }

    boolean isTrustedPrincipal(String principal) {
        return true;
    }

}

public class StrictnessTest {

    @Rule
    public MockitoRule rule = MockitoJUnit.rule().strictness(Strictness.STRICT_STUBS);

    @Test
    public void test() {
        Principal principal = new Principal("user");
        AccessControl accessControl = spy(new AccessControl(principal));
        doReturn(false).when(accessControl).isTrustedPrincipal(anyString());
        accessControl.allowAccess();
    }

}
```

**Comment by afillatre** [comment]
I'm having a similar problem, spending a lot of time debuging to find out what went wrong, because the only hint I have is `org.mockito.exceptions.misusing.PotentialStubbingProblem` (without the stack explaining where it happened).

Throwing an `Error` rather than an `Exception` seems to be the good way.
