### ISSUE TITLE
MockitoException: Could not modify all classes [interface java.util.concurrent.Future, class org.apache.kafka.common.KafkaFuture, class java.lang.Object]

### ISSUE THREAD

**Issue by barryzhounb** [mockito/mockito#2278]
> Hey,
> 
> First thanks for reporting, in order to help us to classify issue can you make sure the following check boxes are checked ?
> 
> If this is about mockito usage, the better way is to reach out to
> 
>  - stackoverflow : https://stackoverflow.com/questions/tagged/mockito
>  - the mailing-list  : https://groups.google.com/forum/#!forum/mockito / mockito@googlegroups.com
>    (Note mailing-list is moderated to avoid spam)
>
> _This block can be removed_
> _Something wrong in the template fix it here `.github/ISSUE_TEMPLATE.md`

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ x] Provide versions (mockito / jdk / os / any other relevant information)
 - 
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/release/3.x/.github/CONTRIBUTING.md)

Linux
Java 8
mockito:   'org.mockito:mockito-core:3.9.0'  and   'org.mockito:mockito-inline:3.9.0',

Error info:
```
com.ibm.si.dlc.common.cp4s.KafkaProcessorTest > Unit test init() method given Kafka unavailable or Topic not exist in Kafka cluster FAILED
    org.mockito.exceptions.base.MockitoException: 
    Mockito cannot mock this class: class org.apache.kafka.common.KafkaFuture.
    If you're not sure why you're getting this error, please report to the mailing list.
    Early IBM virtual machine are known to have issues with Mockito, please upgrade to an up-to-date version.
    Java               : 1.8
    JVM vendor name    : IBM Corporation
    JVM vendor version : 2.9
    JVM name           : IBM J9 VM
    JVM version        : 8.0.5.27 - pxa6480sr5fp27-20190104_01(SR5 FP27)
    JVM info           : JRE 1.8.0 Linux amd64-64-Bit Compressed References 20181219_405297 (JIT enabled, AOT enabled)
    OpenJ9   - 3f2d574
    OMR      - 109ba5b
    IBM      - e2996d1
    OS name            : Linux
    OS version         : 3.10.0-1160.15.2.el7.x86_64
    You are seeing this disclaimer because Mockito is configured to create inlined mocks.
    You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.
    Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.util.concurrent.Future, class org.apache.kafka.common.KafkaFuture, class java.lang.Object]
        at com.ibm.si.dlc.common.cp4s.KafkaProcessorTest.init_KafkaUnavailableOrTopicNotExistInKafkaCluster_ThrowException(KafkaProcessorTest.java:52)
        Caused by:
        org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface java.util.concurrent.Future, class org.apache.kafka.common.KafkaFuture, class java.lang.Object]
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
            at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
            at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
            ... 1 more
            Caused by:
            java.lang.instrument.UnmodifiableClassException
                at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
                at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:163)
                at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:276)
                at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:213)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:51)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:48)
                at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
                at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
                at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
                at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
                at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:41)
                at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:379)
                at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.doCreateMock(InlineByteBuddyMockMaker.java:339)
                at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:318)
                at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
                at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
                at org.mockito.Mockito.mock(Mockito.java:1951)
                at org.mockito.Mockito.mock(Mockito.java:1862)
                ... 1 more
```

**Comment by suzaku** [comment]
Same problem here.

**Comment by bmarwell** [comment]
I think this is a problem with IBM runtimes, I opened an IBM case for this. IBM Semeru is also affected.

**Comment by paulcheeseman** [comment]
OpenJ9 issue:

https://github.com/eclipse-openj9/openj9/issues/17454
