### ISSUE TITLE
MockedConstruction not autoclosed

### ISSUE THREAD

**Issue by snv** [mockito/mockito#2281]
Hi,
i am using jUnit5 5.7.1 and Mockito 3.9.0, still on Java 8, starting the tests from IntelliJ IDEA 2020.3.4

I have two testclasses (marked with  `@ExtendWith({MockitoExtension.class})`), which each have a test-method, which mocks the construction of MOCKED_CLASS via `@Mock` as parameter.

The second test fails though, with 

> org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [org.mockito.MockedConstruction<MOCKED_CLASS> arg1] in method [public void SECONDLY_INVOCED_TEST_METHOD(org.mockito.MockedConstruction<MOCKED_CLASS>) throws java.lang.Exception]: 
For MOCKED_CLASS, static mocking is already registered in the current thread
>
>To create a new mock, the existing static mock registration must be deregistered
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:239)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:144)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:96)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
> 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
> 	at java.util.ArrayList.forEach(ArrayList.java:1257)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
> 	at java.util.ArrayList.forEach(ArrayList.java:1257)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
> 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
> 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
> 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
> 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
> 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
> 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
> 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
> 	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
> 	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
> 	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
> 	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
> Caused by: org.mockito.exceptions.base.MockitoException: 
> For com.oda.core.domain.production.customerImport.returns.ImportReturnsTransmissionFile, static mocking is already registered in the current thread
> 
> To create a new mock, the existing static mock registration must be deregistered
> 	at org.mockito.junit.jupiter.MockitoExtension.resolveParameter(MockitoExtension.java:198)
> 	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:216)
> 	... 50 more
> 
> 

I can prevent that from happening, if i add a call to [`ScopedMock#closeOnDemand`](https://www.javadoc.io/static/org.mockito/mockito-core/3.9.0/org/mockito/ScopedMock.html#closeOnDemand--) on the injected `MockedConstruction<MOCKED_CLASS>` at the end of the first invoced test method.
So my conclusion is that the mocked construction was not auto-closed at the end of the method's scope, which is what i expected `@Mock` in combination with `@ExtendWith({MockitoExtension.class})` to do.

Otherwise `@Mock` would be unusable for this, and i would have to use the try-with-ressouces syntax, to make sure the `MockedConstruction` actually gets released, even if the test fails.

**Comment by wisecodecraft** [comment]
Is this still an open issue? Potentially interested in helping out here.

**Comment by TimvdLippe** [comment]
@wisecodecraft Yes feel free to send us a PR with a fix 😄

**Comment by snv** [comment]
Thanks for looking into this.

I just checked and this still happens with updated Version:
Java 11
jUnit 5.7.2
mockito 3.11.1

Related to that (but maybe separate), would be the missing ability to configure the injected MockedConstruction:
- With an injected MockedStatic i can just configure mock-Responses with the usual when(...)-Syntax.
- With a self-made MockedConstruction i can supply a configuration at creation with a [MockInitializer](https://javadoc.io/static/org.mockito/mockito-core/3.11.1/org/mockito/Mockito.html#mockConstruction-java.lang.Class-org.mockito.MockedConstruction.MockInitializer-)
- To be able to actually configure an injected MockedConstruction, it would need an accessor to assign it a MockInitializer to use on newly created Mocks.

**Comment by temp-droid** [comment]
Hi @snv ,

From the javadoc it seems clear Mockito expects you to handle it:
```javadoc
org.mockito.Mockito @Incubating 
public static <T> org.mockito.MockedConstruction<T> mockConstruction(Class<T> classToMock)

Creates a thread-local mock controller for all constructions of the given class. 
The returned object's MockedConstruction.close() method must be called upon completing the test 
or the mock will remain active on the current thread.  
```

I'm not sure to have fully grabbed your way of using it (particularly your `@Mock` usage), but could `@AfterEach` or a similar annotation help you?

```java
    private MockedConstruction<ClassToMock> mockConstruction;

    @BeforeEach
    public void setUp() {
        mockConstruction = Mockito.mockConstruction(ClassToMock.class);
    }

    @AfterEach
    public void tearDown() {
        mockConstruction.close();
    }
```

**Comment by snv** [comment]
Hi,

i hoped to use it the same way as a MockedStatic instance, letting the test-environment inject me what i need.

Somewhat like that:
```java
@Test
public void testing_for_something(@Mock MockedConstruction<WhatEver> whatEverConstruction){
  // arrange
  //add configuration to whatEverConstruction

  // act
  //call something that instantiates whatEver

  // assert
  //stuff
}
```

When using this pattern with MockedStatic it does work, but sadly not with MockedConstruction, which has to be used in a try-with-ressources block. 
Since i often do not even use the MockedConstruction-instance (_not_ the mocked instances created by the mockedConstruction-instance), this leads to code-inspection warnings, and is just very boilerplaty-verbose and even prevents me from separating the arrange- and act-parts inside the test-code.
This sabotages readability a lot:

```java
@Test
public void testing_for_something(){
  // arrange  
  //configure other stuff
  try (MockedConstruction ignored = mockConstruction(
    whatEver.class,
    (mock, ctx) -> {
       //add configuration to mock
    }
  ) {
    // act
    //call something that instantiates WhatEver
 }  

  // assert
  //stuff
}
```

Since https://javadoc.io/static/org.mockito/mockito-core/3.12.4/org/mockito/MockitoAnnotations.html#openMocks-java.lang.Object- returns AutoCloseable i kinda assumed that the instances get closed after each test.

I know this is marked as an incubating feature, so i hope this is useful feedback.

**Comment by snv** [comment]
Thanks
