### ISSUE TITLE
Null Pointer when invoking Whitebox.invokeMethod() with null one of the params null 

### ISSUE THREAD

**Issue by DarshanBangre** [mockito/mockito#230]
Getting below exceptions when trying to invoke Whitebox.invokeMethod(erxProviderManager, "setCommand", Provider, null,retait, mail);

Version used 1.6.2

FAILED: testSetEnrollmentCommandWithUnEnrollmentWithNull
java.lang.NullPointerException
	at java.lang.Class.isAssignableFrom(Native Method)
	at org.powermock.reflect.internal.WhiteboxImpl.checkIfParameterTypesAreSame(WhiteboxImpl.java:2257)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1800)
	at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:955)
	at org.powermock.reflect.internal.WhiteboxImpl.findMethodOrThrowException(WhiteboxImpl.java:832)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:770)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)

**Comment by bric3** [comment]
It's powermock API ;)

Also the code you're mentioning use an **internal** API which is not thought for use outside the library.
