### ISSUE TITLE
Mockito 3.11.2 seems to fail in Android instrumentation tests

### ISSUE THREAD

**Issue by Wasky** [mockito/mockito#2355]
After updating Mockito from 3.11.1 to 3.11.2, Android instrumentation tests started to fail with the following exception:

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:250)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:232)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:83)
	at org.mockito.Mockito.mock(Mockito.java:1954)
	at org.mockito.Mockito.mock(Mockito.java:1865)
	at pl.waskysoft.waskytest.ExampleInstrumentedTest.useAppContext(ExampleInstrumentedTest.kt:25)
	... 27 trimmed
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@848f49f
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:65)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:26)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:20)
	at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:36)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:28)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:52)
	... 42 more
Caused by: java.lang.ExceptionInInitializerError
	at net.bytebuddy.utility.dispatcher.JavaDispatcher.of(JavaDispatcher.java:104)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8282)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.of(TypeDescription.java:8355)
	at net.bytebuddy.implementation.bind.annotation.Super$Binder.<clinit>(Super.java:222)
	at net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$ParameterBinder.<clinit>(TargetMethodAnnotationDrivenBinder.java:166)
	at net.bytebuddy.implementation.MethodDelegation.withDefaultConfiguration(MethodDelegation.java:601)
	at net.bytebuddy.implementation.MethodDelegation.to(MethodDelegation.java:271)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:64)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:74)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:37)
	at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.<init>(AndroidByteBuddyMockMaker.java:22)
	... 45 more
Caused by: java.lang.IllegalStateException: Failed to create invoker for net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1270)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$CreationAction.run(JavaDispatcher.java:431)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$CreationAction.run(JavaDispatcher.java:420)
	at java.security.AccessController.doPrivileged(AccessController.java:43)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:65)
	... 56 more
Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
	at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1266)
	... 60 more
```

**Comment by raphw** [comment]
Try explicitly setting Byte Buddy 1.11.6, this should resolve the issue. Newer Mockito releases will automatically resolve the issue.

**Comment by Wasky** [comment]
Your solution solved the problem. Thanks!
