### ISSUE TITLE
"Could not initialize plugin: interface org.mockito.plugins.MockMaker" on Android instrumented tests

### ISSUE THREAD

**Issue by francescocervone** [mockito/mockito#2370]
This issue has been introduced in `3.11.2`, it doesn't occur on `3.11.1`.

Mockito fails mocking any class.

This code:
```kotlin
class MyClassTest {
  open class MyClass
  private val myClass: MyClass = Mockito.mock(MyClass::class.java)
}
```

Causes the following exception:

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
        at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy3.isTypeMockable(Unknown Source)
        at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
        at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
        at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:250)
        at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:232)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:83)
        at org.mockito.Mockito.mock(Mockito.java:1954)
        at com.example.MyClassTest.<init>(MyClassTest.kt:211)
        ... 32 trimmed
     Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@555399f
        at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:57)
        at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:65)
        at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
        at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:26)
        at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:20)
        at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:36)
        at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:28)
        ... 40 more
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:52)
        ... 46 more
     Caused by: java.lang.ExceptionInInitializerError
        at net.bytebuddy.utility.dispatcher.JavaDispatcher.of(JavaDispatcher.java:104)
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8282)
        at net.bytebuddy.description.type.TypeDescription$ForLoadedType.of(TypeDescription.java:8355)
        at net.bytebuddy.implementation.bind.annotation.Super$Binder.<clinit>(Super.java:222)
        at net.bytebuddy.implementation.bind.annotation.TargetMethodAnnotationDrivenBinder$ParameterBinder.<clinit>(TargetMethodAnnotationDrivenBinder.java:166)
        at net.bytebuddy.implementation.MethodDelegation.withDefaultConfiguration(MethodDelegation.java:601)
        at net.bytebuddy.implementation.MethodDelegation.to(MethodDelegation.java:271)
        at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:64)
        at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.<init>(SubclassBytecodeGenerator.java:74)
        at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.<init>(SubclassByteBuddyMockMaker.java:37)
        at org.mockito.android.internal.creation.AndroidByteBuddyMockMaker.<init>(AndroidByteBuddyMockMaker.java:22)
        ... 49 more
     Caused by: java.lang.IllegalStateException: Failed to create invoker for net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1270)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$CreationAction.run(JavaDispatcher.java:431)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$Invoker$CreationAction.run(JavaDispatcher.java:420)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher.<clinit>(JavaDispatcher.java:65)
        ... 60 more
     Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
        at java.lang.ClassLoader.defineClass(ClassLoader.java:591)
        at net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader.invoker(JavaDispatcher.java:1266)
        ... 64 more

```

**Comment by wonTonx** [comment]
I'v got the same issue while try to use the latest version

**Comment by victormpineda** [comment]
Same problem here with version `3.11.2`, working fine with `3.11.1`

**Comment by snijsure** [comment]
Actually I ran into same issue --

This issue for me surfaced when I converted one of java to to kotlin !!

I tried running things with version 3.11.1 which leads to issue 
```
    This should not happen unless you are using a third-party mock maker
```

So I tried going back to version 3.10.0 and that didn't work either. Now objects that Mockito is creating are not really mocks and it ends up calling actually methods on mocked object!!!

**Comment by francescocervone** [comment]
After a year we tried to upgrad Mockito from 3.11.1 to 4.7 and everything works as expected. 
This issue can be closed, it doesn't occur anymore.
