### ISSUE TITLE
Incorrect "has following stubbing(s) with different arguments" message when using Argument Matchers

### ISSUE THREAD

**Issue by vcvitaly** [mockito/mockito#2468]
Hello,
I have a following error when running one of my tests:
```
org.mockito.exceptions.misusing.PotentialStubbingProblem: 
Strict stubbing argument mismatch. Please check:
 - this invocation of 'prepareCommonCostsLinesForCommonCosts' method:
    contractLinePreparationHelperServiceMock.prepareCommonCostsLinesForCommonCosts(
    8L,
    com.zpot.contract.core.dto.contract.line.LinePreparationCharacteristicsBO@57b9e423,
    [com.zpot.contract.core.dto.contract.line.LinePreparationBaseInfoBO@304a3655]
);
    -> at com.zpot.contract.core.service.contract.impl.ReadyContractService.prepareCommonCostsLineBOs(ReadyContractService.java:953)
 - has following stubbing(s) with different arguments:
    1. contractLinePreparationHelperServiceMock.prepareCommonCostsLinesForCommonCosts(
    0L,
    null,
    null
);
      -> at com.zpot.contract.core.service.contract.impl.ReadyContractServiceTest.createContractSuccessWithSignedByBothPartiesStatusTest(ReadyContractServiceTest.java:470)
```

I use argument matches so that what my code at line 470 looks like:
```
when(contractLinePreparationHelperServiceMock.prepareCommonCostsLinesForCommonCosts(eq(CONTRACT_ID),
                argThat(charBO -> charBO.getTenantVatType() == StandardVatType.COMPLIANT),
                argThat((List<LinePreparationBaseInfoBO<CommonCostsBO>> lineBaseInfos) -> lineBaseInfos.size() == 1 &&
                        lineBaseInfos.get(0).getCalculationType() == RentCalculationType.FIXED &&
                        BigDecimalUtils.is(lineBaseInfos.get(0).getYearlyBasePrice()).eq(BigDecimal.ONE) &&
                        lineBaseInfos.get(0).getQuantity().equals(INCLUSIVE_AREA))))
                .thenReturn(singletonList(commonCostsLineBO));
```

Clearly there is nothing like 0L, null, null in stubbing, it's just Mockito cannot properly recognise matchers and prints nulls instead, it distracted me for a while to understand where this 0L comes from until I started suspecting that some matcher might not work.

Do you think that can be classified as an issue?

**Comment by temp-droid** [comment]
Hi @vcvitaly! I'm wondering if `0L, null, null` couldn't be correct. Not affirming anything.

I suspect the `0L` comes from the `eq` method:
```java
    public static long eq(long value) {
        reportMatcher(new Equals(value));
        return 0;
    }
```
https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/ArgumentMatchers.java#L610

In the same spirit the 2 `null` that you get could make sense because that's what `argThat` returns:
```java
    public static <T> T argThat(ArgumentMatcher<T> matcher) {
        reportMatcher(matcher);
        return null;
    }
```
https://github.com/mockito/mockito/blob/main/src/main/java/org/mockito/ArgumentMatchers.java#L858

Can you try with an easier example, using `any()` everywhere to start with, and make it more complex / matching your needs until it breaks?

**Comment by vcvitaly** [comment]
Thanks, @temp-droid , I have already found the issue, one of the match clauses didn't work anymore, I  just substituted a new correct value into the matcher and everything worked.

I only posted this because I thought that it's misleading that  Mockito prints 0L, null, null as arguments of the stubbed method instead of printing the real values passed to the stubbed method, from what you posted
```
 public static long eq(long value) {
        reportMatcher(new Equals(value));
        return 0;
    }
```
I now see why.
My question was whether it's possible to print a real long value instead of 0 and print something like "<some_argument_matcher>" instead of nulls.

**Comment by temp-droid** [comment]
Not sure what you mean with `a real long value`. Zero is a real long value. 

Also, your return type needs to match your method signature. I don't see how returning a `<some_argument_matcher>` would be compatible with your method. You need to return the type of object that your function is waiting for.

**Comment by ts14ic** [comment]
> Not sure what you mean with a real long value. Zero is a real long value.

Assuming, that `CONTRACT_ID` is `8L`, for example (as seen in the error), and assuming that the contract id passed into the method was correct,

The "real" value that we expect here be `8L`.
Aka, the expected message should be:
```
 - has following stubbing(s) with different arguments:
    1. contractLinePreparationHelperServiceMock.prepareCommonCostsLinesForCommonCosts(
    8L,
    ... some lambda reference,
    ... some lambda reference
);
```

I'm pretty sure that this WAS the behavior earlier, because I remember why using `argThat` with lambdas was not helpful - it was always reporting some anonymous inner object reference for the lambda passed. 
It was solved previously with providing a proper `ArgumentMatcher` implementation with an overriden `toString` method,

The documentation STILL says that overriding `toString` is the way to achieve that.

But right now any use of matchers always reports default values for all argument positions

**Comment by ts14ic** [comment]
OKay, managed to reproduce it minimally:
I noticed that this potential stubbing problem requires use of different source files
So:
DemoTest.java
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class DemoTest {
    @Mock Dependency dependency;

    @Test
    void test() {
        var sut = new Sut();
        sut.dependency = dependency;

        when(dependency.getSomething(eq(10))).thenReturn("ten");

        sut.doSomething();
    }
}
```
Sut.java
```java
public class Sut {
    public Dependency dependency;

    void doSomething() {
        dependency.getSomething(null);
    }

    public interface Dependency {
        String getSomething(Integer i);
    }
}
```

The error:
```
Strict stubbing argument mismatch. Please check:
 - this invocation of 'getSomething' method:
    dependency.getSomething(null);
    -> at Sut.doSomething(Sut.java:7)
 - has following stubbing(s) with different arguments:
    1. dependency.getSomething(0);
      -> at DemoTest.test(DemoTest.java:20)
```

It says here, that `getSomething(0)` was stubbed, while clearly `getSomething(10)` is expected

**Comment by ts14ic** [comment]
Based on what cursory look, there's this `DefaultStubbingLookupListener`
Which contains this method `potentialArgMismatches`, which is supposed to return `List<Stubbing>` from the name alone.
But instead, it returns `List<Invocation>`, which is collects from `Stubbing.getInvocation()`

`Stubbing`'s `toString` has the right data to be reported.
`Stubbing.getInvocation()`'s `toString` - is what we see currently, which causes `null/0/false` to be reported

**Comment by patkovskyi** [comment]
I stumbled on the same problem and it took me almost an hour to realize that `argThat` was not matching. 
The error message with values like `0, 0, null` is very confusing and made me think that you can't use `eq` and `argThat` in the same stubbing.

**Comment by eheinlein-verta** [comment]
Chiming in to agree - I got the error message
```java
    -> at myClass(MyClass.java:107)
 - has following stubbing(s) with different arguments:
    1. userDao.hydrateUsersFromIds(
      null,
      null,
      null
);
```
In fact, all of the arguments were not null - only one was incorrectly null. But the error message shows them all as null, which led me down the wrong path for a while. It would be helpful if the error message either includes the actual arguments, or doesn't try to list them at all.

**Comment by vdavidp** [comment]
This still happens in version 4.12 :( . Any plans to improve error messaging?

**Comment by RAM237** [comment]
I'm on 5.3.1 and suffering from the same trying to fix more than a 💯 of such issues now

**Comment by pratikg1999** [comment]
Facing the same problem. Having nulls in the output is not intuitive at all. I wouldn't have known that the problem is my matcher not matching the actual argument and was instead thinking that somehow my matcher is null!
