### ISSUE TITLE
Mockito-inline creates instance of class, instead of a mockito proxy and does not intercept private method calls

### ISSUE THREAD

**Issue by henrykuijpers** [mockito/mockito#2488]
When creating a Mockito mock, with mockito-inline, we observed that Mockito creates an instance of the original class, instead of a Mockito proxy object. When doing this with an interface, we have seen that it does create a proxy object.

We have also seen that private method calls are not being intercepted by Mockito and therefore make calls to the original private method (which may access private fields that are always null).

In the example below, you will see that the private field "items" is null. This is because Mockito only calls the constructor and doesn't initialize the private fields.

Our dependency injection framework calls private methods on our objects, which make our unit tests fail, because they access the private fields in the class, which should not be the case in the first place, since we're mocking the class.

*Using the real implementation of a private method also seems to be an issue with the original Mockito-core, not only with Mockito-inline.*

Versions: jdk1.8.0_211, MacOS BigSur, Mockito inline version 4.1.0
Failing test case ("testMockWithPrivateFieldCalls" fails):
```
public class Testing {
    @Test
    void testOriginal() {
        final TestClass testClass = new TestClass();
        testClass.publicAdd("test-1");
        testClass.privateAdd("test-2");
        assertEquals(2, testClass.getAmountOfItems());
    }

    @Test
    void testMockWithoutPrivateMethodCalls() {
        final TestClass testClass = mock(TestClass.class);
        testClass.publicAdd("test-1");
        testClass.publicAdd("test-2");
        // The mock shouldn't interact with the original field
        assertEquals(0, testClass.getAmountOfItems());
    }

    @Test
    void testMockWithPrivateFieldCalls() {
        final TestClass testClass = mock(TestClass.class);
        assertDoesNotThrow(() -> testClass.privateAdd("test"));
        // The mock still shouldn't interact with the original field
        assertEquals(0, testClass.getAmountOfItems());
    }

    public static class TestClass {
        private final Set<String> items = new LinkedHashSet<>();

        private void privateAdd(final String item) {
            items.add(item);
        }

        public void publicAdd(final String item) {
            items.add(item);
        }

        public int getAmountOfItems() {
            return items.size();
        }
    }
}
```

**Comment by henrykuijpers** [comment]
Unit test failure:
```
Connected to the target VM, address: '127.0.0.1:55021', transport: 'socket'

org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.NullPointerException

	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3060)
	at x.Testing.testMockWithPrivateFieldCalls(Testing.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException
	at x.Testing$TestClass.privateAdd(Testing.java:42)
	at x.Testing$TestClass.access$000(Testing.java:38)
	at x.Testing.lambda$testMockWithPrivateFieldCalls$0(Testing.java:33)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 68 more

Disconnected from the target VM, address: '127.0.0.1:55021', transport: 'socket'

Process finished with exit code 255
```

**Comment by Niteshkc225** [comment]
Hi @henrykuijpers , I also see same issue!
Was this was issue resolved!

**Comment by henrykuijpers** [comment]
@Niteshkc225 the issue is not solved yet

**Comment by vtsyvina** [comment]
Same story here. The resulting "mocks" are not even mocks in this case, just a regular instance of a class. You can't setup the behavior with when for them, when you wrap with spy it has no effect. Actual methods of the class are called and causes a lot of issues.

But I don't know how to fix it and be able to mock final classes at the same time.

**Comment by henrykuijpers** [comment]
@TimvdLippe  Do you have any idea on how to approach this issue?
(Sorry for tagging you, I'm not sure who is the main developer of Mockito)

**Comment by TimvdLippe** [comment]
Since these methods are private, they should not be called from outside the class. I am not sure to what extent we do this well for inner classes, but for regular classes, I wouldn't expect private methods on mocks to work. I understand the implications of using a framework that works differently here, but my first impression is that the framework shouldn't call private methods in the first place.

That is to say: we do not define a guarantee thet private methods of mocks are callable from the outside. We have never done so and if it worked in the past, that is pure coincidence. It sucks that you now run into issues, but I think you were relying on unsupported behaviour. E.g. https://www.hyrumslaw.com/

We can keep this issue open for documentation, but personally this behaviour seems okay to me.

**Comment by henrykuijpers** [comment]
@TimvdLippe 
Let's say a class:
```
public class X {
    private void throwException() { throw new RuntimeException(); }
    public void doSomething() { throwException(); }
}
```
is used.

When doing the following:
```
final X mockX = mock(X.class);
mockX.doSomething();
```
What would be the expected outcome?
1. The program is finished and there is no exception thrown
2. The program throws an exception, because the original "doSomething"-method is called and was not specified as a mock

If the answer is 2, then, what is the use of:
```
mock(X.class, Mockito.CALLS_REAL_METHODS)
```
If that would be the default behaviour already?

Is there some kind of documentation about Mockito, that specifies that when creating a mock of a class, by default, the real methods will be called?

**Comment by henrykuijpers** [comment]
To me, it seems that all original behaviour should be removed from the class, since a proxy will be created. That includes any private methods that can be invoked by dependency injection framework or similar.

The easy solution would be to create an interface and then use the interface everywhere, so mocking an interface would never result in any implementation code behind it (though I wouldn't know what would happen with private interface methods?).

**Comment by philipwhiuk** [comment]
It's bizarre that you get a real object back. It makes it hard to determine whether it's actually been mocked or not.

**Comment by henrykuijpers** [comment]
Indeed, I think that is actually the whole problem: this should not have been a real object instance. However, maybe this is not possible without creating an instance of the real class? 

For interfaces, mockito does something else.

**Comment by philipwhiuk** [comment]
Previous versions of mockito used to create mocks of concrete classes correctly. This is a regression IMO.
