### ISSUE TITLE
Misleading error message "An unexpected error occurred while verifying a static stub" on static method verify failure

### ISSUE THREAD

**Issue by MattiL** [mockito/mockito#2576]
Misleading error message "An unexpected error occurred while verifying a static stub

To correctly verify a stub, invoke a single static method of it.Main in the provided lambda.
For example, if a method 'sample' was defined, provide a lambda or anonymous class containing the code

() -> Main.sample()
or
Main::sample
" on static method verify failure due to different expectation and actual called values.

mockito-inline 4.3.1, jdk.1.8.0_201, macOS Monterey 12.2.1

org.mockito.exceptions.base.MockitoException: 
An unexpected error occurred while verifying a static stub

To correctly verify a stub, invoke a single static method of it.Main in the provided lambda.
For example, if a method 'sample' was defined, provide a lambda or anonymous class containing the code

() -> Main.sample()
or
Main::sample

	at com.portalify.MainTest.testLogin(MainTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: Argument(s) are different! Wanted:
Main.class.do(
    1L
);
-> at com.portalify.Main.do(Main.java:11)
Actual invocations have different arguments:
Main.class.do(
    0L
);
-> at com.portalify.Main(Main.java:43)

	at it.Main.do(Main.java:11)
	at com.portalify.MainTest.lambda$testLogin$0(MainTest.java:57)
	... 29 more

**Comment by elpollouk** [comment]
I just ran into this today and was stumped as to what I was doing wrong until I found this ticket. Fixing this would be much appreciated.

**Comment by saltcreek-alberto** [comment]
@MattiL Thank you!!

**Comment by garretwilson** [comment]
Any news on this? I just ran into it, and since I was trying to set up static mocking for the first time (at least recently), I at first thought Mockito was telling me I was doing it wrong.

**Comment by kpatel-harmonicinc** [comment]
I ran into this issue as well

**Comment by sivankri** [comment]
I ran into this issue as well
