### ISSUE TITLE
spy(ForkJoinPool.commonPool()) fails.

### ISSUE THREAD

**Issue by uweschaefer** [mockito/mockito#2584]
Hi

not sure if this is a no-no anyway, so feel free to just close the issue. However, since i ran across this it might be helpful to have it documented.

When using inline mock-maker, trying to spy on `ForkJoinPool.commonPool()` seems to fail badly:

`private final ExecutorService execServiceSpy = spy(ForkJoinPool.commonPool());`

gives us:

```
Caused by: org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class java.util.concurrent.ForkJoinPool.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : Amazon.com Inc.
JVM vendor version : 11.0.14.1+10-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.14.1+10-LTS
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.13.0-30-generic


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class java.util.concurrent.ForkJoinPool, interface java.util.concurrent.ExecutorService, interface java.util.concurrent.Executor, class java.util.concurrent.AbstractExecutorService]
	at xyz.FooTest.<init>(...)
	... 27 more
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class java.util.concurrent.ForkJoinPool, interface java.util.concurrent.ExecutorService, interface java.util.concurrent.Executor, class java.util.concurrent.AbstractExecutorService]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	... 28 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:120)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:97)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$1.call(TypeCachingBytecodeGenerator.java:34)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:32)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMockType(InlineByteBuddyMockMaker.java:200)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:181)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:65)
	at org.mockito.Mockito.spy(Mockito.java:1904)
	... 28 more
Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7
	at net.bytebuddy.jar.asm.ClassVisitor.visitNestMember(ClassVisitor.java:236)
	at net.bytebuddy.jar.asm.ClassVisitor.visitNestMember(ClassVisitor.java:239)
	at net.bytebuddy.jar.asm.ClassVisitor.visitNestMember(ClassVisitor.java:239)
	at net.bytebuddy.jar.asm.ClassVisitor.visitNestMember(ClassVisitor.java:239)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining$WithFullProcessing$RedefinitionClassVisitor.onVisitNestMember(TypeWriter.java:4525)
	at net.bytebuddy.utility.visitor.MetadataAwareClassVisitor.visitNestMember(MetadataAwareClassVisitor.java:190)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:651)
	at net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:391)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3393)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:116)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3394)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:181)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:117)
	... 41 more


```

**Workaround**

For us, working around this is as easy as using a regular ThreadPool to spy on instead.

**Comment by uweschaefer** [comment]
Thanks for helping out @TimvdLippe 

Sorry, i should of course have mentioned to mockito version used in the first place, which was '_a bit outdated_' with version 2.11.0. :blush: 
I just upgraded to **3.12.4**, and **4.3.1**, which both work as expected.

Thanks again and keep up the excellent work!
