### ISSUE TITLE
Mocking with explicit constructor fails with varargs parameter

### ISSUE THREAD

**Issue by jeff303** [mockito/mockito#2601]
Consider the following test

```
import org.junit.Test;
import org.mockito.Mockito;

public class MockitoTest {

    private static class A {
        A(String a, int b, AutoCloseable... c) {
            System.out.println("Constructor called");
        }
    }

    @Test
    public void testIssue() {

        AutoCloseable c = () -> {
            System.out.println("Closing");
        };
        A a = Mockito.mock(A.class, Mockito.withSettings().useConstructor("hi", 1, new AutoCloseable[] {c}));

    }
}
```

On Temurin JDK 11, OS X, `mockito-core` 4.4.0, this fails with:

```
Unable to create mock instance of type 'A'
org.mockito.exceptions.base.MockitoException: Unable to create mock instance of type 'A'
	at MockitoTest.testIssue(MockitoTest.java:20)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.14/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.mockito.creation.instance.InstantiationException: 
Unable to create instance of 'A'.
Please ensure the target class has a constructor that matches these argument types: [java.lang.String, java.lang.Integer, [Ljava.lang.AutoCloseable;] and executes cleanly.
	... 44 more
Caused by: java.lang.reflect.InvocationTargetException
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:198)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:161)
	at org.mockito.internal.util.reflection.ModuleMemberAccessor.newInstance(ModuleMemberAccessor.java:42)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.invokeConstructor(ConstructorInstantiator.java:70)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.withParams(ConstructorInstantiator.java:53)
	at org.mockito.internal.creation.instance.ConstructorInstantiator.newInstance(ConstructorInstantiator.java:39)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:358)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:328)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:96)
	at org.mockito.Mockito.mock(Mockito.java:1965)
	... 44 more
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.AutoCloseable; to java.lang.AutoCloseable
	at java.base/java.lang.Class.cast(Class.java:3605)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at java.base/java.lang.invoke.MethodHandleImpl$AsVarargsCollector.invokeWithArguments(MethodHandleImpl.java:578)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$2DHh04hv.invokeWithArguments(Unknown Source)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.lambda$newInstance$0(InstrumentationMemberAccessor.java:191)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.newInstance(InstrumentationMemberAccessor.java:188)
	... 55 more
```

Changing the constructor param `c` to be `AutoCloseable[]` makes it work.  Is it possible to invoke the constructor with varargs in this case?

**Comment by TimvdLippe** [comment]
I think the correct usage should be `Mockito.withSettings().useConstructor("hi", 1, c)`, would that work? In case you want to specify multiple, it would become `Mockito.withSettings().useConstructor("hi", 1, c1, c2)`.

**Comment by jeff303** [comment]
> I think the correct usage should be `Mockito.withSettings().useConstructor("hi", 1, c)`, would that work? In case you want to specify multiple, it would become `Mockito.withSettings().useConstructor("hi", 1, c1, c2)`.

This: `Mockito.mock(A.class, Mockito.withSettings().useConstructor("hi", 1, c))`

fails with:

    Caused by: org.mockito.creation.instance.InstantiationException: 
    Unable to create instance of 'A'.
    Please ensure that the target class has a constructor that matches these argument types: [java.lang.String, java.lang.Integer, org.apache.kafka.connect.MockitoTest$$Lambda$47/0x0000000800154840].
    	... 44 more

**Comment by big-andy-coates** [comment]
FYI @TimvdLippe, the test case in the description of this issue runs just find on the latest code (4.9.0)

**Comment by TimvdLippe** [comment]
Thanks for confirming!

**Comment by yashmayya** [comment]
This issue occurs even with Mockito `4.11.0` (the latest `4.x` version currently). I tried reproducing it with JDK 8, 11, 17 - the issue occurs on JDK 11 and JDK 17 but not on JDK 8. @TimvdLippe can this be re-opened?

**Comment by TimvdLippe** [comment]
@yashmayya Can you please open a PR to Mockito with the regression test so that we can confirm it still breaks and work towards fixing it?

**Comment by big-andy-coates** [comment]
Happy to take a look if we can merge in the test.

**Comment by yashmayya** [comment]
Is there a better way to configure the member accessor plugin? The draft PR I pushed out to demonstrate the bug will cause every test to use `member-accessor-module` which is probably not what we want.

**Comment by yashmayya** [comment]
Thanks Tim, that makes sense. I've removed that file.

**Comment by TimvdLippe** [comment]
Closing this per https://github.com/mockito/mockito/pull/3081#issuecomment-1672780170
