### ISSUE TITLE
Mockito verify() doesn't work anymore after upgrading from Spring Boot 2.5.12 to 2.6.7

### ISSUE THREAD

**Issue by du-it** [mockito/mockito#2638]
I recently upgraded Spring Boot from version 2.5.12 to version 2.6.7. This implies an upgrade of Mockito from version 3.9 to 4.0. This seems to cause problems because a test running well with Spring Boot 2.5.12 (Mockito 3.9) now fails:

```
@Mock
private JournalAppender<X> journalAppender;

@Test
void testReceiveMessage() {
    when(journalAppender
        .append(any(X.class), any(JournalEntryTemplate.class), any(), any()))
        .thenAnswer(invocation -> CwResult.ok(invocation.getArgument(0)));
    when(notificationParser.parseNotificationToObject(anyString()))
        .thenReturn(Result.ok(new IncomingObject("/test.xml", "test.xml", UUID.randomUUID().toString())));
    when(inboundWorkflow.handleDocument(any(X.class)))
        .thenAnswer(invocation -> CwResult.ok(invocation.getArgument(0)));
    when(fileService.deleteInboundFile(any(X.class)))
        .thenAnswer(invocation -> CwResult.ok(invocation.getArgument(0)));

    assertDoesNotThrow(() -> listener.receiveMessage("test"));
    verify(journalAppender, atLeast(1))
        .append(any(X.class), any(JournalEntryTemplate.class), isNull(), anyString());
}
```

...now results in...
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.826 s - in de.d.a.c.r.o.MyApplicationTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MyListenerTest.testReceiveMessage:75 
Wanted but not invoked:
journalAppender.append(
    <any de.d.a.c.w.c.o.r.X>,
    <any de.d.a.c.a.j.JournalEntryTemplate>,
    isNull(),
    <any string>
);
-> at de.d.a.c.a.j.JournalAppender.append(JournalAppender.java:34)

However, there were exactly 5 interactions with this mock:
journalAppender.append(
    X(super=OutboundDocumentContext(s...),
    JournalEntryTemplate.MESSAGE_PROCESS_START(zzz);
-> at de.d.a.c.c.BaseListener.audit(MyListener.java:207)
```
I am using Java 11 with junit jupiter 5.7.2 on MacBook Pro with macOS Monterey v12.3.1.

It was running perfectly with Mockito 3.9 which comes with Spring Boot 2.5.12.
How can I make my Mockito test run again?

**Comment by TimvdLippe** [comment]
We need a small reproduction case that we can debug to help you further. Also, keep in mind that Mockito 4.0 only removed some deprecated APIs. You were probably using `org.mockito.Matchers` and were still relying on the deprecated behaviour.

**Comment by TimvdLippe** [comment]
Closing per the above comment.
