### ISSUE TITLE
Mock WebClient object with Answers.RETURNS_DEEP_STUBS cannot stub .header() & .headers()

### ISSUE THREAD

**Issue by doljae** [mockito/mockito#2639]
## Description
When performing unit tests by mocking the WebClient of Spring Boot 2.6.7 with `@Mock(answer = Answers.RETURNS_DEEP_STUBS)`, an issue was found that the return value was null when calling the `.header() and .headers()` methods.

### Used dependencies
- spring-boot-starter-webflux:2.6.7
- mockito-core:4.0.0
- mockito-junit-jupiter:4.0.0

## Codes
```java
@Service
@RequiredArgsConstructor
public class WebClientService {

    private final WebClient webClient;
    private final WebClient.Builder webClientBuilder;

    public WebClientResponse request() {

        final ResponseEntity<WebClientResponse> response =
            webClient.get()
                     .uri("http://localhost:1234")
                     .header("a", "a") // comment out these line, it works
                     .retrieve()
                     .toEntity(WebClientResponse.class)
                     .block();

        return response.getBody();
    }
}

public record WebClientRequest() {}
public record WebClientResponse(HttpStatus httpStatus, String response) {}

@ExtendWith(MockitoExtension.class)
class WebClientServiceTest {

    @Mock(answer = Answers.RETURNS_DEEP_STUBS)
    private WebClient webClient;
    @Mock(answer = Answers.RETURNS_SELF)
    private WebClient.Builder webClientBuilder;
    @InjectMocks
    private WebClientService webClientService;

    @Test
    void test() {
        when(webClient.get()
                      .uri(anyString())
                      .header(anyString(), anyString()) // (any(), any()) also does not work
                      .retrieve()
                      .toEntity(WebClientResponse.class)
                      .block())
            .thenReturn(ResponseEntity.ok(new WebClientResponse(HttpStatus.OK,
                                                                HttpStatus.OK.getReasonPhrase())));

        final WebClientResponse response = webClientService.request();
        assertEquals(HttpStatus.OK, response.httpStatus());
    }
}
```
## Errors
```
Cannot invoke "org.springframework.web.reactive.function.client.WebClient$RequestHeadersSpec.retrieve()" because the return value of "org.springframework.web.reactive.function.client.WebClient$RequestHeadersSpec.header(String, String[])" is null
java.lang.NullPointerException: Cannot invoke "org.springframework.web.reactive.function.client.WebClient$RequestHeadersSpec.retrieve()" because the return value of "org.springframework.web.reactive.function.client.WebClient$RequestHeadersSpec.header(String, String[])" is null
	at com.example.service.WebClientServiceTest.test(WebClientServiceTest.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

## Additional info
- There is only `.header()` example in the code, but `.headers()` also has the same NPE.
- If I'm misunderstanding what `@Mock(answer = Answers.RETURNS_DEEP_STUBS)` is for, please comment.

**Comment by akutschera** [comment]
I find this interesting. It looks like because of type erasure somewhere in the stack mockito does not know what type of object it should return and therefore returns null (see [here](https://github.com/mockito/mockito/blob/4629ed801868d9fd12117359a5084784003f582c/src/main/java/org/mockito/internal/stubbing/defaultanswers/ReturnsDeepStubs.java#L71)

I can reproduce this with a smaller test
```
@ExtendWith(MockitoExtension.class)
public class SimpleTest {

    public interface TopLevel<T> {
        T getT();
        List<String> getList();
    }

    @Mock // (answer = Answers.RETURNS_DEEP_STUBS) -- fails with and without
    private TopLevel<List<String>> topLevel;

    @Test
    void test() {
        assertThat( topLevel.getList() ).isEmpty(); // works as expected
        assertThat( topLevel.getT() ).isNotNull(); // fails
    }
}
```
It seems that the information that we have a List<String> as the generic for topLevel is lost somewhere. There is the workaround of mocking each step instead of using RETURNS_DEEP_STUBS, even though I agree this leads to a test that is difficult to read/maintain.

**Comment by doljae** [comment]
@akutschera 
Thanks for the comment.
As you described, WebClient returns generics through method chaining.
But `.uri().retrieve()` does not cause NPE. On the other hand, `.uri().header().retrieve()` causes an NPE. when I checked
Both `.uri()` and .`header()` seem to return generics.

### WebClient.java
<img width="632" alt="image" src="https://user-images.githubusercontent.com/37795866/168576840-ad17048b-3a2d-4f64-9db1-811d62216c25.png">

<img width="481" alt="image" src="https://user-images.githubusercontent.com/37795866/168576811-e6d7d226-05a4-4816-9e12-6f4035aac1aa.png">


I wonder what this difference is. (Of course, the mockito implementation code you gave would answer this, but I didn't understand it.)
Could you please explain in more detail?

**Comment by doljae** [comment]
@akutschera 
In addition, do you think this is an area that can be improved technically?
If possible, I would like to revise it and send a PR.

**Comment by doljae** [comment]
@akutschera 
Thank you for kind reply. You make me catch the cause of this situation 🙂

**Comment by raphw** [comment]
The problem is, that from the inside of the mock, we do not know what `getT()` returns. We only know the erasure, where `Object` would be returned. But javac adds a check cast after each call to a generic method where a class cast exception would be thrown for any `getT` that returns something else then `Object` than what the caller would expect. Therefore, we need to return `null` in such cases. You can of course write your own `Answer` that behaves differently.
