### ISSUE TITLE
RETURN_DEEP_STUBS and toArray(T[]) stops working with versions > 1.9.5

### ISSUE THREAD

**Issue by scameronde** [mockito/mockito#268]
With version 1.9.5 the following test works without a problem:

```
  @Test
  public void toArrayTypedDoesNotWork() throws Exception {
    Container container = mock(Container.class, RETURNS_DEEP_STUBS);
    container.getInnerContainer().getTheProblem().toArray(new String[]{});
  }

  class Container {
    private InnerContainer innerContainer;

    public InnerContainer getInnerContainer() {
      return innerContainer;
    }
  }

  class InnerContainer {
    private Set<String> theProblem;

    public Set<String> getTheProblem() {
      return theProblem;
    }
  }
```

With version 1.10.0 and beyond (including 2.0.26-beta) the following exception gets thrown

```
org.mockito.exceptions.base.MockitoException: Ouch, it shouldn't happen, type 'sun.reflect.generics.reflectiveObjects.GenericArrayTypeImpl' on method : 'public abstract <T> T[] java.util.Set.toArray(T[])' is not supported : T[]
	at eu.lindenbaum.ToArrayProblemTest.toArrayTypedDoesNotWork(BookingWebServiceTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

```

Using

```
    Container container = mock(Container.class, RETURNS_MOCKS);
```
instead of
```
    Container container = mock(Container.class, RETURNS_DEEP_STUBS);
```
works.

**Comment by raphw** [comment]
I looked at the code and it seems like there is no specific handler for generic arrays. The strange thing is that there never was one.

Did you maybe run with a different Java version in the process? Before Java, non-generic arrays were also represented by generic array representations. Since after Java 6, generic arrays with a non-generic component type are properly resolved.

Nevertheless, this needs a fix in Mockito, as I understand it.

**Comment by scameronde** [comment]
The test code is executed using Oracle Java 8 (1.8.0.40-b25) on OSX.
I updated to mockito 1.9.5 to 1.10.0 in the process of updating from Java7 to Java8

**Comment by raphw** [comment]
You are right, the change came with Java 8. Fixed with my pull request.

**Comment by bric3** [comment]
@raphw Nice catch, and thanks for the patch :)
@scameronde Thanks for reporting :)

**Comment by bric3** [comment]
By the way @raphw As you may be one of the only person around mockito that can give thorough feedback on the generic support class in mockito, do you see how to improve it ?

**Comment by raphw** [comment]
Well, as I am currently dealing with generic types a lot I can only tell that it is quite complex to beginn with. But I am deep in the matter these days, I will look at the implementation some time and see if I can improve it. For now, it looks save, apart from the fact that you were missing generic type arrays.

**Comment by bric3** [comment]
Yes it was developed on java 7 and missed that.

**Comment by scameronde** [comment]
you got to love the open source community. Thank you a lot for the fast response and the fix.
