### ISSUE TITLE
Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null) after upgrading Mockito to 4.6.1

### ISSUE THREAD

**Issue by xfluo-cn** [mockito/mockito#2696]
My environment:
jdk-11.0.15.1.jdk
Gradle wrapper 7.4
Intellij core plugin version   212.5712.43 or Android Studio Chipmunk | 2021.2.1

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 I found the [similar issue ](https://github.com/mockito/mockito/issues/2625), and tried the workaround method, but it doesn't help me,
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [ ] Provide versions (mockito / jdk / os / any other relevant information)
 I tried the mockito 4.3.1, 4.5, 4.6 and 4.6.1, met the same issue with them.
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
dependencies {
    testImplementation group: 'org.mockito', name: 'mockito-core', version: mockitoVersion
    testImplementation group: 'org.mockito', name: 'mockito-inline', version: mockitoVersion
....
}

 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

Our code can compiled successfully, but it's failed to run and threw the below exceptions:
...
Can't modify, MockJDK is read-only, consider calling .clone() first
com.intellij.util.IncorrectOperationException: Can't modify, MockJDK is read-only, consider calling .clone() first
	at app//com.intellij.openapi.projectRoots.impl.MockSdk.throwReadOnly(MockSdk.java:224)
	at app//com.intellij.openapi.projectRoots.impl.MockSdk.getSdkModificator(MockSdk.java:136)
	at app//com.android.tools.idea.startup.GradleSpecificInitializer.lambda$setupSdks$0(GradleSpecificInitializer.java:285)
	at app//com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at app//com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at app//com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at app//com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at app//com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at app//com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at app//com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at app//com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at app//com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop@11.0.15.1/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop@11.0.15.1/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop@11.0.15.1/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop@11.0.15.1/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base@11.0.15.1/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.15.1/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.15.1/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at app//com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at app//com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at app//com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at app//com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at app//com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at app//com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at app//com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at app//com.intellij.testFramework.PlatformTestUtil.dispatchAllInvocationEventsInIdeEventQueue(PlatformTestUtil.java:477)
	at app//com.intellij.testFramework.LightPlatformTestCase.lambda$doSetup$4(LightPlatformTestCase.java:331)
	at app//com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:438)
	at app//com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:456)
	at app//com.intellij.testFramework.LightPlatformTestCase.doSetup(LightPlatformTestCase.java:286)
	at app//com.intellij.testFramework.LightPlatformTestCase.lambda$setUp$1(LightPlatformTestCase.java:238)
	at app//com.intellij.testFramework.EdtTestUtil.runInEdtAndWait(EdtTestUtil.java:33)
	at app//com.intellij.testFramework.LightPlatformTestCase.setUp(LightPlatformTestCase.java:233)
	at app//com.intellij.testFramework.LightPlatformCodeInsightTestCase.setUp(LightPlatformCodeInsightTestCase.java:281)
	at app//com.intellij.testFramework.LightJavaCodeInsightTestCase.setUp(LightJavaCodeInsightTestCase.java:32)
	at app//com.sap.cloud.mobile.android.assistant.test.application.tests.appgeneration.common.AuthenticationsGenerationTests.setUp(AuthenticationsGenerationTests.java:192)
	at app//com.intellij.testFramework.UsefulTestCase.invokeSetUp(UsefulTestCase.java:486)
	at app//com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:478)
	at app//com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:531)
	at app//com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
	at java.desktop@11.0.15.1/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop@11.0.15.1/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop@11.0.15.1/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop@11.0.15.1/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base@11.0.15.1/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.15.1/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop@11.0.15.1/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at app//com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop@11.0.15.1/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

com.sap.cloud.mobile.android.assistant.test.application.tests.appgeneration.java.AuthenticationsGenerationTests_Java > testNoAuthAppGeneration FAILED
    com.intellij.util.IncorrectOperationException at MockSdk.java:224

Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:88)
	at com.sun.proxy.$Proxy93.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:261)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:234)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:94)
	at org.mockito.Mockito.mock(Mockito.java:1981)
	at org.mockito.Mockito.mock(Mockito.java:1896)
	at com.sap.cloud.mobile.android.assistant.test.application.util.MockAssistantProject.mockPreparation(MockAssistantProject.java:66)
	at com.sap.cloud.mobile.android.assistant.test.application.tests.appgeneration.common.AuthenticationsGenerationTests.testNoAuthAppGeneration(AuthenticationsGenerationTests.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$11(UsefulTestCase.java:523)
	at com.intellij.testFramework.UsefulTestCase.lambda$wrapTestRunnable$13(UsefulTestCase.java:544)
	at com.intellij.testFramework.UsefulTestCase.runTestRunnable(UsefulTestCase.java:464)
	at com.intellij.testFramework.LightPlatformTestCase.runTestRunnable(LightPlatformTestCase.java:493)
	at com.intellij.testFramework.LightPlatformCodeInsightTestCase.lambda$runTestRunnable$1(LightPlatformCodeInsightTestCase.java:74)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:216)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.testFramework.LightPlatformCodeInsightTestCase.runTestRunnable(LightPlatformCodeInsightTestCase.java:72)
	at com.intellij.testFramework.UsefulTestCase.defaultRunBare(UsefulTestCase.java:480)
	at com.intellij.testFramework.UsefulTestCase.lambda$runBare$12(UsefulTestCase.java:531)
	at com.intellij.testFramework.EdtTestUtil.lambda$runInEdtAndWait$1(EdtTestUtil.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:451)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:486)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@387e70f7
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:58)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:69)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:54)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:28)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:22)
	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:77)
	at org.mockito.Mockito.<clinit>(Mockito.java:1630)
	... 50 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:53)
	... 56 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 11
JVM vendor name    : Oracle Corporation
JVM vendor version : 11.0.15.1+2-LTS-10
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 11.0.15.1+2-LTS-10
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 12.4

	at app//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:244)
	at app//org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
	... 61 more
Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:670)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:601)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<clinit>(InlineDelegateByteBuddyMockMaker.java:115)
	... 62 more

com.sap.cloud.mobile.android.assistant.test.application.tests.appgeneration.kotlin.AuthenticationsGenerationTests_Kotlin > testNoAuthAppGeneration FAILED
    java.lang.IllegalStateException at PluginLoader.java:88
        Caused by: java.lang.IllegalStateException at PluginInitializer.java:58
            Caused by: java.lang.reflect.InvocationTargetException at NativeConstructorAccessorImpl.java:-2
                Caused by: org.mockito.exceptions.base.MockitoInitializationException at InlineDelegateByteBuddyMockMaker.java:244
                    Caused by: java.lang.IllegalStateException at ByteBuddyAgent.java:670
Disconnected from the target VM, address: 'localhost:51847', transport: 'socket'
2 tests completed, 2 failed
> Task :appGenerationUnitTestPR FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':appGenerationUnitTestPR'.
> There were failing tests. See the report at: file:///Users/i063050/git/cloud-assistant-android/build/reports/tests/appGenerationUnitTestPR/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 4m 3s
18 actionable tasks: 4 executed, 14 up-to-date

...

**Comment by xfluo-cn** [comment]
[mockito4-gradle-example.zip](https://github.com/mockito/mockito/files/9015734/mockito4-gradle-example.zip)

**Comment by xfluo-cn** [comment]
Attach a simple project to reproduce this issue, it's a project for developing Intellij plugin, different from a common gradle project. I used the same configuration for a common gradle project, it can work, but failed to a intellij plugin project, after debugging, I found it's failed to load some plugin by Mockito when validate some class type which will be mocked, the error is as below:
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:88)
	at com.sun.proxy.$Proxy7.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:261)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:234)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:94)
	at org.mockito.Mockito.mock(Mockito.java:1981)
	at org.mockito.Mockito.mock(Mockito.java:1896)
	at com.sap.test.AndroidStudioUtilityTest.testGetExceptionRootCause(AndroidStudioUtilityTest.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in java.lang.CompoundEnumeration@158a8276
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:58)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:69)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:54)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:28)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:22)
	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:77)
	at org.mockito.Mockito.<clinit>(Mockito.java:1630)
	... 23 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:53)
	... 29 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 11
JVM vendor name    : JetBrains s.r.o.
JVM vendor version : 11.0.11+9-b1504.5
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.11+9-b1504.5
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 11.4

	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:244)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
	... 34 more
Caused by: java.lang.IllegalStateException: Error during attachment using: net.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@7770f470
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:608)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:581)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:533)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:510)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<clinit>(InlineDelegateByteBuddyMockMaker.java:115)
	... 35 more
Caused by: java.io.IOException: Cannot run program ""/Applications/IntelliJ IDEA CE 2021.app/Contents/jbr_jcef-11_0_11-osx-x64-b1504.5/Contents/Home/bin/java"": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:669)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:601)
	... 39 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 42 more

**Comment by topherli** [comment]
i have the same problem, i think becuse mockito-inline 4.6.1 depend on mockito-core 3.9.0, and i do not know inline mock maker is mockito inline?
and i think use 3.9.0 better,because spring boot test use 3.9.0

**Comment by xfluo-cn** [comment]
Thanks your comments and I tried it with mockito-core 4.6.1 and mockito-inline 3.9.0, met the same issue, if I set mockito-inline 4.6.1 with mockito-core 3.9.0, the version of mockito-core will be set with 4.6.1 automatically, I think this issue is related to plugin environment, it's a little different with yours.

**Comment by 1006245347** [comment]
I get the same problem....

**Comment by swumao** [comment]
I get the same problem....

**Comment by TimvdLippe** [comment]
Unfortunately, this appears to be an IntelliJ upgrade issue rather than Mockito's. I recommend following up with JetBrains to fix their implementation.

**Comment by xfluo-cn** [comment]
Yes, it's caused by IntelliJ upgrade, but Mokito doesn't consider to support the new change from JetBrains? as you know, they did a big change for their framework, but Mokito couldn't run based on the new one, whether Mokito will consider to do some upgrade to satisfy this new change?

**Comment by xfluo-cn** [comment]
@TimvdLippe It's not IntelliJ issue, I found it should be byte-buddy issue which referenced by Mokito, here is the link for this problem: https://github.com/raphw/byte-buddy/issues/732, I tried its workaround method and can make our test work, do you team have any plan to resolve it?
