### ISSUE TITLE
Mockito cannot mock this class: class android.telephony.TelephonyManager

### ISSUE THREAD

**Issue by krishnasoumya** [mockito/mockito#2710]
Mockito cannot mock this class: class android.telephony.TelephonyManager.

If you're not sure why you're getting this error, please report to the mailing list.

Java               : 11
JVM vendor name    : JetBrains s.r.o.
JVM vendor version : 11.0.12+0-b1504.28-7817840
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.12+0-b1504.28-7817840
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 12.4

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : java.lang.IllegalArgumentException: Could not create type
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class android.telephony.TelephonyManager.

If you're not sure why you're getting this error, please report to the mailing list.

Java               : 11
JVM vendor name    : JetBrains s.r.o.
JVM vendor version : 11.0.12+0-b1504.28-7817840
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.12+0-b1504.28-7817840
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 12.4

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:389)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:349)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:328)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:96)
	at org.mockito.Mockito.mock(Mockito.java:1981)
	at org.mockito.Mockito.mock(Mockito.java:1896)
	... 18 more
Caused by: java.lang.InternalError: class redefinition failed: invalid class
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:280)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:217)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 30 more

**Comment by TimvdLippe** [comment]
> Caused by: java.lang.InternalError: class redefinition failed: invalid class

Indicates that your class is corrupt. You should cleanup the class output and recompile with the JDK to fix the inconsistency.
