### ISSUE TITLE
Cannot mock Enum with abstract method in Java 17

### ISSUE THREAD

**Issue by mira-silhavy** [mockito/mockito#2716]
Hi,
recently we migrated to Java 17, but we're having some problems with Enum mocking. We are using `mockito-inline` and that helped a lot, but there are still problems with some of the Enums that have abstract methods (or implementing interface) inside them.
Can this be fixed?

Here is the example Enum class that will fail to be mocked. Enum without abstract method is mocked correctly.

Mockito version 4.6.1

```
    enum Foo {
        FOO {
            @Override
            public String Bar() {
                return "Foo";
            }
        };

        public abstract String Bar();
    }
```

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.Foo.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 17
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 17.0.4+8
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.4+8
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Unsupported settings with this type 'com.Foo'

	at com.TestFoo:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.mockito.exceptions.base.MockitoException: Unsupported settings with this type 'com.unimarket.contract.domain.ContractDocument$Foo'
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	... 34 more


Process finished with exit code -1
```

**Comment by mira-silhavy** [comment]
Test
```
package org.example;

import org.junit.Test;

import static org.mockito.Mockito.mock;

public class EnumTest {

    @Test
    public void testEnumWithAbstractMethod() {
        mock(FooAbstract.class);
        // fails
    }

    @Test
    public void testEnumImplInterface() {
        mock(FooInterface.class);
        // fails
    }
    
    @Test
    public void testEnumWithMethodOverride() {
        mock(FooOverride.class);
        // passed
    }

    enum FooAbstract {

        BAR {
            @Override
            String foo() {
                return "bar";
            }
        };

        abstract String foo();
    }

    enum FooInterface implements IFooBar {

        BAR {
            @Override
            public String foo() {
                return "fooBar";
            }
        };
    }

    enum FooOverride {

        BAR {
            @Override
            String foo() {
                return "bar";
            }
        };

        String foo() {
            return null;
        }
    }

    public interface IFooBar {

        String foo();
    }
}

**Comment by mira-silhavy** [comment]
I see why this does't fail when running mockito https://github.com/mockito/mockito/blob/main/subprojects/inline/src/test/java/org/mockitoinline/EnumMockingTest.java

Gradle plugin compiles this with, changing this to version 17 and existing test fails.
```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

**Comment by bilak** [comment]
@mira-silhavy were you able to resolve this issue somehow? I'm facing the same.

**Comment by mira-silhavy** [comment]
> @mira-silhavy were you able to resolve this issue somehow? I'm facing the same. 

No, we had to find a workaround. I think it's because of enums are sealed in Java 17.
