### ISSUE TITLE
JDK 9 compatibility regression in Mockito 2.0.21-beta

### ISSUE THREAD

**Issue by Stephan202** [mockito/mockito#272]
The following TestNG test fails when run on JDK 9 with Mockito 2.0.21-beta or later (including 2.0.31-beta), but passes with Mockito 2.0.20-beta or earlier (including 1.9.5). Tested with the latest JDK 9  early access build ([b73](https://jdk9.java.net/download/) at the time of writing), but have noticed this with earlier builds as well. (Just didn't get around to filing the ticket until now.)

	import org.mockito.Mock;
	import org.mockito.MockitoAnnotations;
	import org.testng.annotations.BeforeMethod;
	import org.testng.annotations.Test;
	
	public class DemoTest {
		@Mock
		private Object o;
	
		@BeforeMethod(groups = "unit")
		public void setUp() {
			MockitoAnnotations.initMocks(this);
		}
	
		@Test(groups = "unit")
		public void dummyTest() {
			/* NOP. */
		}
	}

Tried to make the reproduction case as small as possible. The bug isn't triggered without the group specifications. Stack trace:

    java.lang.ExceptionInInitializerError
        at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
        at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
        at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
        at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:35)
        at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
        at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
        at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
        at org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues.<init>(ReturnsEmptyValues.java:57)
        at org.mockito.internal.stubbing.defaultanswers.ReturnsMoreEmptyValues.<init>(ReturnsMoreEmptyValues.java:51)
        at org.mockito.internal.stubbing.defaultanswers.ReturnsSmartNulls.<init>(ReturnsSmartNulls.java:40)
        at org.mockito.Answers.<clinit>(Answers.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:502)
        at java.lang.Class.getEnumConstantsShared(Class.java:3338)
        at java.lang.Class.enumConstantDirectory(Class.java:3359)
        at java.lang.Enum.valueOf(Enum.java:234)
        at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:483)
        at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:347)
        at java.lang.reflect.Method.getDefaultValue(Method.java:610)
        at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
        at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
        at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
        at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
        at java.lang.reflect.Field.declaredAnnotations(Field.java:1153)
        at java.lang.reflect.Field.declaredAnnotations(Field.java:1151)
        at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1139)
        at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:207)
        at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:65)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:71)
        at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:55)
        at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
        at DemoTest.setUp(DemoTest.java:14)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:502)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
        at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:517)
        at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:601)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.NullPointerException
        at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
        at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
        ... 50 more

**Comment by raphw** [comment]
I think this is a consequence of Byte Buddy's byte code version auto discovery which was included in this beta version. Byte Buddy does not yet discover Java 9 appropriately but this is something I am currently working on. I think that I will release a version some time this weak such that Mockito becomes Java 9 ready.

**Comment by raphw** [comment]
Fixed with updating to Byte Buddy 0.6.15.
