### ISSUE TITLE
org.mockito.exceptions.misusing.UnfinishedStubbingException

### ISSUE THREAD

**Issue by Anthonysdu** [mockito/mockito#2750]
> I have the following code:
`OngoingStubbing <Integer> stubbing_int = Mockito.when(Verifier.nondetInt());`
`OngoingStubbing <Boolean> stubbing_boolean = Mockito.when(Verifier.nondetBoolean());`
`if ("int".equals(types[i]))`
`  stubbing_int = stubbing_int.thenReturn(Integer.parseInt(assumptions[i]));`
`else if ("boolean".equals(types[i]))`
 `stubbing_boolean = stubbing_boolean.thenReturn(Boolean.parseBoolean(assumptions[i]));`

Then I got the exception:

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
at test.main(test.java:17)

E.g. thenReturn() may be missing.
Examples of correct stubbing:
    when(mock.isOk()).thenReturn(true);
    when(mock.isOk()).thenThrow(exception);
    doThrow(exception).when(mock).someVoidMethod()
Hints:
 1. missing thenReturn()
 2. you are trying to stub a final method, which is not supported
 3. you are stubbing the behaviour of another mock inside before 'thenReturn' instruction is completed

	at org.sosy_lab.sv_benchmarks.Verifier.nondetBoolean(Verifier.java:21)
	at test.main(test.java:22)

Is there a good way to mock multiple classes? Thanks!

**Comment by Anthonysdu** [comment]
the mockito version is 3.4.3
