### ISSUE TITLE
Possible concurrency issue in Mockito spies

### ISSUE THREAD

**Issue by beikov** [mockito/mockito#2820]
Hey there,

I'm using Mockito 4.3.1 in the Hibernate testsuite and we are seeing some intermittent failures of a test that uses spies, but only on the s390x architecture. I didn't dig into the Mockito spies code yet, but it is fishy that this only happens on s390x and even there it doesn't happen always. See e.g. https://ci.hibernate.org/job/hibernate-orm-pipeline/job/main/1173/testReport/junit/org.hibernate.orm.test.insertordering/InsertOrderingDuplicateTest/Build___s390x_h2___Test___testBatching__/

Here are the specs:

* Architecture: s390x
* OS: IBM LinuxOne
* Mockito: 4.3.1
* JDK:
```
openjdk version "11.0.12" 2021-07-20
IBM Semeru Runtime Open Edition 11.0.12.0 (build 11.0.12+7)
Eclipse OpenJ9 VM 11.0.12.0 (build openj9-0.27.0, JRE 11 Linux s390x-64-Bit Compressed References 20210728_182 (JIT enabled, AOT enabled)
OpenJ9   - 1851b0074
OMR      - 9db1c870d
JCL      - 21849e2ca0 based on jdk-11.0.12+7)
```

The error is that a method was supposedly not invoked. But it is strange that methods from within the supposedly not called method appear in the interactions list which can't be called other than through that very method.

Any idea if there was a bug in 4.3.1 that could cause this? Possibly a concurrency issue?

This is the error message:

```
Wanted but not invoked:
jdbcPreparedStatement.executeBatch();							-> at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1252)

However, there were exactly 33 interactions with this mock:

jdbcPreparedStatement.setNull(1, 12); 							-> at org.hibernate.type.descriptor.jdbc.BasicBinder.doBindNull(BasicBinder.java:98)
jdbcPreparedStatement.isDebugEnabled();							-> at org.h2.jdbc.JdbcPreparedStatement.setNull(JdbcPreparedStatement.java:337)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1391)
jdbcPreparedStatement.setNull(2, 2);							-> at org.hibernate.type.descriptor.jdbc.BasicBinder.doBindNull(BasicBinder.java:98)
jdbcPreparedStatement.isDebugEnabled();							-> at org.h2.jdbc.JdbcPreparedStatement.setNull(JdbcPreparedStatement.java:337)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1391)
jdbcPreparedStatement.setLong(3, 1L);							-> at org.hibernate.type.descriptor.jdbc.BigIntJdbcType$1.doBind(BigIntJdbcType.java:62)
jdbcPreparedStatement.isDebugEnabled();							-> at org.h2.jdbc.JdbcPreparedStatement.setLong(JdbcPreparedStatement.java:675)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.setParameter(JdbcPreparedStatement.java:1391)
jdbcPreparedStatement.addBatch();								-> at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$addToBatch$0(BatchImpl.java:136)
jdbcPreparedStatement.debugCodeCall( "addBatch" );				-> at org.h2.jdbc.JdbcPreparedStatement.addBatch(JdbcPreparedStatement.java:1350)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.addBatch(JdbcPreparedStatement.java:1351)
jdbcPreparedStatement.debugCodeCall( "executeBatch" );			-> at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1252)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.executeBatch(JdbcPreparedStatement.java:1261)
jdbcPreparedStatement.closeOldResultSet();						-> at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:205)
jdbcPreparedStatement.setExecutingStatement(
    insert into SaleDocumentSummary (sale_number,totalPrice,id) values (?,?,?) {1: NULL, 2: NULL, 3: CAST(1 AS BIGINT)}
);																-> at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:208)
jdbcPreparedStatement.setExecutingStatement( null );			-> at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:217)
jdbcPreparedStatement.isDebugEnabled();							-> at org.h2.jdbc.JdbcStatement.getGeneratedKeys(JdbcStatement.java:888)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcStatement.getGeneratedKeys(JdbcStatement.java:891)
jdbcPreparedStatement.isClosed();								-> at org.hibernate.engine.jdbc.batch.internal.BatchImpl.clearBatch(BatchImpl.java:193)
jdbcPreparedStatement.debugCodeCall( "isClosed" );				-> at org.h2.jdbc.JdbcStatement.isClosed(JdbcStatement.java:1333)
jdbcPreparedStatement.clearBatch();								-> at org.hibernate.engine.jdbc.batch.internal.BatchImpl.clearBatch(BatchImpl.java:194)
jdbcPreparedStatement.debugCodeCall( "clearBatch" );			-> at org.h2.jdbc.JdbcPreparedStatement.clearBatch(JdbcPreparedStatement.java:1214)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcPreparedStatement.clearBatch(JdbcPreparedStatement.java:1215)
jdbcPreparedStatement.getMaxRows();								-> at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.close(ResourceRegistryStandardImpl.java:193)
jdbcPreparedStatement.debugCodeCall( "getMaxRows" );			-> at org.h2.jdbc.JdbcStatement.getMaxRows(JdbcStatement.java:459)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcStatement.getMaxRows(JdbcStatement.java:460)
jdbcPreparedStatement.getQueryTimeout();						-> at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.close(ResourceRegistryStandardImpl.java:196)
jdbcPreparedStatement.debugCodeCall( "getQueryTimeout" );		-> at org.h2.jdbc.JdbcStatement.getQueryTimeout(JdbcStatement.java:709)
jdbcPreparedStatement.checkClosed();							-> at org.h2.jdbc.JdbcStatement.getQueryTimeout(JdbcStatement.java:710)
jdbcPreparedStatement.close();									-> at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.close(ResourceRegistryStandardImpl.java:208)
jdbcPreparedStatement.debugCodeCall("close");					-> at org.h2.jdbc.JdbcStatement.close(JdbcStatement.java:342)
jdbcPreparedStatement.closeOldResultSet();						-> at org.h2.jdbc.JdbcStatement.closeInternal(JdbcStatement.java:351)
```

**Comment by big-andy-coates** [comment]
Could it be related to https://github.com/mockito/mockito/issues/2812?

If you update to the latest release, does the issue go away?

**Comment by beikov** [comment]
The fix for https://github.com/mockito/mockito/pull/2812 was not released yet. I'll try updating to 4.10.0 and see if that helps.

**Comment by big-andy-coates** [comment]
Ah, you may need to wait until 5.0 then, unless you're up for compiling from source to try out the fix?

**Comment by beikov** [comment]
So you are not backporting this bug fix to 4.x?

**Comment by beikov** [comment]
I updated to Mockito 5.0.0, but we still have the same issue.

**Comment by big-andy-coates** [comment]
@beikov  are you able to create a small example that exhibits this issue?

**Comment by beikov** [comment]
I'm sorry, but since this only seems to be reliably reproducible on the s390x architecture it would be quite the effort for me to simplify the scenario in an isolated fashion. Maybe you can run your testsuite on s390x and the error will pop up already? Also see https://www.ibm.com/community/z/open-source/virtual-machines-request/

**Comment by big-andy-coates** [comment]
@beikov, that makes sense. Can you at least share an example test that fails occasionally?  As this will provide insight into how you're creating and configuring your spies, and what your testing.

I'm assuming your test or the thing being tested  is multi-threaded?

**Comment by beikov** [comment]
The issue happens consistently for tests in this package: https://github.com/hibernate/hibernate-orm/tree/main/hibernate-core/src/test/java/org/hibernate/orm/test/insertordering

I actually don't know if it's concurrency related, it is just a wild guess since the problem only happens on s390x which is an out of order architecture AFAIK.

>Is there any static state anywhere around the test / test subject?

No.

>Is it your test, or the test subject, that is multi-threaded?

The particular tests which use Mockito are not multi-threaded, but other tests that run in between might be.
My guess was that one Mockito related test runs and sets up something, then other possibly multi-threaded tests run, and then another Mockito test runs that then observes some broken state. It could just as well be a problem with the support of Mockito on OpenJ9 though.

Do you test Mockito on OpenJ9?

**Comment by big-andy-coates** [comment]
@TimvdLippe any thoughts on this?  Any thoughts on where in the code there may be a concurrency issue? I'm happy to have a look if you can give some pointers...

**Comment by TimvdLippe** [comment]
The best way forward if you can extract a regression test for our test suite that reproduces this issue. Until then, it is difficult to make any forward progress on trying to figure out what the root cause is.

**Comment by beikov** [comment]
Hibernate is an open source project and all the necessary bits you'd need to run the testsuite are there. If this were 100% reproducible I'd love to provide you an isolated test, but that's the thing, it's not, so I'm having a hard time understanding what I can possibly do to help you further. I [started a CI run](https://github.com/hibernate/hibernate-orm/pull/6080) to check if this issue also pops up on OpenJ9 on x86, and if it does, I could possibly try to reproduce it locally with an OpenJ9 distribution to further dig into it.

>Do you test Mockito on OpenJ9?

My question still stands. Maybe you can add a matrix entry for OpenJ9 to your testsuite and the issue will pop up already?

**Comment by big-andy-coates** [comment]
Looks like above [PR](https://github.com/hibernate/hibernate-orm/pull/6080) didn't fail on anything `spy` related.

**Comment by big-andy-coates** [comment]
@beikov 

> The issue happens consistently for tests in this package: https://github.com/hibernate/hibernate-orm/tree/main/hibernate-core/src/test/java/org/hibernate/orm/test/insertordering

I've had a quick look at this package and then [only reference to `spy` that I can see](https://github.com/hibernate/hibernate-orm/search?q=insertordering+%26+spy) is to `PreparedStatementSpyConnectionProvider`.  At the top of `PreparedStatementSpyConnectionProvider` is static state. Notably static `MockSettings` instances: 

https://github.com/hibernate/hibernate-orm/blob/2dbf38ef7b141e2f06ec9bff43c4b974611d640a/hibernate-testing/src/main/java/org/hibernate/testing/orm/jdbc/PreparedStatementSpyConnectionProvider.java#L39-L46

`MockSettings` instances are _not_ thread safe.  Methods such as `spiedInstance` mutate the internal state of the settings instance without any synchronisation.

If you're running into concurrency issues, then it must either be the case that the test code is multi-threaded, or the code under test is.  Otherwise a concurrency issue just can't occur.

Without a reproducible test case, I can't say for certain, but it seems highly possible that it may be your own test code that is introducing the multi-threading issue.  

I would suggest changing `PreparedStatementSpyConnectionProvider` to create `MockSettings` as needed, (I don't believe they are expensive to create), and also searching the test code for other similar static state and miss-use of Mockito types.

Hope this helps...

**Comment by big-andy-coates** [comment]
Confused... that change looks nothing to do with what I've suggested.  The title mentions Mockito, but the diff doesn't change anything in `PreparedStatementSpyConnectionProvider`...

**Comment by beikov** [comment]
It's the parent commit https://github.com/hibernate/hibernate-orm/commit/563880037e6f6540a70cb50c2f35147e0c4c94e1

**Comment by big-andy-coates** [comment]
@beikov I've spent a good few minutes looking through the logs, code and tests, but unfortunately there's just too much going on here for me to be able to comment more.

If you were able to extract out a simple, self-contained, test case that fails, then I'm happy to look more.  Such a test case can be in the hibernate code base if you want, as that will make it easier to test on the right architecture etc.

If you're having problems recreating the issue, then it may be worth putting the test in a loop of a few thousand, or more, iterations.  This will really give it a good chance of hitting the race condition.
