### ISSUE TITLE
mockito behaves strange in multiple thread test

### ISSUE THREAD

**Issue by sanChouIsACat** [mockito/mockito#2896]
Hey,
I'm running a scheduler implemented by multiple threads test , and using mockito to mock some task. Mockito complains that some of my task methods are not executed.But the scheduler log says those methods were executed.And when i put Thread.Sleep between my scheduler and mockito's verify methods, things become normal. It really seems like a mockito bug.
Please note that I have deleted some fragment in my code due to it's a business code and it has some Chinese in the code.The code can hardly be used directly, but it should be ok with some little modified.Sorry for this!
My Schedule Code:
```
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import lombok.extern.slf4j.Slf4j;
import org.apache.xmlbeans.impl.common.Mutex;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Function;
import java.util.function.Supplier;


public interface TaskExecutorService {
//    Boolean executeATask(AbstractTaskModel task);
//
//    /**
//     * 优雅关闭，不再接受新任务，等待任务结束才返回
//     */
//    void shutdown();
//
//    Integer peekTaskCount();
//}

@Slf4j
@Service
public class TaskExecutorServiceImpl implements TaskExecutorService {
    /**
     * 使用iterator将访问下一个子任务的复杂度降为常量级别
     * subTask永远位于iterator的
     * @author sanchouisacat
     * @version 2023/02/01
     */
    private static class TaskBinder implements Iterator<AbstractSubTaskModel>{
        /**
         * Iterator没有current()方法，只能用该变量来访问
         */
        private AbstractSubTaskModel currentSubTask;

        private final ListIterator<AbstractSubTaskModel> iterator;

        public final AbstractTaskModel task;
        /**
         * 是否已经位于需要落库的节点后
         */
        public Boolean afterWriteDown= Boolean.FALSE;



        public TaskBinder(AbstractTaskModel task) {
            this.iterator = task.getSubTaskList().listIterator();
            this.task = task;
        }

        /**
         * 当前子任务
         *
         * @return {@link AbstractSubTaskModel}
         */
        public AbstractSubTaskModel current(){
            return currentSubTask;
        }

        /**
         * 下一个子任务
         *
         * @return {@link AbstractSubTaskModel}
         */
        public AbstractSubTaskModel next(){
            currentSubTask= iterator.next();
            return currentSubTask;
        }

        /**
         * 是否有下一个子任务
         *
         * @return boolean
         */
        public boolean hasNext(){
            return iterator.hasNext();
        }
    }

    private enum IteratorResultEnum{
        REMOVE,
        TRANSFER_TO_SYNC,
        NONE;
    }

    /**
     * 避免以下情况：
     * 异步工作线程轮询队列中的异步任务结果，考虑到网络IO，该操作可能需要较长的时间，此时异步任务队列是临界区。将导致同步任务线程无法将已经完成post的异步任务入队，形成瓶颈。
     * 通过读写分离减少临界区的时间长度
     * @author sanchouisacat
     * @date 2023/02/02
     */
    private class ReadWriteLinkedList {


        Mutex innerMutex =new Mutex();

        private void doOperatorExclusive(Runnable task){
            doOperatorExclusive(()->{
                task.run();
                return false;
            });
        }

        private <T> T doOperatorExclusive(Supplier<T> task){
            try {
                innerMutex.acquire();
            } catch (InterruptedException e) {
                log.warn("thread interrupted");
            }
            T res=task.get();
            innerMutex.release();
            return res;
        }


        private final List<TaskBinder> readList =new LinkedList<>();
        private final List<TaskBinder> writeList= new LinkedList<>();

        public void addWriteList(TaskBinder data){
            doOperatorExclusive(()-> writeList.add(data));
        }

        public Boolean isEmpty(){
            return doOperatorExclusive(()-> readList.isEmpty() && writeList.isEmpty());
        }

        public int size(){
            return doOperatorExclusive(()-> readList.size()+writeList.size());
        }

        public void iterateReadList(Function<TaskBinder,IteratorResultEnum> function){
            doOperatorExclusive(()-> {
                readList.addAll(writeList);
                writeList.clear();
            });
            Iterator<TaskBinder> iterator=readList.listIterator();
            while (iterator.hasNext()){
                TaskBinder currentTask = iterator.next();
                IteratorResultEnum res = function.apply(currentTask);
                switch (res){
                    case REMOVE:
                        iterator.remove();
                        setTaskFinishTagIfPossible();
                        break;
                    case TRANSFER_TO_SYNC:
                        try {
                            mutexForSyncQueueAsyncListTransfer.acquire();
                        } catch (InterruptedException e) {
                            log.warn("a interrupte happened in task executor");
                        }
                        iterator.remove();
                        syncSubTaskQueue.add(currentTask);
                        syncSubTaskResources.release();
                        mutexForSyncQueueAsyncListTransfer.release();
                        break;
                    case NONE:
                    default:
                }
            }
        }

    }

    @Value("${taskExecutor.syncParallelNum}")
    private Integer   syncParallelNum;
    @Value("${taskExecutor.syncWaitingInterval}")
    private Long   syncWaitingInterval;

    @Value("${taskExecutor.asyncWorkerIntervals}")
    private Integer asyncWorkerIntervals;

    /**
     * 用于优雅关闭服务
     */
    private final AtomicBoolean shutdownTag=new AtomicBoolean(false);
    private final AtomicBoolean taskFinishTag =new AtomicBoolean(true);

    /**
     * 同步工作线程池，用于执行同步子任务及异步子任务的第一个状态
     */
    ExecutorService syncWorkerThreadPool;

    private final Timer asyncWorker =new Timer("taskAsyncExecutor");
    /**
     * 同步子任务队列，同步线程池消费该子任务
     */
    Queue<TaskBinder> syncSubTaskQueue=new ConcurrentLinkedQueue<>();
    /**
     * 异步子任务队列,单独一个线程用于查询这些子任务是否已经完成了，线程局部变量
     */
    ReadWriteLinkedList asyncSubTaskList =new ReadWriteLinkedList();

    Semaphore syncSubTaskResources=new Semaphore(0);



    @PostConstruct
    public void init(){
        syncWorkerThreadPool=new ThreadPoolExecutor(syncParallelNum,syncParallelNum,syncWaitingInterval,TimeUnit.SECONDS,
                new LinkedBlockingQueue<>(),
                new ThreadFactoryBuilder().setNameFormat("taskExecutor-sync-%d").build());
        asyncWorker.schedule(new TimerTask() {
            @Override
            public void run() {
                asyncWork();
            }
        },asyncWorkerIntervals,asyncWorkerIntervals);
        for (int i = 0; i < syncParallelNum; i++) {
            syncWorkerThreadPool.execute(this::syncWork);
        }
        log.info("task executor start successfully,sync parallel num [{}],async intervals [{}] "
        ,syncParallelNum,asyncWorkerIntervals);
    }

    private void addToAsync(TaskBinder task){
        log.debug("add sub task to async [{}]",task.current().getName());
        try {
            mutexForSyncQueueAsyncListTransfer.acquire();
        } catch (InterruptedException e) {
            log.warn("a interrupte happened in task executor");
        }
        asyncSubTaskList.addWriteList(task);
        mutexForSyncQueueAsyncListTransfer.release();
    }

    /**
     * 异步传输同步,如果可能话
     * 移除任务，如果还有子任务，将异步队列任务中的任务移到同步队列中，两个参数应该指向同一个对象
     *
     * @param asyncTaskListIterator 异步任务列表迭代器
     * @param subTaskIterator       子任务迭代器,也是asyncTaskListIterator所指向的对象
     */
    private void transferAsyncToSyncIfPossible(Iterator<TaskBinder> asyncTaskListIterator,TaskBinder subTaskIterator){


    }

    /**
     * 互斥锁，在异步子任务队列和同步子任务队列的增删时需要为原子操作，否则退出时可能会出现任务没有执行完成就退出
     */
    Mutex mutexForSyncQueueAsyncListTransfer =new Mutex();



    private void updateDbIfPossible(AbstractSubTaskModel finishedSubTask, TaskBinder taskBinder){
        if(finishedSubTask==taskBinder.task.getStorageSubTask()){
            taskBinder.afterWriteDown=true;
        }
        if(taskBinder.afterWriteDown){
            taskBinder.task.updateDb(finishedSubTask.getTaskData());
        }
    }

    private void syncWork(){
        while (true){
            syncSubTaskResources.acquireUninterruptibly();
            //关闭时需要释放该手动释放该信号量，但队列中实际上没有值
            if(shutdownTag.get()){
                return ;
            }
            TaskBinder currentTask=syncSubTaskQueue.poll();
            boolean transferToAsync=false;
            //执行该总任务直到遇到异步任务
            while (currentTask.hasNext()){
                AbstractSubTaskModel currentSubTask=currentTask.next();
                //log.debug("current task acquired by current method [{}],by next method [{}]",currentTask.current().hashCode(),currentSubTask.hashCode());
                currentSubTask.runSubTask();
                log.debug("execute sub task [{}] finish,father task [{}]",currentSubTask.getName(),currentTask.task.getTaskName());
                if(currentSubTask instanceof AbstractAsyncSubTaskModel){
                    log.debug("sub task [{}] is a async task ,add to async list,father task [{}]",currentSubTask.getName(),currentTask.task.getTaskName());
                    //log.debug("add to Async:current task acquired by current method [{}],by next method [{}]",currentTask.current().hashCode(),currentSubTask.hashCode());
                    addToAsync(currentTask);
                    transferToAsync=true;
                    break;
                }
                currentTask.task.updateMemory(currentSubTask.getTaskData());
                updateDbIfPossible(currentSubTask,currentTask);
//                //将任务重新加入到同步任务中
//                syncSubTaskQueue.add(currentTask);
//                syncSubTaskResources.release();
            }
            if(!transferToAsync){
                log.debug("father task [{}] finish!",currentTask.task.getTaskName());
                setTaskFinishTagIfPossible();
            }
        }
    }

    private void setTaskFinishTagIfPossible(){
        if(syncSubTaskQueue.isEmpty() && asyncSubTaskList.isEmpty()){
            taskFinishTag.set(true);
        }
    }


    /**
     * 仅用来轮询异步子任务是否已经完成，异步子任务的主要工作仍然由同步任务Worker来处理
     */
    private void asyncWork(){
        asyncSubTaskList.iterateReadList(totalTask ->{
            TaskBinder subTaskIterator=totalTask;
            if(subTaskIterator.current() instanceof AbstractSyncSubTaskModel){
                log.warn("task cast error ,sub task name:[{}]",subTaskIterator.current().getName());
            }
            AbstractAsyncSubTaskModel asyncSubTask = (AbstractAsyncSubTaskModel) subTaskIterator.current();
            if(!asyncSubTask.describeTaskFinish()){
                return IteratorResultEnum.NONE;
            }
            log.debug("async sub task [{}] finished,father task [{}]",asyncSubTask.getName(),totalTask.task.getTaskName());
            totalTask.task.updateMemory(asyncSubTask.getTaskData());
            updateDbIfPossible(asyncSubTask,totalTask);
            if(subTaskIterator.hasNext()){
                log.debug("add task to sync queue");
                return IteratorResultEnum.TRANSFER_TO_SYNC;
            }
            log.debug("father task [{}] finish!",totalTask.task.getTaskName());
            return IteratorResultEnum.REMOVE;
        });
    }
    @Override
    public Boolean executeATask(AbstractTaskModel task) {
        if(shutdownTag.get()){
            return false;
        }
        syncSubTaskQueue.add(new TaskBinder(task));
        syncSubTaskResources.release();
        taskFinishTag.set(false);
        return true;
    }


    @Override
    public void shutdown() {
        log.info("task executor shutdown");
        shutdownTag.set(true);
        while (!taskFinishTag.get()){
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                log.warn("thread being interrupted");
            }
        }

        //优雅关闭服务
        syncSubTaskResources.release(Integer.MAX_VALUE);//释放正在等待的同步服务线程
        try {
            syncWorkerThreadPool.wait();
            asyncWorker.wait();
        } catch (InterruptedException e) {
            log.warn("thread being interrupted");
        }
    }

    @Override
    public Integer peekTaskCount() {
        return asyncSubTaskList.size()+syncSubTaskQueue.size();
    }
}
```
My task model:
```
@Getter
public abstract class AbstractTaskModel {
    private final TaskEnum taskType;
    private String taskName;
    private final LinkedList<AbstractSubTaskModel> subTaskList;
    /**
     * 在该子任务及之后的子任务执行完成后，数据库将会落库
     */
    private final AbstractSubTaskModel storageSubTask;

    /**
     * 在落库时将会调用该方法来落库
     *
     * @param subTaskResults :执行完成的子任务及之前的返回数据
     */
    public abstract void updateDb(Serializable subTaskResults);

    /**
     * 在内存中更新数据，无论落库落库之前还是落库任务之后都会调用该任务
     *
     * @param subTaskResults 子任务结果
     */
    public abstract void updateMemory(Serializable subTaskResults);

    /**
     * 抽象任务模型
     *
     * @param taskType       任务类型
     * @param subTaskList    子任务列表:必须为链表，任务执行框架依赖于链表结构来降低时间复杂度
     * @param storageSubTask 存储子任务
     */
    protected AbstractTaskModel(TaskEnum taskType, LinkedList<AbstractSubTaskModel> subTaskList, AbstractSubTaskModel storageSubTask) {
        this.taskType = taskType;
        this.subTaskList = subTaskList;
        this.storageSubTask = storageSubTask;
    }
}

//base task model
public abstract class AbstractSubTaskModel {
    @Getter
    protected Serializable taskData;
    @Setter
    @Getter
    private String name;
    public abstract void runSubTask();
}


//sync sub task model
public abstract class AbstractSyncSubTaskModel extends AbstractSubTaskModel {
}

//async sub task model
public abstract class AbstractAsyncSubTaskModel extends AbstractSubTaskModel{
    public abstract boolean describeTaskFinish();
}
```
My Test Code
```
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.LinkedList;

import static org.mockito.Mockito.*;

@RunWith(SpringRunner.class)
@SpringBootTest
public class TaskExecutorServiceImplTest {
    @Autowired
    TaskExecutorService taskExecutorService;


    @Before
    public void setUp(){


    }


    /**
     * 一共5个子函数a1-s1-a2_i-s2-a3，在第三个中进行插入数据库测试
     */
    @Test
    public void executeTemplate1() {
        AbstractAsyncSubTaskModel async1=mock(AbstractAsyncSubTaskModel.class);
        when(async1.describeTaskFinish()).thenReturn(false,true);
        when(async1.getName()).thenReturn("async1");
        AbstractAsyncSubTaskModel async2=mock(AbstractAsyncSubTaskModel.class);
        when(async2.getName()).thenReturn("async2");
        when(async2.describeTaskFinish()).thenReturn(false,false,true);
        AbstractSyncSubTaskModel sync1=mock(AbstractSyncSubTaskModel.class);
        when(sync1.getName()).thenReturn("sync1");
        AbstractSyncSubTaskModel sync2=mock(AbstractSyncSubTaskModel.class);
        when(sync2.getName()).thenReturn("sync2");
        AbstractSyncSubTaskModel sync3=mock(AbstractSyncSubTaskModel.class);
        when(sync3.getName()).thenReturn("sync3");
        AbstractTaskModel totalTask=mock(AbstractTaskModel.class);
        LinkedList<AbstractSubTaskModel> subTaskList =  new LinkedList<>();
        subTaskList.add(sync1);
        subTaskList.add(async1);
        subTaskList.add(sync2);
        subTaskList.add(async2);
        subTaskList.add(sync3);
        when(totalTask.getSubTaskList()).thenReturn(subTaskList);
        when(totalTask.getStorageSubTask()).thenReturn(sync2);
        taskExecutorService.executeATask(totalTask);
        while (taskExecutorService.peekTaskCount()>0){

            System.out.printf("task count is %d%n",taskExecutorService.peekTaskCount());
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
        
        
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        //子任务是否被运行
        verify(sync1,times(1)).runSubTask();
        verify(sync2,times(1)).runSubTask();
        verify(sync3,times(1)).runSubTask();
        verify(async1,times(1)).runSubTask();
        verify(async2,times(1)).runSubTask();
        //异步任务回调函数
        verify(async1,times(2)).describeTaskFinish();
        verify(async2,times(3)).describeTaskFinish();
        //数据库插入操作
        verify(totalTask,times(3)).updateDb(null);
        //内存更新操作
        verify(totalTask,times(5)).updateMemory(null);
    }


    /**
     * 一共5个子函数a1-s1-a2_i-a3-s2，在第三个中进行插入数据库测试，以异步任务结尾
     */
    @Test
    public void executeTemplate2() {
        AbstractAsyncSubTaskModel async1=mock(AbstractAsyncSubTaskModel.class);
        when(async1.describeTaskFinish()).thenReturn(false,true);
        when(async1.getName()).thenReturn("async1");
        AbstractAsyncSubTaskModel async2=mock(AbstractAsyncSubTaskModel.class);
        when(async2.getName()).thenReturn("async2");
        when(async2.describeTaskFinish()).thenReturn(false,false,true);
        AbstractSyncSubTaskModel sync1=mock(AbstractSyncSubTaskModel.class);
        when(sync1.getName()).thenReturn("sync1");
        AbstractSyncSubTaskModel sync2=mock(AbstractSyncSubTaskModel.class);
        when(sync2.getName()).thenReturn("sync2");
        AbstractSyncSubTaskModel sync3=mock(AbstractSyncSubTaskModel.class);
        when(sync3.getName()).thenReturn("sync3");
        AbstractTaskModel totalTask=mock(AbstractTaskModel.class);
        LinkedList<AbstractSubTaskModel> subTaskList =  new LinkedList<>();
        subTaskList.add(sync1);
        subTaskList.add(async1);
        subTaskList.add(sync2);
        subTaskList.add(sync3);
        subTaskList.add(async2);
        when(totalTask.getSubTaskList()).thenReturn(subTaskList);
        when(totalTask.getStorageSubTask()).thenReturn(sync2);
        taskExecutorService.executeATask(totalTask);
        while (taskExecutorService.peekTaskCount()>0){

            System.out.printf("task count is %d%n",taskExecutorService.peekTaskCount());
            try {
                Thread.sleep(10000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
//        try {
//            Thread.sleep(1000);
//        } catch (InterruptedException e) {
//            throw new RuntimeException(e);
//        }
        //子任务是否被运行
        verify(sync1,times(1)).runSubTask();
        verify(sync2,times(1)).runSubTask();
        verify(sync3,times(1)).runSubTask();
        verify(async1,times(1)).runSubTask();
        verify(async2,times(1)).runSubTask();
        //异步任务回调函数
        verify(async1,times(2)).describeTaskFinish();
        verify(async2,times(3)).describeTaskFinish();
        //数据库插入操作
        verify(totalTask,times(3)).updateDb(null);
        //内存更新操作
        verify(totalTask,times(5)).updateMemory(null);
    }
}
```
Here is my test output with sleep method called, it looks fine:
```
[DEBUG] 21:14:42.127 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - execute sub task [sync1] finish,father task [null]
[DEBUG] 21:14:42.132 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - execute sub task [async1] finish,father task [null]
[DEBUG] 21:14:42.132 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - sub task [async1] is a async task ,add to async list,father task [null]
[DEBUG] 21:14:42.132 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - add sub task to async [async1]
[DEBUG] 21:14:42.148 [taskAsyncExecutor] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - async sub task [async1] finished,father task [null]
[DEBUG] 21:14:42.151 [taskAsyncExecutor] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - add task to sync queue
[DEBUG] 21:14:42.152 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - execute sub task [sync2] finish,father task [null]
[DEBUG] 21:14:42.157 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - execute sub task [sync3] finish,father task [null]
[DEBUG] 21:14:42.158 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - execute sub task [async2] finish,father task [null]
[DEBUG] 21:14:42.158 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - sub task [async2] is a async task ,add to async list,father task [null]
[DEBUG] 21:14:42.158 [taskExecutor-sync-0] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - add sub task to async [async2]
[DEBUG] 21:14:42.176 [taskAsyncExecutor] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - async sub task [async2] finished,father task [null]
[DEBUG] 21:14:42.178 [taskAsyncExecutor] c.a.o.o.c.s.i.t.TaskExecutorServiceImpl - father task [null] finish!
```
Here is my test output without sleep, which complains.
```
abstractSyncSubTaskModel.runSubTask();
-> at ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest.executeTemplate1(TaskExecutorServiceImplTest.java:77)
Actually, there were zero interactions with this mock.
, mergedContextConfiguration = [WebMergedContextConfiguration@5a63fa71 testClass = TaskExecutorServiceImplTest, locations = '{}', classes = '{class ***.cloud.CloudApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3f197a46, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@1817d444, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ef3eef9, org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizer@1ea9f6af, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@4d9e68d0, org.springframework.boot.test.context.SpringBootTestArgs@1], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].
[DEBUG] 21:04:07.825 [main] o.s.t.c.w.ServletTestExecutionListener - Resetting RequestContextHolder for test context [DefaultTestContext@7e9a836 testClass = TaskExecutorServiceImplTest, testInstance = ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest@124ff64d, testMethod = executeTemplate1@TaskExecutorServiceImplTest, testException = Wanted but not invoked:
abstractSyncSubTaskModel.runSubTask();
-> at ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest.executeTemplate1(TaskExecutorServiceImplTest.java:77)
Actually, there were zero interactions with this mock.
, mergedContextConfiguration = [WebMergedContextConfiguration@5a63fa71 testClass = TaskExecutorServiceImplTest, locations = '{}', classes = '{class ***.cloud.CloudApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@3f197a46, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@1817d444, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@2ef3eef9, org.springframework.boot.test.web.reactive.server.WebTestClientContextCustomizer@1ea9f6af, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@4d9e68d0, org.springframework.boot.test.context.SpringBootTestArgs@1], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true]].


Wanted but not invoked:
abstractSyncSubTaskModel.runSubTask();
-> at ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest.executeTemplate1(TaskExecutorServiceImplTest.java:77)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
abstractSyncSubTaskModel.runSubTask();
-> at ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest.executeTemplate1(TaskExecutorServiceImplTest.java:77)
Actually, there were zero interactions with this mock.

	at ***.cloud.services.impl.taskExecutor.TaskExecutorServiceImplTest.executeTemplate1(TaskExecutorServiceImplTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


```
Let me briefly explain the scheduler idea:
- A Task consists of multiple subtasks.These subtasks are ordered in Task.
- A subtask can be sync or async.
- A ThreadPool for executing sync SubTasks.
- A Single thread for polling async  SubTasks.
- A queue that holds sync subtasks orderly, but sync subtasks of different Task can be placed together.Like this: a1-a2-b1-b2-c1-c2, which a,b,c is subtask of A,B,C.
- A linked list that holds async subtasks which waiting to be scheduled to poll

My enviroment:
- OS:Mac Os
- IDE:IntelliJ IDEA 2022.2 (Ultimate Edition)
- JDK Version: java 1.8.0_341
- Mockito Info:mockito-core 4.8.0
- Framework:  :: Spring Boot ::        (v2.3.4.RELEASE)

Please let me know whether it's my fault or a bug.And i'm happy to be contacted!
Best wish!

**Comment by TimvdLippe** [comment]
Thanks for filing the issue. Could you please provide us a minimal reproduction case that we can clone/download to debug the issue? Thanks in advance!

**Comment by StummeJ** [comment]
I'm also seeing this where it looks like multiple tests are updating the mock at the same time
