### ISSUE TITLE
initMocks produces NullPointerException

### ISSUE THREAD

**Issue by DariusL** [mockito/mockito#295]
public class MockitoTest {
        @Rule public MockitoRule mockitoRule = MockitoJUnit.rule();
        @Mock private Interface mock;
        private Foo foo;

        @Test
        public void testName() throws Exception {

        }

        private interface Interface{}
        private static class Foo{}
    }

Causes 

    java.lang.NullPointerException
    at com.android.dx.mockito.DexmakerMockMaker.getInvocationHandlerAdapter(DexmakerMockMaker.java:81)
    at com.android.dx.mockito.DexmakerMockMaker.getHandler(DexmakerMockMaker.java:76)
    at org.mockito.internal.util.MockUtil.isMockitoMock(MockUtil.java:74)
    at org.mockito.internal.util.MockUtil.isMock(MockUtil.java:66)
    at org.mockito.internal.configuration.injection.scanner.MockScanner.isMockOrSpy(MockScanner.java:86)
    at org.mockito.internal.configuration.injection.scanner.MockScanner.preparedMock(MockScanner.java:72)
    at org.mockito.internal.configuration.injection.scanner.MockScanner.scan(MockScanner.java:61)
    at org.mockito.internal.configuration.injection.scanner.MockScanner.addPreparedMocks(MockScanner.java:47)
    at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:96)
    at org.mockito.internal.configuration.InjectingAnnotationEngine.processInjectMocks(InjectingAnnotationEngine.java:62)
    at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:56)
    at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
    at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:15)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
    at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)

It seems that `null` fields cause this. Initializing `foo` in the declaration or in `setUp` and then calling `initMocks` works fine. If this is a dexmaker issue, I can move it there.

**Comment by raphw** [comment]
This is due to #243 which is already fixed in master.

**Comment by DariusL** [comment]
Missed that one. I'll wait for a release then.
