### ISSUE TITLE
InOrder fails when an unverified method is called between calls verified with times(x)

### ISSUE THREAD

**Issue by patchwork01** [mockito/mockito#2957]
Here's an example of a test that fails incorrectly (tested on Mockito 4.11.0, JDK 11):

```java
public interface B {
    void unverified(String value);
    void verified(String value);
}

@Test
void shouldReproduceBug() {
    Consumer<String> a = mock(Consumer.class);
    B b = mock(B.class);

    a.accept("1");
    b.unverified("2");
    a.accept("3");
    b.verified("4");
    a.accept("5");

    InOrder order = Mockito.inOrder(a, b);
    order.verify(a, times(2)).accept(any());
    order.verify(b).verified(any());
    order.verify(a).accept(any());
    order.verifyNoMoreInteractions();
}
```

We want to verify that `a.accept` is called twice, then `b.verified`, then `a.accept` again. This is what's happening, but there's also a call to `b.unverified` in between the first 2 calls to `a.accept`.

This test should pass, but it fails on the first order.verify assertion with this message:

```
org.mockito.exceptions.verification.VerificationInOrderFailure: 
Verification in order failure:
consumer.accept(<any>);
Wanted 2 times:
-> at TestClass.shouldReproduceBug(TestClass.java:18)
But was 3 times:
-> at TestClass.shouldReproduceBug(TestClass.java:11)
-> at TestClass.shouldReproduceBug(TestClass.java:13)
-> at TestClass.shouldReproduceBug(TestClass.java:15)
```

**Comment by TimvdLippe** [comment]
I think you need to use `ignoreStubs` for this: https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#ignore_stubs_verification

**Comment by patchwork01** [comment]
No, it still has the same failure with `ignoreStubs`. It fails on the first verify call, before there are any calls that could interfere with the assertions. I've updated the description to include the `ignoreStubs` call I've tested with.
