### ISSUE TITLE
Mockito 5 NPE on OpenJ9 11

### ISSUE THREAD

**Issue by daniloesk** [mockito/mockito#2963]
Running a test using `@InjectMocks` and `@Spy` on an object using IBM OpenJ9 OpenJDK 11 results in an **occasional** (~80%) NullPointerException.

Before the details, thank you! Great work!

This only happens:
* Mockito 5
  * 4.11: OK
  * 5.0: NPE
  * 5.2: NPE
* IBM OpenJ9 OpenJDK 11
  * Hotspot 11.0.18: OK
  * Hotspot 17.0.6: OK
  * OpenJ9 11.0.13+8: NPE
  * OpenJ9 11.0.18+10: NPE
  * OpenJ9 17.0.6+10: OK

The problem occurred in both Linux and Windows.
OpenJ9 site: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/

Below is a code that reproduces the problem. I will also attach the files in `npe.tgz`.

Main code (`src/main/java/mockitotest/Service.java`):
```java
package mockitotest;

public class Service {

    private Dependency dep;

    public String external() {
        return this.dep.config() + "-ext";
    }

    public static class Dependency {

        public String config() {
            return "config";
        }

    }

}
```

Test code (`src/test/java/ServiceTest.java`):
I know that in this case the Spy is not used, but using it or not does not affect the NPE.

```java
package mockitotest;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Spy;
import org.mockito.junit.jupiter.MockitoExtension;

import mockitotest.Service.Dependency;

@ExtendWith(MockitoExtension.class)
class ServiceTest {

    @Mock
    Dependency dep;

    @InjectMocks
    @Spy
    Service regular;

    @Test
    void test() throws Exception {
        var returned = this.regular.external();
        assertEquals("null-ext", returned);
    }

}
```

Dependencies (`pom.xml`):
```xml
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>
	<modelVersion>4.0.0</modelVersion>

	<groupId>mockito.test</groupId>
	<artifactId>mockito-test</artifactId>
	<version>1.0.0-SNAPSHOT</version>

	<properties>
		<maven.compiler.release>11</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.9.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>5.2.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.11.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.0.0</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>
```

Possible workarounds:
* Upgrade to Java 17
* Change JVM vendor
* Fallback to Mockito 4

This problem also shows up with the annotated object being null, not only the dependency (`service` in the above example), but this was simpler to put on an example.

**Comment by TimvdLippe** [comment]
@jfrantzius another regression I think

**Comment by jfrantzius** [comment]
@daniloesk would you mind sharing the NPE stack trace here?

At any rate, if it's an "Occasional (~80%) NullPointerException on IBM OpenJ9 OpenJDK 11", which can be solved by upgrading to Java 17 or changing the JVM vendor, then I'd suspect a OpenJ9 OpenJDK 11 bug here?

**Comment by daniloesk** [comment]
Running with `mvn test`:
```stacktrace
java.lang.NullPointerException
	at mockitotest.Service.external(Service.java:14)
	at mockitotest.ServiceTest.test(ServiceTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at <unknown class>.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at <unknown class>.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at <unknown class>.apply(Unknown Source)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at <unknown class>.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at <unknown class>.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at <unknown class>.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at <unknown class>.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at <unknown class>.invoke(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at <unknown class>.execute(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at <unknown class>.accept(Unknown Source)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
```

I also suspect of a OpenJ9 OpenJDK 11 bug, but since the behavior changed from Mockito 4 I guess the Mockito implementation also changed and maybe it is relying on some undocumented behavior that was changed on the JVM. Or something like that. :-)

I thought it was important to at least post it here so other people can know about it and maybe they will have some tricky situation like us, kind of being stuck with OpenJ9 OpenJDK 11 for some time and unable to upgrade Mockito as well.

**Comment by jfrantzius** [comment]
What strikes me a bit odd is that `private Dependency dep;` in class `Service` doesn't have an `@Inject` annotation?

**Comment by daniloesk** [comment]
@jfrantzius, I've got an email but did not find it here... :-p

Well, the code is a demo and is somewhat weird. No constructors, `@Inject`, inner class, etc. But the ideia is to keep it as simple as possible. I will try to simplify it later, but the most important is that it does not work with Mockito 5 and  OpenJ9 OpenJDK 11. The same code works with other settings.

About the `@Inject` I always had the impression that Mockito worked purely with reflection injecting on construtor and fields. I will try adding it as well.

It may be important that removing the `@Spy` also makes it work, although I haven't mentioned it explicitly before.

**Comment by jfrantzius** [comment]
@daniloesk sorry for the comment on `@Inject` that I then deleted, once I realized that my own Junit tests don't use it either, and didn't have the time to figure out why it does work without 😛 

May I ask why you need to stick with OpenJ9 OpenJDK 11?

**Comment by daniloesk** [comment]
> sorry for the comment

No problem ;-)

We use IBM servers that need to run on IBM JVM's due to support contracts, so we cannot change vendor.
And we have compatiblity issues blocking server upgrade, and the JVM version is stuck with it.

Of course that will happen in time and maybe it is not worth investing time fixing this issue since it is quite specific and for an old JVM version.

**Comment by jfrantzius** [comment]
Given the Org I work for, I feel I should ask a bit further here ;)

@jfrantzius do you per chance know whether there are JUnit tests for combining `@InjectMocks` and `@Spy` on the same field, as is the case here?

```java
    @InjectMocks
    @Spy
    Service regular;
```

**Comment by TheSnoozer** [comment]
Sorry if I may hijack this issue, but the issue I bumped in feels awfully similar to the problem described here (so it feels related).

Before going into details, thank you for this project!

Now, to the details:
I have a reproducible NPE with mockito 5.3.0, openjdk version "11.0.18". With mockito 5.1.0 and 5.2.0 the same works just fine.

In a nutshell the problem can be summarized as using a spy on an already existing object. This object requires a log interface that is being passed on in the constructor call and will be used / called during the procedure that shall be verified. To put it simply in the end the spy is being used to verify results.
Now the initial object has `log != null`, but the object that comes out of `spy(orgObject)` has `log == null`. When the  procedure now reaches the code wants to log something the test fails with a NPE.

Code for reference:
https://github.com/git-commit-id/git-commit-id-plugin-core/blob/de412959a3709d9ea342392eafcf55047e22c18d/src/test/java/pl/project13/core/jgit/DescribeCommandOptionsTest.java#L51

Please let me know if you prefer a new ticket, but since it sounds related so I hope it's ok to steal this :-)

**Comment by bmarwell** [comment]
MAYBE a duplicate of https://github.com/mockito/mockito/issues/2278 (please close this in favour of #2278).
Upstream issue: https://github.com/eclipse-openj9/openj9/issues/17454

The linked issues are about a modification exception, but they seem to have appeared at the same time.

Thanks to @paulcheeseman from IBM for providing the link to the upstream issue (I am merely another user, but my company has IBM support and we ran into this, too. So I opened an issue so IBM could work on this more quickly).

HTH
