### ISSUE TITLE
Could not initialize inline Byte Buddy mock maker

### ISSUE THREAD

**Issue by luojiao** [mockito/mockito#2973]
hey, i got a problem when i run with junit5
my dependencies list:
![image](https://user-images.githubusercontent.com/10434684/231770869-8d8cca38-39c8-49ac-b05b-f8aa8852086a.png)
cause by :

> Caused by: java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

> Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:104)
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.getDefaultPlugin(DefaultMockitoPlugins.java:78)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:75)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:27)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:22)
	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:73)

> Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

> It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 17
JVM vendor name    : Amazon.com Inc.
JVM vendor version : 17.0.6+10-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.6+10-LTS
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0

> 	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:244)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
	... 101 more
Caused by: java.lang.IllegalArgumentException
	at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)

my env:

- oracle jdk 17.0.3 can't work
- amazon corretto 17.0.6_10 can't work

> IntelliJ IDEA 2022.1.3 (Ultimate Edition)
Build #IU-221.5921.22, built on June 21, 2022
Licensed to blues arable
You have a perpetual fallback license for this version.
Subscription expired on January 1, 2023.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2536M
Cores: 8
Non-Bundled Plugins:
    org.jetbrains.plugins.go (221.5921.16)
    com.intellij.guice (221.5921.16)
    Builder Generator (1.2.0)
    com.intellij.bigdatatools (221.4165.72)
    MavenRunHelper (4.20.213.3714.1)
    zielu.gittoolbox (212.9.7)
    com.baomidou.plugin.idea.mybatisx (1.5.4)

Kotlin: 221-1.6.21-release-337-IJ5921.22

**Comment by luojiao** [comment]
i found same problems
