### ISSUE TITLE
Race condition when using and setting up stubs in multiple threads [5.3.1]

### ISSUE THREAD

**Issue by aldexis** [mockito/mockito#3010]
When running the below test on Mockito 5.3.1 with Jupiter 5.9.3, the assert on the `method2` call flakes somewhat frequently on the last assert, giving a `null` return value rather than the value stubbed literally the previous line.

If you uncomment the `awaitTermination` line, it works fine.

If you remove the arguments from `method2`, it also flakes less, which I assume is related to timing of the race condition.

```
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;
import static org.mockito.Mockito.withSettings;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
public final class TestRepro {

    interface Service {
        String method1();

        String method2(String arg1, String arg2, String arg3, String arg4);
    }

    @RepeatedTest(10000)
    @SuppressWarnings({"DirectInvocationOnMock", "checkstyle:HiddenField"})
    public void testRepro() {
        Service service = Mockito.mock(Service.class, withSettings().verboseLogging());

        when(service.method1()).thenReturn("sync");

        // Here to avoid complaints about unnecessary stubbings
        String response = service.method1();
        assertThat(response).isEqualTo("sync");

        ExecutorService executorService = Executors.newSingleThreadExecutor();
        executorService.execute(() -> {
            String sync = service.method1();
            assertThat(sync).isEqualTo("sync");
        });
        executorService.shutdown();
        //        executorService.awaitTermination(1, java.util.concurrent.TimeUnit.SECONDS);

        when(service.method2(any(), any(), any(), any())).thenReturn("send");

        assertThat(service.method2("arg1", "arg2", "arg3", "arg4")).isEqualTo("send");
    }
}
```

Error:
```
org.opentest4j.AssertionFailedError: 
expected: "send"
 but was: null
	at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.7/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.7/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.7/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//TestRepro.testRepro(TestRepro.java:49)
        ...
```

**Comment by TimvdLippe** [comment]
https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe

**Comment by MendelMonteiro** [comment]
@TimvdLippe , we might want to make that FAQ more explicit with concrete examples.

With regard to the sentences from the FAQ: "that is tests without multiple threads stubbing/verifying a shared mock." / "you can let multiple threads call methods on a shared mock to test in concurrent conditions".

In the example above only one thread is stubbing/verifying and the other thread is only calling methods on the mock.  To me from reading the sentences I would say that it should work but obviously it does not.

What do you think?
