### ISSUE TITLE
Cannot inject a generic instance in a superclass

### ISSUE THREAD

**Issue by julien-breda** [mockito/mockito#3019]
Hello !

### The context
I'm trying to update Mockito from version 1 to 5.3.1 (there's some work to do)
I'm facing an issue and I built a tiny project to illustrate it : [mockito-upgrade.zip](https://github.com/mockito/mockito/files/11562158/mockito-upgrade.zip)

### The environment
I'm using OpenJDK 11.0.14.1, Maven 3.6.1, JUnit 4.11, on Windows 10.

### The code
There's an EntryPoint extending AbstractGenericClass. This last one uses a ParameterizerInjectedObject. The class Something was only created to specify generics.
When I try to test EntryPoint, with EntryPointTest, I uses Mockito to inject a mock of ParameterizerInjectedObject<Something> in my EntryPoint instance.

### The problem
The problem is that the mock isn't injected.
If I remove all generics it works but this is not an acceptable solution.

If you run my test you'll have a NPE because AbstractGenericClass.object isn't initialized : it is intended to demonstrate the problem.
If you initialize it by replacing 
`private ParameterizedInjectedObject<T> object;`
with
`private ParameterizedInjectedObject<T> object = new ParameterizedInjectedObject<>();`

you'll see the following failure :

> Wanted but not invoked:
> injected.init();
> -> at test.ParameterizedInjectedObject.init(ParameterizedInjectedObject.java:7)
> Actually, there were zero interactions with this mock.
> 	at test.ParameterizedInjectedObject.init(ParameterizedInjectedObject.java:7)
> 	at test.EntryPointTest.testInit(EntryPointTest.java:23)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:55)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
> 	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100)
> 	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107)
> 	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41)
> 	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)

### My analyzis
When I downgrade to version 5.2.0 I'm facing this issue : https://github.com/mockito/mockito/issues/2958
The fix for this one, introduced in version 5.3.0, doesn't seem to handle my case.

I tried to debug Mockito and I think there's a problem with TypeBasedCandidateFilter, starting at line 140 when AbstractGenericClass is analyzed to see if parameter Something is valid for the injection point.

Thanks for reading,

**Comment by philsttr** [comment]
I believe I'm running into this same problem.

Here's a small project ([mockito-parameterized-type-injection.zip](https://github.com/mockito/mockito/files/11645910/mockito-parameterized-type-injection.zip)) with a unit tests that fails to inject a mock with mockito 5.3.1.   The test works with mockito 5.1.1, so something regressed after 5.1.1

**Comment by LordMaduz** [comment]
I also experienced the same issue today with the mockito version 5.8.0.
Interestingly, when I downgrade version back to 5.1.1 it works fine.

**Comment by melloware** [comment]
+1
