### ISSUE TITLE
org.mockito.exceptions.base.MockitoException:  Mockito cannot mock this class:

### ISSUE THREAD

**Issue by Asrivast1** [mockito/mockito#3048]
My Project has the following dependencies -:

- implementation **'org.mockito:mockito-core:5.4.0'**
- implementation **'org.mockito:mockito-inline:5.2.0'**
- implementation **'net.bytebuddy:byte-buddy:1.14.5'**
- implementation **'net.bytebuddy:byte-buddy-agent:1.14.5'**
- implementation **'org.objenesis:objenesis:3.3'**
- implementation **'org.objenesis:objenesis-test:3.3'**

**Spring 5.3.20**

This is the line that's throwing the error - 
_try (MockedStatic<ServiceLocator> locatorMockedStatic = Mockito.mockStatic(ServiceLocator.class)){_

I even tried Invalidating the Cache and restarting but am still facing the error "Mockito cannot mock this class"

Stacktrace -;

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.org.locator.ServiceLocator.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 17
JVM vendor name    : Oracle Corporation
JVM vendor version : 17.0.6+9-LTS-190
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 17.0.6+9-LTS-190
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:285)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:174)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:376)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
	at org.mockito.Mockito.mock(Mockito.java:2087)
	at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:76)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:28)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:25)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:44)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:72)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:73)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:47)
	at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:81)
	... 47 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:184)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:166)
	at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:152)
	at net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:82)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3390)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1930)
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:207)
	at net.bytebuddy.dynamic.scaffold.inline.AbstractInliningDynamicTypeBuilder.make(AbstractInliningDynamicTypeBuilder.java:116)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3397)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:402)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	... 69 more
```
>Thanks
>Asrivast

**Comment by JintaoXIAO** [comment]
you'd better to paste the content of "com.org.locator.ServiceLocator"

**Comment by khmarbaise** [comment]
Given the deps you have written:
```
implementation 'org.mockito:mockito-core:5.4.0'
implementation 'org.mockito:mockito-inline:5.2.0'
implementation 'net.bytebuddy:byte-buddy:1.14.5'
...
```

shows that you are mixing different mockito-versions... 5.4.0 and 5.2.0 (via mockito-inline)... starting with Mockito 5.3.0 no project for mockito-inline existed anymore and it is not needed anymore...(already before since 5.0.0 If I correctly remember)... So best is to define the deps via the BOM:

```xml
      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-bom</artifactId>
        <version>5.4.0</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
```
which defines all needed artifacts with their appropriate correct versions.. including byte-buddy etc. 
That means the dependency to mockito-inline can simply being removed...

**Comment by Asrivast1** [comment]
As it turns out, there was an additional bundled library in the project positioned ahead of our library in the sequence. This library contained an older version of byte-buddy, which was the cause of the problem with the class file's major version. The issue was resolved by updating byte-buddy to align with our version as that version was being picked. I'd like to express my gratitude to @raphw for identifying the root cause of the problem. I also took note of your comment @khmarbaise , and removed the unnecessary duplicate libraries from the project. Thank you.

**Comment by dekhrhaVinod** [comment]
Hi @Asrivast1 
could you please explain the procedure on how to remove the additional bundled library from the project and version issues of byte -buddy .

**Comment by akumar10-chwy** [comment]
I also facing this issue, how did u resolve this error. I am upgrading from gradle 7.3 to 8.7 and using below -
 testImplementation group: 'org.mockito', name: 'mockito-core', version: '5.4.0'
    testImplementation group: 'org.mockito', name: 'mockito-junit-jupiter', version: '5.4.0'
    testImplementation group: 'org.mockito', name: 'mockito-inline', version: '5.1.0'

**Comment by akumar10-chwy** [comment]
org.mockito:mockito-core:4.5.1 -> 5.4.0
|    |    +--- net.bytebuddy:byte-buddy:1.14.5 -> 1.12.23
|    |    \--- net.bytebuddy:byte-buddy-agent:1.14.5 -> 1.12.23
