### ISSUE TITLE
org.mockito.exceptions.verification.TooManyActualInvocations print confused message

### ISSUE THREAD

**Issue by thachlp** [mockito/mockito#3057]
Here my example to reproduce the message: 

```public class EmployeeService {
    private final EmployeeRepository employeeRepository;

    public void persistAll(List<Employee> employees) {
        employees.forEach(employee -> {
        .
        .
        .
        .
        employeeRepository.save(employee);
        });
    }
}
```

Testing using verify:
```
    @Test
    void persist() {
        final Employee employee1 = Employee.builder()
                .name("Jack")
                .build();
        final Employee employee2 = Employee.builder()
                .name("Kevin")
                .build();
        employeeService.persistAll(List.of(employee1, employee2));
        verify(employeeRepository).save(employee1);
        verify(employeeRepository).save(employee2);
    }
```

```
org.mockito.exceptions.verification.TooManyActualInvocations: 
employeeRepository.save(
    Employee(id=null, name=Jack, role=null)
);
Wanted 1 time:
-> at ....service.EmployeeServiceTest.persist(EmployeeServiceTest.java:32)
But was 2 times:
-> at ....EmployeeService.lambda$persistAll$0(EmployeeService.java:16)
-> at ....service.EmployeeService.lambda$persistAll$0(EmployeeService.java:16)
```

If I consider Employee object different by id, which means employee1 and employee2 are equal (id = null)
So why is it required this:
```
 verify(employeeRepository, times(2)).save(employee1);
 verify(employeeRepository, times(2)).save(employee2);
```
If I understand, because employee1 is equal to employee2 so we expected `employeeRepository.save(employee1)` to be called 2 times, why `employeeRepository.save(employee2)` also 2?

**Comment by TimvdLippe** [comment]
Mockito uses the `eq` matcher by default if you don't specify one. Since your IDs are different and your equals method checks for that, it reports the difference. If you would like to ensure it is this exact instance to match on, either set the ID as you mentioned, or use `same()`.

**Comment by thachlp** [comment]
Thanks for replying to me.
