### ISSUE TITLE
ArgumentCaptor not working with varargs in version 5.4.0

### ISSUE THREAD

**Issue by olliegator** [mockito/mockito#3065]
Hi,

I've upgraded to version 5.4.0, but the ArgumentCaptor stopped working for mocks with varargs.

The test class below works for a single argument but fails for varargs with the message:

```
Argument(s) are different! Wanted:
mock.varargs(<Capturing argument: String>);
-> at org.example.mockito.VarArgsTest$MockedClass.varargs(VarArgsTest.java:38)
Actual invocations have different arguments:
mock.varargs("a", "b", "c");
-> at org.example.mockito.VarArgsTest.testVargs(VarArgsTest.java:23)
```

Code:

```
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.mockito.Mockito.verify;

@ExtendWith(MockitoExtension.class)
class VarArgsTest {

    @Mock
    MockedClass mock;

    @Captor
    ArgumentCaptor<String> captor;

    @Test
    void testVargs() {
        mock.varargs("a", "b", "c");

        verify(mock).varargs(captor.capture());
    }

    @Test
    void testSingleArg() {
        mock.singleArg("a");

        verify(mock).singleArg(captor.capture());
    }

    static class MockedClass {

        public void varargs(String... args) {
        }

        public void singleArg(String arg) {
        }
    }
}
```

**Comment by TimvdLippe** [comment]
This is mentioned as breaking change in https://github.com/mockito/mockito/releases/tag/v5.0.0

> In a similar fashion, the behavior of ArgumentCaptor.forClass has changed as well.
If you want to capture all arguments, use an ArgumentCaptor for String[], otherwise String
