### ISSUE TITLE
Mockito.mockStatic()+Mockito.any() with throw java.lang.IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by xiao02wei** [mockito/mockito#3089]
I have java code like this
```
public static String test1(String[] arrayA, String b){
    return null;
}
```
and I want to use mockito to test like this
```
MockedStatic<ClassC> c = Mockito.mockStatic(ClassC)
c.when(ClassC.test1(Mockito.any(), Mockito.any())).then{"test ok"}
```
run test with result:
```
Expected exception of type 'XxxException', but got 'java.lang.IllegalArgumentException'
	at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:84)
	at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:71)
	at xxx.ClassC:test1(Xxx.groovy:xxx)
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
	at xxx.ClassC:test1(Xxx.groovy:{rowNumber->Mockito.any()})
```

if I reduce 2* Mockito.any() to 1* , and with result:
```
Caused by: groovy.lang.MissingMethodException: No signature of method: static xxx.ClassC.test1 is applicable for argument types: (null) values: [null]
Possible solutions: test1([Ljava.lang.String;, java.lang.String)
```

my environment
JDK1.8.0_301
intelij idea 2023.2
mockito-core+mockito-inline/3.12.4
groovy 4.0.6

any help?
thanks

**Comment by xiao02wei** [comment]
maybe, I got error usage, and finally I fix code like this
```
MockedStatic<ClassC> c = Mockito.mockStatic(ClassC)
Mockito.when(ClassC.test1(Mockito.any(), Mockito.any())).then{"test ok"}
```
**(c -> Mockito)**
and move this code to

> def setup(){}
--setup() as @Before in Java

thus, everything is ok
