### ISSUE TITLE
Records: First mock of record with annotated parameter fails

### ISSUE THREAD

**Issue by infeo** [mockito/mockito#3107]
## Description
Mocking a record with an annotated parameter fails the first time `Mockito.mock()`is called. If the parameter ordering is changed, mocking succeeds.

## Setup
JVM:
```
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)
```
Mockito: 5.5.0
OS: 
```
Edition: Windows 11 Pro N
Version: 22H2
OS build: 22621.2134
Experience: Windows Feature Experience Pack 1000.22659.1000.0
```
## Example
Requires Junit.
```java
class TestMockito {

	@interface MyAnnotation{};

	public record RecordA(@MyAnnotation Object o, Object other) {}
	public record RecordB(Object o, Object other) {}
	public record RecordC(@MyAnnotation Object o) {}
	public record RecordD(Object other, @MyAnnotation Object o) {}
	
	@Test
	public void testA_1() {
		var test = Mockito.mock(RecordA.class);
	}
	@Test
	public void testA_2() {
		var test = Mockito.mock(RecordA.class);
	}
	@Test
	public void testB() {
		var test = Mockito.mock(RecordB.class);
	}
	@Test
	public void testC() {
		var test = Mockito.mock(RecordC.class);
	}
	@Test
	public void testD() {
		var test = Mockito.mock(RecordD.class);
	}
}
```

**Expected:** All Tests succeed
**Actual:** Test `A_1` fails with
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.cryptomator.frontend.fuse.ReadOnlyAdapterTest$RecordA.
Can not mock final classes with the following settings :
 - explicit serialization (e.g. withSettings().serializable())
 - extra interfaces (e.g. withSettings().extraInterfaces(...))

You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : java.lang.IllegalArgumentException: Could not create type

	at my.package@3.1.0-SNAPSHOT/my.package.TestMockito.testA_1(TestMockito.java:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:75)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:396)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:355)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:334)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
	at org.mockito.Mockito.mock(Mockito.java:2101)
	at org.mockito.Mockito.mock(Mockito.java:2016)
	... 4 more
Caused by: java.lang.ClassFormatError
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 16 more
```

check that
 
 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
@raphw Do we even want to support mocking of records? To me it seems better if we don't allow records to be mocked, as creating a fake record seems more appropriate.

**Comment by raphw** [comment]
Records can contain methods, I would not see why we would make an exception.

**Comment by raphw** [comment]
Must be something wrong with the type path of the first. Might even be in the JDK. I'll look into it!

**Comment by raphw** [comment]
Interesting enough, this simple line of code fails:

    Instrumentation inst ByteBuddyAgent.install();
    inst.retransformClasses(RecordA.class);

The second line causes the exception. It seems like the JVM does not like the annotations to begin with. The problem goes away if the annotation is marked as runtime retained.

**Comment by raphw** [comment]
Registered in OpenJDK: https://bugs.openjdk.org/browse/JDK-8315575

**Comment by smallufo** [comment]
I encountered the same problem even annotate one record's field @Nullable (`org.jetbrains.annotations.Nullable`) 
Mockito 5.7.0
After removing the annotation , every tests pass.

**Comment by infeo** [comment]
@raphw The JDK ticket got closed for being "not an issue". So are we back at mockito or bytebuddy?

**Comment by raphw** [comment]
It's incorrectly closed. We cannot do anything about it.

**Comment by dennishendriksen** [comment]
Ran into this issue as well, seems like a JDK fix is on the way, see https://bugs.openjdk.org/browse/JDK-8315575 and https://git.openjdk.org/jdk/pull/18161

**Comment by yvasyliev** [comment]
I'm experiencing this issue as well. It appears that https://github.com/openjdk/jdk/pull/18161 has been delivered.

Hey @raphw, any chance you could take another look at this? 🙏

**Comment by raphw** [comment]
Did you update to JDK 23+? I do not think this is backported.

**Comment by yvasyliev** [comment]
Okay, it's working in JDK 25, but fails in JDK 17

**Comment by raphw** [comment]
That is expected as of the missing backport. Closing this ticket.
