### ISSUE TITLE
Mockito failed to Mock Spring Components 

### ISSUE THREAD

**Issue by hantsy** [mockito/mockito#3119]
I tried to upgrade my Spring 6.x examples to Java 21, but there are some failure from Mockito like this.

```bash 
You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface org.springframework.data.jpa.repository.JpaRepository, interface org.spring
framework.data.repository.PagingAndSortingRepository, interface org.springframework.data.repository.ListCrudRepository, interface com.example.demo.domain.repository.PostRepositoryCusto
m, interface org.springframework.data.repository.ListPagingAndSortingRepository, interface org.springframework.data.querydsl.QuerydslPredicateExecutor, interface org.springframework.da
ta.repository.CrudRepository, interface org.springframework.data.jpa.repository.JpaSpecificationExecutor, interface com.example.demo.domain.repository.PostRepository, interface org.spr
ingframework.data.repository.Repository, interface org.springframework.data.repository.query.QueryByExampleExecutor]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650)
        ... 48 more
Caused by: org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: interface com.example.demo.domain.repository.PostRepository.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 21
JVM vendor name    : Oracle Corporation
JVM vendor version : 21+35-2513
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 21+35-2513
JVM info           : mixed mode, sharing
OS name            : Windows 10
OS version         : 10.0


```

**Comment by nathan-boyd** [comment]
had a similar issue while upgrading to java 21, enabling this byte buddy flag fixed it for me.

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <argLine>-Dnet.bytebuddy.experimental=true</argLine>
    </configuration>
</plugin>
```

**Comment by hantsy** [comment]
I added a new version of `bytebuddy` explicitly in project POM file to fix this issue, the newest bytebuddy has already supported Java 21.

**Comment by hantsy** [comment]
Mokito should upgrade the dependent bytebuddy to get Java 21 support.

**Comment by AlexanderGunnarssonMW** [comment]
I had the same problem but it disappeared with the latest mockito version (5.10.0) which includes the latest bytebuddy (1.14.11) so this issue can be closed.
