### ISSUE TITLE
Mockito doesn't initialise static constructors before instrumentation correctly

### ISSUE THREAD

**Issue by ascopes** [mockito/mockito#3156]
# Issue

I seem to have run into a little issue that I assume is not expected behaviour when creating static mocks of a class via the JUnit Jupiter extension.

```java
import org.apache.commons.lang3.SystemUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Answers;
import org.mockito.Mock;
import org.mockito.MockedStatic;
import org.mockito.junit.jupiter.MockitoExtension;

class PathProtocResolverTest {
  @Mock(answer = Answers.RETURNS_SMART_NULLS)
  MockedStatic<SystemUtils> systemUtilsMock;
  
  @Test
  void undefinedPathThrowsException() {}
}
```

Upon running this, I get the following exception:

```log
org.mockito.exceptions.base.MockitoException: Cannot instrument class org.apache.commons.lang3.SystemUtils because it or one of its supertypes could not be initialized

	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:159)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	Suppressed: java.lang.NullPointerException
		at org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:190)
		... 2 more
Caused by: java.lang.NumberFormatException: empty String
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:455)
	at org.apache.commons.lang3.JavaVersion.get(JavaVersion.java:304)
	at org.apache.commons.lang3.SystemUtils.<clinit>(SystemUtils.java:407)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.assureInitialization(InlineBytecodeGenerator.java:236)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:254)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClassStatic(InlineBytecodeGenerator.java:226)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClassStatic(TypeCachingBytecodeGenerator.java:108)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createStaticMock(InlineDelegateByteBuddyMockMaker.java:566)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createStaticMock(InlineByteBuddyMockMaker.java:83)
	at org.mockito.internal.util.MockUtil.createStaticMock(MockUtil.java:202)
	at org.mockito.internal.MockitoCore.mockStatic(MockitoCore.java:134)
	at org.mockito.Mockito.mockStatic(Mockito.java:2325)
	at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:69)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:28)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:25)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:44)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:72)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:62)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:47)
	at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:81)
	at org.mockito.internal.framework.DefaultMockitoSession.<init>(DefaultMockitoSession.java:43)
	at org.mockito.internal.session.DefaultMockitoSessionBuilder.startMocking(DefaultMockitoSessionBuilder.java:83)
	... 3 more
```

# Workaround

It appears that Mockito (well, ByteBuddy I guess) is not ensuring that the class being referenced in a MockedStatic is loaded into memory and initialised prior to the tests running (instead relying on implicit side effects to ensure that). I believe this is the case because if I add this block to my test class, then everything passes.

```java
  static {
    // Do some dummy call to eagerly load the class before Mocktio runs.
    SystemUtils.getHostName();
  }
```

My (albeit very ignorant) guess is that this is to do with the static constructor of the class referencing other static fields after the class has been mocked (and thus discarded the private-scope static fields in the bytecode proxy).

It is also worth noting the class has to be fully loaded first. Loading the class descriptor only does *not* resolve this issue: the following still allows the test to fail:

```java
  static {
    // Do some dummy call to eagerly load the class before Mocktio runs.
    assert SystemUtils.class != null;
  }
```

# Platform details

- `org.apache.commons/commons-lang3/3.13.0`
- `org.mocktio/mockito-junit-jupiter/5.6.0`
- `org.junit.jupiter/junit-jupiter/5.10.0`

```console
$ java -version
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Corretto-19.0.1.10.1 (build 19.0.1+10-FR)
OpenJDK 64-Bit Server VM Corretto-19.0.1.10.1 (build 19.0.1+10-FR, mixed mode, sharing)

$ uname -oipmsrv
Linux 6.5.6-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:02:35 UTC 2023 x86_64 unknown unknown GNU/Linux
```

Since IntelliJ IDEA messes with some of the classpath in odd ways sometimes, I replicated this in IntelliJ IDEA with the following version. Doubt this is overly relevant but I thought I'd include it _just in case_.

```
IntelliJ IDEA 2023.2.3 (Community Edition)
Build #IC-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.6-200.fc38.x86_64
GC: ZGC Cycles, ZGC Pauses
Memory: 2048M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    idea.plugin.protoeditor (232.9559.10)
    com.jetbrains.space (232.10072.29)

Kotlin: 232-1.9.0-IJ10072.27
Current Desktop: GNOME
```

**Comment by u7498708** [comment]
Hi there, first time contributor here! Wondering if this is something that I could possibly have a go at trying to solve? Let me know!

**Comment by u7498708** [comment]
So am I understanding this that the MockedStatic method runs too quickly and doesn't let SystemUtils initialise properly. I could be wrong but if there is a wait() or notify() call in the MockedStatic to wait for systemutils to finish would that work? Or is there something flawed in that logic? Thanks

**Comment by ascopes** [comment]
I think so. It seems to be triggered without static constructors as well as I was able to replicate it on a class that doesn't use static constructors.

It appears to be just invoking methods before classloading occurs.

**Comment by u7498708** [comment]
So what I can see of other implementations of the MockedStatic<T> method is that is used in a try() call, where it makes the mocked static call to the class and when it returns any string it returns that. Could this be a possible solution to your issue?

For reference I have got it from [diffblue](https://docs.diffblue.com/features/cover-cli/mock-static) where they explain how to use it to get the class from the Currency class.

`  @Test
  public void testCurrency() {
    Currency usd = Currency.getInstance("USD");
    try (MockedStatic<Currency> mockedStatic = mockStatic(Currency.class)) {
      mockedStatic.when(() -> Currency.getInstance(anyString())).thenReturn(usd);

      Currency eur = Currency.getInstance("EUR");
      assertEquals("USD", eur.getCurrencyCode());
      mockedStatic.verify(() -> Currency.getInstance(anyString()));
    }
  }`
  
This may not be what you are looking for but I think it could possibly be something that might aid with your issue? Or is it that the method MockedStatic should be able to support what you are trying to do?

**Comment by ascopes** [comment]
@u7498708 yeah that is one workaround that will work for sure. Definitely a lifecycle issue somewhere!

**Comment by u7498708** [comment]
@TimvdLippe Sorry to mention you, but I was wondering if there is anything else that I can do for this issue. Whether the workaround works but if it should be fixed in code level too so the workaround is not needed? or is this intended design to use a try() statement? Thanks and hope to hear back soon! :)

**Comment by TimvdLippe** [comment]
`MockedStatic` is indeed marked as auto-closeable and therefore we only officially support it if you explicitly open and close it. Therefore, you need to use it with try-with-resources. Typically, assigning to a field can lead to unspecified behavior, as the scope of the mockedstatic escapes the test method itself. Therefore, I think the workaround is actually the supported use case and therefore the proper solution imo.

**Comment by TimvdLippe** [comment]
If we can detect this case, then yes. But let's not hardcode any assumptions in this detection.

**Comment by u7498708** [comment]
Is there any code that I can do to generally just check if Junit is being called and perhaps relay a new exception to the user about trying it with the try() method instead of the issue here? I am just wondering because if I can check for junit being used and this error comes up where something doesn't work because it is given an empty string, I can tell the user/programmer what is happening and a potential solution via an exception thrown. Thoughts on this?

**Comment by ascopes** [comment]
In this case, I would guess it would need a change to MockitoException, in whatever internal mechanism parses the fields in the class and detects the annotations.

Anything annotated with `@Mock` that has the raw type `MockedStatic` or `MockedConstruction` would then result in an exception.

I'd possibly err on the side of caution though, as this would technically be a breaking change (I know that I have projects where I have definitely done this in the past which would break as part of this).

A better immediate solution may be to consider the behaviour to be deprecated and emit some kind of warning about it without halting test execution. Then in Mockito 6.x, change it to raise an exception. That way minor version upgrades do not immediately impact consumers without prior warning.

This'd also include updating any existing documentation to advise against doing this.

**Comment by TimvdLippe** [comment]
Rather than runtime checks, we can implement an ErrorProne static analysis check that does the same. We have a subproject with existing checks.

**Comment by ascopes** [comment]
> ErrorProne check

Sounds reasonable. I assume the docs for MocktioExtension would also need updating for this? E.g. I don't use ErrorProne in my builds at the moment, so it could be quite easy to miss this.

**Comment by u7498708** [comment]
Sounds good, I was wondering if I am looking at the right files here and was wondering if I could get some clarification on if I were to modify existing ones of make a new test if we needed it? I am still a first time contributor to this and I haven't used errorprone before so help would be great!

I am looking under subprojects/errorprone/src/main/java/org.mockito.errorprone/bugpatterns/

- AbstractMockitoAnyForPrimitiveType
- MockitoAnyClassWithPrimitiveType
- MockitoAnyIncorrectPrimitiveType
- MockitoInternalUsage
- MockitoNotExtensible

I was wondering if I would make a new file with similiar structure to one of them or modify one of the existing ones, and if it would need to be adapted into the mockitoExtension to then be used, as ascopes was mentioning. Thanks! Let me know if I can do anything even it is a little bit! I will be happy to help!

**Comment by TimvdLippe** [comment]
You should create a new file that implements a check that ensures that if a `MockedStatic` field or parameter is annotated with `@Mock`, that it fails the compilation. I think `MockitoNotExtensible` is your best source for inspiration. You can use the corresponding tests to know you implemented it correctly.

**Comment by u7498708** [comment]
Awesome I will have a start on it! I will let you know if I need anything else, thanks for the speedy reply!

**Comment by u7498708** [comment]
I have come up with some basic code that I think could possibly be a step in the right direction. I have tried my best to get them to what I think is a good code structure but let me know what I could do to make it work a bit better. The tests run, but don't pass properly, so if anyone can see what is wrong with it let me know!

```
/*
 * Copyright (c) 2017 Mockito contributors
 * This program is made available under the terms of the MIT License.
 */
package org.mockito.errorprone.bugpatterns;

import com.google.auto.service.AutoService;
import com.google.errorprone.BugPattern;
import com.google.errorprone.BugPattern.SeverityLevel;
import com.google.errorprone.VisitorState;
import com.google.errorprone.bugpatterns.BugChecker;
import com.google.errorprone.bugpatterns.BugChecker.VariableTreeMatcher;
import com.google.errorprone.matchers.Description;
import com.sun.source.tree.VariableTree;

@AutoService(BugChecker.class)
@BugPattern(
        name = "MockitoMockedStatic",
        summary = "Fields or parameters annotated with @Mock in MockedStatic can lead to compilation issues.",
        explanation = "Fields or parameters annotated with @Mock in MockedStatic can lead to compilation issues.",
        severity = SeverityLevel.ERROR)
public class MockitoMockedStatic extends BugChecker implements VariableTreeMatcher {

  @Override
  public Description matchVariable(VariableTree tree, VisitorState state) {
    if (tree.getModifiers().getAnnotations().stream()
            .anyMatch(annotation ->
                    state.getSourceForNode(annotation).equals("@org.mockito.Mock")
                            && state.getSourceForNode(tree.getType()).equals("org.mockito.MockedStatic"))) {
      return describeMatch(tree);
    }

    return Description.NO_MATCH;
  }
}
```

```
/*
 * Copyright (c) 2017 Mockito contributors
 * This program is made available under the terms of the MIT License.
 */
package org.mockito.errorprone.bugpatterns;

import com.google.errorprone.CompilationTestHelper;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class MockitoMockedStaticTest {

    private CompilationTestHelper compilationTestHelper;

    @Before
    public void setup() {
        compilationTestHelper =
            CompilationTestHelper.newInstance(MockitoMockedStatic.class, getClass());
    }

    @Test
    public void mockedStaticWithMockField_shouldError() {
        compilationTestHelper
            .addSourceLines(
                "input.java",
                "import org.mockito.Mock;",
                "import org.mockito.MockedStatic;",
                "class Test {",
                "  @Mock",
                "  private Object mock;",
                "  public void test() {",
                "    try (MockedStatic<Object> mockedStatic = Mockito.mockStatic(Object.class)) {",
                "      // Do something with the mock",
                "    }",
                "  }",
                "}")
            .doTest();
    }

    @Test
    public void mockedStaticWithMockParameter_shouldError() {
        compilationTestHelper
            .addSourceLines(
                "input.java",
                "import org.mockito.Mock;",
                "import org.mockito.MockedStatic;",
                "class Test {",
                "  public void test(@Mock Object mock) {",
                "    try (MockedStatic<Object> mockedStatic = Mockito.mockStatic(Object.class)) {",
                "      // Do something with the mock",
                "    }",
                "  }",
                "}")
            .doTest();
    }

    @Test
    public void mockedStaticWithoutMock_shouldNotError() {
        compilationTestHelper
            .addSourceLines(
                "input.java",
                "import org.mockito.MockedStatic;",
                "class Test {",
                "  public void test() {",
                "    try (MockedStatic<Object> mockedStatic = Mockito.mockStatic(Object.class)) {",
                "      // Do something without a mock",
                "    }",
                "  }",
                "}")
            .doTest();
    }
}
```

These are in the same directories as the NotExtensible versions.

subprojects/errorprone/src/main/java/org.mockito.errorprone/bugpatterns/

**Comment by ascopes** [comment]
Should this cover MockedConstruction as well? I assume this'd have similar semantics?

**Comment by TimvdLippe** [comment]
Please put it in a pull request so that it is easier for us to comment on the code

**Comment by u7498708** [comment]
sure I can, for reference is it to a branch?

**Comment by u7498708** [comment]
I was also working on a fork in case, should I do it on main repo?

**Comment by ascopes** [comment]
You'd fork this repo, make an appropriately named branch on that fork, then push that branch to your GitHub. Once ready, you can go to the pull request page and it should give you the option to raise it against master/main on the original repo you forked from.

You wouldn't have access to push to the main repo (mockito/mockito) directly unless you were an authorized maintainer on this project

**Comment by u7498708** [comment]
Alrighty, created a pull request! Let me know what I need to do!

**Comment by ascopes** [comment]
Just a thought, but in Mockito 6.0.0, should this kind of usage become an error to prevent users who do not use ErrorProne from continuing to use this?
