### ISSUE TITLE
Cannot mock class `ServerHttpSecurity` with Spring Security 6.2.0

### ISSUE THREAD

**Issue by thombergs** [mockito/mockito#3205]
Hey.

After upgrading my Spring Boot app to Spring Boot 3.2.0 (which implies Spring Security 6.2.0), I'm getting the below error message when trying to mock the class `ServerHttpSecurity` via `Mockito.mock(ServerHttpSecurity.class)`.

I created a reproducer at https://github.com/thombergs/mockito-reproducer:
- run the test `SecurityTest` on the `main` branch and you will get the below error
- run the same test in the `success` branch and there will not be an error
- the only difference between the `main` and `success` branches is the version number of Spring Boot (and thus the version of Spring Security, where the class `ServerHttpSecurity` comes from).

[This](https://github.com/spring-projects/spring-security/blob/fd1b92b7d06af8fbaf71d9cdd54e219ac247ef51/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java) is the `ServerHttpSecurity` class in Spring Security 6.2.0 (the version that can't be mocked - failing with the error message below). 

[This](https://github.com/spring-projects/spring-security/blob/52e646e0cfc7b3350b95bfde2a54f9d474e48f4c/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java) is the`ServerHttpSecurity` class in Spring Security 6.1.5 (the version that could successfully be mocked before). 

Full error message:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.springframework.security.config.web.server.ServerHttpSecurity.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 18
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 18+36
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 18+36
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 13.5.2


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class org.springframework.security.config.web.server.ServerHttpSecurity]

	at com.example.demo.SecurityTest.test(SecurityTest.java:11)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class org.springframework.security.config.web.server.ServerHttpSecurity]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	... 4 more
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost, NestMembers, Record, or PermittedSubclasses attribute
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:75)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:412)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:371)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:350)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:88)
	at org.mockito.Mockito.mock(Mockito.java:2101)
	at org.mockito.Mockito.mock(Mockito.java:2016)
	... 4 more
```

**Comment by de313e** [comment]
Having the same issues, did you find a solution yet?

**Comment by thombergs** [comment]
No. My solution was to `@Disable` the affected test 😬

**Comment by kpentchev** [comment]
Had the same problem. Since the affected test was not really doing any mocking, I changed the instantiation of the variable to:
```
private var security =  ServerHttpSecurity.http()
```

**Comment by ezarko** [comment]
subscribe

**Comment by de313e** [comment]
subscrubed

**Comment by lyang3-atlassian** [comment]
Seeing the same issue

**Comment by datagitlies** [comment]
**WORKAROUND:**

```java
ServerHttpSecurity mock = Mockito.mock(ServerHttpSecurity.class, Mockito.withSettings().mockMaker(MockMakers.SUBCLASS));
```
