### ISSUE TITLE
2.0.31-beta Incompatible with Byte Buddy 0.7.3

### ISSUE THREAD

**Issue by nathansgreen** [mockito/mockito#322]
Just by calling `Mockito.mock(MyInterface.class)`, I get the following stack trace when using `2.0.31-beta` in my project that uses Byte Buddy `0.7.3`.

```
java.lang.NoClassDefFoundError: net/bytebuddy/dynamic/ModifierResolver

	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.<init>(CachingMockBytecodeGenerator.java:20)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:33)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44)
	at org.mockito.Mockito.<clinit>(Mockito.java:1101)
. . .
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.dynamic.ModifierResolver
```

**Comment by raphw** [comment]
The current master has the Byte Buddy update incorporated but the Mockito betas are no longer published. Once new betas are build, you would only need to use the latest beta.

**Comment by szczepiq** [comment]
Thanks for reporting. I'll look into the publication issue!

On Wed, Dec 2, 2015 at 10:03 AM, Rafael Winterhalter <
notifications@github.com> wrote:

> The current master has the Byte Buddy update incorporated but the Mockito
> betas are no longer published. Once new betas are build, you would only
> need to use the latest beta.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mockito/mockito/issues/322#issuecomment-161382490>.
>



-- 
Szczepan Faber
Founder mockito.org; Core dev gradle.org
tweets as @szczepiq; blogs at blog.mockito.org
