### ISSUE TITLE
`mockStatic` fails with `class redefinition failed: invalid class`

### ISSUE THREAD

**Issue by scordio** [mockito/mockito#3273]
Mockito message in the stack trace:

```
java.lang.InternalError: class redefinition failed: invalid class

	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClassStatic(InlineBytecodeGenerator.java:226)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClassStatic(TypeCachingBytecodeGenerator.java:108)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createStaticMock(InlineDelegateByteBuddyMockMaker.java:592)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createStaticMock(InlineByteBuddyMockMaker.java:83)
	at org.mockito.internal.util.MockUtil.createStaticMock(MockUtil.java:202)
	at org.mockito.internal.MockitoCore.mockStatic(MockitoCore.java:134)
	at org.mockito.Mockito.mockStatic(Mockito.java:2328)
	at org.mockito.Mockito.mockStatic(Mockito.java:2265)
	at <line of try block in test method>
```

The problematic class belongs to the Thales [JCPROV](https://thalesdocs.com/gphsm/luna/7/docs/network/Content/sdk/java/jcprov.htm) library which is unfortunately not available on Maven Central so I cannot compose a reproducer.

However, I can describe its characteristics:

* Public, top level and non-final
* With a default constructor that is private and does nothing
* With public methods that are all static and native
* With a static initialization block that loads a native library via `System.loadLibrary`

As the native library is not available during test execution (and I cannot make it available), I would guess that the failure in the static block triggers the exception above. However, I don't know how to prove it.

Is there anything I could do to properly mock such a class? Otherwise, do you see any possible improvements in Mockito for these cases?

Please, let me know in case I could grab additional details to help the analysis.

The issue happens on Mockito 5.10.0 and OpenJDK 11.0.12.

**Comment by jkim323** [comment]
Although I am unfamiliar to the the Thales JCPROV library, I am a bit curious on this issue. I am wondering if you have tried checking if your class is missing in your class path by simply trying to use the static method before mocking it because this has happened to me once before. But based on your issue since you are work involves with native code maybe mocking the native methods is not the best route because I have heard of challenges on doing this. Have you tried exploring doing something like encapsulating it in a wrapper class or in an interface?

**Comment by scordio** [comment]
Yes, the library is in the classpath: if I call one of the methods without mocking, it fails in the static initialization block with a missing native library error, as expected.

Also yes, wrapping works fine as a workaround. In addition, there is another class (still part of the library) that offers similar static methods, wrapping each native call with exception throwing in case of errors, and mocking this class works as expected.

**Comment by jkim323** [comment]
Interesting. Does the other successful class also share the same characteristics as the class you are having problems with or are there differences? I am wondering if two classes share the last bullet you mentioned in the post.

**Comment by scordio** [comment]
No, they are not the same. The successful one:

* Is also public, top level and non-final
* Has also default constructor that is private and does nothing
* Has public methods that are all static but **not native**
* Has **no static initialization block** (i.e., no load of a native library)

Imagine something like:

```java
class NativeClass {

  private NativeClass() {}

  public static native int method();

  static {
    System.loadLibrary("native");
  }

}

class WrapperClass {

  private WrapperClass() {}

  public static int method() {
    int result = NativeClass.method();
    if (result != 0) throw new RuntimeException(result);
  }

}
```

(wrote without checking the original code – beware of typos 🙂 )

**Comment by jkim323** [comment]
That makes sense because it seems like a common known issue that Mockito is unable to mock native methods; it is currently a limitation on Mockito as of now. Perhaps you can try PowerMock as an alternative solution but I am not aware of a definitive solution.. unless we develop on this maybe creating a discussion on this topic might help.

**Comment by mamingcong** [comment]
if you use slf4j, you can try to upgrade your version of slf4j-api , I was fixed by this way:
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.13</version>
        </dependency>

**Comment by scordio** [comment]
@mamingcong I don't see how this is related to slf4j

**Comment by mamingcong** [comment]
for me , the error was caused by this line, maybe it is different from your case
`private static final Logger LOG = LoggerFactory.getLogger(A.class);`

**Comment by AndreasTu** [comment]
This issue has maybe the same cause as #3498, where Mockito swallows the root cause `Error` of the Class static initializer.
 
>With a static initialization block that loads a native library via System.loadLibrary

The PR #3499 would change Mockito to report such errors.

@scordio Could you check if you have the same root cause.
You can do that, by calling the follwoing code before the Mock creation:

```java
Class.forName(yourClass.getName(), true, yourClass.getClassLoader());
``` 
If this throws an `Error` , which is not an `ExceptionInInitializerError`, then it is the same issue as #3498 and you need to fix whatever the `Error` had reported.

**Comment by scordio** [comment]
Thanks, @AndreasTu!

I'll need a few days to return to the affected project, and then I'll try your suggestion.
