### ISSUE TITLE
AdditionalMatchers.and() and or() swap matcher order

### ISSUE THREAD

**Issue by DidierLoiseau** [mockito/mockito#3331]
Consider the following code:

```java
@ExtendWith(MockitoExtension.class)
public class MockitoTest {
  @Mock MyService myService;

  @Test
  public void test() {
    Mockito.when(
            myService.doSomething(
                and(any(MyPojo.class),
                    argThat(p -> p.id == 1))))
        .thenReturn(1);

    myService.doSomething("hello");
  }

  interface MyService {
    int doSomething(Object pojo);
  }

  static class MyPojo {
    int id = 1;
  }
}

```

This test throws the following exception:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class MockitoTest$MyPojo (java.lang.String is in module java.base of loader 'bootstrap'; MockitoTest$MyPojo is in unnamed module of loader 'app')
	at org.mockito.internal.matchers.And.matches(And.java:23)
	at org.mockito.internal.invocation.TypeSafeMatching.apply(TypeSafeMatching.java:35)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.argsMatch(MatcherApplicationStrategy.java:85)
	at org.mockito.internal.invocation.MatcherApplicationStrategy.forEachMatcherAndArgument(MatcherApplicationStrategy.java:71)
	at org.mockito.internal.invocation.InvocationMatcher.argumentsMatch(InvocationMatcher.java:156)
	at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:82)
	at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:92)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:56)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:161)
	at MockitoTest$MyService$MockitoMock$v3DeXXsQ.doSomething(Unknown Source)
	at MockitoTest.test(MockitoTest.java:23)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

Debugger inspection of [`And.matches()`](https://github.com/mockito/mockito/blob/fb9ff6d40442ea98c8c3f8bc9fffbe253bd8df7b/src/main/java/org/mockito/internal/matchers/And.java#L22) shows that `m1` is the lambda and `m2` is the `InstanceOf`, as opposed to what was passed to `and()`. I guess this comes from [`ArgumentMatcherStorageImpl#reportAnd()` and `reportOr()`](https://github.com/mockito/mockito/blob/fb9ff6d40442ea98c8c3f8bc9fffbe253bd8df7b/src/main/java/org/mockito/internal/progress/ArgumentMatcherStorageImpl.java#L42-L59) which pop `m1` before `m2`, swapping the order.

This is with Mockito 5.11.0, Junit 5.10.2 and Java 11.

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
    _No, it does not provide useful information (here the exception is similar to the one in #2268 but it could be something else like an NPE, depending on the use case)_
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by TimvdLippe** [comment]
Yes this appears to be a legitimate bug, good catch! Feel free to submit a pull request with a fix and a regression test for it!

**Comment by dev-jonghoonpark** [comment]
can i try contribute?

**Comment by TimvdLippe** [comment]
@dev-jonghoonpark feel free to submit a pull request!

**Comment by DidierLoiseau** [comment]
> I think it's correct that I'm getting an UnnecessaryStubbingException because I didn't enter the expected input. (Passed "hello", not any(MyPojo.class))
> However, something feels like the result is not clear.

I think this is normal, I didn’t write the MRE such that the mock would actually be used, but you could simply add a second call with a parameter that matches the mock, e.g.

    myService.doSomething(new MyPojo());
