### ISSUE TITLE
verify can't differ/handle logging methods with "Object... arguments" in signature

### ISSUE THREAD

**Issue by fourhundredfortyfour** [mockito/mockito#3343]
Test code should verify twice the call log.error() with identical parameters, but it is blind for the second call to log.error().
Mockito prints identicals calls but behaves different.
Probably the parameter "Object... arguments" leads the jvm to a different method implementation for log.error() and mockito internally differes between them, but there is not interface in mockito to verify the second call different to the first call.

**Test code:**
```
  @Test
  void verifyBug() {
    org.slf4j.Logger log = mock(org.slf4j.Logger.class, withSettings().verboseLogging());

    log.error("Format {}", "param");
    callLogger(log, "Format {}", "param");

    verify(log, times(2)).error("Format {}", "param");
  }

  void callLogger(org.slf4j.Logger log, String format, Object... arguments) {
    log.error(format, arguments);
  }
```

**Mockito states:**
```
############ Logging method invocation #1 on mock/spy ########
logger.error("Format {}", "param");
   invoked: -> at com.eosts.logappender.AlertLoggerTest.verifyBug(AlertLoggerTest.java:65)
   has returned: "null"

############ Logging method invocation #2 on mock/spy ########
logger.error("Format {}", "param");
   invoked: -> at com.eosts.logappender.AlertLoggerTest.callLogger(AlertLoggerTest.java:71)
   has returned: "null"

############ Logging method invocation #3 on mock/spy ########
logger.error("Format {}", "param");
   invoked: -> at com.eosts.logappender.AlertLoggerTest.verifyBug(AlertLoggerTest.java:67)
   has thrown: class org.mockito.exceptions.verification.TooFewActualInvocations with message 
logger.error("Format {}", "param");
Wanted 2 times:
-> at com.eosts.logappender.AlertLoggerTest.verifyBug(AlertLoggerTest.java:67)
But was 1 time:
-> at com.eosts.logappender.AlertLoggerTest.verifyBug(AlertLoggerTest.java:65)
```

**Comment by margussipria** [comment]
Found this same thing, upgraded to newest and still same problem.

Logger has signatures ```java
    public void error(String msg);
    public void error(String format, Object arg);
    public void error(String format, Object arg1, Object arg2);
    public void error(String format, Object... arguments);
```
Verify with 1 or 4 string arguments work, but fails to match with 2 or 3 arguments.
