### ISSUE TITLE
2.0.31-beta -> 2.0.32-beta Cannot mock RecyclerView.Adapter

### ISSUE THREAD

**Issue by jaydeep17** [mockito/mockito#335]
Using `2.0.31-beta` mocking a RecyclerView.Adapter is possible, but with `2.0.32-beta`, the below error is thrown.

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.jaydp.androidapp.SomeAdapter

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.util.NoSuchElementException

	at com.jaydp.androidapp.ExampleUnitTest.mockAdapter(ExampleUnitTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.util.NoSuchElementException
	at java.util.AbstractList$Itr.next(AbstractList.java:364)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:564)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:548)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:562)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:548)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:562)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:502)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:423)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:493)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:212)
	at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:58)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:55)
	at org.mockito.Mockito.mock(Mockito.java:1377)
	at org.mockito.Mockito.mock(Mockito.java:1290)
	... 28 more
```

Here's an example RecyclerView.Adapter class

```
import android.support.v7.widget.RecyclerView;
import android.view.ViewGroup;

public class SomeAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

  @Override public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
    return null;
  }

  @Override public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {

  }

  @Override public int getItemCount() {
    return 0;
  }
}

```

**Comment by raphw** [comment]
I will have a look at this at the end of this week but did you test a newer version of Mockito? There were some issues with the generic type resolution in an in-between version of Byte Buddy that was later fixed.

**Comment by jaydeep17** [comment]
Same error with `2.0.34-beta`

**Comment by raphw** [comment]
I just tried this out but I cannot reproduce the issue when using the latest Android SDK:

```java
public class SomeAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
  @Override public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
    return null;
  }

  @Override public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) { }

  @Override public int getItemCount() {
    return 0;
  }
}

@Test
public void testMethodGraph() throws Exception {
  MethodGraph.Compiler.Default.forJavaHierarchy().compile(new TypeDescription.ForLoadedType(SomeAdapter.class));
}
```

The only way I could see this happening would be a divergence of the length of the interfaces returned by `getGenericInterfaces` versus `getInterfaces` what is not allowed in Java, i.e. would be a bug in Android. Can you run the test on your machine and see if it fails?

**Comment by jaydeep17** [comment]
yes it fails.
BTW, I'm using Robolectric for testing. Does that mean it's a bug in Robolectric ??

But it used to work before `2.0.32-beta` :confused:

**Comment by raphw** [comment]
Does the equality assertion already fail? Meaning

```java
assertEquals(RecyclerView.Adapter.class.getInterfaces().length, RecyclerView.Adapter.class.getGenericInterfaces().length);
```

already fails? In this case, any tool processing generic type information will work incorrectly.

Before the release, Byte Buddy did not process generic type information. This made the library a lot simpler but had some heavy disadvantages, for example the target of bridge methods could not be determined reliably. Also, disregarding generic information will be a problematic when value types are introduced.

Newer versions of the library take generic types into consideration. In the future, I will look into ways of making the processing more robust when illegal generic types are found in a class file. It is however so little of an issue in practice that it is not on my list of current priorities.

It seems to me like Robolectric is creating illegal class files when mimicing the Android API for the framework. I would get in touch with them and ask them to fix their binaries. I assume that they break something in their compilation as the problem does not occure when using the official Android SDK.

**Comment by raphw** [comment]
Ok, never mind. I now already added the fallback. Testing is a bit tricky, I will do that after New Year's and hopefully push a new version some time next week.

**Comment by raphw** [comment]
@jaydeep17 Could you double-check that this problem does no longer occure with the latest beta?

**Comment by jaydeep17** [comment]
:+1: works perfectly!
