### ISSUE TITLE
Mockito 5.12.0 and Java 22

### ISSUE THREAD

**Issue by PavelTurk** [mockito/mockito#3354]
I am trying to do:

        MyInterface i = Mockito.mock(MyInterface.class);
        Mockito.when(i.getA()).thenReturn(new DefaultA());

And this is what I get:

```
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [interface com.foo.MyInterface]
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	... 5 more
Caused by: java.lang.IllegalStateException: 
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
 - Compiled by older versions of scalac
 - Classes that are part of the Android distribution
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:285)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy@1.14.7/net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:75)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:414)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:373)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:352)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito@5.12.0/org.mockito.internal.util.MockUtil.createMock(MockUtil.java:99)
	at org.mockito@5.12.0/org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
	at org.mockito@5.12.0/org.mockito.Mockito.mock(Mockito.java:2104)
	at org.mockito@5.12.0/org.mockito.Mockito.mock(Mockito.java:2019)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Java 22 (66) is not supported by the current version of Byte Buddy which officially supports Java 21 (65) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
	at net.bytebuddy@1.14.7/net.bytebuddy.utility.OpenedClassReader.of(OpenedClassReader.java:96)
	at net.bytebuddy@1.14.7/net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4011)
	at net.bytebuddy@1.14.7/net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2224)
	at net.bytebuddy@1.14.7/net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4055)
	at net.bytebuddy@1.14.7/net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3739)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:402)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:242)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:225)
	at org.mockito@5.12.0/org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
	... 20 more

Mockito cannot mock this class: interface com.foo.MyInterface.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 22
JVM vendor name    : Oracle Corporation
JVM vendor version : 22.0.1+8-16
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 22.0.1+8-16
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 5.15.0-88-generic

```
Could anyone say if its a bug or mockito 5.12.0 doesn't support Java 22?

**Comment by TimvdLippe** [comment]
Please ensure you are using the latest version of ByteBuddy which supports Java 22.

**Comment by TimvdLippe** [comment]
It is, but if you have any other dependencies in your project you could be using the wrong version. Check with your dependency management system which version you are using and ensure it is up-to-date.
