### ISSUE TITLE
`MockitoExtension.beforeEach(…)` fails with `NullPointerException`

### ISSUE THREAD

**Issue by mp911de** [mockito/mockito#3411]
After upgrading to Mockito 5.12.0 (from 5.11.0), the JUnit 5 extension fails with an NPE:

```
org.mockito.exceptions.misusing.UnfinishedMockingSessionException: 
Unfinished mocking session detected.
Previous MockitoSession was not concluded with 'finishMocking()'.
For examples of correct usage see javadoc for MockitoSession class.

	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:160)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "org.junit.jupiter.api.extension.ExtensionContext$Store.remove(Object, java.lang.Class)" is null
		at org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:194)
		... 2 more
```

Test code:

```java
@ExtendWith(MockitoExtension.class)
@ContextConfiguration(classes = JpaRepositoryConfig.class)
@Transactional
class RepositoryPropertyReferenceControllerIntegrationTests extends AbstractControllerIntegrationTests {

	// …
	@Mock(answer = Answers.RETURNS_MOCKS) RepresentationModelAssemblers assembler;
	// …
}
```

JUnit version: 5.10.3
Mockito version: 5.12.0

Reproducer: https://github.com/spring-projects/spring-data-rest/blob/26257871511914659e91adec111bdb9680244f9e/spring-data-rest-tests/spring-data-rest-tests-jpa/src/test/java/org/springframework/data/rest/webmvc/RepositoryPropertyReferenceControllerIntegrationTests.java

**Comment by maksadbek** [comment]
haven't looked at your dependencies, but adding `Mockito-inline = 4.x;` into my dependencies has fixed the issue.
