### ISSUE TITLE
`thenCallRealMethod` does not work with JDK 24-ea

### ISSUE THREAD

**Issue by xuwei-k** [mockito/mockito#3420]
java version

```
$ java --version
openjdk 24-ea 2025-03-18
OpenJDK Runtime Environment (build 24-ea+11-1194)
OpenJDK 64-Bit Server VM (build 24-ea+11-1194, mixed mode, sharing)
```

pom.xml

```xml
<dependency>
    <groupId>org.mockito</groupId>
    <artifactId>mockito-subclass</artifactId>
    <version>5.12.0</version>
</dependency>
```

`Main.java`

```java
package example;

import org.mockito.Mockito;

interface A1 {
  default String hello() {
    return "hello";
  }
}

class Main{
  public static void main(String[] args) {
    var mock = Mockito.mock(A1.class);
    Mockito.when(mock.hello()).thenCallRealMethod();
    System.out.println(mock.hello());
  }
}
```

run result

```
 org.mockito.exceptions.base.MockitoException: 
 Cannot call abstract real method on java object!
 Calling real methods is only possible when mocking non abstract method.
   //correct example:
   when(mockOfConcreteClass.nonAbstractMethod()).thenCallRealMethod();
         at example.Main.main(Main.java:15)
         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
         at java.base/java.lang.reflect.Method.invoke(Method.java:588)
```

**Comment by xuwei-k** [comment]
fixed 25-ea

```
$ java --version
openjdk 25-ea 2025-09-16
OpenJDK Runtime Environment (build 25-ea+1-3)
OpenJDK 64-Bit Server VM (build 25-ea+1-3, mixed mode, sharing)
```
