### ISSUE TITLE
Mockito 5 on WildFly has a llegalStateException in MethodWriter.visitFrame

### ISSUE THREAD

**Issue by tbee** [mockito/mockito#3435]
The stacktraces says to report it here if I have no idea why I'm getting the exception. Well...

We're upgrading from Mockito 3.2.4 to 5.13.0 on WildFly 33.0.1.
I've included [issue 3304](https://github.com/mockito/mockito/issues/3304)
And upgraded to Byte Buddy 1.15.1
But the exception is not gone. We do not use scala and this is not a Android application, and it also occurs on Termurin and Ubuntu, so that is not a factor.

Any suggestions where to look next?

```
org.mockito.exceptions.base.MockitoException:
Mockito cannot mock this class: class com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepository$$$view233.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java : 17
JVM vendor name : Azul Systems, Inc.
JVM vendor version : 17.0.6+10-LTS
JVM name : OpenJDK 64-Bit Server VM
JVM version : 17.0.6+10-LTS
JVM info : mixed mode, sharing
OS name : Mac OS X
OS version : 14.6.1


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class com.nedap.healthcare.administration.ebean.BaseRepository, class com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepositoryImpl, interface java.io.Serializable, interface org.jboss.as.ee.component.serialization.WriteReplaceInterface, interface com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepository, interface org.jboss.as.ejb3.validator.EjbProxy, class com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepository$$$view233]
at deployment.integration-test.war//com.nedap.healthcare.administration.export.gds801.TestGDS801UnexportableLogProcessor.setup(TestGDS801UnexportableLogProcessor.java:164)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class com.nedap.healthcare.administration.ebean.BaseRepository, class com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepositoryImpl, interface java.io.Serializable, interface org.jboss.as.ee.component.serialization.WriteReplaceInterface, interface com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepository, interface org.jboss.as.ejb3.validator.EjbProxy, class com.nedap.healthcare.administration.finance.careorder.model.zpm.CareOrderZpmGbggzProfielRepository$$$view233]
at deployment.integration-test.war//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
at deployment.integration-test.war//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
at deployment.integration-test.war//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
at deployment.integration-test.war//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
... 4 more
Caused by: java.lang.IllegalStateException:
Byte Buddy could not instrument all classes within the mock's type hierarchy

This problem should never occur for javac-compiled classes. This problem has been observed for classes that are:
- Compiled by older versions of scalac
- Classes that are part of the Android distribution
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:285)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:218)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
at deployment.integration-test.war//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
at deployment.integration-test.war//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
at deployment.integration-test.war//net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
at deployment.integration-test.war//net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:75)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:414)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:373)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createSpy(InlineDelegateByteBuddyMockMaker.java:363)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createSpy(InlineByteBuddyMockMaker.java:62)
at deployment.integration-test.war//org.mockito.internal.util.MockUtil.createMock(MockUtil.java:91)
at deployment.integration-test.war//org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
at deployment.integration-test.war//org.mockito.Mockito.spy(Mockito.java:2191)
... 4 more
Caused by: java.lang.IllegalStateException
at deployment.integration-test.war//net.bytebuddy.jar.asm.MethodWriter.visitFrame(MethodWriter.java:793)
at deployment.integration-test.war//net.bytebuddy.jar.asm.MethodVisitor.visitFrame(MethodVisitor.java:312)
at deployment.integration-test.war//net.bytebuddy.jar.asm.ClassReader.readCode(ClassReader.java:2074)
at deployment.integration-test.war//net.bytebuddy.jar.asm.ClassReader.readMethod(ClassReader.java:1512)
at deployment.integration-test.war//net.bytebuddy.jar.asm.ClassReader.accept(ClassReader.java:745)
at deployment.integration-test.war//net.bytebuddy.utility.AsmClassReader$Default.accept(AsmClassReader.java:132)
at deployment.integration-test.war//net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:4039)
at deployment.integration-test.war//net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2246)
at deployment.integration-test.war//net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4057)
at deployment.integration-test.war//net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3741)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:402)
at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:169)
at deployment.integration-test.war//org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:281)
... 18 more
```

**Comment by tbee** [comment]
I was able to get rid of the exception by replacing the spy with a mock. Apparently spying on a WildFly stateless service proxy is not supported.
