### ISSUE TITLE
Mockito agent doesn't work in an Eclipse OSGi environment

### ISSUE THREAD

**Issue by jhonnen** [mockito/mockito#3457]
The following repro test fails in an Eclipse OSGi environment when [Mockito is applied as a `-javaagent`](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#0.3).

```
package repro;

import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

class MockitoTest {

    @Test
    void test() {
        var mock = Mockito.mock(org.slf4j.Logger.class);
        mock.debug("test");

        Mockito.verify(mock).debug("test");
        Mockito.verifyNoMoreInteractions(mock);
    }
}
```

```
org.mockito.exceptions.misusing.UnfinishedVerificationException: 
Missing method call for verify(mock) here:
-> at repro.MockitoTest.test(MockitoTest.java:13)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

	at repro.MockitoTest.test(MockitoTest.java:14)
```

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
    * mockito:5.14.1
    * Java 21.0.4+7-LTS
    * Eclipse 2024-09
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [ ] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

Since I cannot provide a full self contained repro, here's what I could debug:

The created mocks do not have a `mockInterceptor` set because of a classloader conflict:
The classloader used to load the mock in `org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator#mockClass` contains the following classloaders:
  1. the bundle of the mocked class ("X")
  2. mockito itself
  3. context classloader

When `MockAccess` is then loaded via that classloader, the `EquinoxClassLoader` for "X" is then queried first. That classloader will try to load the class from its parent (i.e. the app classloader) [as a last resort](https://github.com/eclipse-equinox/equinox/blob/163cb3ad9d6f1d2c28ded832bd85385da3bc6685/bundles/org.eclipse.osgi/container/src/org/eclipse/osgi/internal/loader/BundleLoader.java#L546-L556).  
When the agent is applied, it will find the class there and will not load it from Mockito's classloader.
--> `instanceof MockAccess` in `org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker#doCreateMock` is then always false:
![image](https://github.com/user-attachments/assets/ea5f8324-85f2-434b-8111-a38ab5d00ac4)

A fix might be to reorder the classloader of `mockClass()` so that Mockito is always queried first.

**Comment by TimvdLippe** [comment]
We have an osgi-test suite that you can attempt to reproduce the issue there. Then we can figure out a fix. FYI @raphw

**Comment by jhonnen** [comment]
Thanks for the hint, I managed to reproduce it in the integration tests: https://github.com/mockito/mockito/compare/main...jhonnen:mockito:main

**Comment by raphw** [comment]
We should probably have an accessor that explicitly queries the system class loader via reflection to avoid this.

**Comment by raphw** [comment]
The main issue is that Mockito is not supposed to be in the system class loader to begin with, but this is a by-product of adding the javaagent parameter.

Appending `MockAccess.class` and `DispatcherDefaultingToRealMethod.class` first would indeed solve the problem, but I am wondering if there are other implications of this error. The cleanest solution would be if you attached the Byte Buddy agent in this case, or even better a custom agent that does not contain anything and invokes Mockito's `premain` manually.

**Comment by jhonnen** [comment]
> The cleanest solution would be if you attached the Byte Buddy agent in this case

We actually had the byte buddy agent attached before. The only reason to switch was to get rid of the new warning in Mockito.

**Comment by raphw** [comment]
Indeed. Would you consider the last option and have your own agent that invokes Mockito's premain.

@TimvdLippe Maybe we should make the warning suppressable?

**Comment by TimvdLippe** [comment]
> Maybe we should make the warning suppressable?

I am not sure which warning you refer to? If the ByteBuddy agent itself works in an OSGi context, then I think we should support that instead.

**Comment by raphw** [comment]
We do currently print the warning even if the Byte Buddy agent is installed on the command line: https://github.com/mockito/mockito/blob/72dcfa459aa7525b98163aa225e8a47af7029c5e/src/main/java/org/mockito/internal/util/reflection/InstrumentationMemberAccessor.java#L53

Byte Buddy only falls back to dynamic attach. Maybe we should check if the Byte Buddy agent is preattached, too?

**Comment by TimvdLippe** [comment]
Yeah I think we should. I think these are the scenarios:

1. The user specifies Mockito as a java agent -> no warning
2. The user specifies ByteBuddy as a java agent -> no warning
3. The user specifies nothing, ByteBuddy dynamically attaches, below Java 21 -> no warning
4. The user specifies nothing, ByteBuddy dynamically attaches, above Java 21 -> warning

**Comment by raphw** [comment]
Agreed. This implements the change: https://github.com/mockito/mockito/pull/3459
