### ISSUE TITLE
Problem with tests failing in Mockito 5.14.0, 5.14.1 (byte-buddy)

### ISSUE THREAD

**Issue by fp024** [mockito/mockito#3463]
### Runtime Environment

* mockito: 5.14.0, 5.14.1
* os: Windows 11
* jdk: Java 17 temurin (17.0.12+7)

---

Hello.
I am using Mocktio "5.13.0" and I was using the following code for Mocking LocalDateTime.

```java
@ExtendWith(MockitoExtension.class)
class FileCheckTaskTest {
  ...
  private MockedStatic<LocalDateTime> mockedJSONContext;
  ...
  @BeforeEach
  public void beforeEach() throws IOException {
    mockedJSONContext = mockStatic(LocalDateTime.class, Mockito.CALLS_REAL_METHODS);
    LocalDateTime testCurrentNow = LocalDateTime.of(2022, 12, 2, 2, 0, 0, 0);
    mockedJSONContext.when(LocalDateTime::now).thenReturn(testCurrentNow);
    ...
  }
  ...
```

However, after upgrading to version "5.14.0" or "5.14.1", the test fails with the following exception:

```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)

	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy26.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:78)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:275)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:236)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:82)
	at org.mockito.Mockito.mock(Mockito.java:2162)
	at org.mockito.internal.configuration.MockAnnotationProcessor.processAnnotationForMock(MockAnnotationProcessor.java:79)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:28)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:25)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.createMockFor(IndependentAnnotationEngine.java:44)
	at org.mockito.internal.configuration.IndependentAnnotationEngine.process(IndependentAnnotationEngine.java:72)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:62)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:47)
	at org.mockito.MockitoAnnotations.openMocks(MockitoAnnotations.java:81)
	at org.mockito.internal.framework.DefaultMockitoSession.<init>(DefaultMockitoSession.java:43)
	at org.mockito.internal.session.DefaultMockitoSessionBuilder.startMocking(DefaultMockitoSessionBuilder.java:83)
	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:160)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because the return value of "org.junit.jupiter.api.extension.ExtensionContext$Store.remove(Object, java.lang.Class)" is null
		at org.mockito.junit.jupiter.MockitoExtension.afterEach(MockitoExtension.java:194)
		... 2 more
Caused by: java.lang.IllegalStateException: Internal problem occurred, please report it. Mockito is unable to load the default implementation of class that is a part of Mockito distribution. Failed to load interface org.mockito.plugins.MockMaker
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:105)
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.getDefaultPlugin(DefaultMockitoPlugins.java:79)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:75)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:49)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:29)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:26)
	at org.mockito.internal.MockitoCore.<clinit>(MockitoCore.java:71)
	at org.mockito.Mockito.<clinit>(Mockito.java:1741)
	at org.mockito.junit.jupiter.MockitoExtension.beforeEach(MockitoExtension.java:156)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.mockito.internal.configuration.plugins.DefaultMockitoPlugins.create(DefaultMockitoPlugins.java:103)
	... 10 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.

It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 17
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 17.0.12+7
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 17.0.12+7
JVM info           : mixed mode, sharing
OS name            : Windows 11
OS version         : 10.0

	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<init>(InlineDelegateByteBuddyMockMaker.java:273)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:23)
	... 13 more
Caused by: java.lang.NoSuchFieldError: JAVA_V21
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.<clinit>(InlineDelegateByteBuddyMockMaker.java:142)
	... 14 more

```

So, I tried upgrading ‘byte-buddy’ to see if it would solve the problem, and added the following dependency to my project.

```xml
    <dependency>
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
      <version>1.15.3</version>
    </dependency>
```

After adding the "byte-buddy" dependency as above, the test was successful.

Then please check it. Thank you. 👍

check that

 - [ ] The mockito message in the stacktrace have useful information, but it didn't help
 - [ ] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [ ] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/main/.github/CONTRIBUTING.md)

**Comment by fp024** [comment]
I was wrong.

It's not a mockito issue... I think Hibernate 5.6.15 is using an older version of byte-buddy (1.12.18).

```
[INFO] +- org.hibernate:hibernate-core:jar:5.6.15.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.12.18:compile
```


* mockito 5.14.1 is already using version byte-buddy 1.15.3.
https://github.com/mockito/mockito/commit/e9280596b3ca488803d6dcb227c4db2d7391a31b

I'll close the issue..

Thank you. 👍
