### ISSUE TITLE
Mockito cannot mock this class: class org.apache.lucene.index.IndexReader

### ISSUE THREAD

**Issue by parnmatt** [mockito/mockito#3518]
We are in the process of bumping to Lucene 10.0.0, and JDK 21.
We are using the latest Mockito version available 5.14.2.

There have been some internal changes in this major version of Lucene; however, now our mocked tests are failing trying to mock the `IndexReader`. We get the lovely exception to reach out below:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.apache.lucene.index.IndexReader.

If you're not sure why you're getting this error, please open an issue on GitHub.


Java               : 21
JVM vendor name    : Eclipse Adoptium
JVM vendor version : 21.0.4+7-LTS
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 21.0.4+7-LTS
JVM info           : mixed mode
OS name            : Linux
OS version         : 5.19.0-35-generic


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Unsupported settings with this type 'org.apache.lucene.index.IndexReader'
[...]
Caused by: org.mockito.exceptions.base.MockitoException: Unsupported settings with this type 'org.apache.lucene.index.IndexReader'
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	... 11 more
```
---

The bare minimum is enough to trigger this:
```java
IndexReader indexReader = mock(IndexReader.class);
```

In a different test we did have:
```java
private final IndexSearcher indexSearcher = mock(IndexSearcher.class, Mockito.RETURNS_DEEP_STUBS);
// ...
IndexReader indexReader = new IndexReaderStub(new SamplingFields(fieldTermsMap));
when(indexSearcher.getIndexReader()).thenReturn(indexReader);
```
The `IndexReaderStub` is a concrete stubbed class we have. Removing `Mockito.RETURNS_DEEP_STUBS` was enough to fix _this_ case, as we arguably did not need it. I presume it failed in a similar way as it likely tries to internally `mock(IndexReader.class)` in case it was chained. It wasn't, so arguably, there is no need to be mocked in that way.

I will try to use a stub for now to make progress with the upgrade; however,
> If you're not sure why you're getting this error, please open an issue on GitHub

so here I am :grin:

**Comment by bric3** [comment]
The reason is that this `IndexReader` is _sealed_

```
public abstract sealed class IndexReader implements Closeable permits CompositeReader, LeafReader {
```

I haven't followed, byte buddy / mockito for some time. The reason is explained in #2392.
And today I learned !

> [!WARNING]
> From @raphw's message:
> Sealed types do not allow for mocks as the sealing property is unmodifiable even by retransformation. This means sealed classes can only be mocked if they are real inline mocks. We should produce proper error messages for this to avoid user confusion.

Maybe @raphw has more knowledge / updates there !

Indeed we could update the failure message to indicate why, maybe following the same approach as in `org.mockito.plugins.MockMaker.TypeMockability#nonMockableReason`. Right ow this fails in the generator, but could we add this check there `org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker#isTypeMockable` as well ?.

<details><summary>real stack</summary>

For reference only here's the interesting part of the real stack trace: 


```
...
Caused by: org.mockito.exceptions.base.MockitoException: Unsupported settings with this type 'org.apache.lucene.index.IndexReader'
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.checkSupportedCombination(InlineBytecodeGenerator.java:359)
        at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:211)
        at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:78)
        at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
```

Which points here


```java
private <T> void checkSupportedCombination(
        boolean subclassingRequired, MockFeatures<T> features) {
    if (subclassingRequired
            && !features.mockedType.isArray()
            && !features.mockedType.isPrimitive()
            && (Modifier.isFinal(features.mockedType.getModifiers())
                    || TypeSupport.INSTANCE.isSealed(features.mockedType)
                    || features.interfaces.stream().anyMatch(TypeSupport.INSTANCE::isSealed))) {
        throw new MockitoException(
                "Unsupported settings with this type '" + features.mockedType.getName() + "'");
    }
}
```

</details>

**Comment by raphw** [comment]
We should update the error message indeed. Ironically, it is possible to mock a non-abstract instance of a sealed interface which then can serve the same purpose. The reason that we cannot mock the interface itself is because we cannot create a subclass to represent the mock instance.

**Comment by bric3** [comment]
> The reason that we cannot mock the interface itself is because we cannot create a subclass to represent the mock instance.

Yeah that surprised me. as I hadn't the chance to play with sealed class much. (Did mostly kotlin for the past years). But I understand it certainly helps with the VM integrity / closed world trend.

**Comment by raphw** [comment]
I assume that Kotlin will adapt to sealed interfaces eventually, at a minimum for Java-interop. I think we should improve the error message: https://github.com/mockito/mockito/pull/3534

**Comment by parnmatt** [comment]
Thanks all; I understand the issue. I missed that Lucene made `IndexReader` `sealed`, which obviously will cause issues with mocking. I agree that an improved exception message noting this is best, as there really is nothing else to do.
I see the PR is up addressing this, so I am happy for this to be closed once its merged.
