### ISSUE TITLE
cannot mock/spy because : final class

### ISSUE THREAD

**Issue by Sathya-ac9** [mockito/mockito#3556]
Hi,

I am facing an issue while trying to mock or spy on ZoomSDK in an Android project using Mockito. The following error occurs:

`org.mockito.exceptions.base.MockitoException: Cannot mock/spy class us.zoom.sdk.ZoomSDK Mockito cannot mock/spy because : final class at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:50) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:100) at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:107) at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:41) at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163) at org.junit.runners.Suite.runChild(Suite.java:128) at org.junit.runners.Suite.runChild(Suite.java:27) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.junit.runner.JUnitCore.run(JUnitCore.java:137) at org.junit.runner.JUnitCore.run(JUnitCore.java:115) at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:68) at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:59) at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:463) at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2415)`

The error indicates that ZoomSDK is a final class, and Mockito cannot mock or spy on final classes by default.

Seeking Help/Suggestions:

Is there a workaround for mocking or spying on final classes in Mockito?
Should I consider using a different approach or library for testing with ZoomSDK?
Any guidance on how to resolve this issue would be greatly appreciated.
Thanks in advance!

Best Regards,
Sathya

**Comment by kfynn007** [comment]
Newer versions of mockito can mock final classes, try upgrading to version 2.1 and above eg:

`package org.mockito;

import org.junit.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class FinalMockingTest {
    @Test
    public void testMockedStaticCalendar_Isolated() {

        T obj = mock(T.class);

        when (obj.getT()).thenReturn(4);

        assertEquals(4, obj.getT());

    }


    static final class T{

        int getT(){
            return 1;
        }

    }
}
`

**Comment by brunobaiano** [comment]
Hello, just found this issue and I tried to mock a record with 5.x and it worked.
If I tried with 3.x version got the same error.
