### ISSUE TITLE
Enhancement: ArgumentCaptor.captureIf(ArgumentMatcher)

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#358]
Assume we have the following test.

```
 @Mock
 private Consumer<Collection<?>> consumer;

 @Test
 public void test() throws Exception {
       
    consumer.accept(new HashSet<>());
    consumer.accept(new ArrayList<>());
       
    ArgumentCaptor<ArrayList<?>> captor = ArgumentCaptor.forClass(ArrayList.class);
    verify(consumer).accept(captor.capture());
 }
```

The test fails with:
```
org.mockito.exceptions.verification.TooManyActualInvocations:
consumer.accept(<Capturing argument>);
Wanted 1 time:
-> at foo.TestClass.testName(TestClass.java:64)
But was 2 times. Undesired invocation:
-> at agh.TestClass.testName(TestClass.java:61)

    at foo.TestClass.test(TestClass.java:64)
    [..]
```

The test fails because the ArgumentCaptor stores every type, because the type information is erased a runtime. How can we capture the type that is specified in the captor, in this case `ArrayList`?  It is possible to implement an `Answer `that stores the argument, and use
`Matchers.isA(ArrayList.class) `but thats ugly->

` doAnswer(captureArg1).when(consumer).accept(isA(ArrayList.class));`

Maybe it is a good idea to create a pull req and extend the ArgumentCaptor API by adding a method like `<T> T captureIf(ArgumentMatcher<? extends T>) `?

Then we could write:
`verify(consumer).accept(captor.captureIf(isA(ArrayList.class)));`

**Comment by gauravsak** [comment]
@ChristianSchwarz I was trying to investigate this issue but I am getting an Incompatible types compiler error on the line:

`ArgumentCaptor<ArrayList<?>> captor = ArgumentCaptor.forClass(ArrayList.class);`

Wonder how its working for you.

**Comment by ChristianSchwarz** [comment]
@gauravsak I am using Java 8, i guess this a problem of your IDE compiler settings. You can also reproduce it by using:
```
@Captor
ArgumentCaptor<ArrayList<?>> captor;
```

**Comment by terebesirobert** [comment]
Hi,
Anyone working on this? It's a good and useful idea, I would like to help, if needed.

**Comment by ChristianSchwarz** [comment]
I tried to implement a prototype of the proposed `captureIf` but I think it is not a easy task. I think a new `getValue(ArgumentMatcher)` and  `getValues(ArgumentMatcher)` is the way to go and easier to implement.

**Comment by terebesirobert** [comment]
Yes, but this does not resolve the problem you raised

**Comment by terebesirobert** [comment]
Do you mind if I give it a try?

**Comment by terebesirobert** [comment]
@ChristianSchwarz 
Hi,
I implemented a version of captureIf. Could you take a look, please. Thanks

**Comment by ChristianSchwarz** [comment]
I have some questions about the user experience/expectation of the `captureIf(..)` API,  that lead me to the conclusion that it is better have an API like `getValue(ArgumentMatcher)`. What do you think of this uses cases:

Use Case 1:
```
ArgumentCaptor<Collection> captor = ...
Consumer<Collection> consumer = mock(Consumer.class)

consumer.consume(new ArrayList());
consumer.consume(new HashSet());

verify(consumer).consume(captor.captureIf(instanceOf(List.class)));
verify(consumer).consume(captor.captureIf(instanceOf(Set.class)));

List<Collection> values = captor.getValues(); 
```

What does the user expect is the content of `values` here?

-----

Use Case 2:
```
ArgumentCaptor<Number> captor = ...
Consumer<Number> consumer = mock(Consumer.class)

consumer.consume(1);
consumer.consume(-2);

verify(consumer).consume(captor.captureIf(gt(0)));
verify(consumer).consume(captor.capture());

List<Collection> values = captor.getValues(); 
```
What does the user expect is the content of `values` here?

**Comment by terebesirobert** [comment]
@ChristianSchwarz 
For Use Case 1:
The returned value will be the last matcher registered by captureIf. In this case, the returned value will be the values captured by instanceOf(Set.class). If we want to support this use case, we could use the existing matcher, and create some getValues(Matcher).

For Use Case 2:

the captor will return the values that matcher the grater than matcher. The default matcher will be ignored. 

I think we could keep the captureIf api also and the getValues(Matcher) api too. By this, when the values are captured are stored under the correct capture, so with this you don't have to filter them when you call getValues(Matcher). What do you think?

**Comment by ChristianSchwarz** [comment]
@terebesirobert Your idea to implement `captureIf(..)`looks good! Now I think it will be possible to satisfy the described use cases without the need of `getValue(ArgumentMatcher)` and  `getValues(ArgumentMatcher)`. 

The `CapturingMatcher`/`CustomCapturingMatcher `should not have its own List of captured arguments but the `ArgumentCaptor`. Once ArgumentCaptor.capture() or captureIf(..) is called the argument List should be passed to the new created `CapturingMatcher`/`CustomCapturingMatcher `. This way all CapturingMatchers add arguments to/share the same list.

**Comment by terebesirobert** [comment]
@ChristianSchwarz Thanks.

**Comment by ChristianSchwarz** [comment]
@terebesirobert thank you for being open minded and considering my "hints", good style of cooperation !

**Comment by ChristianSchwarz** [comment]
@bric3 @szczepiq @raphw 

We or better @terebesirobert added the class `ArgumentMatchers `that is equivalent to the class `Matchers `but returns `ArgumentMatcher `instead of default values. It is intended to be used in captureIf(AgrumentMatcher) like this : `captureIf(gt(5))`. 
Maybe it should be renamed. Problem for future users is to distinguish which helper class to use in which case. Currently argument matching methods life in the class `Mockio`, `AdditionalMatchers `, `Matchers `and the introduced ArgumentMatchers too. Maybe an other pull request should move all matcher methods (returning defaults) into class Mockito?

**Comment by ChristianSchwarz** [comment]
Duplicated by #409
