### ISSUE TITLE
v2.0.42-beta: Cannot mock interface io.netty.channel.EventLoop

### ISSUE THREAD

**Issue by manderson23** [mockito/mockito#360]
I have recently upgraded from 2.0.7-beta to 2.0.42-beta and some tests are failing as https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/EventLoop.java cannot be mocked.

The trace is as follows:
```org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface io.netty.channel.EventLoop

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalStateException: Cannot implement bridge public io.netty.channel.EventLoop io.netty.channel.EventLoop$MockitoMock$1373022630.next() to public abstract io.netty.util.concurrent.EventExecutor io.netty.channel.EventLoop$MockitoMock$1373022630.next()
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl$1.withBefores(JUnit45AndHigherRunnerImpl.java:27)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:276)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Cannot implement bridge public io.netty.channel.EventLoop io.netty.channel.EventLoop$MockitoMock$1373022630.next() to public abstract io.netty.util.concurrent.EventExecutor io.netty.channel.EventLoop$MockitoMock$1373022630.next()
	at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$AccessBridgeWrapper.apply(TypeWriter.java:1069)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:3450)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:1577)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:164)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2508)
	at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:55)
	at org.mockito.Mockito.mock(Mockito.java:1449)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:43)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:66)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:71)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:55)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
	... 18 more

```

**Comment by raphw** [comment]
This is a bug in Byte Buddy where bridge methods on interfaces for overridden return types are not adapted correctly. I just released a new version of Byte Buddy where this is fixed and triggered a new released for Mockito.

**Comment by raphw** [comment]
The build does not seem to work because of Jacoco using too much memory. I am not sure how I can fix this. @bric3?

**Comment by bric3** [comment]
@raphw Not sure either. However when I run locally `gralde ciBuild` there's a few test failures with localized matchers.

```
org.mockito.internal.matchers.LocalizedMatcherTest > shouldMatchTypesWhenActualMatcherHasCorrectType FAILED
    java.lang.ClassCastException: org.mockito.internal.matchers.Equals cannot be cast to org.hamcrest.Matcher
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldMatchTypesWhenActualMatcherHasCorrectType(LocalizedMatcherTest.java:18)

org.mockito.internal.matchers.LocalizedMatcherTest > shouldNotMatchTypesWhenActualMatcherDoesNotHaveCorrectType FAILED
    java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.<init>(Lorg/hamcrest/Matcher;)V
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldNotMatchTypesWhenActualMatcherDoesNotHaveCorrectType(LocalizedMatcherTest.java:28)

org.mockito.internal.matchers.LocalizedMatcherTest > shouldDescribeWithTypeInfoWhenActualMatcherHasCorrectType FAILED
    java.lang.ClassCastException: org.mockito.internal.matchers.Equals cannot be cast to org.hamcrest.Matcher
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldDescribeWithTypeInfoWhenActualMatcherHasCorrectType(LocalizedMatcherTest.java:38)

org.mockito.internal.matchers.LocalizedMatcherTest > shouldNotDescribeWithTypeInfoWhenActualMatcherDoesNotHaveCorrectType FAILED
    java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.<init>(Lorg/hamcrest/Matcher;)V
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldNotDescribeWithTypeInfoWhenActualMatcherDoesNotHaveCorrectType(LocalizedMatcherTest.java:57)

org.mockito.internal.matchers.LocalizedMatcherTest > shouldDelegateToCapturingMatcher FAILED
    java.lang.NoSuchMethodError: org.mockito.internal.matchers.LocalizedMatcher.<init>(Lorg/hamcrest/Matcher;)V
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldDelegateToCapturingMatcher(LocalizedMatcherTest.java:67)

org.mockito.internal.matchers.LocalizedMatcherTest > shouldDescribeStringWithType FAILED
    java.lang.ClassCastException: org.mockito.internal.matchers.Equals cannot be cast to org.hamcrest.Matcher
        at org.mockito.internal.matchers.LocalizedMatcherTest.shouldDescribeStringWithType(LocalizedMatcherTest.java:48)
```

**Comment by raphw** [comment]
@bric3 Strange. I do not get any errors when triggering the CI build locally. Also, the build started failing after a simple version upgrade of Byte Buddy. That should not cause any of that.

**Comment by bric3** [comment]
@raphw OK weird, I don't understand why it failed, now it it works correctly locally on my box. _Probably a user error_. However I don't get why travis build failed.

However I relaunched the travis build and it seemed to have worked, and thus published the new build. https://travis-ci.org/mockito/mockito/builds/111013608

**Comment by bric3** [comment]
Anyway version 2.0.43-beta has been published on bintray, propagation on maven should happen within the next couple of hours.
