### ISSUE TITLE
Class cast exception in PluginLoader.loadPlugin

### ISSUE THREAD

**Issue by thekingnothing** [mockito/mockito#368]
I've been working on two defects for PowerMock ([first]( https://github.com/jayway/powermock/issues/634) and [second](https://github.com/jayway/powermock/issues/632)). Both has very similar stack trace: 

> java.lang.ExceptionInInitializerError
> at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.(ConditionalStackTraceFilter.java:17)
> at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
> at org.mockito.exceptions.base.MockitoException.(MockitoException.java:30)
> at org.mockito.exceptions.misusing.MockitoConfigurationException.(MockitoConfigurationException.java:18)
> at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:66)
> at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
> at org.mockito.internal.configuration.plugins.PluginRegistry.(PluginRegistry.java:12)
> at org.mockito.internal.configuration.plugins.Plugins.(Plugins.java:11)
> at org.mockito.internal.util.MockUtil.(MockUtil.java:24)
> at org.mockito.internal.MockitoCore.(MockitoCore.java:44)
> at org.mockito.Mockito.(Mockito.java:975)
> at org.powermock.modules.test.junit4.rule.objenesis.MockStaticNotPreparedTest.testWhenNotPrepared(MockStaticNotPreparedTest.java:45)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
> at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1898)
> at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
> at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
> at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
> at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
> at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
> at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:57)
> at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:110)
> at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
> at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
> at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
> at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: java.lang.NullPointerException
> at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
> at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.(StackTraceFilter.java:21)
> ... 51 more

As @bric3 recommend in issue #355 I had started debug `PluginLoader` and I found class cast exception in `org.mockito.internal.configuration.plugins.PluginLoader#loadImpl`. And this class cast exception is transformed to NPE. Main reason of class class exception, that plugin interface class and plugin implementor could be loaded by different class loader, because for plugin implementor current context class loader is used. 

I've create the [gist](https://gist.github.com/thekingnothing/9674b6196f91b67aa944) with test which demonstrate the issue. 

Issue could be reproduce on both latest version:  1.10.19 2, 2.0.43-beta

I'm going to  raise a pull request soon for Mockito 2, but I think hot-fix also should be release for 1.10.

**Comment by bric3** [comment]
Cool thanks for the investigation.

Otherwise I personally find it's reasonable to include the gist code in a comment here ;)

> I'm going to raise a pull request soon for Mockito 2,

Cool too

> but I think hot-fix also should be release for 1.10.

Not sure we have the build infrastructure to backport the fix on 1.x

**Comment by TimvdLippe** [comment]
Since #370 has been closed, @raphw did you resolve this issue as indicated in https://github.com/mockito/mockito/pull/370#issuecomment-227023691 ?

**Comment by tomkalafut** [comment]
Was this ever finished?  I am still getting it with Mockito 1.10.19 & PM 1.6.5.  When I upgrade to newer versions like 2.8.9/2.07, I get the ever so annoying "Invalid use of argument matchers!" error.
=====
import static org.mockito.Mockito.when
...
//Line 147: 
when(someCacheService.getSomeStringList(anyString())).thenReturn(anyList())
=====
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
0 matchers expected, 1 recorded:
-> at com.mycompany.myproject.TestCase.setUp(TestCase.groovy:147)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(anyObject(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(anyObject(), eq("String by matcher"));

**Comment by TimvdLippe** [comment]
@tomkalafut Please create a new issue with a reproduction project that shows the issue in isolation. Then we can take a look.

**Comment by tomkalafut** [comment]
Done: https://github.com/mockito/mockito/issues/1970
