### ISSUE TITLE
Feature Request: Debugable Invocation, VerboseLogging Control

### ISSUE THREAD

**Issue by zglagola** [mockito/mockito#411]
Part of a conversation w/Szczepan. Pasting in the email below.

Summary:
It'd be great to see a debugable invocation point (described below) and the ability to control how invocations are logged (for verbose logging). The first item is more pertinent :)

Let me know if you'd like me to split these guys out.

------------------------------------------------------------------------------------------------------------------------------------
...
Per our chat yesterday, a few things we are trying to accommodate with our new test framework with respect to Mockito.

**Problem to solve**

In the unit testing world we are (ideally) testing single classes, and the gap between the test code and the mock implementation is minimal. Usually folks need only circulate between the class they are testing and the test class itself. In this new paradigm, lets call it isolated functional test, a single class now becomes 30+ classes and the debugging complexity increases dramatically.

The below are useful for the more 'traditional' form of unit testing as well.

**Solutions**

To resolve this we've imagined two measures, presented in the context of a RESTful API:

1. Common debug point in the test - We want to surface a similar object to `org.mockito.MockSettings`, with an added option `debugPoint(DebuggableInvocation)`. During development, users can add this to their mock and have a single break point to see all of the invocations on their single mock object, in this instance RestClient#sendRequest.
2. Extended logging - Today we leverage `com.mockito.MockSettings#verboseLogging`, but this has a few limitations. Hence the email :)

**Help we need**

For the first point, it'd be great to see a common break point just before the invocation on the mock were clients have access to the upcoming invocation within the context of their test code. This allows them to climb up the stack trace to all of the points of invocation, test all their matchers against the invocation, etc. With an IDE this would be even more fun :)

To the latter point, we could use your help flexing the Mockito library or adding the appropriate appendages. With reference to org.mockito.internal.debugging.VerboseMockInvocationLogger, i'd like to profile an ideal logger.

1. Real time printing - `org.mockito.listeners.InvocationListener` does this super well and i'd love to maintain this capability.
2. Multiple PrintStream support - Love this, want to keep it.
3. Control over printing the invocation - Lots of information about the `Request` object is unnecessary. EX. It'd be great to filter out the important bits, or even control them with a log level-like parameter.
4. Parsing/Changing the invocation location - Most folks releasing Java APIs leverage ParSeq, so `org.mockito.invocation.DescribedInvocation#getLocation` always returns the same result. Being able to specify (or autodetect) something like a common package matcher ('com.blah.myproduct.api') would allow us to consistently show the user where the issue in their code is. With the additional flexibility we could even print the stacktrace up to that point if it helps abbreviate things.
5. Has returned upgrade - I don't believe 'has returned' is aware of delegating to a real method, returning a default answer, etc.. Love to add this capability so clients are aware of how we are handling their request.
6. Filter out logging mocking invocations - Not sure if this is because we are using the `doReturn` syntax, but we end up with logging artifacts like this guy which we get when we set our mock returns.

############ Logging method invocation #1 on mock/spy ########
restClient.sendRequest(null, null, null);
   invoked: -> at com.blah.blah.blah.blah.MockRestClientBuilder.generateMockClient(MockRestClientBuilder.java:91)
   has returned: "null"
############ Logging method invocation #2 on mock/spy ########
restClient.sendRequest(null, null, null);
   invoked: -> at com.blah.blah.blah.blah.blah.MyTest.example(MyTest.java:40)
   has returned: "null"

**Comment by zglagola** [comment]
Splitting these tickets up. See https://github.com/mockito/mockito/issues/414 for the other item.
