### ISSUE TITLE
Mockito cannot mock this class: interface java.util.List

### ISSUE THREAD

**Issue by ChristianSchwarz** [mockito/mockito#416]
The unit tests of  mockito-master branch have 827 errors + 7 failures when i run them in Eclipse and IntelliJ.

@raphw  The most of them look like this

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface java.util.List

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalArgumentException: java.lang.ClassCastException@68034211
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.prettifyFailure(CachingMockBytecodeGenerator.java:86)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:74)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:64)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:27)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:55)
	at org.mockito.Mockito.mock(Mockito.java:1449)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:1)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:43)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.createMockFor(InjectingAnnotationEngine.java:35)
	at org.mockito.configuration.MockitoConfiguration$1.createMockFor(MockitoConfiguration.java:62)
	at org.mockito.MockitoAnnotations.processAnnotationDeprecatedWay(MockitoAnnotations.java:123)
	at org.mockito.MockitoAnnotations.scanDeprecatedWay(MockitoAnnotations.java:115)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:102)
	at org.mockitoutil.TestBase.init(TestBase.java:53)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@68034211
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$ForTypeArgument.resolve(TypeDescription.java:3875)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator$Chained.resolve(TypeDescription.java:3501)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$ForTypeArgument.resolve(TypeDescription.java:3834)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator.asList(TypeDescription.java:3477)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType$ForLoadedType.getDeclaredAnnotations(TypeDescription.java:4771)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onWildcard(TypeDescription.java:676)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onWildcard(TypeDescription.java:659)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType.accept(TypeDescription.java:4679)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onParameterizedType(TypeDescription.java:687)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onParameterizedType(TypeDescription.java:659)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:5021)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:5794)
	at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:866)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:85)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:635)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:862)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1059)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:569)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:565)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:565)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:502)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:423)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:489)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2564)
	at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:72)
	... 39 more
```

**Comment by ChristianSchwarz** [comment]
```
dependencies {
    compile 'net.bytebuddy:byte-buddy:1.3.16'
    provided "junit:junit:4.12", "org.hamcrest:hamcrest-core:1.3"
    compile "org.objenesis:objenesis:2.1"
    testCompile 'org.ow2.asm:asm:5.0.4'
    testCompile 'org.assertj:assertj-core:2.1.0'
    testRuntime configurations.provided
    testUtil sourceSets.test.output
}
```

**Comment by TimvdLippe** [comment]
I am unable to reproduce this issue. Both `./gradlew build` and running tests in IntelliJ pass on current master. Would a gradle refresh maybe fix the issue?

**Comment by raphw** [comment]
I cannot reproduce this problem either, is this still a problem @ChristianSchwarz?

**Comment by ChristianSchwarz** [comment]
Yes it is still a problem. I am using [Gradle-Buildship](http://projects.eclipse.org/projects/tools.buildship) with eclipse now but the problem remains the same. Ironically the test are green when I run the gradle test task.

**Comment by raphw** [comment]
I am using IntelliJ so I wonder it is some form of plugin problem in this case.

**Comment by raphw** [comment]
It might be that this issue is related to this: http://stackoverflow.com/questions/37527038/mockito-object-is-not-an-instance-of-declaring-class/37528479#37528479

What JVM version are you running?

**Comment by ChristianSchwarz** [comment]
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by raphw** [comment]
Could ypu set a break point at the error root instruction and check the class loaders in question?

**Comment by ChristianSchwarz** [comment]
I updated to:

Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Now it works almost:

![junit](https://lh3.googleusercontent.com/k1K0nFmdx4wC2jMd2v5jEpihCy5XDgrP1_3YT9D8D-O4jlGgQhQGHUzmyb_xPw2pePjG7MUU_jP-Q8KEYJYxNNpKsnCRfNLOjOz23_B7oe63b00jphdqFBn0-ngMJbeZOiTffXATunkH4sa8mbBtzfiv-8c_eXb1qtaaDyju4g_1PXmJbgcburY5yRv7-xemEgtm8EhueTn4l0O7TwXkF3RTtRUOK5tSzxiG4dKXI5LH46oVw-wASVZaIMxvslyG53qcaCGXoopgTtXJAf9bgQz5j2rXXLE-a5N1N0ocpmdYScLUfDaPRQaBfbsSrZw2ZZFdv0CPVhp_hxclnEf3XFVQUw2YcJxRQ1INS6QhKiouVzb2c3dA1xoe23NckekejrMX747oQPxg72F3oDrRMztJHiXEOgI6n-DfDg0nFeKqhusu7RExi0Q0qUXIaTM7NNWomPLCRcNfFD2fHfR4Q7IZFHh-Bvrm5hqgWi0YbzIADt-SAkTZxLMPVAEEhCJT7V2ZYwY94nLACAiXpvS48bdzKkNBqfFRbFCpNBPiPfrS2F2MBeUXE0uEsxoQgVBIc_TI58RU-KGMLQHQlUvWc6exk2P3DkE=w663-h186-no)

**Comment by TimvdLippe** [comment]
The first one is expected to fail. With `./gradlew build` it is exluded correctly, but the IDEs do not ignore this test correctly. The second and third are related to class loaders on Windows and Eclipse.

**Comment by ChristianSchwarz** [comment]
Sounds interesting. Were can I read more about it? Does the JDT-Team have a bug-ticket for these cases?

**Comment by TimvdLippe** [comment]
There was a previous discussion in #225

**Comment by ChristianSchwarz** [comment]
@TimvdLippe Thanks for the link!

I will close this issue cause the main errors are fixed and the 2 remaining failures are a different story.
