### ISSUE TITLE
Can not Return deep stubs from generic method that returns generic type

### ISSUE THREAD

**Issue by chisui** [mockito/mockito#484]
Hey,

if I try to mock a generic method which a generic returntype, where the returntype is derived from the generic type of the method using deep stubs I get a `ClassCastException` when calling `when` on it.

    interface I {
        <T> Supplier<T> m(Class<T> type);
    }
    @Test
    public void test() throws Exception {
        I i = mock(I.class, RETURNS_DEEP_STUBS);
        when(i.m(Boolean.class).get()); // <- ClassCastException
    }

When you don't use deep stubs and a raw `Supplier` mock to pass around it works:

    I i = mock(I.class);
    Supplier s = mock(Supplier.class);
    when(i.m(Boolean.class)).thenReturn(s);
    when(i.m(Boolean.class).get());

The `ClassCastException`:

    java.lang.ClassCastException: org.mockito.internal.creation.cglib.ClassImposterizer$ClassWithSuperclassToWorkAroundCglibBug$$EnhancerByMockitoWithCGLIB$$cdb13154 cannot be cast to java.lang.String
      at MockitoGenerics.test(MockitoGenerics.java:21)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
      at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
      at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
      at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
      at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
      at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
      at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
      at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
      at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
      at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Tested using mockito 1.10.19, jdk 1.8.0_20 and no Powermock

**Comment by bric3** [comment]
Unfortunately this is not possible in Java at this time, because Java implements Generic with erasure.
The only exceptions where generic metadata are kept by the compiler are :

* class or interface that extends or implements a generic type and **sets** this generic type, then method generic type may be _inferred_ e.g.

    ```java
    interface C extends Iterable<A> {}
    ```


* when bounds are declared, either on the type or on a method

    ```java
    interface C<T extends Number> {
      T get();
      <O extends Observer> observe();
    }
    ```

**Comment by bric3** [comment]
```java
    I i = mock(I.class, RETURNS_DEEP_STUBS);
    when(i.m(Boolean.class).get()); // <- ClassCastException
