### ISSUE TITLE
Mocking a class with a generic wildcard <?> type does not work with java8

### ISSUE THREAD

**Issue by craigeebach** [mockito/mockito#509]
Not sure about java 8 support for Mockito 2.0, but reporting this FWIW.  Perhaps a known issue but could not find.  

When attempting to mock a class that contains a generic wildcard using Mockito 2.0.90-beta, the failure below occurs.  The problem does not occur if you use java7.  The problem also does not occur if you use java8 and Mockito 1.10.19.

Sample project
[mockito-generics-error.zip](https://github.com/mockito/mockito/files/384917/mockito-generics-error.zip)   

Class that cannot be mocked:
```
package org.craig.test;

public class ClassB {

	public void methodWithClassWildcard(java.lang.Class<?> iface) {
		// Does not work, results in:
		// Mockito cannot mock this class: class org.craig.test.ClassB
		// Mockito can only mock visible & non-final classes.
		// If you're not sure why you're getting this error, please report to the mailing list.
		// Underlying exception : java.lang.IllegalArgumentException: object is not an instance of declaring class
	}
	
	public void method2WithClassNoWildcard(java.lang.Class iface) {
		// no issue without wildcard <?>
	}
}
```
Exception
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class org.craig.test.ClassB

Mockito can only mock visible & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.

Underlying exception : java.lang.IllegalArgumentException: object is not an instance of declaring class
	at org.mockito.internal.runners.SilentJUnitRunner$1.withBefores(SilentJUnitRunner.java:29)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:276)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.SilentJUnitRunner.run(SilentJUnitRunner.java:39)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:104)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$ForTypeArgument.resolve(TypeDescription.java:3875)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator$Chained.resolve(TypeDescription.java:3501)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$ForTypeArgument.resolve(TypeDescription.java:3834)
	at net.bytebuddy.description.type.TypeDescription$Generic$AnnotationReader$Delegator.asList(TypeDescription.java:3477)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType$ForLoadedType.getDeclaredAnnotations(TypeDescription.java:4771)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onWildcard(TypeDescription.java:676)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onWildcard(TypeDescription.java:659)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfWildcardType.accept(TypeDescription.java:4679)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onParameterizedType(TypeDescription.java:687)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$TypeVariableErasing.onParameterizedType(TypeDescription.java:659)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfParameterizedType.accept(TypeDescription.java:5021)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:5794)
	at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:859)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:85)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:685)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:861)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1058)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:568)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:528)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:547)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:561)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:501)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:422)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:489)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:160)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2564)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2666)
	at org.mockito.internal.creation.bytebuddy.MockBytecodeGenerator.generateMockClass(MockBytecodeGenerator.java:60)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.generate(CachingMockBytecodeGenerator.java:99)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(CachingMockBytecodeGenerator.java:89)
	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.get(CachingMockBytecodeGenerator.java:37)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createProxyClass(ByteBuddyMockMaker.java:54)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:27)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:60)
	at org.mockito.Mockito.mock(Mockito.java:1560)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:39)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:63)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:59)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:43)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:67)
	... 19 more
```

**Comment by bric3** [comment]
This may be because of Eclipse. Running `mvn clean test` is successful.

```
~/opensource/mockito-generics-error ○ ❯ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
~/opensource/mockito-generics-error ○ ❯ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"



~/opensource/mockito-generics-error ○ ❯ mvn clean test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building mockito-generics-error 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://nexus.build.libon.com/content/groups/public/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.pom (10 KB at 8.0 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.jar
Downloaded: https://nexus.build.libon.com/content/groups/public/org/apache/maven/plugins/maven-compiler-plugin/3.5/maven-compiler-plugin-3.5.jar (49 KB at 106.9 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/org/mockito/mockito-core/2.0.90-beta/mockito-core-2.0.90-beta.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/org/mockito/mockito-core/2.0.90-beta/mockito-core-2.0.90-beta.pom (2 KB at 4.0 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy/1.4.8/byte-buddy-1.4.8.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy/1.4.8/byte-buddy-1.4.8.pom (11 KB at 77.9 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy-parent/1.4.8/byte-buddy-parent-1.4.8.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy-parent/1.4.8/byte-buddy-parent-1.4.8.pom (25 KB at 141.3 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis/2.4/objenesis-2.4.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis/2.4/objenesis-2.4.pom (3 KB at 11.7 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom
Downloaded: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis-parent/2.4/objenesis-parent-2.4.pom (17 KB at 96.3 KB/sec)
Downloading: https://nexus.build.libon.com/content/groups/public/org/mockito/mockito-core/2.0.90-beta/mockito-core-2.0.90-beta.jar
Downloading: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy/1.4.8/byte-buddy-1.4.8.jar
Downloading: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis/2.4/objenesis-2.4.jar
Downloaded: https://nexus.build.libon.com/content/groups/public/org/objenesis/objenesis/2.4/objenesis-2.4.jar (51 KB at 281.4 KB/sec)
Downloaded: https://nexus.build.libon.com/content/groups/public/org/mockito/mockito-core/2.0.90-beta/mockito-core-2.0.90-beta.jar (766 KB at 1233.0 KB/sec)
Downloaded: https://nexus.build.libon.com/content/groups/public/net/bytebuddy/byte-buddy/1.4.8/byte-buddy-1.4.8.jar (2386 KB at 2519.2 KB/sec)
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mockito-generics-error ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mockito-generics-error ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/brice/opensource/mockito-generics-error/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5:compile (default-compile) @ mockito-generics-error ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/brice/opensource/mockito-generics-error/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mockito-generics-error ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/brice/opensource/mockito-generics-error/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5:testCompile (default-testCompile) @ mockito-generics-error ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/brice/opensource/mockito-generics-error/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mockito-generics-error ---
[INFO] Surefire report directory: /Users/brice/opensource/mockito-generics-error/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.craig.test.MockitoClassFailureTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.459 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.785 s
[INFO] Finished at: 2016-07-27T10:59:07+02:00
[INFO] Final Memory: 18M/217M
[INFO] ------------------------------------------------------------------------
```

**Comment by bric3** [comment]
I'm closing the issue. I will reopen when something new is added

**Comment by raphw** [comment]
@craigeebach Please update your JVM. This error is a bug in the runtime that only occurs with early versions of Java 8. You probably run a version that is 2+ years old.

**Comment by craigeebach** [comment]
I just updated to a newer java 8 and the problem no longer occurs so @raphw is absolutely correct that the cause was my stale version of java 8.   Thanks!
