### ISSUE TITLE
JDK9 NoClassDefFoundError

### ISSUE THREAD

**Issue by ben-manes** [mockito/mockito#546]
Building with jdk9-ea build 130 and Mockito 2.0.96-beta fails with,

```
java.lang.NoClassDefFoundError: Could not initialize class com.github.benmanes.caffeine.cache.CacheWriter$MockitoMock$1566132372
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor13.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Constructor.java:453)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:32)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
	at org.mockito.Mockito.mock(Mockito.java:1560)
	at org.mockito.Mockito.mock(Mockito.java:1473)
	at com.github.benmanes.caffeine.cache.testing.CacheSpec$Writer$2.get(CacheSpec.java:515)

**Comment by raphw** [comment]
The problem is that Objenesis does not yet support Java 9. There are still too many moving parts in the JDK for attempting to fix this, the whole subsystem in question is currently discussed to be removed.

**Comment by ben-manes** [comment]
Yep, that's fair and my viewpoint as well. A user decided to pitch in and see if he could migrate my project and this was a blocker.

**Comment by raphw** [comment]
I think this will be decided soon, as soon as I know more, I will try to get Mockito Java 9 ready.

**Comment by szpak** [comment]
Objenesis claims to [support](https://github.com/easymock/objenesis/blob/master/SupportedJVMs.md) Java 9:
> List of currently supported JVMs
>  Sun Hotspot VM, versions 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9
>  OpenJDK 6, 7, 8, 9

I don't see an open issue about Java 9 there. @raphw, could you create one with some example to allow to track when/if Objenesis will support case(s) required in Mockito?

**Comment by bric3** [comment]
They may have changed something in build 130. It seems it was released on august 8 : https://groups.google.com/forum/m/#!topic/gradle-dev/n9Zegz9hLRM
I'm on a mobile device so I didn’t look much the change log, but I suppose Objenesis is not following closely each early access build (they need vacation time too)

**Comment by raphw** [comment]
I just ran Mockito with the latest build of Java 9 and all tests return run green (besides two tests that yield errors in AspectJ.) I would not understand how the problem you are currently experiencing is within Mockito. Can you create a reconstruction?

**Comment by ben-manes** [comment]
The problem seems to be due to Gradle in some manner. Even though I had cleaned, it required deleting `<project>/.gradle` and `~/.gradle`. I'm pretty sure only the former was necessary as I was able to make a standalone project work, but for good measure deleted the older cruft. Afterwords I was able to run the test suite without any Mockito-based errors.

Thanks for the help!
