### ISSUE TITLE
VerificationWithTimeoutTest is unstable

### ISSUE THREAD

**Issue by szczepiq** [mockito/mockito#548]
See build failure: https://travis-ci.org/mockito/mockito/jobs/151406672

Full stack trace:

```
org.mockitousage.verification.VerificationWithTimeoutTest > shouldAllowTimeoutVerificationInOrder FAILED
    org.mockito.exceptions.verification.VerificationInOrderFailure: 
    Verification in order failure
    Wanted but not invoked:
    mock.oneArg('1');
    -> at org.mockitousage.verification.VerificationWithTimeoutTest.shouldAllowTimeoutVerificationInOrder(VerificationWithTimeoutTest.java:161)
    Wanted anywhere AFTER following interaction:
    mock.oneArg('x');
    -> at org.mockitousage.verification.VerificationWithTimeoutTest.shouldAllowTimeoutVerificationInOrder(VerificationWithTimeoutTest.java:155)
```

**Comment by TimvdLippe** [comment]
Refs #433, #446 and #451.

**Comment by bric3** [comment]
We may want to look at `VerificationAfterDelayTest` too.

Also see #601

I have some ideas, I'll try them when I have some time.
