### ISSUE TITLE
One test fails probably undeterministically 

### ISSUE THREAD

**Issue by lukasz-szewc** [mockito/mockito#601]
Hey,

Check console output for this build: 
https://travis-ci.org/mockito/mockito/jobs/155443990

It seems that one test from time to time for no apparent reason.

```
org.mockitousage.verification.VerificationWithTimeoutTest > canIgnoreInvocationsWithJunit FAILED
    Wanted but not invoked:
    mock.oneArg('1');
    -> at org.mockitousage.verification.VerificationWithTimeoutTest.canIgnoreInvocationsWithJunit(VerificationWithTimeoutTest.java:147)
    Actually, there were zero interactions with this mock.
        at org.mockito.internal.exceptions.Reporter.wantedButNotInvoked(Reporter.java:329)
        at org.mockito.internal.verification.checkers.MissingInvocationChecker.checkMissingInvocation(MissingInvocationChecker.java:37)
        at org.mockito.internal.verification.Times.verify(Times.java:37)
        at org.mockito.internal.verification.VerificationOverTimeImpl.verify(VerificationOverTimeImpl.java:78)
        at org.mockito.internal.verification.VerificationWrapper.verify(VerificationWrapper.java:15)
        at org.mockito.internal.verification.MockAwareVerificationMode.verify(MockAwareVerificationMode.java:21)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:73)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:32)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:36)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:36)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.access$000(MockMethodInterceptor.java:17)
        at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:113)
        at org.mockitousage.IMethods$MockitoMock$1357077317.oneArg(Unknown Source)
        at org.mockitousage.verification.VerificationWithTimeoutTest.canIgnoreInvocationsWithJunit(VerificationWithTimeoutTest.java:147)
```

**Comment by lukasz-szewc** [comment]
Well, I looked closely to this test, and it fails for a very good reason.
There is absolutely no guarantee that executor will start and finish method execution on mock in given time duration. (delay value used in test)
That's why from time to time this test will fail, because verification will be 'quicker' than executor.

**Comment by bric3** [comment]
Yes this is a time related test, the only thing we have done now is to augment the timeout.

There's ways to make the test deterministic though via some thread synchronisation, I'm thinking about `CountDownLatch` especially.

**Comment by lukasz-szewc** [comment]
Yet another undeterministic result.

`org.mockitousage.verification.VerificationAfterDelayTest > shouldReturnListOfArgumentsWithSameSizeAsGivenInAtMostVerification FAILED
    org.mockito.exceptions.base.MockitoAssertionError: Expected that more than 200ms elapsed! But was: 199ms
        at org.mockitoutil.Stopwatch.fail(Stopwatch.java:63)
        at org.mockitoutil.Stopwatch.assertElapsedTimeIsMoreThan(Stopwatch.java:45)
        at org.mockitousage.verification.VerificationAfterDelayTest.shouldReturnListOfArgumentsWithSameSizeAsGivenInAtMostVerification(VerificationAfterDelayTest.java:135)
`

**Comment by bric3** [comment]
Duplicate #548
Related issues / PR are #433, #446 and #451
