### ISSUE TITLE
Could not initialize class org.mockito.internal.util.MockUtil" - Maven , Mockito > 2.0.111-beta

### ISSUE THREAD

**Issue by dolendupes** [mockito/mockito#638]
I get a "java.lang.NoClassDefFoundError: **Could not initialize class org.mockito.internal.util.MockUtil"** when running junit tests in maven (fine in Eclipse) and using a mockito version > 2.0.111-beta.

**Environment**
- Mockito - 2.1.0-RC.1 (issue started after 2.0.111-beta)
- Maven - 3.3.9 (tests work in eclipse)
- JUnit - 4.12 + MockitoJUnitRunner
- JDK - 1.8.0_60-b27 

Happy to help triage but don't know what more to share at the moment.

**Comment by TimvdLippe** [comment]
`MockUtil` is an internal class you should not be relying on. The internal API is subject to change at all times, you should instead use the public APIs defined in all non-internal packages. Are you using `MockUtil` in production/your project?

**Comment by szczepiq** [comment]
@dolendupes, can you provide us a sample build that reproduces the problem? Is your code trying to initialize MockUtil class or is it one of the 3rd party libraries (like maven surefire plugin).

@ChristianSchwarz, can you help driving this issue to resolution? Static utility class refactoring might be connected to this problem.

Thanks!

**Comment by TimvdLippe** [comment]
@szczepiq Yes this is definitely related to the static utility as that was added in the 112 beta. However users should not rely on the internal class, so probably there is an equivalent public API available.

**Comment by szczepiq** [comment]
@TimvdLippe, absolutely. The problem gets interesting when 3rd party library depends on internal API. Users don't really have control over that 3rd party library, they just want to use use Mockito mocks ;)

**Comment by dolendupes** [comment]
@szczepiq Let me try and put together a project to demonstrate.  I would guess that it is "maven surefire" since the same tests work in eclipse.

**Comment by TimvdLippe** [comment]
Maven surefire does not seem to use MockUtil: https://github.com/apache/maven-surefire/search?utf8=✓&q=mockutil&type=Code

**Comment by ChristianSchwarz** [comment]
@dolendupes can you provide a stacktrace of the `NoClassDefFoundError`

**Comment by dolendupes** [comment]
Sure,

`java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.util.MockUtil
       	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
       	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
       	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
       	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
       	at org.mockito.Mockito.mock(Mockito.java:1544)
       	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
       	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
       	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:39)
       	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:63)
       	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:59)
       	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:43)
       	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:67)
       	at org.mockito.internal.runners.SilentJUnitRunner$1.withBefores(SilentJUnitRunner.java:29)
       	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:276)
       	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
       	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
       	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
       	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
       	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
       	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
       	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
       	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       	at org.mockito.internal.runners.SilentJUnitRunner.run(SilentJUnitRunner.java:39)
       	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:35)
       	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:104)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
       	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
       	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
       	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
       	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)`

Also see the following:
`java.lang.NoClassDefFoundError: net/bytebuddy/matcher/ElementMatcher
       	at org.mockito.internal.creation.bytebuddy.CachingMockBytecodeGenerator.<init>(CachingMockBytecodeGenerator.java:26)
       	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.<init>(ByteBuddyMockMaker.java:22)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       	at java.lang.Class.newInstance(Class.java:442)
       	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:31)
       	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:13)
       	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:12)
       	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
       	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
       	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
       	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
       	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
       	at org.mockito.Mockito.mock(Mockito.java:1544)
       	at org.mockito.Mockito.mock(Mockito.java:1457)
       	at com.pt.advertiser.domain.model.enrollment.EnrollmentNewTest.testEnrollmentAbandonedTriggersManualWorkoutIfAddressPopulated(EnrollmentNewTest.java:23)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
       	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
       	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
       	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
       	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
       	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
       	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
       	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
       	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
       	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
       	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
       	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
       	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
       	at org.mockito.internal.runners.SilentJUnitRunner.run(SilentJUnitRunner.java:39)
       	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:35)
       	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:104)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
       	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
       	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
       	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
       	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
       	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.matcher.ElementMatcher
       	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       	... 50 more`

**Comment by TimvdLippe** [comment]
Could you execute `mvn clean` and then run `mvn install` again?

**Comment by ChristianSchwarz** [comment]
@dolendupes Thanks for the stack traces! The class MockUtil & ElementMatcher  is not referenced from a 3rd party lib. Can you ensure that the tests are compiled agains the same mockito version you build process use?

**Comment by raphw** [comment]
Seems like you are missing Byte Buddy on the class path.

**Comment by dolendupes** [comment]
@raphw Works in eclipse and mockito-core should pull in byte-buddy.  See below:

`mvn dependency:tree | grep byte-buddy
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test
[INFO] |  \- net.bytebuddy:byte-buddy:jar:1.4.20:test`

**Comment by dolendupes** [comment]
@TimvdLippe The output was from a mvn clean install.

**Comment by dolendupes** [comment]
@ChristianSchwarz I'm running a local mvn clean install from the parent/anchor project.  Is there any other information I could provide to help?

**Comment by dolendupes** [comment]
I was able to create a simple set of files to reproduce bytebuddy.  Run mvn clean install with the following and it fails, change mockito version to 2.0.111-beta and the same fails.  Hope this helps in figuring out the MockUtil issue as well.  Apologies for the formatting.

	<modelVersion>4.0.0</modelVersion>
	<groupId>fail</groupId>
	<artifactId>app</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>2.1.0-RC.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class FailTest {
	@Mock FailInterface failInterface;

	@Test
	public void testFail() {
		failInterface.doSomething();
	}
}

interface FailInterface {
	public int doSomething();
}

**Comment by raphw** [comment]
I think that there is something broken in your local Maven setup. Maybe you have an incomplete version in your repository? If I recreate your setup, everything works out fine for me when building with Maven. Can you delete Byte Buddy and Mockito from your `.m2` repository and try again?

**Comment by bric3** [comment]
No problem here as well.

**Comment by dolendupes** [comment]
👍 Nothing to see here.  Maven was corrupted.  Part of me wants to find out why it was broken for several versions after 2.0.111, but the majority of me wants to not have to look at this agin.  Thanks again everyone.

**Comment by TimvdLippe** [comment]
Glad your issue has been resolved!

**Comment by szczepiq** [comment]
Impressive debugging effort. Fantastic guys, thank you!!!!

**Comment by rovkinmax** [comment]
I have the same problem when I use `RobolectricTestRunner` from version 3.1.2

```
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.util.MockUtil
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:62)
	at org.mockito.Mockito.mock(Mockito.java:1620)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:39)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:63)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:59)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:43)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:67)
	at ru.myproject.presenter.LoginPresenterTest.setUp(LoginPresenterTest.kt:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at ru.myproject.rule.RxSchedulersOverrideRule$apply$1.evaluate(RxSchedulersOverrideRule.kt:42)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:176)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:142)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)```

**Comment by bric3** [comment]
@rovkinmax Could it be a classpath issue as well ?

**Comment by rovkinmax** [comment]
@bric3 I don't understand what I need do. I use gradle and try stop all daemons, clear dependencies and redownload it. It not helped. Exception thrown when test executed

**Comment by bric3** [comment]
That's weird, what versions are used mockito and roboelectric ?

I fell this looks like an issue with RoboElectric itself (maybe related to mockito 2.1.0). We don't know much about Android platform.

Usually a `NoClassDefFoundError` means the class is not available on the classpath or that the class failed initialisation. In the later case there should be another stacktrace happening before that may indicates better what is the real problem behind.

**Comment by rovkinmax** [comment]
Robolectric version 3.1.2, Mockito version 2.1.0.

**Comment by bric3** [comment]
I didn't checkout the code to see how it works but the [`RoboelectrictestRunner`](https://github.com/robolectric/robolectric/blob/robolectric-3.1.2/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L198-L244) does a lot to transform classes, I wouldn't be surprised that their transformation failed. And as such `MockUtil` cannot be loaded anymore.

**Comment by noelmansour** [comment]
Some additional info that might be helpful: I didn't have this issue with Robolectric v3.1.4 until I added `mock-maker-inline`.

**Comment by SupperMutton** [comment]
I have the same problem,my "mockito-core" version is 2.15.0,so I try to added "mockito-core" to maven dependencies,there is still this mistake,and after this miastake I try to change version 2.15.0 to1.10.19, success!     ~~sorry, I can't use English too much,I hope guys can understand this solution.
