### ISSUE TITLE
OSGI bundle problem - incorrect version range syntax in manifest file

### ISSUE THREAD

**Issue by mgrafl** [mockito/mockito#678]
The mockito-core version 2.1.0 has an incorrect version range syntax for the Byte Buddy dependencies  in the _META-INF/MANIFEST.MF_ file. Consequently, the bundle cannot be loaded by OSGi (tested with equinox R-4.6). 

Actual: 
> net.bytebuddy;version="[1.4.26",...

Expected: 
> net.bytebuddy;version="[1.4.26,2.0)",...

On the other hand, the version ranges for Objensis dependencies are specified correctly. 

The problem originates from missing double quotes around the version specification in https://github.com/mockito/mockito/blob/v2.1.0/gradle/osgi.gradle#L19 

Stacktrace: 
> !MESSAGE Error installing bundle: reference:file:plugins/mockito-core.jar
> !STACK 0
> org.osgi.framework.BundleException: Error occurred installing a bundle.
	at org.eclipse.osgi.storage.Storage.install(Storage.java:562)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.installBundles(EclipseStarter.java:974)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.loadBasicBundles(EclipseStarter.java:583)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:319)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
Caused by: java.lang.IllegalArgumentException: invalid range "[1.4.26": invalid format
	at org.osgi.framework.VersionRange.<init>(VersionRange.java:173)
	at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.addPackageImports(OSGiManifestBuilderFactory.java:360)
	at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.getPackageImports(OSGiManifestBuilderFactory.java:339)
	at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.createBuilder(OSGiManifestBuilderFactory.java:87)
	at org.eclipse.osgi.container.builders.OSGiManifestBuilderFactory.createBuilder(OSGiManifestBuilderFactory.java:54)
	at org.eclipse.osgi.storage.Storage.getBuilder(Storage.java:604)
	at org.eclipse.osgi.storage.Storage.install(Storage.java:531)
	... 13 more
Caused by: java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(Unknown Source)
	at org.osgi.framework.VersionRange.<init>(VersionRange.java:157)
	... 19 more

**Comment by bric3** [comment]
OK thank you for the report ! And fix in #679

**Comment by ChristianSchwarz** [comment]
Now that #679 is closed this one can be closed too I guess.
