### ISSUE TITLE
Fails to create mock of inner class hierarchy with type variable from outer class

### ISSUE THREAD

**Issue by bric3** [mockito/mockito#699]
Reported on the mailing-list [here](https://groups.google.com/d/msg/mockito/KkErqUKB8PQ/LanMehSpAQAJ) by Thang

This bug exists in Mockito 2.1.0 and does not exists in 1.10.19. The issue seems related to how ByteBuddy gather type variables.

Here's how to I reproduced the issue : 

```java
public abstract class AbstractOuter<InputT, OutputT> {
    public abstract class AbstractInnerParent {
        public abstract InputT input();
        public abstract void output(OutputT output);
    }

    public abstract class AbstractInnerParentChild extends AbstractInnerParent { }
}
```

```java
@Test
public void should_not_fail_creating_mock_of_inner_class_with_type_variable_of_outer() {
    mock(AbstractOuter.AbstractInnerParentChild.class,
         withSettings().outerInstance(AbstractOuter.class));
}
```

This code produces the following stacktraces, VM is irrelevant here.

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class AbstractOuter$AbstractInnerParentChild.

Mockito can only non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : Azul Systems, Inc.
JVM vendor version : 25.102-b14
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_102-b14
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.11.6


Underlying exception : java.lang.IllegalStateException: Unknown type variable: OutputT

	at BugTest.should_not_fail_creating_mock_of_inner_class_with_type_variable_of_outer(BugTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException: Unknown type variable: OutputT
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding$TypeVariableSubstitutor.onType(TypeDescription.java:2183)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding$TypeVariableSubstitutor.onType(TypeDescription.java:2163)
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.accept(TypeDescription.java:7221)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding.onTypeVariable(TypeDescription.java:2136)
	at net.bytebuddy.description.type.TypeDescription$Generic$Visitor$Substitutor$ForTypeVariableBinding.onTypeVariable(TypeDescription.java:2095)
	at net.bytebuddy.description.type.TypeDescription$Generic$OfTypeVariable.accept(TypeDescription.java:5416)
	at net.bytebuddy.description.type.TypeDescription$Generic$LazyProjection.accept(TypeDescription.java:5857)
	at net.bytebuddy.description.method.ParameterDescription$TypeSubstituting.getType(ParameterDescription.java:858)
	at net.bytebuddy.description.method.ParameterList$AbstractBase.asTypeList(ParameterList.java:86)
	at net.bytebuddy.description.method.MethodDescription$AbstractBase.asTypeToken(MethodDescription.java:675)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Harmonized.of(MethodGraph.java:862)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default$Key$Store.registerTopLevel(MethodGraph.java:1059)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:569)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:548)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:562)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyze(MethodGraph.java:529)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.analyzeNullable(MethodGraph.java:548)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.doAnalyze(MethodGraph.java:562)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$Default.compile(MethodGraph.java:502)
	at net.bytebuddy.dynamic.scaffold.MethodGraph$Compiler$AbstractBase.compile(MethodGraph.java:423)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:478)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:160)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:153)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2568)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:2670)
	at org.mockito.internal.creation.bytebuddy.SubclassBytecodeGenerator.mockClass(SubclassBytecodeGenerator.java:80)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator$CachedBytecodeGenerator.getOrGenerateMockClass(TypeCachingBytecodeGenerator.java:87)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:34)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMockType(SubclassByteBuddyMockMaker.java:64)
	at org.mockito.internal.creation.bytebuddy.SubclassByteBuddyMockMaker.createMock(SubclassByteBuddyMockMaker.java:35)
	at org.mockito.internal.creation.bytebuddy.ByteBuddyMockMaker.createMock(ByteBuddyMockMaker.java:22)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:35)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:63)
	at org.mockito.Mockito.mock(Mockito.java:1620)
	... 28 more
```

------------------------

Original issue with Google Dataflow SDK

```xml
<dependency>
  <groupId>com.google.cloud.dataflow</groupId>
  <artifactId>google-cloud-dataflow-java-sdk-all</artifactId> 
  <version>1.8.0</version> 
</dependency> 
```

Mocked classe : [`DoFn.ProcessContext`](https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/v1.8.0/sdk/src/main/java/com/google/cloud/dataflow/sdk/transforms/DoFn.java)

```java
DoFn<String, ETEvent>.ProcessContext mockContext = 
    mock(DoFn.ProcessContext.class, withSettings().stubOnly().outerInstance(DoFn.class));
```

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.google.cloud.dataflow.sdk.transforms.DoFn$ProcessContext.

Mockito can only non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : Oracle Corporation
JVM vendor version : 25.91-b14
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 1.8.0_91-b14
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.11.6


Underlying exception : java.lang.IllegalStateException: Unknown type variable: OutputT
```

**Comment by raphw** [comment]
Its a bug in Byte Buddy, it does not capture the scope of the variables correctly.

**Comment by raphw** [comment]
I see what is happening here. Byte Buddy is asked to subclass an inner type what is not normally legal. A subclass must always be declared in the scope of its outer type. As Byte Buddy applies the Java rules for type variable resolution, such a variable cannot be found and the exception is thrown.

I need to detect such subclassing and rather apply the erasure as the variable does not technically exist for the mock class.

**Comment by raphw** [comment]
I have fixed this and will try to do a release some time this week.

**Comment by bric3** [comment]
@raphw You impersonate awesomeness itself !

**Comment by szczepiq** [comment]
Wow, thanks a lot guys for super quick turnaround!!!

**Comment by raphw** [comment]
@bric3 Maybe we should ask people to report to this issue tracker instead of the mailing list. I never read the latter.

Currently releasing a new version, fixing this some time today.

**Comment by bric3** [comment]
The user wasn't sure it was a bug at that time, Eric and I confirmed it.
