### ISSUE TITLE
Mockito 2 + Roboelectric

### ISSUE THREAD

**Issue by arturogutierrez** [mockito/mockito#703]
I'm using Mockito 2 to mock final (Kotlin) classes in a Java module in Android Studio without problems. But now, I wanted to also use Mockito 2 in Android module in order keep mocking final classes (hello Kotlin again), the thing is I'm getting an exception when launching the tests:

```
java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:35)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:120)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
```

Debugging `InlineByteBuddyMockMaker`, I saw that `dispatcher.getClassLoader()  != null`, here the snippet:

```
            try {
                Class<?> dispatcher = Class.forName("org.mockito.internal.creation.bytebuddy.MockMethodDispatcher");
                if (dispatcher.getClassLoader() != null) {
                    throw new MockitoException(join(
                            "The MockMethodDispatcher must not be loaded manually but must be injected into the bootstrap class loader.",
                            "",
                            "The dispatcher class was already loaded by: " + dispatcher.getClassLoader()));
```

Exactly, there is an instrumentation classloader provided by Roboelectric. But, funny thing is, if a launch the tests in command line instead of using Android Studio it works, but using a JUnit launch configuration in Android Studio (2.2.1) provokes the error.

Any idea how to avoid this error? or any workaround?

Thanks

**Comment by TimvdLippe** [comment]
I think this is related to https://github.com/robolectric/robolectric/issues/2677 It seems that RoboElectric is incompatible with Mockito 2 just yet. Unfortunately I have no more information to share at this moment :(

**Comment by arturogutierrez** [comment]
Thanks @TimvdLippe, that explains... 👍
