### ISSUE TITLE
Deep stubbing and UnnecessaryStubbingException

### ISSUE THREAD

**Issue by bschelberg** [mockito/mockito#756]
Mocks that return deep stubs sometimes cause UnnecessaryStubbingExceptions to be thrown, when I don't think that they should. Here's a small self-contained example.

```
package some.package;

import org.jboss.netty.channel.ChannelFuture;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Answers;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;

@RunWith(MockitoJUnitRunner.class)
public class MockitoDeepStubsTest {

    private final ClassUnderTest classUnderTest = new ClassUnderTest();

    @Mock(answer = Answers.RETURNS_DEEP_STUBS) private ChannelFuture mockChannelFuture;

    @Test
    public void shouldAllowDeepStubsUnnecessaryStubbing() {
        classUnderTest.methodUnderTest(mockChannelFuture);
    }

    public static class ClassUnderTest {

        public void methodUnderTest(ChannelFuture future) {
            future.getChannel().close();
        }

    }
}
```
Running this test prints the following output:
```
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 
Unnecessary stubbings detected in test class: MockitoDeepStubsTest
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at some.package.MockitoDeepStubsTest$ClassUnderTest.methodUnderTest(MockitoDeepStubsTest.java:25)
Please remove unnecessary stubbings. More info: javadoc for UnnecessaryStubbingException class.

	at org.mockito.internal.exceptions.Reporter.formatUnncessaryStubbingException(Reporter.java:838)
	at org.mockito.internal.junit.UnnecessaryStubbingsReporter.validateUnusedStubs(UnnecessaryStubbingsReporter.java:30)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:45)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:104)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Versions: Mockito 2.2.8
JDK: OpenJDK 1.8.0_111
OS: CentOS 7
Netty: 3.10.6.Final

I know that I can suppress the error with the Silent runner, but I like the unnecessary stubbing checking and don't really want to disable it. For now, we're working around it, but this doesn't seem like correct behaviour.

**Comment by szczepiq** [comment]
Fantastic bug report: reproducible sample, clear motivation. Thanks! I'm looking at it now.

**Comment by szczepiq** [comment]
I was able to repro this with a smaller example that does not use netty. It's a bug that needs to be fixed. Thank you for reporting!

```java
@RunWith(MockitoJUnitRunner.class)
public class MockitoDeepStubsTest {

    private final ClassUnderTest classUnderTest = new ClassUnderTest();

    @Mock(answer = Answers.RETURNS_DEEP_STUBS) private ChannelFuture mockChannelFuture;

    @Test
    public void shouldAllowDeepStubsUnnecessaryStubbing() {
        classUnderTest.methodUnderTest(mockChannelFuture);
    }

    public static class ClassUnderTest {
        void methodUnderTest(ChannelFuture future) {
            future.getChannel().close();
        }
    }

    interface ChannelFuture {
        Channel getChannel();
    }

    interface Channel {
        void close();
    }
}
```

**Comment by szczepiq** [comment]
@bschelberg, thank you for reporting! Stay tuned for Mockito 2.3.0 that will come with even better support for cleaner and easier to debug tests!
