### ISSUE TITLE
"mock-maker-inline" prevents collection of code coverage for spys

### ISSUE THREAD

**Issue by Godin** [mockito/mockito#757]
Hi,

Being one of [JaCoCo (Java Code Coverage Library)](http://www.jacoco.org/jacoco/index.html) developers, I was curious about interoperability of Mockito 2.2.x and JaCoCo on-the-fly instrumentation (using agent), so did some tests and came across following behavior:

with `mock-maker-inline`:
![mock-maker-inline](https://cloud.githubusercontent.com/assets/138671/20305994/94290260-ab38-11e6-96ed-5d274d06cdda.png)
without:
![normal](https://cloud.githubusercontent.com/assets/138671/20305987/8c27b174-ab38-11e6-9230-6fccaee64541.png)

Here is small example that reproduces this behavior - [example.zip](https://github.com/mockito/mockito/files/592003/example.zip) , `mvn clean verify` to run tests and generate JaCoCo report.

* Mockito 2.2.16
* JaCoCo 0.7.7
* JDK 8u102

As a workaround possible to use JaCoCo offline instrumentation (`mvn clean verify -Djacoco-offline` on the given example), but we don't recommend this mode and it is not available nor in EclEmma (plugin for Eclipse based on JaCoCo), nor when using JaCoCo in IntellIJ IDEA.

Also should be noted that the same happens for IntelliJ IDEA's own built-in coverage engine:

![intellij-mock-maker-inline](https://cloud.githubusercontent.com/assets/138671/20306440/8d6f6eb2-ab3a-11e6-9d07-e9a0108f8794.png)
vs
![intellij-normal](https://cloud.githubusercontent.com/assets/138671/20306446/93948e44-ab3a-11e6-9b73-ee4d78d3d55f.png)

Unfortunately, I didn't had time (yet) to dig deeper into code of Mockito to understand why this happens. Best guess based on investigation of similar issue with PowerMock: Mockito's agent bypasses other agents by reading class files from disk.

**Comment by TimvdLippe** [comment]
@Godin Your initial description is about code coverage in general, but this issue only affects mocks created with `@Spy` or `Mockito.spy` right?

**Comment by TimvdLippe** [comment]
On a different note: my expectation for the code coverage would be that `getName` does not have any coverage, since that method is mocked. So that means that nor the default mock maker nor the inline mock maker generate the correct coverage imo

**Comment by Godin** [comment]
@TimvdLippe 

> Your initial description is about code coverage in general, but this issue only affects mocks created with @Spy or Mockito.spy right?

Yes, given example is only about `Mockito.spy`. I do not expect to have coverage in case of complete mocks ;)

> On a different note: my expectation for the code coverage would be that getName does not have any coverage, since that method is mocked. So that means that nor the default mock maker nor the inline mock maker generate the correct coverage imo

Right. Expectation is to have coverage only for non-mocked method (`say`). I didn't noticed this before, being more focused on obvious difference between default mock maker and inline. Do you think that this case might be different in Mockito 1.x? I'll check.

**Comment by Godin** [comment]
@TimvdLippe hm, on given example Mockito 1.9.5 fails even without coverage:
```
java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:30)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:19)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.ClassPathLoader.loadImplementations(ClassPathLoader.java:145)
	at org.mockito.internal.configuration.ClassPathLoader.findPluginImplementation(ClassPathLoader.java:110)
	at org.mockito.internal.configuration.ClassPathLoader.findPlatformMockMaker(ClassPathLoader.java:106)
	at org.mockito.internal.configuration.ClassPathLoader.<clinit>(ClassPathLoader.java:59)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:21)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
	at org.mockito.Mockito.<clinit>(Mockito.java:932)
	at ExampleTest.test(ExampleTest.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 41 more
```

**Comment by TimvdLippe** [comment]
@Godin did you clean the directory and recompile? Sometimes lingering class files cause these problems.

**Comment by Godin** [comment]
@TimvdLippe I almost always do `mvn clean verify`. But double checked and failure was in presence of `src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker`. No failure after removal and result remains the same as for 2.2.x - both methods marked as covered.

**Comment by Godin** [comment]
@TimvdLippe Ouch, my bad - I'm probably setup spy incorrectly, sorry, I'll recheck everything.

**Comment by Godin** [comment]
@TimvdLippe after correction of example ( [example.zip](https://github.com/mockito/mockito/files/592106/example.zip) ) as
```diff
@@ -5,7 +5,7 @@ public class ExampleTest {
   @Test
   public void test() {
     Example spy = spy(new Example());
-    when(spy.getName()).thenReturn("spy");
+    doReturn("spy").when(spy).getName();
     spy.sayHello();
   }
 }
```

**Mockito 1.9.5**, **1.10.19** and **2.2.16 with default mock maker** as expected:
![normal](https://cloud.githubusercontent.com/assets/138671/20308310/922b2816-ab43-11e6-8147-ed07d94e8ba8.png)

**2.2.16 with inline mock maker** still no coverage.

**Comment by raphw** [comment]
Well, we added a hack to read the original class file instead of the pre-instrumented class file in order to retain parameter name information which is currently erased due to a bug in the VM: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8168623

We basically can support parameter names or the combination with other agents. We cannot do both.

**Comment by Godin** [comment]
@raphw unless JDK bug is fixed? 😉 

From a code coverage point of view hard to say if this is important case for users or not. And we probably won't know till the moment of wide adoption of inline mock maker. But could be noted that the fact that PowerMock reads classes from disk still creates a lot of noise around and questions from JaCoCo users.

P.S. probably was possible to discuss this with you at JokerConf, but I'm slowpoke

**Comment by raphw** [comment]
The question is: even if this gets fixed, how quickly will people adopt Java 9 VMs? This bug is a bit of a headache.

PS: Always good to have things documentated in the open instead of floor talk ;)

**Comment by Godin** [comment]
@raphw wondering why you exclude possibility of backport from 9 at least to 8?

**Comment by raphw** [comment]
Maybe they do it but there are quite some instrumentation-API-related issues that are currently fixed in 9 but not in 8. I have my doubts.

**Comment by Godin** [comment]
As a crazy idea 😈  - combine class bytes from disk with bytes from agent to overcome this bug?

**Comment by raphw** [comment]
Would be possible in theory, Byte Buddy can represent the class file as a `TypeDescription` and read all parameter names. It would then be possible to register a `Transformer` for any method to add the parameter meta data in the created class.

**Comment by raphw** [comment]
Ok, I could not let it go. Could you try out this one: https://github.com/mockito/mockito/tree/parameter-experiement

**Comment by Godin** [comment]
Seems that it works! :thumbsup: I guess that test will be added before merge? :wink:

**Comment by SPY** [comment]
I've never used java and mockito, but I read the issues here so often(due to mentioning). Maybe I should start contribute here.

**Comment by raphw** [comment]
@Godin Non-trivial to test as we need a class that was explicitly compiled with parameters but I probably add something that is precompiled. I try to get this merged some time soon.

**Comment by Godin** [comment]
@raphw Cool! Thank you. Feel free to ping me, if you'll need some additional testing.

**Comment by raphw** [comment]
Ok, the patch is out. I could also add a test for this, in the end, we have a code generation library on the class path ;)

**Comment by TimvdLippe** [comment]
Issue opened and closed within 6 hours. New record? 🎉

**Comment by bric3** [comment]
@raphw wow ! That was fast, it reminds me of some movie ;)

![matrix-bugs](https://cloud.githubusercontent.com/assets/803621/20342458/c0d6cbe6-abea-11e6-86e0-07ea1521ba3c.gif)
