### ISSUE TITLE
Merge commits with [ci skip] should not trigger release

### ISSUE THREAD

**Issue by szpak** [mockito/mockito#784]
I'm a little bit concerned about [ci skip] comment in a commit which I [supposed](https://github.com/mockito/mockito-release-tools/blob/9a0fa73ad0face74d824477b6d32dba850eb4507/src/main/groovy/org/mockito/release/notes/vcs/IgnoreCiSkip.java) surpass a release of the new version of Mockito. 

Two days ago my [merge commit](https://github.com/mockito/mockito/commit/1d09b3e628f0f12dab269d4bff167c9c19b40ea9) with this tag did not caused version to be released. Today, that [commit](https://github.com/mockito/mockito/commit/d0efa8c901af187fbaa7f6e4cc52c5c3e7aece15) triggered a new version. Is it a bug in mockito-release-tools?

Later on I have recalled `[ci skip-release]` tag. I will try to use it another time.

**Comment by szczepiq** [comment]
Did merge commit bring other commits without "ci skip" tag?

**Comment by bric3** [comment]
When `ci skip` is in the commit message, travis should not run the build at all, however it seems Travis ignores `ci skip` of merge commits.

If we explore the build history we find that 

* #783 https://travis-ci.org/mockito/mockito/builds/179172589 did trigger a build
* #778 https://travis-ci.org/mockito/mockito/builds/178937222 did trigger a build
* ...

#778 did bring some changes. And the build should have released something but the release job [failed due to an SSL exception](https://travis-ci.org/mockito/mockito/jobs/178937223#L436)

However it may be sensible to add ci-skip support in our gradle build.



It seems the PR #778 did bring some change, however `ci skip` indicates to travis to skip the build, my question is why travis did start the build then it does not even show up in https://travis-ci.org/mockito/mockito/builds, while previous merge commits are there.

However it seems travis ignores the `ci skip` for merge commits as it did launch the build for 
https://travis-ci.org/mockito/mockito/builds/179172589,

**Comment by TimvdLippe** [comment]
That seems to be https://github.com/travis-ci/travis-ci/issues/6669

**Comment by bric3** [comment]
For information travis updated the [OpenJDK 6 to build 40](https://travis-ci.org/mockito/mockito/jobs/183531262#L197) which seems to fix security issues and probably update root certificates as well.

That seems to fix the `SSLHandshakeException` appearing in some jobs running on OpenJDK 1.6.0_b39 (https://travis-ci.org/mockito/mockito/jobs/180397538)

```
$ jdk_switcher use openjdk6
Switching to OpenJDK6 (java-1.6.0-openjdk-amd64), JAVA_HOME will be set to /usr/lib/jvm/java-6-openjdk-amd64
$ export TERM=dumb
cache.1
Setting up build cache
$ export CASHER_DIR=$HOME/.casher
0.06s$ Installing caching utilities
0.00s
1.48sattempting to download cache archive
fetching android-mock/cache-linux-precise-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--jdk-openjdk6.tgz
found cache
0.00s
8.64sadding /home/travis/.gradle/caches to cache
adding /home/travis/.gradle/wrapper to cache
$ java -Xmx32m -version
java version "1.6.0_39"
OpenJDK Runtime Environment (IcedTea6 1.13.11) (6b39-1.13.11-0ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
$ javac -J-Xmx32m -version
javac 1.6.0_39
before_install.1
0.01s$ export TRAVIS_COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
before_install.2
0.00s$ echo "$TRAVIS_COMMIT_MESSAGE"
Revert Travis configuration and configure jar publication
install
0.00s$ true
10.72s$ ./gradlew ciBuild release -Dscan
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Support for running Gradle using Java 6 has been deprecated and will be removed in Gradle 3.0
Parallel execution is an incubating feature.
:buildSrc:clean UP-TO-DATE
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar
:buildSrc:assemble
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build
Version: 2.2.23
FAILURE: Build failed with an exception.
* Where:
Build file '/home/travis/build/mockito/mockito/subprojects/android/android.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':android'.
> Cannot configure the 'publishing' extension after it has been accessed.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 9.072 secs
Publishing build information...
A network error occurred publishing to: https://scans-in.gradle.com/in/2.14.1/1.0
Your network environment may be preventing transmission.
The following is the error trace which may help diagnose the issue:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.gradle.scan.a.a.a.a.a(SourceFile:97)
	at com.gradle.scan.a.a.a.a.a(SourceFile:47)
	at com.gradle.scan.plugin.internal.c.a.a(SourceFile:38)
	at com.gradle.scan.plugin.internal.l.a(SourceFile:39)
	at com.gradle.scan.plugin.b.buildFinished(SourceFile:146)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:249)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:229)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:221)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:209)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy10.buildFinished(Unknown Source)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 58 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	... 58 more
The command "./gradlew ciBuild release -Dscan" exited with 1.
```

**Comment by bric3** [comment]
Maybe not, it seems there's still issues when uploading some gradle scans.

**Comment by szczepiq** [comment]
Can we close this ticket?

**Comment by TimvdLippe** [comment]
The upstream issue of Travis has not been closed yet. Unsure what we can do from our part.

**Comment by TimvdLippe** [comment]
This is now filed in Shipkit under https://github.com/mockito/shipkit/issues/536
