### ISSUE TITLE
A ClassCastException of unrelated objects while injecting mocks in Android Robolectric test (Robolectric Runner and Activity)

### ISSUE THREAD

**Issue by mkoslacz** [mockito/mockito#790]
**Mockito Version: 2.2.22
jdk Version: 1.8.0_91
Mosby Version: 2.0.1
Robolectric Version: 3.1.4
Android SDK Version: 23, 25 with robolectric SDK set to 23 or 21, probably others
OS: macOS Sierra 10.12, Fedora Linux (some of the latest releases, will provide the exact version soon), probably others**

We have encountered a problem while developing [Robolectric](https://github.com/robolectric/robolectric) tests using Mockito to inject mocked [Mosby](https://github.com/sockeqwe/mosby) Presenter to Mosby MVP Activity.
We create a shadow of a UserDetailsActivity using Robolectric. After that we inject a Presenter mock to the mentioned Robolectric shadow of Activity. The problem is that when we try to call a `Activity#onCreate()` method, there is an issue with casting a mocked Presenter to Robolectric ShadowActivity.

The exception is kinda strange, because the mocked Presenter should have nothing in common with the Robolectric Activity.

You can see my test class below, and it's hosted [here](https://github.com/mkoslacz/Moviper/blob/c24420fb1256c29ace89bee6c82ed291c156077a/rxsample/src/test/java/com/mateuszkoslacz/moviper/rxsample/viper/view/activity/ListingActivityTest.java#L57). The UserDetailsActivity class extends Mosby's MvpActivity.
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class UserDetailsActivityTest {

    @Mock
    private UserDetailsPresenter mPresenter;

    @InjectMocks
    private UserDetailsActivity mActivity;

    @Before
    public void setup() {
        ActivityController<UserDetailsActivity> controller = Robolectric.buildActivity(UserDetailsActivity.class);
        mActivity = controller.get();
        MockitoAnnotations.initMocks(this);
        controller.create();
    }

    @Test
    public void testOnViewCreated_shouldCallPresenterOnViewCreated() {
        Mockito.verify(mPresenter).onViewCreated();
    }
}
```

When the `controller.create()` is called, the test fails and a following cast exception appears:
```ruby
java.lang.ClassCastException: Cannot cast com.mateuszkoslacz.moviper.rxsample.viper.presenter.UserDetailsPresenter$MockitoMock$679472448 to org.robolectric.shadows.ShadowActivity

	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361)
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356)
	at android.app.Activity.getWindow(Activity.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:525)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:74)
	at com.hannesdorfmann.mosby.mvp.MvpActivity.onCreate(MvpActivity.java:41)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.UserDetailsActivity.onCreate(UserDetailsActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:356)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at com.mateuszkoslacz.moviper.rxsample.viper.view.activity.UserDetailsActivityTest.setup(UserDetailsActivityTest.java:36)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

It's thrown while trying to go through (or in) this return statement:
```java
    /**
     * Create a {@link android.support.v7.app.AppCompatDelegate} to use with {@code activity}.
     *
     * @param callback An optional callback for AppCompat specific events
     */
    public static AppCompatDelegate create(Activity activity, AppCompatCallback callback) {
        return create(activity, activity.getWindow(), callback);
    }
```
Actually, the arguments of this method look fine in a debugger:
![zrzut ekranu 2016-11-26 o 11 33 39](https://cloud.githubusercontent.com/assets/7924595/20639747/4824e8ec-b3cc-11e6-8ee9-9f7eecdf9da5.png)

It could be suspicious that arguments here are not listed as a shadow of the Activity, but as the Activity itself.

We have created issues in Mosby ([here](https://github.com/sockeqwe/mosby/issues/179)) Robolectric ([here](https://github.com/robolectric/robolectric/issues/2726)) repos, but still, no clue.

What could possibly cause this exception? Any suggestions?

**Comment by bric3** [comment]
Hi @mkoslacz, nice issue report !

However I can't answer your question, I don't think any mockito developers are actual android developers. Anyway looking at the stack trace I see no mockito code involved here, it looks rather related to roboelectric code. I don't know how work Roboelectric, but I'm puzzled by why `Robolectric.buildActivity(UserDetailsActivity.class)` is executed before `initMocks`.

**Comment by raphw** [comment]
This seems like a Robolectric issue to me, too.

**Comment by mkoslacz** [comment]
@bric3, `buildActivity` is called before `initMocks` because of the order of `ActivityController<UserDetailsActivity> controller = Robolectric.buildActivity(UserDetailsActivity.class);` and `MockitoAnnotations.initMocks(this);` lines in the `setup()` method:


```java
    @Before
    public void setup() {
        ActivityController<UserDetailsActivity> controller = Robolectric.buildActivity(UserDetailsActivity.class);
        mActivity = controller.get();
        MockitoAnnotations.initMocks(this);
        controller.create();
    }
```

Take note that we're not using a Robolectric test runner here.


Well, yes, I was kinda aware that I'll rather find pure Java devs here, but I'm still looking for a solution for this problem, as both Mockito and Robolectric are really great to use in tests.

@raphw, @jongerrish mentioned in Robolectric issue that it's probably caused by incompatibility between Mockito and Robolectric bytecode wrangling. He referenced following issues:

[#2677](https://github.com/robolectric/robolectric/issues/2677)
[#2429](https://github.com/robolectric/robolectric/issues/2429)
[#2442](https://github.com/robolectric/robolectric/issues/2442)

I wonder if it's possible to make these libs compatible, and if yes, in which of them changes needs to be done.

**Comment by bric3** [comment]
@mkoslacz I can read the before method code, but I may express myself better ;) By "executed" I meant the statement order. But I probably bugged there as well...

**Comment by bric3** [comment]
I'm closing the issue as it is related to roboelectric, if they need to rech to us for some modification then so be it ;)
