### ISSUE TITLE
Exception when using mock-maker-inline

### ISSUE THREAD

**Issue by vyazelenko** [mockito/mockito#824]
I was trying out `mock-maker-inline` feature with the following example:
```java
import static org.mockito.Mockito.*;

final class FinalClass {
  int m1() {
    throw new RuntimeException("42");
  }
}

public class TestMockFinal {
  public static void main(String[] args) {
    FinalClass cl = mock(FinalClass.class);
    when(cl.m1()).thenReturn(-1);
    if (cl.m1() != -1) {
      throw new Error("Not mocked!");
    }
  }
}
```

When I run this code I get the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
	at org.mockito.Mockito.mock(Mockito.java:1665)
	at org.mockito.Mockito.mock(Mockito.java:1578)
	at TestMockFinal.main(TestMockFinal.java:11)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@379619aa
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:86)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:40)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
	... 8 more
Caused by: java.lang.IllegalStateException: Error during attachment using: ByteBuddyAgent.AttachmentProvider.Compound{attachmentProviders=[ByteBuddyAgent.AttachmentProvider.ForJigsawVm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForJ9Vm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JVM_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JDK_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.MACINTOSH]}
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:314)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:280)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:248)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:234)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:81)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:301)
	... 21 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 26 more
```

Environment:
- Windows 7 (64 bit)
- JDK 1.8.0_112 (64 bit)
```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```
- Mockito 2.3.4
- ByteBuddy 1.5.5 (transitive from Mockito)

**Comment by vyazelenko** [comment]
@bric3 well, it is Mockito 2.3.4 as I've mentioned in the original comment and the corresponding ByteBuddy version which according to [mockito-core-2.3.4.pom](http://central.maven.org/maven2/org/mockito/mockito-core/2.3.4/mockito-core-2.3.4.pom) is *1.5.5*.

**Comment by vyazelenko** [comment]
@bric3 Unfortunately using [byte-buddy-1.5.9](https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.5.9) didn't help. I get similar exception:
```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
	at org.mockito.Mockito.mock(Mockito.java:1665)
	at org.mockito.Mockito.mock(Mockito.java:1578)
	at TestMockFinal.main(TestMockFinal.java:11)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@53bd815b
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:86)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:40)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
	... 8 more
Caused by: java.lang.IllegalStateException: Error during attachment using: ByteBuddyAgent.AttachmentProvider.Compound{attachmentProviders=[ByteBuddyAgent.AttachmentProvider.ForJigsawVm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForJ9Vm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JVM_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JDK_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.MACINTOSH, ByteBuddyAgent.AttachmentProvider.ForUnixHotSpotVm.INSTANCE]}
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:314)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:280)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:248)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:234)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:81)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:301)
	... 21 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 26 more
```

**Comment by vyazelenko** [comment]
Also fails with release [2.3.5](https://github.com/mockito/mockito/tree/v2.3.5).

**Comment by bric3** [comment]
Thanks @vyazelenko 
I'm not sure what's wrong here. Maybe @raphw has a better idea. Do you think you can debug the agent installation `net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:314)` ? Preferrably with ByteBuddy 1.5.9 as the fix will go after this version.

**Comment by raphw** [comment]
The problem is here:

```cmd
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

Mockito is typically used on a JDK VM, the regular VM does not support the tools jar which is required for runtime attachment. You can avoid this problem by attaching [the Byte Buddy agent](http://search.maven.org/#artifactdetails%7Cnet.bytebuddy%7Cbyte-buddy-agent%7C1.5.9%7Cjar) manually via `-javaagent:byte-buddy-agent.jar` upon running your program.

**Comment by bric3** [comment]
@raphw But the description also says : JDK 1.8.0_112 (64 bit).

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

Could come from the command line, and on the comand line maybe the PATH is looking at the JRE instead of the JDK.

**Comment by raphw** [comment]
Yes, I revised my answer after googling a bit. Seems like an Eclipse debugger issue.

**Comment by bric3** [comment]
Ah interesting.

**Comment by vyazelenko** [comment]
I have created a reproducer project [mockito-mock-maker-inline-dynamic-attach](https://github.com/vyazelenko/mockito-mock-maker-inline-dynamic-attach).
It provides single gradle command `dist` that will generate scripts to execute test program from command line on Windows and Unix systems.

**Comment by raphw** [comment]
I just debugged this on a virtual Windows box and I think I understand what happens:

First, everything went as expected. I could run the program and did not get the exception you experienced. I then installed an additional non-JDK JVM to see if the VM reproduced your problem. This was the case and I thought, this was your problem for sure.

To be sure, I retried it now with the JDK installation and it did no longer work. To my surprise, the installation had set some `..\ProgramData\Oracle\Java\...` folder in my user's hidden folder and overrode the `JAVA_HOME` property even if I set it to the proper place. I had to manually remove this folder and adjust my Windows `PATH` before I could run the above program with the installation specified at `JAVA_HOME`.

The best part is that even without doing this, `java -version` shows the value of `JAVA_HOME`, not the one set on the Windows path. If you call `System.gerProperty("java.home")` from a program you run with `java`, you can however see the actual value.

The longer exception you see is a small issue in Byte Buddy that does however not change the outcome of the attachment. On Unix, if no JDK is available, Byte Buddy attempts to use its own attachment implementation. On Windows, this is impossible and would result in another `IllegalStateException`.

**Comment by vyazelenko** [comment]
@raphw you are absolutely right!

If I print `JAVA_HOME` variable I get:
``` 
P:\>echo %JAVA_HOME%
c:\Program Files\Java\jdk1.8.0_112\
```
But when I run test program which prints `System.getProperty("java.home")` I get the following:
``` 
java.home=C:\Program Files\Java\jre1.8.0_112
```
This happens, because I'm always installing JDK with JRE from the same installer. Installer first installs JDK and then installs JRE. What I do then is set `JAVA_HOME` to point to newly installed JDK and always include `JAVA_HOME\bin` into `PATH` variable.
However when I print  `PATH` variable I see the following:
``` 
P:\>echo %PATH%
C:\ProgramData\Oracle\Java\javapath
...
c:\Program Files\Java\jdk1.8.0_112\\bin
...
```
The very first entry is this magic `C:\ProgramData\Oracle\Java\javapath` which is apparently breaking everything.

**Comment by vyazelenko** [comment]
After I uninstalled everything it works now from command line but still fails in Eclipse.
```
java.home=C:\Program Files\Java\jdk1.8.0_112\jre
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
	at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
	at org.mockito.Mockito.mock(Mockito.java:1665)
	at org.mockito.Mockito.mock(Mockito.java:1578)
	at test.TestMockFinal.main(TestMockFinal.java:14)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@53bd815b
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:86)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:40)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
	... 8 more
Caused by: java.lang.IllegalStateException: Error during attachment using: ByteBuddyAgent.AttachmentProvider.Compound{attachmentProviders=[ByteBuddyAgent.AttachmentProvider.ForJigsawVm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForJ9Vm.INSTANCE, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JVM_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.JDK_ROOT, ByteBuddyAgent.AttachmentProvider.ForToolsJarVm.MACINTOSH, ByteBuddyAgent.AttachmentProvider.ForUnixHotSpotVm.INSTANCE]}
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:314)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:280)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:248)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:234)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:81)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:301)
	... 21 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: no providers installed
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
	... 26 more
```

And it happens when I run it in debug mode (`Debug As -> Java Application`) and without it (`Run As -> Java Application`).

**Comment by bric3** [comment]
Could it be that the Eclipse sdk is misconfigured.

**Comment by vyazelenko** [comment]
@bric3 No, cause I've uninstalled all JRE's from the system and there is only 1 JDK installation on the system which is also configured in the Eclipse's workspace.

**Comment by jpenglert** [comment]
Adding this comment in case it helps others who want to use a JRE to run their tests with MockMaker plugin enabled.

Our company uses a JRE checked into VCS to run tests locally and in CI. This is the same JRE we ship embedded with our app installers. This is nice because it allows us to ensure the everyone is using the same JRE that gets shipped in production to run tests. Since MockMaker requires a JDK (well, only a few pieces), using it doesn't work in our situation. After a bit of research I discovered all that's needed is "tools.jar" from `JDK/lib` and `attach.dll` from `JRE/bin`. So, we can simply check "tools.jar" and "attach.dll" into VCS without having to check in the entire JDK. Below is the gradle solution we have to use a JRE (plus tools.jar) to run our tests with MockMaker plugin enabled:

    String jre = rootProject.file("$relativePathToRoot/JavaLauncher/jre").absolutePath
    String jdk = rootProject.file("$relativePathToRoot/JavaLauncher/jdk").absolutePath
    String jreBin = rootProject.file("$jre/bin").absolutePath // This has "attach.dll"
    String jreLib = rootProject.file("$jre/lib").absolutePath
    FilenameFilter jarFilter = {dir, file -> file.endsWith(".jar")} as FilenameFilter
    tasks.withType(Test) {
      executable = "$jreBin/java"
      bootstrapClasspath files(new File("$jreLib").listFiles(jarFilter))
      bootstrapClasspath files(new File("$jreLib/ext").listFiles(jarFilter))
      
      // The JDK "lib" dir is needed to support Mockito's MockMaker plugin to mock final classes.
      // Specifically tools.jar (which references jre/lib/attach.dll) is needed.
      bootstrapClasspath files(new File("$jdk/lib").listFiles(jarFilter))
    }
