### ISSUE TITLE
Failed Resolution of: Ljava/lang/management/ManagementFactory on Android

### ISSUE THREAD

**Issue by eygraber** [mockito/mockito#841]
I'm using Mockito 2.3.11 and mockito-kotlin 1.0.1 (nhaarman) in my espresso tests on Android, and I have a property in my test class that looks like this (I'm using Kotlin in both the tests and the code under test):

```
val controller: Controller = mock()
```

Running the tests (there is only one and all it does is verify that a call was made using controller) results in a NoClassDefFoundError:

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
at net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm$ForLegacyVm.resolve(ByteBuddyAgent.java:728)
at net.bytebuddy.agent.ByteBuddyAgent$ProcessProvider$ForCurrentVm.resolve(ByteBuddyAgent.java:708)
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:280)
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:248)
at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:234)
at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.<init>(InlineByteBuddyMockMaker.java:101)
at java.lang.Class.newInstance(Native Method)
at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:81)
at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:40)
at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:18)
at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:17)
at org.mockito.internal.configuration.plugins.Plugins.getMockMaker(Plugins.java:33)
at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:168)
at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:162)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:64)
at org.mockito.Mockito.mock(Mockito.java:1665)
at org.mockito.Mockito.mock(Mockito.java:1578)
at com.myapp.LaunchActivityTest.<init>(LaunchActivityTest.kt:66)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myapp.test-2/base.apk", zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.test-2/lib/arm64, /data/app/com.myapp-1/lib/arm64, /system/lib64, /vendor/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 48 more
```

**Comment by eygraber** [comment]
I also have dexmaker-mockito 2.2.0 as a dependency

**Comment by bric3** [comment]
Hi, what is the VM the test is running on.

Also from the look of it, the code is enforcing the inline mock maker, which only works on a Java VM as [documented](https://static.javadoc.io/org.mockito/mockito-core/2.2.7/org/mockito/Mockito.html#Mocking_Final).

You may have to remove that file if the code is running on dalvik.

**Comment by eygraber** [comment]
Yeah, it's running on Android; not sure how I missed that in the documentation. Will `mockito-android` allow mocking finals on dalvik?

**Comment by bric3** [comment]
I don't know enough on that, @raphw as you are the author of bytebudy-android, do you know if it is possible ?

**Comment by raphw** [comment]
Android only supports a subset of the Java APIs, not including the instrumentation API that is required for the inline mock maker. It cannot be used on Android.
