### ISSUE TITLE
When custom exception fillInstackTrace() returns null, Exception mock cannot work properly

### ISSUE THREAD

**Issue by wuwen5** [mockito/mockito#866]
```java
public class CustomException extends Exception {

    public CustomException() {
        super();
    }

    @Override
    public Exception fillInStackTrace() {
        return null;
    }
}
```

TestCase like this
```java
 when(demo.process()).thenThrow(new CustomException())

//... test code
```

```
java.lang.NullPointerException
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.filter(ConditionalStackTraceFilter.java:23)
	at org.mockito.internal.stubbing.answers.ThrowsException.answer(ThrowsException.java:32)
	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:35)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:95)
```

**Comment by bric3** [comment]
This is a bug in the user code. Yet Mockito should handle that gracefully.

Thanks for reporting.
