### ISSUE TITLE
Collection being changed after call throws off the verify results

### ISSUE THREAD

**Issue by dclements** [mockito/mockito#967]
If a collection being acted on is mutated after the verification call, it will cause the verifications to verify against the wrong value (post modification) instead of at the time of the call being verified. 

Mockito Version: `org.mockito:mockito-core:2.7.11`, Java Version = 1.8.0_112. Guava version 21.0 (shouldn't matter). OS X 10.12.3. Problem occurs both through IntelliJ and on the command line using sbt (sbt version 0.13.13, scala version 2.12.1). 

Code demonstrating the problem on my machine:

```java
import com.google.common.collect.Lists;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import java.util.List;

import static org.mockito.Mockito.verify;

@RunWith(MockitoJUnitRunner.class)
public class DemoTest {
    interface Demonstration {
        void operator(List<String> value);
    }

    @Mock
    private Demonstration call;

    //This will pass
    @Test
    public void call_List_TestPasses() {
        List<String> values = Lists.newArrayList("test");
        List<String> values2 = Lists.newArrayList("test");

        call.operator(values);

        verify(call).operator(values2);
    }

    //I expect this to pass and it fails. 
    @Test
    public void call_List_ListIsCleared_TestPasses() {
        List<String> values = Lists.newArrayList("test");
        List<String> values2 = Lists.newArrayList("test");

        call.operator(values);

        values.clear();

        verify(call).operator(values2);
    }
}

```

The result: 

```
Argument(s) are different! Wanted:
call.operator([test]);
-> at DemoTest.call_List_ListIsCleared_TestPasses(DemoTest.java:39)
Actual invocation has different arguments:
call.operator([]);
-> at DemoTest.call_List_ListIsCleared_TestPasses(DemoTest.java:35)

Comparison Failure: 
Expected :call.operator([test]);
Actual   :call.operator([]);
 <Click to see difference>

Argument(s) are different! Wanted:
call.operator([test]);
-> at DemoTest.call_List_ListIsCleared_TestPasses(DemoTest.java:39)
Actual invocation has different arguments:
call.operator([]);
-> at DemoTest.call_List_ListIsCleared_TestPasses(DemoTest.java:35)

	at DemoTest.call_List_ListIsCleared_TestPasses(DemoTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:68)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:74)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

check that

 - [x] The mockito message in the stacktrace have useful information, but it didn't help
 - [x] The problematic code (if that's possible) is copied here;
       Note that some configuration are impossible to mock via Mockito
 - [x] Provide versions (mockito / jdk / os / any other relevant information)
 - [x] Provide a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) of the issue
       (same as any question on stackoverflow.com)
 - [x] Read the [contributing guide](https://github.com/mockito/mockito/blob/master/.github/CONTRIBUTING.md)

**Comment by raphw** [comment]
This is expected behavior. By default, Mockito compares arguments by their equality. If this is not what you want, compare them by any other matcher, for example by object identity. Have a look at the Mockito class that offers a buch of matters or lookat its argThat method that provides its own.

**Comment by damien-git** [comment]
I did not find a workaround for this issue. Using refEq or argThat doesn't change anything, verify passes the modified object. There should be a way to test calls (parameter values and times) without changing a valid code that modifies the passed object. Ideally there would be a way to clone it during the call, and check the cloned object values in verify(). Maybe there is a way to do that ?

**Comment by raphw** [comment]
You can test for identity by using your own, custom matcher.

**Comment by ahawtho** [comment]
I also ran into this same issue. In my example, I'm working with a 3rd party API where I accumulate state and then flush the state to the API:
```
interface Flusher {
    void flush(List<Record> r);
}
public class Committer {
    private List<Record> records = new ArrayList<>();
    private Flusher api;
    public Committer(Flusher f) {
        this.api = f;
    }

    public void commitRecord(Record r) {
        records.add(r);
    }

    public void flush() {
        api.flush(records);
        records.clear();
    }
```

I don't want to incur the heap penalty of reallocating `records`. Since this is invoked in batches of records, I want to test various combinations of batches. I planned to write a table-driven test:

```
Record b1r1 = new Record("b1r1");
Record b1r2 = new Record("b1r2");
Record b1r3 = new Record("b1r3");

Record b2r1 = new Record("b2r1");
Record b2r2 = new Record("b2r2");

Record b3r1 = new Record("b3r1");

// ... set up record batches and verifications, imagine multiple rows:
List<List<Record>> batches = Arrays.asList(
    Arrays.asList(b1r1, b1r2, b1r3),
    Arrays.asList(b2r1, b2r2),
    Arrays.asList(b3r1));
List<java.util.function.Consumer<Flusher>> verifications = Arrays.asList(
    f -> verify(f).flush(Arrays.asList(b1r1, b1r2, b1r3),
    f -> verify(f).flush(Arrays.asList(b2r1, b2r2),
    f -> verify(f).flush(Arrays.asList(b3r1));

Flusher f = Mockito.mock(Flusher.class);
Committer c = new Committer(f);
for (List<Record> batch : batches) {
    for (Record r : batch) {
        c.commitRecord(r);
    }
    c.flush();
}

verifications.stream().forEach(v -> v.consume(f));
```

This fails because the mock does not provide a way to copy the argument on each call to `Flusher.flush(List<Record>)` . To use a matcher, I will need to specify the matcher using `doNothing().when(f).ack(myMatcher(records));` and then verify both the number of calls to `flush()` and that each of the arguments for each call was correct. This makes the table test much messier. The shared state between setup/verification requires external coordination. Ironically, I find the test setup becomes more complex than the code being tested.

To make this easier, one can imagine a way to specify on the mock that it attempt to clone its arguments, or at least to specify this behavior in `when()` . Note that I am not concerned about the identity of the argument, so an identity matcher is not sufficient. Also, `ArgumentCaptor` is not sufficient as it too does not copy the argument. The behavior is hidden in the implementation of the mocked methods themselves.
