### ISSUE TITLE
Wrong actual invocation shown using a hamcrest matcher

### ISSUE THREAD

**Issue by jOlliv** [mockito/mockito#970]
I got a strange behaviour using a hamcrest matcher with mockito and I assume this is a bug.
used versions:
mockito-core-2.7.12
byte-buddy-1.6.9
objenesis-2.5
jdk 1.8.0_121
junit-4.10

With the following code wrong actual invocations are shown by mockito and the test failed. But I would expect that it will be successful.
The printed lines shows the executed code:

    ### create: 1
    ### update: 2
    ### update: 3

But mockito says:

    Argument(s) are different! Wanted:
    mockRepository.create(
        a state entity with description "1"
    );
    -> at hamcrest_matching.ServiceTest.test(ServiceTest.java:49)
    Actual invocation has different arguments:
    mockRepository.create(
        StateEntity{id=21008411305506, description='3'}
    );
    -> at hamcrest_matching.Service.persistState(Service.java:32)

The example code:
```java
    public class StateEntity {
        private Long id;
        private String description;
        public Long getId() { return id; }
        public void setId( Long id ) { this.id = id; }
        public String getDescription() { return description; }
        public void setDescription( String description ) { this.description = description; }
        @Override public String toString() {
            return "StateEntity{" + "id=" + id + ", description='" + description + '\'' + '}';
        }
    }
    
    public class Repository {
        public StateEntity create( StateEntity state ) { return state; }
        public void update( StateEntity state ) {}
    }
    
    public class Service {
        private final Repository repository;
        private StateEntity state;
        public Service( Repository repository ) {
            this.repository = repository;
            state = new StateEntity();
        }
        public void execute() {
            nextStep( "1" );
            nextStep( "2" );
            nextStep( "3" );
        }
        private void nextStep( String description ) {
            state.setDescription( description );
            persistState();
        }
        private void persistState() {
            if (state.getId() == null) {
                System.out.println("### create: " + state.getDescription());
                state = repository.create( state );
            }
            else {
                System.out.println("### update: " + state.getDescription());
                repository.update( state );
            }
        }
    }

    public class ServiceTest {
        @InjectMocks private Service service;
        @Mock private Repository mockRepository;
        @Before public void setUp() {
            MockitoAnnotations.initMocks( this );
            service = new Service( mockRepository );
        }

        @Test
        public void test throws Exception {
            when( mockRepository.create( any( StateEntity.class )) ).thenAnswer(
                new Answer<StateEntity>() {
                    @Override public StateEntity answer( InvocationOnMock invocation ) throws Throwable
                    {
                        final StateEntity stateEntity = (StateEntity) invocation.getArguments()[0];
                        stateEntity.setId( System.nanoTime() );
                        return stateEntity;
                    }
            } );

            service.execute();

            verify( mockRepository ).create( MockitoHamcrest.argThat( stateHasDescription( "1" )));
            verify( mockRepository ).update( MockitoHamcrest.argThat( stateHasDescription( "2" )));
            verify( mockRepository ).update( MockitoHamcrest.argThat( stateHasDescription( "3" )));
        }

        private static Matcher<StateEntity> stateHasDescription( final String expectedDescription )
        {
            return new TypeSafeMatcher<StateEntity>() {
                @Override public boolean matchesSafely( StateEntity item ) {
                    return item.getDescription().equals( expectedDescription );
                }
                @Override public void describeTo( Description description ) {
                    description.appendText( "a state entity with description " )
                    .appendValue( expectedDescription );
                }
            };
        }
    }
```

**Comment by TimvdLippe** [comment]
Hm I think we will someday deprecate `MockitoHamcrest`, but is the usage of HamCrest required here? Could you maybe use one of the other matchers available? The sample code is fairly big, so it will be hard to debug this issue as there a lot of factors. Given that HamCrest is discouraged and we are very time-constrained, we would probably need to see the root issue to fix it.

**Comment by TimvdLippe** [comment]
Closing as wont-fix.
