### ISSUE TITLE
MockitoJUnitRunner.StrictStubs does not detect 'Unnecessary Stubbing' when inline mock maker is enabled

### ISSUE THREAD

**Issue by tmurakami** [mockito/mockito#974]
- mockito-core 2.7.13
- OpenJDK 1.8.0_121
- Ubuntu 16.10
- Enable `mock-maker-inline` (or use `mockito-inline` artifact)

If running the following test, 'Unnecessary Stubbing' is not detected.

```java
@RunWith(MockitoJUnitRunner.StrictStubs.class)
public class MockitoTest {

    @Mock
    ArrayList<String> mock;

    @Test
    public void should_pass() {
        when(mock.get(0)).thenReturn("foo");
        assertEquals("foo", mock.get(0));
    }

    @Test
    public void should_detect_unnecessary_stubbing() {
        when(mock.get(1)).thenReturn("foo");
    }

}
```

In the above code, 'Unnecessary Stubbing' is detected by changing ArrayList to List.
```java

    @Mock
//    ArrayList<String> mock;
    List<String> mock;

```

This problem does not occur with default mock maker.

**Comment by TimvdLippe** [comment]
This is working as intended. You should not mock Data classes such as `List`. The new mock maker is stricter in this regard as we could not ship another breaking change for the original mock maker.

We could add an explicit exception when we encounter these classes, instead of silently continueing. WDYT @raphw ?

**Comment by tmurakami** [comment]
I am sorry that my test case was bad.

The following test **passes** using inline mock maker.
This test does not use data classes.
```java
@RunWith(MockitoJUnitRunner.StrictStubs.class)
public class MockitoTest {

    @Mock
    C mock;

    @Test
    public void should_pass() {
        when(mock.doIt()).thenReturn("foo");
        assertEquals("foo", mock.doIt());
    }

    @Test
    public void should_detect_unnecessary_stubbing() {
        when(mock.doIt()).thenReturn("foo");
    }

    public static class C {
        public String doIt() {
            throw new UnsupportedOperationException();
        }
    }

}
```

Using default mock maker, this test **fails**.
This is the result that I expect.
```
org.mockito.exceptions.misusing.UnnecessaryStubbingException: 
Unnecessary stubbings detected in test class: MockitoTest
Clean & maintainable test code requires zero unnecessary code.
Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at com.example.MockitoTest.should_detect_unnecessary_stubbing(MockitoTest.java:25)
Please remove unnecessary stubbings or use 'silent' option. More info: javadoc for UnnecessaryStubbingException class.

	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:49)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Does **new mock maker** mean **inline mock maker**?
According to the results of this test, inline mock maker seems to be less strict than default mock maker.
Sorry if I have misunderstood.

**Comment by TimvdLippe** [comment]
Ah that is a better testcase. Definitely a bug!

**Comment by raphw** [comment]
Just tested this on master and the result is the same for both mock makers where neither test detects the unneccessary stubbung. I do not know this part of Mockito too well but I assume there is a bug in this component.

**Comment by tmurakami** [comment]
I wrote a new test for this issue.

```java
public class StrictStubsRunnerByMockingAbstractClassTest {

    private final JUnitCore jUnitCore = new JUnitCore();

    @Test
    public void test_for_abstract_method_should_detect_unnecessary_stubbings() {
        runTest(ForAbstractMethod.class);
    }

    @Test
    public void test_for_concrete_method_should_detect_unnecessary_stubbings() {
        runTest(ForConcreteMethod.class);
    }

    private void runTest(Class<?> testClass) {
        Result result = jUnitCore.run(testClass);
        List<Failure> failures = result.getFailures();
        assertThat(failures.size(), equalTo(1));
        Failure failure = failures.get(0);
        assertThat(failure.getException(), instanceOf(UnnecessaryStubbingException.class));
    }

    static abstract class TestTarget {

        abstract String abstractMethod();

        String concreteMethod() {
            throw new UnsupportedOperationException();
        }

    }

    @RunWith(MockitoJUnitRunner.StrictStubs.class)
    public static class ForAbstractMethod {

        @Mock
        TestTarget mock;

        @Test
        public void correct_stubbing() {
            when(mock.abstractMethod()).thenReturn("");
            mock.abstractMethod();
        }

        @Test
        public void unused_stubbing() {
            when(mock.abstractMethod()).thenReturn("");
        }

    }

    @RunWith(MockitoJUnitRunner.StrictStubs.class)
    public static class ForConcreteMethod {

        @Mock
        TestTarget mock;

        @Test
        public void correct_stubbing() {
            when(mock.concreteMethod()).thenReturn("");
            mock.concreteMethod();
        }

        @Test
        public void unused_stubbing() {
            when(mock.concreteMethod()).thenReturn("");
        }

    }

}
```

To test this test on the master, I put this into the following directory.
1. src/test/java/org/mockitousage/junitrunner (using the default mock maker)
1. inline/src/test/java/org/mockitoinline (using the inline mock maker)

In the first case, this test passed.
```
$ ./gradlew -Dorg.gradle.parallel=false clean :test --tests "org.mockitousage.junitrunner.StrictStubsRunnerByMockingAbstractClassTest"
Version: 2.7.14
:clean
:android:clean UP-TO-DATE
:extTest:clean UP-TO-DATE
:inline:clean
:testng:clean UP-TO-DATE
:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:copyMockMethodDispatcher
:processResources UP-TO-DATE
:classes
:createTestResources
:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:removeTestResources
:processTestResources UP-TO-DATE
:testClasses
:test

BUILD SUCCESSFUL

Total time: 5.707 secs
```

However, in the second case it failed.
```
$ ./gradlew -Dorg.gradle.parallel=false clean :inline:test --tests "org.mockitoinline.StrictStubsRunnerByMockingAbstractClassTest"
Version: 2.7.14
:clean
:android:clean UP-TO-DATE
:extTest:clean UP-TO-DATE
:inline:clean
:testng:clean UP-TO-DATE
:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:copyMockMethodDispatcher
:processResources UP-TO-DATE
:classes
:jar
:inline:compileJava UP-TO-DATE
:inline:processResources
:inline:classes
:inline:compileTestJava
:inline:processTestResources UP-TO-DATE
:inline:testClasses
:inline:test

org.mockitoinline.StrictStubsRunnerByMockingAbstractClassTest > test_for_concrete_method_should_detect_unnecessary_stubbings FAILED
    java.lang.AssertionError: 
    Expected: <1>
         but: was <0>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.mockitoinline.StrictStubsRunnerByMockingAbstractClassTest.runTest(StrictStubsRunnerByMockingAbstractClassTest.java:36)
        at org.mockitoinline.StrictStubsRunnerByMockingAbstractClassTest.test_for_concrete_method_should_detect_unnecessary_stubbings(StrictStubsRunnerByMockingAbstractClassTest.java:30)

2 tests completed, 1 failed
:inline:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':inline:test'.
> There were failing tests. See the report at: file:///home/tmura/IdeaProjects/mockito/subprojects/inline/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.505 secs

```

For the abstract method, 'Unnecessary Stubbing' was detected correctly, but it did not detected for the concrete method.

**Comment by tmurakami** [comment]
I thnk I have found the cause of this problem.
When using the inline mock maker, it seems that LocationImpl cannot get the stubbed location of the concrete method correctly.

`UnusedStubbingFinder` which detects 'Unnecessary stubbing' calls `LocationImpl#toString()` to get the stabbed location.

The code below is the implementation of `LocationImpl#toString()`.
```java
StackTraceElement[] filtered = stackTraceFilter.filter(stackTraceHolder.getStackTrace(), false);
if (filtered.length == 0) {
    return "-> at <<unknown line>>";
}
return "-> at " + filtered[0].toString();
```

This method filters the stack trace elements of `stackTraceHolder` to get the location.
`stackTraceHolder` is a Throwable object that is created in the constructor of `LocationImpl`.

The stack trace elements of this object are as follows:

- Stubbing the concrete method with the default mock maker
```
0 = {StackTraceElement@1679} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:23)"
1 = {StackTraceElement@1680} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:18)"
2 = {StackTraceElement@1681} "org.mockito.internal.creation.bytebuddy.InterceptedInvocation.<init>(InterceptedInvocation.java:52)"
3 = {StackTraceElement@1682} "org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:41)"
4 = {StackTraceElement@1683} "org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptSuperCallable(MockMethodInterceptor.java:102)"
5 = {StackTraceElement@1684} "com.example.MockitoTest$C$MockitoMock$648066763.doIt(Unknown Source)"
6 = {StackTraceElement@1685} "com.example.MockitoTest.should_detect_unnecessary_stubbing(MockitoTest.java:25)"
```

- Stubbing the abstract method with the inline mock maker
```
0 = {StackTraceElement@2201} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:23)"
1 = {StackTraceElement@2202} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:18)"
2 = {StackTraceElement@2203} "org.mockito.internal.creation.bytebuddy.InterceptedInvocation.<init>(InterceptedInvocation.java:52)"
3 = {StackTraceElement@2204} "org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:41)"
4 = {StackTraceElement@2205} "org.mockito.internal.creation.bytebuddy.MockMethodInterceptor$DispatcherDefaultingToRealMethod.interceptAbstract(MockMethodInterceptor.java:120)"
5 = {StackTraceElement@2206} "com.example.MockitoTest$C$MockitoMock$1683798279.doIt(Unknown Source)"
6 = {StackTraceElement@2207} "com.example.MockitoTest.should_detect_unnecessary_stubbing(MockitoTest.java:25)"
```

- Stubbing the concrete method with the inline mock maker
```
0 = {StackTraceElement@1927} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:23)"
1 = {StackTraceElement@1928} "org.mockito.internal.debugging.LocationImpl.<init>(LocationImpl.java:18)"
2 = {StackTraceElement@1929} "org.mockito.internal.creation.bytebuddy.InterceptedInvocation.<init>(InterceptedInvocation.java:52)"
3 = {StackTraceElement@1930} "org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:41)"
4 = {StackTraceElement@1931} "org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:76)"
5 = {StackTraceElement@1932} "com.example.MockitoTest$C.doIt(MockitoTest.java:30)"
6 = {StackTraceElement@1933} "com.example.MockitoTest.should_detect_unnecessary_stubbing(MockitoTest.java:25)"
```

The resulting location should be `#6`, but in the last case it is `#5`.
Because `stackTraceFilter` does not exclude `#5`.

**Comment by raphw** [comment]
Yes, this is expected. The inline mock maker inlines the code and does therefore not add a stack frame. This is a bug in the `UnusedStubbingFinder` which should not rely on the stack shape.

@TimvdLippe Do you have time to look at this?

**Comment by szczepiq** [comment]
Thank you guys for really thorough debugging!

>This is a bug in the UnusedStubbingFinder which should not rely on the stack shape.

There is a reason why the finder relies on the String representation of line where the unused stub is declared. I documented it in the [Javadoc](https://github.com/mockito/mockito/blob/release/2.x/src/main/java/org/mockito/internal/junit/UnusedStubbingsFinder.java#L46), hopefully it is more less clear :) I'm not saying we should keep the current implementation, I'm ok changing it, I just wanted to give more data points.

After reading this thread my gut feel tells me that the stack trace filter (different component than unused stubbing detection) may not be coping well with inline mocking. This could also have impact on stack trace filtering in general for inline mocking, the quality of exception messages, etc.

@tmurakami, you made fantastic debugging effort to nail down the problem. Can you investigate if stack trace filter needs adapting for inline mocking and potentially submit a PR?

**Comment by raphw** [comment]
With the stack trace filter, I actually did change the implementation to adjust this behavior such that it works. I was not aware that the stubbing finder replicated something similar.

**Comment by tmurakami** [comment]
@szczepiq, @raphw, I can submit the PR, but this problem seems to have already been fixed by @raphw.
Should I submit the PR?

**Comment by raphw** [comment]
Please submit, I only fixed the issue partially.
