### ISSUE TITLE
Failure to use @InjectMocks with multiple potential mocks

### ISSUE THREAD

**Issue by mureinik** [mockito/mockito#990]
When annotating a member with `@InjectMocks` in a class that has more than one appropriate `@Mock` for that member, it will silently leave the member as `null`, and not inject any mock. While it's completely possible that there will be more than one appropriate mock, such an erroneous situation should produce a very visible failure, instead of silently doing nothing and leaving the user to later discover the problem later. E.g., consider the following code - since both `List` and `Set` can be assigned to an `Object`, Mockito can't choose between them, and will leave `objectContainer#object` uninitialized:

```java
@RunWith(MockitoJUnitRunner.class)
public class InjectMultipleMocksTest {
    public static class ObjectContainer {
        public Object object;
    }

    @Mock
    private List aList;
    @Mock
    private Set aSet;

    @InjectMocks
    private ObjectContainer objectContainer = new ObjectContainer();


    @Test
    public void testInjection() {
        assertNotNull(objectContainer.object);
    }
}
```

An even worse variant of this bug presents when the member is anotated with both `@Spy` and `@InjectMocks`. In this case, the test initialization would fail with `NotAMockException`. If we take the example above and add a `@Spy` anotation to `objectContianer`, we'll get the following error (when run from IntelliJ IDEA:

```
Test ignored.

org.mockito.exceptions.misusing.NotAMockException: Argument should be a mock, but is: class org.mockitousage.misuse.InjectMultipleMocksTest$ObjectContainer

	at org.mockito.internal.util.MockUtil.getMockHandler(MockUtil.java:62)
	at org.mockito.internal.util.MockUtil.getMockName(MockUtil.java:75)
	at org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter.selectMatchingName(NameBasedCandidateFilter.java:43)
	at org.mockito.internal.configuration.injection.filter.NameBasedCandidateFilter.filterCandidate(NameBasedCandidateFilter.java:30)
	at org.mockito.internal.configuration.injection.filter.TypeBasedCandidateFilter.filterCandidate(TypeBasedCandidateFilter.java:31)
	at org.mockito.internal.configuration.injection.PropertyAndSetterInjection.injectMockCandidatesOnFields(PropertyAndSetterInjection.java:122)
	at org.mockito.internal.configuration.injection.PropertyAndSetterInjection.injectMockCandidates(PropertyAndSetterInjection.java:110)
	at org.mockito.internal.configuration.injection.PropertyAndSetterInjection.processInjection(PropertyAndSetterInjection.java:87)
	at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:68)
	at org.mockito.internal.configuration.injection.MockInjectionStrategy.relayProcessToNextStrategy(MockInjectionStrategy.java:89)
	at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:71)
	at org.mockito.internal.configuration.injection.MockInjectionStrategy.relayProcessToNextStrategy(MockInjectionStrategy.java:89)
	at org.mockito.internal.configuration.injection.MockInjectionStrategy.process(MockInjectionStrategy.java:71)
	at org.mockito.internal.configuration.injection.MockInjection$OngoingMockInjection.apply(MockInjection.java:92)
	at org.mockito.internal.configuration.DefaultInjectionEngine.injectMocksOnFields(DefaultInjectionEngine.java:25)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:87)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processInjectMocks(InjectingAnnotationEngine.java:48)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:42)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:69)
	at org.mockito.internal.runners.DefaultInternalRunner$1.withBefores(DefaultInternalRunner.java:38)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:276)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:68)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:74)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Version info:
This issue was originally encounted by Shmuel Melamud during his work on oVirt Engine (see the [post on the oVirt devel list](http://lists.ovirt.org/pipermail/devel/2017-March/029864.html)) which uses Mockito 2.7.14.
Using the reproducer I created above, I was able to reproduce it 2.7.14, 2.7.17 and 2.1.0. It probably also happens on 1.x versions, but at this stage that's probably a mute point.

**Comment by HarshHarwani** [comment]
+1, encountered the same bug.

**Comment by emilhotkowski** [comment]
First problem I would call at most a bad design. It is written in [documentation](http://static.javadoc.io/org.mockito/mockito-core/2.21.0/org/mockito/InjectMocks.html)  
"Mockito will try to inject mocks only either by constructor injection, setter injection, or property injection in order and as described below. If any of the following strategy fail, then **Mockito won't report failure**; i.e. you will have to provide dependencies yourself."

But I think there are some opportunities for improvement when it comes to @InjectMocks.

**Comment by TimvdLippe** [comment]
While the state is not great, I am closing this as wont-fix. We sadly are not a dependency injection framework and `@InjectMocks` tries it best. My personal opinion is that we should just remove `@InjectMocks`, but for now we will keep the feature as-is.
